### ISSUE TITLE
Minor editorial comments on DCAT CR candidate

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dxwg#1020]
First of all: Kudos to the editors! The CR candidate is a great piece of work.

Minor nits:

1. [4. Conformance](https://w3c.github.io/dxwg/dcat/#conformance): The last bullet point in the list of conformance criteria reads very differently from the other ones.
> A data catalog conforms to DCAT if:
* DCAT-compliant catalogs MAY include additional ...

I propose to take that bullet point out of the list, like
> * All classes and properties defined in DCAT are used in a way consistent with the semantics declared in this specification.
DCAT-compliant catalogs MAY include additional non-DCAT metadata fields and additional RDF data in the catalog's RDF description.

2. [4. Conformance](https://w3c.github.io/dxwg/dcat/#conformance): I think it would be helpful to implementers to explicitly specify which URI to use to indicate that a catalogue conforms do DCAT 2. Would
```
my:catalogue dct:conformsTo <https://www.w3.org/TR/vocab-dcat/>
```
be correct?

3. Figure 1: The relation `dcat:record` from `dcat:Catalog` to `dcat:CatalogRecord` has the cardinality `1..n`. Shouldn't that be `0..n`? (Otherwise it would be mandatory to have at least one catalogue record, while the [usage note for `dcat:CatalogRecord`](https://w3c.github.io/dxwg/dcat/#Class:Catalog_Record) explicitly says: "This class is optional and not all catalogs will use it."

4. In [§6.3.2 Property: themes](https://w3c.github.io/dxwg/dcat/#Property:catalog_themes), the usage notes has a hyphen in "linked-data". This is the only place where this term is hyphenised; all other occurences spell it "linked data".

5. In the definition of [§6.3.6 Property: catalo](https://w3c.github.io/dxwg/dcat/#Property:catalog_catalog), there is no period/full stop at the end of the sentence (the other definitions have one).

6. In the second usage note of [§6.4 Class: Cataloged Resource](https://w3c.github.io/dxwg/dcat/#Class:Resource), there is no period/full stop at the end of the sentence (the other usage notes have one).

7. In [Example 36](https://w3c.github.io/dxwg/dcat/#ex-conformance-degree-percentage), I think that `iso:inherentandSystemDependentDataQuality a dqv:Category ;` should read `iso:inherentAndSystemDependentDataQuality a dqv:Category ;` (inherent __And__ System Dependent ...)

8. In [Example 40](https://w3c.github.io/dxwg/dcat/#ex-conformance-test-error) you use `dc:format "text/xml"`. I don't think we should point people to deprecated media types and propose to use `dc:format "application/xml"` instead.
And I think there is a comma missing in the last sentence of [§12.2.3](https://w3c.github.io/dxwg/dcat/#quality-conformance-test-results): It currently reads "Of course, the above modelling patterns can represent any quality tests not only conformance to standards." I think that should be "Of course, the above modelling patterns can represent any quality tests**,** not only conformance to standards."

9. In the Note at the end of [§13](https://w3c.github.io/dxwg/dcat/#qualified-forms), there either is an "s" too many in "the context resources is a member", should read "the context resource is a member".

10. In the references section you point [DCAT-AP.de] to https://govdata.de/standardisierung. I think the canonical reference to the spec is https://dcat-ap.de/def/.

**Comment by andrea-perego** [comment]
Thanks for your review, @larsgsvensson .

Your points 4, 5, 6, 9, 10 have been addressed in PR https://github.com/w3c/dxwg/pull/1021

**Comment by davebrowning** [comment]
On point 2 - interesting question. 

For dcat2 I think it would be
```
my:catalogue dct:conformsTo <https://www.w3.org/TR/vocab-dcat2/>
```

That uri points at the latest version of the recommendation which I guess might be what people would want to do.  I guess some cautious publishers might want to use a specific/dated version just in case of some kind of future change that they hadn't foreseen....

**Comment by davebrowning** [comment]
#1023 and #1024 address points 1, 3, and 7.  Thanks for the help.

I'm minded to hold fire on the second point for now - bit wary of getting it wrong, so I'd suggest  keeping this open for now.

**Comment by davebrowning** [comment]
@larsgsvensson - the only remaining item in this list that we don't think we've addressed is point (2) - the suggestion about including a  URI to use.  Since we're now quite/very short of time, we'd prefer to hold this over so there is enough time to make sure its properly discussed (perhaps as some of the profiles work). 

If that's okay, we'll move this issue across to the "Future Priority" milestone.

**Comment by larsgsvensson** [comment]
@davebrowning scripsit:
> If that's (sc. hold over point (2)) okay, we'll move this issue across to the "Future Priority" milestone.

Yes, fine with me. All other points have been addressed.

One very minor nit on point 10.: The text for the link to  https://dcat-ap.de/def/ reads "DCAT-AP.de als formaler Metadatenstandard für offene Verwaltungsdaten bestätigt". The actual title of the document is "Vokabulare und Dokumente für DCAT-AP.de".

**Comment by davebrowning** [comment]
Thanks @larsgsvensson .

**Comment by andrea-perego** [comment]
@larsgsvensson ,

Trying to verify whether the remaining points you raised have been eventually addressed. 

Many thanks for your patience.

About this one - https://github.com/w3c/dxwg/issues/1020#issuecomment-529351294 :

> One very minor nit on point 10.: The text for the link to https://dcat-ap.de/def/ reads "DCAT-AP.de als formaler Metadatenstandard für offene Verwaltungsdaten bestätigt". The actual title of the document is "Vokabulare und Dokumente für DCAT-AP.de".

The corresponding revision has been implemented via PR https://github.com/w3c/dxwg/pull/1059

See: https://www.w3.org/TR/vocab-dcat-2/#bib-dcat-ap.de

About your point (2) , following discussion in https://github.com/w3c/dxwg/issues/1225 , we have updated the guidance section on conformance (see PR https://github.com/w3c/dxwg/pull/1310) to provide some recommendations on the URIs to be used with `dcterms:conformsTo`:

https://w3c.github.io/dxwg/dcat/#quality-conformance-statement

I copy-paste here the relevant text:

> In order to ensure interoperability, it is important to consistently use the URIs identifying the reference standards / specifications. In particular, DCAT recommends the following general rules:
>
> - Use URIs from reference registries, when available. Examples include the W3C TR registry, the OGC Definitions Server, the ISO OBP.
> - Use the URI of the standard / specification, and not the namespace URI. E.g., to express conformance with DCAT, the URI to be used is https://www.w3.org.org/TR/vocab-dcat/, and not http://www.w3.org/ns/dcat#.
> - Use the canonical, persistent URI. This is usually specified in the document itself. If you are in doubt, use the one included in the bibliographic citations for that standard / specification.
> - Use the non-versioned URI. If you need to express conformance with a specific version of the standard / specification, use both the un-versioned and the versioned URI. E.g., in case you need to explicitly state conformance with DCAT 2, use both https://www.w3.org.org/TR/vocab-dcat/ and https://www.w3.org.org/TR/vocab-dcat-2/.

There is still some discussion ongoing on the criteria above (in particular, in issues https://github.com/w3c/dxwg/issues/1211 and https://github.com/w3c/dxwg/issues/1338), so they can be revised / extended.

Could you please confirm that with this we have addressed all your comments?

Thanks!

**Comment by larsgsvensson** [comment]
@andrea-perego scripsit:

> Could you please confirm that with this we have addressed all your comments?

Yes, this is all fine with me and this issue can be closed.

Thanks to all editors for moving this forward!

**Comment by andrea-perego** [comment]
Thanks a lot, @larsgsvensson , and apologies again far taking so long to address all your comments.

Closing this issue.
