### ISSUE TITLE
Create a data model for representing alternate profiles

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#1031]
The `Link` headers in section [7.1 Hypertext Transfer Protocol Headers](https://www.w3.org/TR/dx-prof-conneg/#http) and QSA alternate profiles listing such as in [Example 10: Requesting a list of profiles for a resource by QSA in HTML](https://raw.githack.com/w3c/dxwg/conneg-ACTION-343/conneg-by-ap/index.html#qsa-listprofiles) all use a data model for profiles, tokens for them and Media Types that we have not yet defined. We must define this and provide tools to allow validation of alternate profile listings against it.

**Comment by nicholascar** [comment]
The *Alternates View* as implemented by [pyLDAPI](http://github.com/rdflib/pyLDAPI) can be expressed in HTML or in machine-readable forms like RXF & JSON, see, for example, <http://pid.geoscience.gov.au/sample/AU100?_view=alternates>. I'll be using this data model (see the turtle format of it [here](http://pid.geoscience.gov.au/sample/AU100?_view=alternates&_format=text/turtle)) as a starting point.

**Comment by nicholascar** [comment]
First full description & examples of an *Alternative Profile* model in PR [1038](https://github.com/w3c/dxwg/pull/1038).

**Comment by larsgsvensson** [comment]
There is a data model in the document at https://w3c.github.io/dxwg/conneg-by-ap/#altr including examples at https://w3c.github.io/dxwg/conneg-by-ap/#altr-detail

**Comment by nicholascar** [comment]
Closing after a period of due-for-closing and no further actions.
