### ISSUE TITLE
Alignment issue between dcat:contactPoint and sdo:contactPoint

### ISSUE THREAD

**Issue by wouterbeek** [w3c/dxwg#1032]
The DCAT2 specification (currently under development) indicates the following alignment with Schema.org:

```
dcat:contactPoint 	sdo:contactPoint
```

The domain of `dcat:contactPoint` is `dcat:Resource` which is something very generic, aligned with `sdo:Thing`.

At the same time, `sdo:contactPoint` is intended to have either persons or organizations in its domain.

Conceptually speaking there is a conflict when we assert that a DCAT catalog has a contact point (something we would like to assert), when this results in us (sort of) implying that a DCAT catalog is a person or organization in Schema.org.

**Comment by makxdekkers** [comment]
@wouterbeek As far as I understand, schema.org does not do domains the way RDF does. It only asserts that a property is merely "Used on these types" which does not stop people from using it on other types.
They actually state that "_We expect schema.org properties to be used with new types, both from schema.org and from external extensions_" (https://schema.org/docs/datamodel.html).
In fact, `sdo:contactPoint` is currently also 'used on' `sdo:HealthInsurancePlan` so it doesn't seem like a problem to me to also use it on `dcat:Catalog` and `dcat:Dataset`.

**Comment by wouterbeek** [comment]
@makxdekkers I was not aware of the precedent sent by `sdo:HealthInsurancePlan`.  In that case DCAT is simply following a widening of the applicability of the `sdo:contactPoint` property that is already in effect.  Closing...
