### ISSUE TITLE
Align Alternative Representations Model and PROF

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#1041]
Some parts of the Alternate Representations Data Model in Conneg by P appears to border PROF concepts. We have not yet deliberately aligned the two models.

**Comment by nicholascar** [comment]
It appears to me that PROF is giving us profile modelling - out of scope for Conneg by P - but also hooks from profiles to resources that conform to them, viz `rdfs:Resource dct:conformsTo prof:Profile` and also a description of a `Resource`, viz. the `prof:ResourceDescriptor` class.

Conneg by P seems to require (from our testing) that there is a `Representation` class, instances of which represent, as per the HTTP spec [[RDF7230](https://httpwg.org/specs/rfc7230.html)], "An abstraction of the current or desired state of a thing in HTTP communications.".

It seems fairly obvious that we have something like this:

```
rdf:Resource conneg:hasRepresentation conneg:Representation .
conneg:Representation dct:conformsTo prof:Profile .
```
So the tie-point question seems to be: 
* how does a `conneg:Representation` class fit into PROF, if at all?

`conneg:Representation` is modelling implementations of data which will border PROF and PROF also contains:

`prof:ResourceDescriptor prof:hasArtifact rdf:Resource` 

where the *artifact* is the realisation of the resource that is the thing conforming to a `prof:Profile`. We've not teased apart resources ans representations of them in PROF and this requirement from Conneg could be the thing that does that.

**Comment by nicholascar** [comment]
Being dealt with in PR [1038](https://github.com/w3c/dxwg/pull/1038)

**Comment by nicholascar** [comment]
This Issue depends on completion of Issue #1031 and the associated PR #[1038](https://github.com/w3c/dxwg/pull/1038)

**Comment by larsgsvensson** [comment]
@nicholascar can you state if this issue has been dealt with to your satisfaction? Then we can mark as due-for-closing

**Comment by nicholascar** [comment]
Yes, this issue has been dealt with to my satisfaction through the model extension details in the [Appendix A.2](https://w3c.github.io/dxwg/conneg-by-ap/#altr-detail), particularly [Example 22](https://w3c.github.io/dxwg/conneg-by-ap/#eg-altr-ext).

**Comment by nicholascar** [comment]
Just recapping, this issue has been dealt with to my satisfaction and therefore it may be closed. The resolution here is that alignment between PROF & AltP is given in the document with sections [Alternate Representations Data Model - Details](https://w3c.github.io/dxwg/conneg-by-ap/#altr-detail) and [A.2.2 Extensions](https://w3c.github.io/dxwg/conneg-by-ap/#altr-extensions).
