### ISSUE TITLE
DCAT: Further updates to ack section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1051]
There are other contributors to be added, following PR https://github.com/w3c/dxwg/pull/1021

E.g.:
- Tom Kralidis (see https://github.com/w3c/dxwg/issues/971)

Are there other ones?

**Comment by andrea-perego** [comment]
I created a draft PR adding Tom and Lars (we forgot you, sorry @larsgsvensson!): https://github.com/w3c/dxwg/pull/1052

@pwin , @dr-shorthair , @davebrowning , @agbeltran , @riccardoAlbertoni , please feel free to add any missing contributors in that PR.

Please remember that contributors are listed in two different paragraphs (the first for WG members, and the second for non-members), and in alphabetical order (by given name).

**Comment by davebrowning** [comment]
I think this is complete with @riccardoAlbertoni 's additions (I don't know of any more)

**Comment by davebrowning** [comment]
Marked 'due for closing' - if we need to add further commenters we should use a new issue for clarity

**Comment by andrea-perego** [comment]
New issue created: #1069 

I think we can close this one.
