### ISSUE TITLE
Remove "Alternate ways of conveying URI / token mappings"

### ISSUE THREAD

**Issue by RubenVerborgh** [w3c/dxwg#1064]
There currently is a not in the conneg-by-ap document titled "Alternate ways of conveying URI / token mappings". However, every single listed option is incompatible with the `Content-Profile` header as defined.

I propose to remove this note once we have finalized the token mechanism (for instance, through #1063).

**Comment by larsgsvensson** [comment]
@RubenVerborgh scripsit:
> I propose to remove this note once we have finalized the token mechanism (for instance, through #1063).

+1

**Comment by larsgsvensson** [comment]
Addressed in PR #1075

**Comment by nicholascar** [comment]
The "Alternate ways of conveying URI / token mappings" is no longer in the ED at https://w3c.github.io/dxwg/conneg-by-ap/
