### ISSUE TITLE
Conneg Editorial Nits

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dxwg#1088]
@tombaker has [reported some editorial nits](https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Sep/0682.html) in the conneg-by-ap WD:

I see that PROFPWD is listed under B1 and assume this can be updated and moved to B2 later. (Can someone please confirm?)

Some fixable glitches:

Section 1
These narrower profiles constrains

4
demonstrations

5.4
so that profiles, (the comma)

6.2
may no be capable of dereferencing

6.3
representation of the requested resource represented conforming

7.1
An functional profile

**Comment by nicholascar** [comment]
This Issue is the sole subject of PR #1090

**Comment by larsgsvensson** [comment]
The corresponding PR has been merged.
