### ISSUE TITLE
Reviewing DCAT issues

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1089]
Going through [the open issues labelled as "dcat"](https://github.com/w3c/dxwg/issues?q=is%3Aissue+is%3Aopen+label%3Adcat) (currently, 88), we have nearly a half of them not assigned to any milestones:

https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adcat+no%3Amilestone

I guess that, before the transition to CR, we should proceed with assigning them to a milestone.

How should we proceed to sort this out effectively?

Maybe we can start identifying groups that can be treated the same way:
- Some of them are quite old, and they may have probably been addressed by other issues.
- Some are about alignments between DCAT and other vocabularies - which may be deferred to future work and/or a DCAT primer:
https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adcat+no%3Amilestone+label%3Aalignment 

WDYT?

**Comment by davebrowning** [comment]
Indeed.

I've been unsure whether tagging or milestone is better.  Issues can only be in one milestone, which implies a scheduling decision - perhaps that is best.  I'll have a go with "alignments" and we can see what we think

**Comment by davebrowning** [comment]
So I've done that....and tried to put the relevant story in the milestone description

**Comment by andrea-perego** [comment]
Thanks, @davebrowning .

I wonder whether it may be worth going through them during a subgroup call. The other option (not mutually exclusive) is to do some work offline (just started with old issues that might be moved to future work).

**Comment by andrea-perego** [comment]
Going through these issues, I think a number of them are more specifically related to other deliverables, so probably we should change the project / milestone assigned to them.

The relevant issues:
- https://github.com/w3c/dxwg/issues/393
- https://github.com/w3c/dxwg/issues/238
- https://github.com/w3c/dxwg/issues/223
- https://github.com/w3c/dxwg/issues/145

**Comment by andrea-perego** [comment]
Just started adding the label future-work to possible candidates for milestone [DCAT Future Priority Work](https://github.com/w3c/dxwg/milestone/15).

**Comment by davebrowning** [comment]
Thanks @andrea-perego.  I've also had a go...  Generally I used the future-work tag - if we have agreement on the priority (or whether it goes into a primer or whatever) then we can allocate to a milestone.

With editing hat on = for the CR phase, [this query](https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Adcat+-label%3Afuture-work+-label%3A%22due+for+closing%22+no%3Amilestone+sort%3Aupdated-desc+-project%3Aw3c%2Fdxwg%2F1+-label%3Adcat-primer+) shows the issues that need attention to make status clear - currently nine of them.  For four of those I have suggested a way forward,  for the other five it wasn't clear to me.

There were some stray potential use cases that hadn't been included in the UCR (either the last publication or the ED) so I moved them to the 'UCR' milestone - hopefully that's okay.  I'm making no judgement on whether they are or will be approved.

(Note on that query: open, DCAT issues not in a milestone nor labelled 'future work', 'DCAT primer', 'due for closing')

Obviously this can/needs to be discussed, reviewed and can be changed, but it's a bit less vague (ie either right/wrong or agreed/disagreed).

**Comment by andrea-perego** [comment]
Thanks, @davebrowning . I was unsure whether to create yet another tag, but eventually I opted to use future-work with the assumption that the issues tagged with it were not yet "officially" for future work. My apologies for my misuse of it.

Looking at the remaining 9 issues, I see that some of them are only related to changes in the RDF, so it may not be blocking for CR transition. Not sure, however, if it may be worth creating another milestone for them.

**Comment by davebrowning** [comment]
@andrea-perego I think what you did was fine - I was trying to use the same logic. 

I agree that having a milestone as a container for 'work during CR/PR phases' may be good.  [There are things we'll have to do like setting up an errata page that only makes sense once things get that advanced.]

**Comment by riccardoAlbertoni** [comment]
DCAT issues have been reviewed in the last call and the recent interactions. The related housekeeping activity has closed many of the issues and reassigned the remaining issues to the following GitHub Projects/Milestones:
- Project ["Use Cases and Requirements for dataset exchange"](https://github.com/w3c/dxwg/projects/1) includes use cases to be considered in future work.
- Milestone ["DCAT2 ratification"](https://github.com/w3c/dxwg/milestone/24) holds issues & activities in support of ratification of the DCAT spec through CR and PR.
- Milestone ["DCAT Future Priority Work"](https://github.com/w3c/dxwg/milestone/15) includes the issues believed to be a priority for a future release.
