### ISSUE TITLE
Replace "functional profiles" with "methods" or "implementations"

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#1106]
The Conneg document states:

"While this specification only describes these two Functional Profiles, it is expected that implementers will want to implement methods, and thus Functional Profiles of the Abstract Model, for other environments, some of which may not yet be realized – future environments. " ([Introduction](https://w3c.github.io/dxwg/conneg-by-ap/#introduction), paragraph 6)

In this, "implementation methods" is given as a term for "Functional Profiles". I suggest that instead of "functional profiles" we use "methods", "implementation methods" or simply "implementations" in the place of functional profiles.

Note that it appears that "functional profiles" is used mainly in the area of medicine, both for information technology and for some medical procedures. It does not appear to be commonly used outside of that area. "Method" has particular meaning in [OOP](https://en.wikipedia.org/wiki/Method_(computer_programming)), which may argue against using that term, leaving "implementation" or "implementation method" as in the Conneg quote, above.

**Comment by kcoyle** [comment]
Oh, I should say that I think that calling these implementations "functional profiles" would be less of a problem or not at all a problem if the main thrust of the document weren't "content negotiation by *profile*". There is a great possibility for confusion for readers between the profile as the subject of content negotiation and the profile as the implementation method, so avoiding the functional profile phrase for the latter is best.

**Comment by larsgsvensson** [comment]
@kcoyle scripsit:
> Oh, I should say that I think that calling these implementations "functional profiles" would be less of a problem or not at all a problem if the main thrust of the document weren't "content negotiation by profile". 

This feels like a repetition of the discussion about "Differentiating Functional & Data Profiling in Conneg" starting in https://github.com/w3c/dxwg/issues/1022#issuecomment-530830723...

**Comment by nicholascar** [comment]
Yes, I'm not in favour of changing wording  now. We've discussed this to death and put a lot of effort into the differentiation.

**Comment by kcoyle** [comment]
@nicholascar I don't know who has "discussed this to death" but the working group in general has not given input to Conneg. Having more time means that there can be more input from the whole group. Also, as you know, you will need now to make a wider solicitation of reviews, so I'm afraid that all of Conneg is up for discussion until that wider review takes place. If there is a text for review, I will send it to groups in my community. Please let me know.

**Comment by nicholascar** [comment]
> If there is a text for review, I will send it to groups in my community. Please let me know.

Please just send out the ED. We’ve now merged in all PRs we had.

**Comment by kcoyle** [comment]
It needs its introductory text. What are you sending out to mailing lists?

**Comment by larsgsvensson** [comment]
Wouldn't it make more sense to publish the a 3PWD once the discussion in #544 has been resolved? Then we can ask for wide review on that document.

**Comment by nicholascar** [comment]
> Wouldn't it make more sense to publish the a 3PWD once the discussion in #544 has been resolved? Then we can ask for wide review on that document.

Sure, happy to wait until #544's resolved. 

> It needs its introductory text. What are you sending out to mailing lists?

Previously we've used [this letter on our Wiki](https://github.com/w3c/dxwg/wiki/Profiles-Ont-&-Conneg-RFQ-emails) which we can modify for this round.

**Comment by aisaac** [comment]
@kcoyle for the record the "discussion to death" that @nicholascar alludes is #1022 : basically my preference for closing #1022 was to rename 'functional profiles' into something else, quite like what you've suggested in the issue here.
I've not yet reviewed the last changes pushed to me by Lars (sorry for that @larsgsvensson !) but I have accepted the fact that 'functional profiles' may remain as profile, as long as the difference between both types of profiles is clear. And that it's clear that the focus of the Conneg spec is *not* the functional profiles.

So afaic I would say that the issue here could be closed as redundant with #1022

**Comment by kcoyle** [comment]
@aisaac Thanks, Antoine. I'm coming to your same conclusion, and won't object if functional profiles is left in.

**Comment by rob-metalinkage** [comment]
discussed in CNEG meeting 6/11 closing due to consensus
