### ISSUE TITLE
DCAT2 implementation reports

### ISSUE THREAD

**Issue by draggett** [w3c/dxwg#1115]
Please add your implementation report, or a link to it, to this issue.

**Comment by dr-shorthair** [comment]
[This endpoint](https://gnafld.net/2016-05/) has a rich example of DCAT embedded in the header.  
It includes examples of the following at-risk elements: 
- `:accessService`
- `:bbox`
- `:hadRole`
- `prov:wasGeneratedBy`
- `:spatialResolutionInMeters`
- `:endpointDescription`
- `:endpointURL`
- `:servesDataset`
- `prov:qualifiedAttribution`

**Comment by nicholascar** [comment]
...and that RDF can also be returned as pure RDF, i.e. not embedded in anything, by using Conneg or this URI with query strings:

https://gnafld.net/2016-05/?_view=dcat&_format=text/turtle

**Comment by jakubklimek** [comment]
[LinkedPipes DCAT-AP Viewer](https://github.com/linkedpipes/dcat-ap-viewer/commit/0f23874cf3c98d779a25304bcc4d608bc26aba19) (currently used as part of [Czech National Open Data catalog](https://data.gov.cz)) is adding support for DCAT2 at the moment. The range of newly supported properties will still grow. So far, it supports:
`packageFormat`, `compressFormat`, `DataService`, `endpointURL`, `servesDataset` and `endpointDescription`.

**Comment by jakubklimek** [comment]
[LinkedPipes DCAT-AP Forms](https://github.com/linkedpipes/dcat-ap-forms/commits/feature/dcat2) (currently used as part of [Czech National Open Data catalog](https://data.gov.cz)) is adding support for DCAT2 at the moment. The range of newly supported properties will still grow. So far, it supports: `packageFormat`, `compressFormat`, `DataService`, `endpointURL`, `accessService` and `endpointDescription`. This can already be seen [deployed in development environment - still under development](https://dev.nkod.opendata.cz/formulář/dataset-registration).

**Comment by andrea-perego** [comment]
@dr-shorthair , @nicholascar , @jakubklimek , thanks for your feedback!

The implementation you reported are included in the DCAT2 implementation report - see PR https://github.com/w3c/dxwg/pull/1138

**Comment by andrea-perego** [comment]
The DCAT2 implementation report has been published:

https://w3c.github.io/dxwg/dcat-implementation-report/

I think we can close this issue.

**Comment by andrea-perego** [comment]
Closing.
