### ISSUE TITLE
EXAMPLE 49 Data Catalog Vocabulary (DCAT) - Version 2 coordinates are in wrong order

### ISSUE THREAD

**Issue by nmtoken** [w3c/dxwg#1117]
Example 49 has:

    ga-courts:jc
      rdf:type dcat:Dataset ;
      dct:description "The dataset contains spatial locations, in point format, of the Australian High Court, Australian Federal Courts and the Australian Magistrates Courts."@en ;
      dct:spatial [
        rdf:type dct:Location ;
        dcat:bbox """<http://www.opengis.net/def/crs/EPSG/0/4283> POLYGON((
          115.864566 -42.885989 , 115.864566 -12.460578 ,
          153.276835 -12.460578 , 153.276835 -42.885989 ,
          115.864566 -42.885989
        ))"""^^geosparql:wktLiteral ;
      ] ;
      dct:title "Judicial Courts"@en ;
      dct:type <http://purl.org/dc/dcmitype/Dataset> ;
      dcat:landingPage <https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/cc365600-294a-597d-e044-00144fdd4fa6> ;
    .

However EPSG::4283 (it's clearer if use the EPSG registry WKT~ http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4283)  is lat long.

So 115.864566 -42.885989  must be incorrect as lat has a range +/- 90

**Comment by andrea-perego** [comment]
Thanks for pointing this out, @nmtoken .

@dr-shorthair , would you please look into this?

**Comment by dr-shorthair** [comment]
Hmm. The error is in the original catalogue entry: 
https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search#/metadata/74767
I will check with GA, but meanwhile I guess I could flip the coord order.

**Comment by andrea-perego** [comment]
Thanks, @dr-shorthair , for fixing this in PR https://github.com/w3c/dxwg/pull/1135

@nmtoken , could you please check if you are happy with this revision?

https://w3c.github.io/dxwg/dcat/

**Comment by andrea-perego** [comment]
PR #1135 should have addressed the issue. If this is not the case, this should be reported in a new one.

Closing.
