### ISSUE TITLE
DCAT: Again about "recommended" properties

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1124]
Reviewing again the DCAT2 spec while working on the implementation report, I think we need to sort out the issue already raised in https://github.com/w3c/dxwg/issues/766 about what we list as "recommended" properties.

Re-thinking about it again, I'm no longer convinced of my proposal in https://github.com/w3c/dxwg/issues/766 . Rather, I'm questioning whether the use of "recommended" is actually what we mean.

If we look at what we list as recommended properties for each class reported in the implementation evidence spreadsheet, the majority (23 out of 27) are properties specific to that class, and not inherited by a parent class. 

Moreover, the use of "recommended" may be misunderstood, as it is more something you use in an application profile than in a vocabulary, as DCAT2, which does not specify restrictions / constraints on cardinality, etc.

Based on this, my proposal is to revise the (recurrent) statement:

> The following properties are recommended for use on this class ...

with 

> The following properties are specific to this class ...

and remove from the list the properties which are both recommended and inherited (ensuring they are nonetheless listed among the inherited ones).

The question is whether this change can be considered as editorial.

I would also propose to revise the note after the DCAT diagram, where the list of "recommended" properties in the figure does not reflect what said in the class description - quoting:

> The properties shown in each class reflect those recommended in the descriptions of classes in § 6. Vocabulary specification. To assist in understanding the full scope of each class, properties are copied down from each '::super-class'.

This text is stating that all the properties in the diagram are recommended, which is not at all the case.

So, I would change the text above by replacing "recommended" with "specified":

> The properties shown in each class reflect those **specified** in the descriptions of classes in § 6. Vocabulary specification. To assist in understanding the full scope of each class, properties are copied down from each '::super-class'.

**Comment by andrea-perego** [comment]
I created a draft PR implementing this proposal: https://github.com/w3c/dxwg/pull/1140

**Comment by dr-shorthair** [comment]
I believe that by 'recommended' we mean 'recommended for use in the context of individuals from this class'.

**Comment by andrea-perego** [comment]
PR #1140 merged.

Issue closed.
