### ISSUE TITLE
Aligning ADMS with DCAT

### ISSUE THREAD

**Issue by makxdekkers** [w3c/dxwg#113]
Related to https://github.com/w3c/dxwg/issues/110, I would also like to make a suggestion to drop the domain restrictions from [ADMS](https://www.w3.org/TR/vocab-adms/). 
While revision of ADMS is not in the charter of this group, it is quite possible that changes in DCAT will affect ADMS. I would like to suggest that this group consider aligning ADMS with DCAT after we have a new stable version of DCAT.

**Comment by nicholascar** [comment]
It would be great if such across-the-board alignment could be implemented! I guess this is possible since you are the author Makx?

**Comment by makxdekkers** [comment]
I would certainly want to try to do that, but depends on whether I'll have time to do it. Anyway, I'll put it on my to-do list, but would want to wait until we have a stable version of DCAT, at least after the next Public Working Draft.

**Comment by andrea-perego** [comment]
I think we need to raise this issue in one of the plenary calls, as (as you say, @makxdekkers ) the revision of ADMS was not explicitly included in the DXWG charter.

**Comment by dr-shorthair** [comment]
In #53 I propose to 'promote' adms:Identifier class to DCAT
I think this would also resolve #68 

THere may be other ideas from ADMS that could be added to DCAT instead. 
Otherwise, revision of ADMS is for another time and another working group.

**Comment by makxdekkers** [comment]
@dr-shorthair I agree with @andrea-perego that we need to raise this in a plenary call. ADMS is very closely linked to DCAT so it makes sense to keep them aligned.

**Comment by andrea-perego** [comment]
@makxdekkers , would you like to revive this issue? Or should we close it?

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
