### ISSUE TITLE
machine readible contributors in line with the html page

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1131]
Hi,

in the machine readible documents the list of contributors is different from the list in the html document? Maybe best to align them.

**Comment by riccardoAlbertoni** [comment]
Thanks for the comment.
Up to now, we have maintained the same principle used in DCAT1, whose RDF lists a broader number of contributors not mentioned in the normative document. This choice is in the spirit of acknowledging the authors and translators of the previous dcat releases and others who specifically contributed to the RDF encoding of DCAT 2.
