### ISSUE TITLE
5.1 DCAT Scope states 6 main classes, then shows 7.

### ISSUE THREAD

**Issue by chris-little** [w3c/dxwg#1137]
Section "5.1 DCAT scope" states there are 6 main classes. The text and Figure 1 both show 7 classes. Is one class not a main one, or are there 7?

Or am I missing something?

Creator: @chris-little

**Comment by agbeltran** [comment]
Thanks for checking this. 

The class that is not listed in section 5.1 is ```dcat:Relationship```. 

This class is 'at risk' (as indicated in 6.1 https://www.w3.org/TR/vocab-dcat-2/#Class:Relationship) pending evidence of its implementation.

In any case, it would be good to add a clarification, and take your comment into account once a decision is made around ```dcat:Relationship``` to have consistency across the document. This will include updating the text with the number of main classes and the figure in 5.1.

**Comment by chris-little** [comment]
@agbeltran Thanks.

**Comment by andrea-perego** [comment]
Actually, `dcat:Relationship` is not one of the key classes around which DCAT2 is built, as it has been specifically defined as a means to specify qualified relationships between resources. So, I would not consider it as a **main** class for DCAT2.

**Comment by dr-shorthair** [comment]
We can remove it from Figure 1. if you like.

**Comment by chris-little** [comment]
@andrea-perego and @agbeltran have resolved my issue and the action to update is being tracked.
