### ISSUE TITLE
Content-Profile default behaviour not explicit for single profiles or single profile hierarchy 

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#1149]
The spec states 

"When a resource is returned that conforms to two or more profiles that are not within a profile hierarchy (i.e. none of the multiple profiles the resource conforms to is a profiles of another), the server MUST indicate all conforming profiles individually within the Content-Profile header as such:

Content-Profile: <PROFILE_1>, <PROFILE_2>"

but it hasnt stated explicitly that this applies to a single profile.  Also if the client asks for profile A and profile B is a profile of profile A, then returning profile B is a valid response.   If we generalise this to 

"the server MUST indicate all conforming profiles individually within the Content-Profile header"

then the requirement is to return A and B - - in the same hierarchy.

**Comment by nicholascar** [comment]
@rob-metalinkage's suggestion is for him to create an example for this by PR in time for 3PWD release

**Comment by agreiner** [comment]
Can someone explain the benefit of doing this? It's not clear to me that this is really needed. When someone requests a dataset with a certain profile, does it really matter to them that the dataset returned happens to fit a different profile as well? It can be confusing compared to just stating which profile was chosen among the preferences given.

**Comment by rob-metalinkage** [comment]
I put the PR in shortly - but its actually only about reinforcing the simplest case of a single profile being reported - as you are focussing on.  We were guilty of addressing the inevitable complex case to make sure our model worked under all circumstances and failed to state the obvious - so this risks the complex case confusing the issue.

**Comment by rob-metalinkage** [comment]
On careful reflection the issue is the reference to MUST for HTTP in the abstract model - rewritten to make the HTTP example an example, also relaxed to SHOULD - as conceptually a response may conform to profiles the server does not actually know about.

**Comment by rob-metalinkage** [comment]
merged
