### ISSUE TITLE
DCAT2 implementation in RDF4J

### ISSUE THREAD

**Issue by barthanssens** [w3c/dxwg#1150]
Not sure if this really counts as an implementation, but I'm working on adding the URIs of the DCAT2 classes and properties as a convenience class with java constants to Eclipse RDF4J (which already contains a class for DCAT 1.x)

https://github.com/eclipse/rdf4j/issues/1580

**Comment by andrea-perego** [comment]
Thanks for reporting this implementation, @barthanssens .
