### ISSUE TITLE
What kind of dataset is dataset-001?

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#1155]
Are the small examples given in the DCAT spec supposed to be building up a more complete picture of a bigger example?

If yes, then I'm puzzled by the story told for dataset-001. In example 6 its primary type says it is a dataset of manuscripts. But its content type in example 7 is "standard office documents", which hints these were not created purely by hand. And its temporal coverage elsewhere says it covers 2006. It's unlikely manuscripts would be created as a main source of data at or after that date. And it has a distribution as csv files, later.

I reckon that it is meant to be an imaginary dataset. Still we could aim at presenting slightly more consistent chimeras :-)

This is probably for future work anyway.

**Comment by riccardoAlbertoni** [comment]
Thanks for this editorial suggestion. Though it is not substantial, I agree that we could aim at presenting slightly more consistent chimaeras. So,  as a reminder, I have labelled this issue as future work.

**Comment by riccardoAlbertoni** [comment]
@aisaac, please take a look at PR #1361 , it changes the examples considering your remarks.

**Comment by riccardoAlbertoni** [comment]
> @aisaac, please take a look at PR #1361 , it changes the examples considering your remarks.

@aisaac: PR 1361 has been merged, if there are no objections, I think we can close this issue...

**Comment by aisaac** [comment]
@riccardoAlbertoni sorry for the delay. It doesn't look so inconsistent anymore, so this can be closed!
