### ISSUE TITLE
naming convention of dcat:catalog

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#1156]
This is probably too late for this round, but re-reading the spec I realize that the naming of dcat:catalog is not great: if follows the same convention as dcat:service, dcat:record and dcat:dataset, but instead of linking to a resource that is being catalogues, it links to a resource that catalogues. The naming could instead have better represented that the case here is to represent a part (and that the superproperty is dcterms:hasPart).

For future work?

**Comment by riccardoAlbertoni** [comment]
@aisaac, thanks for the comment.

 I understand your point, I am not sure that your point offers a reason to change the property name in the future. Surely that is something we cannot do at this stage.

 Anyway,  I agree that your observation is something to consider for discussion in future. For this reason, I have labelled this issue as "future work".

**Comment by riccardoAlbertoni** [comment]
@aisaac: I was reconsidering this issue after a while. My apologies for having kept this pending so long.

I think `dcat:catalog` links to a resource that catalogs and that is cataloged.  So I am not sure of an actual inconsistency with the name conventions.

Besides,  changing the name of `dcat:catalog` at this stage breaks the back-compatibility with DCAT 2, which is something that we would like to avoid.  

I wonder if your point implies any concerns that I am not fully catching. Otherwise, if you have no objections I would close this issue.

**Comment by aisaac** [comment]
Hi @riccardoAlbertoni sorry for taking so long. I missed the notification.
Actually your answer may alleviate my worry: `dcat:catalogue` points to a resource (Catalogue) that is considered to being catalogued into the subject Catalogue, just like objects of `dcat:dataset` statements for the same Catalogue?
If yes then this would sound ok to me. But then can I ask for the definition to be clarified? It currently reads "A catalog whose contents are of interest in the context of this catalog". This sounds a much weaker relationship than what you're hinting now.
How about changing the definition to something like "A catalogue that is listed in the catalog because its contents are of interest in the context of this catalog."? Such wording would be more fitting what I expect for what you say, and much better aligned with the definitions of other sub-properties of `dcterms:hasPart` (`dcat:record`, `dcat:service`).

**Comment by riccardoAlbertoni** [comment]
Thanks, @aisaac 
I would slightly rephrase  your proposal as in the following

> "A catalog that is listed in this catalog because its contents are of interest."

Would this rephasing work for you?

**Comment by andrea-perego** [comment]
@riccardoAlbertoni said:

> Thanks, @aisaac
> I would slightly rephrase your proposal as in the following
> 
> > "A catalog that is listed in this catalog because its contents are of interest."
> 
> Would this rephasing work for you?

Or, more simply:

> A catalog that is listed in this catalog.

This would be in line with the definitions of `dcat:dataset` and `dcat:service`. Or there's a reason why having a metadata record about a catalogue is different from having records of datasets and services?

**Comment by riccardoAlbertoni** [comment]
> A catalog that is listed in this catalog.

It works for me.

**Comment by riccardoAlbertoni** [comment]
@aisaac: PR  #1370 has been merged, if there are no objections, I propose to close this issue.

**Comment by aisaac** [comment]
Yes it's perfect!
