### ISSUE TITLE
Broken Creative Commons link

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#1169]
DCAT  has a link to the Creative Commons website in Section 8 (http://raw.githack.com/w3c/dxwg/dcat-remove-at-risk-notes/dcat/index.html#license-rights) in the third Note that is no longer valid.

Would https://creativecommons.org/share-your-work/licensing-considerations/ be a suitable replacement or is https://creativecommons.org/share-your-work/licensing-examples/ a better choice?

**Comment by riccardoAlbertoni** [comment]
I probably prefer the first link which links quite straightly to the "License Chooser". The second offers examples, but also many links in which one can get lost.

**Comment by andrea-perego** [comment]
Actually, I think the 2nd is preferable, as it starts with the list of CC licences - which is what the DCAT spec is talking about. 
Otherwise, based on @riccardoAlbertoni point, I'd rather directly link to the CC licence chooser:

https://creativecommons.org/choose/

**Comment by riccardoAlbertoni** [comment]
I think this issue is outdated: the link in the third note  of section 8 which is about creative commons already points to https://creativecommons.org/share-your-work/licensing-examples/
