### ISSUE TITLE
dcat:record - check constraints

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#118]
In DCAT v1 the property `dcat:record ` is axiomatized 
```
dcat:record
  rdf:type owl:ObjectProperty ;
  rdfs:domain dcat:Catalog ;
  rdfs:range dcat:CatalogRecord ;
.

```

1. Verify that the range is appropriate and necessary
2. Verify that the domain is appropriate and necessary (see #110)
3. Consider whether any guarded constraints (using owl:Restriction) should be introduced (see #105)

**Comment by makxdekkers** [comment]
I would vote to keep the domain and range here -- this property is one of the properties that are part of the backbone structure of DCAT:
Catalog > record > CatalogRecord

**Comment by dr-shorthair** [comment]
Is an inverse property needed?

**Comment by dr-shorthair** [comment]
Makx' makes a compelling case for retaining domain and range. 

I'll bring this proposition to the next DCAT team telecon for resolution.

**Comment by dr-shorthair** [comment]
+1 to no change

**Comment by dr-shorthair** [comment]
https://www.w3.org/2018/03/21-dxwgdcat-minutes
resolved: no change to domain/range of dcat:record
