### ISSUE TITLE
Content negotiation for http://www.w3.org/ns/dcat# 

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1196]
At the moment, http://www.w3.org/ns/dcat# resolves to the old DCAT 2014 land page and related RDF serialization.

As soon as DCAT 2 is ready to get  REC status, we should ask the w3c webmaster (?!?) to 
- replace the old landing page with the one prepared for DCAT2  at https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.html 
- update the content negotiation for http://www.w3.org/ns/dcat# accordingly
- update the links to the published serialization in section 6.1 of the REC

**Comment by plehegar** [comment]
I should be able to do those. It's on my TODO list for the REC release.

**Comment by plehegar** [comment]
New dcat.html in place. content negotiation done.

**Comment by plehegar** [comment]
For changes in 6.1, see https://github.com/w3c/dxwg/pull/1214

**Comment by riccardoAlbertoni** [comment]
Content negotiation for DCAT has been deployed and tested see #1215 
So I think we can close this issue.
