### ISSUE TITLE
Editorial fixes

### ISSUE THREAD

**Issue by plehegar** [w3c/dxwg#1200]
This came from the AC review. There are a couple of trivial typos.

1. In the Status section, suggest that the hyperlink in this sentence: "The exit criteria also included recent commitments by organisations such as EC Joinup to adopt the DCAT v2 model in their work - see https://joinup.ec.europa.eu/solution/abr-specification-registry-registries/document/specification-registry-registries-version-meeting-september." be applied to the words "adopt the DCAT v2 model" (and the long URL thereby hidden from public view).

2. In DCAT history, 2nd para, note the erroneous gap in the word 'set'.

**Comment by andrea-perego** [comment]
This is to note that DCAT-AP 2 has been released in November 2019 - see https://joinup.ec.europa.eu/solution/dcat-application-profile-data-portals-europe/release/200

So, I wonder whether we should update the SOTD section accordingly - it is no longer a commitment, but an existing implementation.
