### ISSUE TITLE
MD_scope_codes link is dead

### ISSUE THREAD

**Issue by pwin** [w3c/dxwg#1202]
The link for https://geo-ide.noaa.gov/wiki/index.php?title=ISO_19115_and_19115-2_CodeList_Dictionaries#MD_ScopeCode in DCAT v2 section 5.5 is dead - it has a dated certificate and returns a 404

Suggestion: ftp://ftp.ncddc.noaa.gov/pub/Metadata/Online_ISO_Training/Intro_to_ISO/workbooks/BIO_Metadata.pdf in table C.24

Is there anything similar in HTML that we could use here in place of the existing link?

**Comment by smrgeoinfo** [comment]
https://standards.iso.org/iso/19115/resources/Codelists/gml/MD_ScopeCode.xml  is a better link.

see also #975
