### ISSUE TITLE
Issue with dct:hasPart as described in DCAT

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#1205]
I think there is possibly a set of issues with `dct:hasPart` as it is currently described in DCAT.

1. In the diagram and [in Catalog description](https://www.w3.org/TR/vocab-dcat-2/#Property:catalog_has_part) it has a domain (`dcat:Catalog`) and a range (`dcat:Resource`) defined.

As I [expressed elsewhere](https://github.com/w3c/dxwg/issues/725#issuecomment-513442046), I have a problem with DCAT imposing domains and ranges on external properties, as this is, in my opinion, basically saying "whoever uses `dct:hasPart` anywhere, from now on, the instances of subjects are (among other things) `dcat:Catalog`s and instances of objects are (among other things) `dcat:Resource`s.", which I think is undesirable.

However, even if I view this statement only "in the context of DCAT", this is still problematic due to a second issue:

2. In the usage note of [dcat:qualifiedRelation](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_qualified_relation) it says:

> Used to link to another resource where the nature of the relationship is known but does not match one of the standard [DCTERMS] properties (dct:hasPart, ...

and in the usage note of the [Relationship class](https://www.w3.org/TR/vocab-dcat-2/#Class:Relationship) it says:

> Use to characterize a relationship between datasets, and potentially other resources, where the nature of the relationship is known but is not adequately characterized by the standard [DCTERMS] properties (dct:hasPart

From both usage notes I gather that if I want to model that one dataset is part of another dataset (or a dataset series), I would use `dct:hasPart`, not a qualified relation. This again has issues:

3. The work on dataset series was moved to DCAT 3 (#868 #806), however, the usage notes above suggest `dct:hasPart` should be used, not qualified relation, for "part of" relationship. This potentially interferes with the usage of qualified relation for dataset series in DCAT 3.
4. If `dct:hasPart` was used, even in scope of DCAT, my `dcat:Dataset` representing the series would also become `dcat:Catalog` thanks to the [domain definition](https://www.w3.org/TR/vocab-dcat-2/#Property:catalog_has_part), which I also see as an undesired side-effect, and potentially interfering with the usage of `dct:hasPart` for dataset series in DCAT 3 unless we say that a dataset representing a dataset series is in fact a catalog.

**Comment by smrgeoinfo** [comment]
Seems like the problem is distinguishing a dataset (including a dataset series) as partOf a catalog, from dataset as partOf a series (independent of any catalog).   If we declare dct:hasPart domain dcat:Catalog we are clearly restricting the usage to denote membership in a catalog.  I don't think membership(partOf) in a series is same as membership(partOf) in a catalog.  In the future, this might be clarified by defining a 'membership/hasMember' property for a catalog, and a 'partOf/hasPart' relation to denote aggregation of granules in a series.

**Comment by dr-shorthair** [comment]
I agree that in the documentation of `dcterms:hasPart` we should make it clear which scope notes apply in which specific context.  As mentioned in https://www.w3.org/TR/vocab-dcat-2/#Property:resource_relation `hasPart` can be used in other places, for example for a multi-part dataset. 

So we should tweak the documentation here: https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-external.ttl#L147 
But I don't think there are any axioms that are harmful.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> I agree that in the documentation of `dcterms:hasPart` we should make it clear which scope notes apply in which specific context. As mentioned in https://www.w3.org/TR/vocab-dcat-2/#Property:resource_relation `hasPart` can be used in other places, for example for a multi-part dataset.
> 
> So we should tweak the documentation here: https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-external.ttl#L147
> But I don't think there are any axioms that are harmful.

I concur. However, I think we should drop the indication of the domain in the spec, to avoid any misunderstanding.

**Comment by andrea-perego** [comment]
> [...] However, I think we should drop the indication of the domain in the spec, to avoid any misunderstanding.

Done via PR https://github.com/w3c/dxwg/pull/1260 . Also removed range.

Waiting for DCAT editors review.

@jakubklimek , does this address the issue?

**Comment by jakubklimek** [comment]
@andrea-perego The PR solves the domain/range and side-effects issue.

What remains to be solved is the relation of usage notes in [dcat:relation](https://w3c.github.io/dxwg/dcat/#Property:resource_relation) and [dcat:QualifiedRelation](https://w3c.github.io/dxwg/dcat/#Property:resource_qualified_relation) to the solution to Dataset Series #806 .
