### ISSUE TITLE
dcat:keyword- check constraints

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#121]
In DCAT v1 the property `dcat:keyword` is axiomatized 
```
dcat:keyword
  rdf:type owl:DatatypeProperty ;
  rdfs:domain dcat:Dataset ;
  rdfs:range rdfs:Literal ;
  rdfs:subPropertyOf dcterms:subject ;
.
```

1. Verify that the range is appropriate and necessary
2. Verify that the domain is appropriate and necessary (see #110)
3. Consider whether any guarded constraints (using owl:Restriction) should be introduced (see #105)

**Comment by dr-shorthair** [comment]
Range axiom is redundant, given that it is `rdf:type owl:DatatypeProperty`

**Comment by dr-shorthair** [comment]
Descriptors like this are correctly attached to the dataset. 
However, utility also depends on being able to navigate back from a distribution - see https://github.com/w3c/dxwg/issues/120#issuecomment-373196754 

But isn't there also a case for having keywords and theme on a Catalog - to enable classification of a discipline- or community-specific catalog service?

**Comment by fellahst** [comment]
I suggest dropping the domain restriction on dcat:keyword (but also dcat:theme) as it can be used in other contexts than Datasets. In SRIM and Geoplatform profile dcat:theme has been promoted to Asset as it can be reused for different types of assets (Map, Layer, Style, Service, Gallery,etc..)

**Comment by dr-shorthair** [comment]
+1 to drop global domain constraint

**Comment by riccardoAlbertoni** [comment]
Am I the only who find the distinction between dcat:keyword and dcat:theme a  little artificial/confusing?   DCAT suggests dcat:theme to classify the dataset according to the catalog's concept scheme, but I would have considered perfectly acceptable its usage to provide tags/keyword as skos:concepts instead of literals.  

I suspect that dropping the domain constraint for dcat:keyword might spread such a confusion on other artefacts (e.g. catalog and distribution).  Perhaps, I would provide more guidance on when to use dcat:keyword and when dcat:theme before removing their domains.

**Comment by dr-shorthair** [comment]
The goal of both is similar. They are both sub-properties of `dcterms:subject`. But: 

- `dcat:keyword` is an `owl:DatatypeProperty`. Its value is a literal (string)
- `dcat:theme` is an `owl:ObjectProperty`. Its value is a `skos:Concept`. 

`dcat:theme` would always be preferred **if a suitable SKOS ConceptScheme is available** because you can more precisely test if different datasets are classified with the same `skos:Concept`, while `dcat:keywords` would involve text comparisons. But people still need to enter keywords as free text sometimes. Yes - more textual guidance is always helpful. @riccardoAlbertoni could you propose some text? 

The proposal to drop domain constraints is to allow them either to be used on more classes, so we don't need yetanother property to attach a them or keyword to Catalogs etc.

**Comment by dr-shorthair** [comment]
Also see https://github.com/w3c/dxwg/wiki/Data-aspects---semantics

**Comment by dr-shorthair** [comment]
https://www.w3.org/2018/03/21-dxwgdcat-minutes
resolved: relax (remove) domain constraint on dcat:keyword

**Comment by dr-shorthair** [comment]
See #171

**Comment by kvistgaard** [comment]
I keep finding the remaining 

```
dcat:keyword
  rdf:type owl:DatatypeProperty ;
  rdfs:range rdfs:Literal ;
.
```

as very restrictive. I would suggest removing the range considering type it only  `rdf:Property` which will cover all use cases. If that's not acceptable, then `owl:ObjectProperty`. But not as `owl:DatatypeProperty`. 

Using `dcat:theme` in cases of `skos:Concept` is not sufficient. For example, in EU data themes are controlled by [this NAL](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/data-theme). This is a useful classification which does not replace the need for keywords, using in other `skos:Concept`.

**Comment by dr-shorthair** [comment]
`dcat:keyword` is intended to hold a literal. 
It is not meant to hold a pointer to a web-resources.
