### ISSUE TITLE
Inheritance terminology not appropriate for RDFS and OWL

### ISSUE THREAD

**Issue by rawmatt** [w3c/dxwg#1228]
4 places in [the Recommendation](https://www.w3.org/TR/vocab-dcat-2/#Class:Catalog) refer to "_The following properties are inherited from the super-class_". The problem with this is that there is no concept of inheritance in the RDFS and OWL ecosystem.

From the OWL2 Primer:
> Furthermore, OWL is a strictly declarative and logical language. OWL therefore has none of the operational aspects of OOP, like methods, and similarly reasoning in OWL is strictly logical, with nothing comparing to inheritance, particularly inheritance with exceptions or overriding. - https://www.w3.org/2007/OWL/draft/ED-owl2-primer-20090414/

In my opinion, referring to Sub-Properties as Inheritance is mis-leading. The term is not defined in the normative references, and therefore leaves the statement ambiguous.

My personal experience implementing DCAT v2  is using OOP terminology causes implementers to incorrectly assume normal OOP semantics.

Please consider removing OOP terminology and replacing with RDFS and OWL terminology.

**Comment by dr-shorthair** [comment]
Thanks @rawmatt you are strictly correct of course. This was loose language. The intention is merely to draw attention to properties associated with the super-class (through either global domain-range constraints, or local restrictions) which would therefore also be associated with sub-classes. 

Would it be OK to write "The following properties associated with the super-class are also available for use."?

**Comment by rawmatt** [comment]
Yes, that would be OK.

How about: "The following properties of the super-class are also available for use." I suggest this because "associated" is undefined, and is also OOP terminology. "Of" is such plain English that I don't think it could be taken as implying anything extra.

**Comment by dr-shorthair** [comment]
@rawmatt I note that the [section that you quote](https://www.w3.org/2007/OWL/draft/ED-owl2-primer-20090414/#Object-oriented_Programming) was in an appendix that did not survive into the [final version of the Primer](https://www.w3.org/TR/owl-primer/) - is there a current reference I can use?

**Comment by rawmatt** [comment]
@dr-shorthair if the term is to be replaced, as you propose, why would it need a reference? Why reference an unused term or concept?

W3C Recommendations seem to state what things are, rather than what they are not. My understanding is nothing could be inferred from the absence of a statement in the [final version of the Primer](https://www.w3.org/TR/owl-primer/), only from what is present.

The issue is the term is undefined in the normative sections and references, and neither does it have its usual or common (OOP) meaning. The Primer is quoted as illustratory only; the Primer is not the source of the issue.

**Comment by dr-shorthair** [comment]
OK @rawmatt you are a good standards lawyer ;-) I've done a bit of that myself so can recognise and respect the argument. However, I was actually thinking that it might be useful to mention this argument in the (non-normative) note below the caption to this figure: 
https://www.w3.org/TR/vocab-dcat-2/#UML_DCAT_All_Attr
which explains that the summary diagram is not UML.

**Comment by rawmatt** [comment]
Yes, I agree wholeheartedly about the diagram. My personal experience of implementing DCAT v2 is that the use of UML notation in Figure 1 reinforced the incorrect assumption of OOP semantics. 

Today, I had the use of UML notation in that diagram quoted to me as justifying assuming OOP semantics.

That diagram uses UML Generalization to represent SubClassOf, which is conflating implementation inheritance with sub typing.

The [Note](https://www.w3.org/TR/vocab-dcat-2/#dcat-scope) say it "...uses UML-style class notation...", yet based on the [UML Specification](https://www.omg.org/spec/UML/2.5.1/PDF), I believe that the most apt UML Relationship is not UML Generalization, but is instead UML Substitution. If UML style notation is to be used, then it should be correct UML style notation.

**Comment by dr-shorthair** [comment]
> Today, I had the use of UML notation in that diagram quoted to me as justifying assuming OOP semantics.

Did you point to the NOTE: ?

**Comment by rawmatt** [comment]
Yes - the NOTE is very helpful.

**Comment by dr-shorthair** [comment]
FWIW - There is plenty of precedent using open arrow-heads for sub-classes. See 

- https://www.w3.org/TR/vocab-org/
- https://www.w3.org/TR/vocab-data-cube/
- https://www.w3.org/TR/vocab-dqv/

And also the standard IDEs (TopBraid, Protege visualization plugins). 

I certainly see where you are coming from arguing for UML Substitution, but it is not widely known outside UML circles, the visual notation is messy (dashed connector with a stereotype), and it risks making the UML connection even stronger, so I'm disinclined to change horses.
