### ISSUE TITLE
dcat:theme - check constraints

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#123]
In DCAT v1 the property `dcat:theme` is axiomatized 
```
dcat:theme
  rdf:type owl:ObjectProperty ;
  rdfs:domain dcat:Dataset ;
  rdfs:range skos:Concept ;
  rdfs:subPropertyOf dcterms:subject ;
.
```

1. Verify that the range is appropriate and necessary
2. Verify that the domain is appropriate and necessary (see #110)
3. Consider whether any guarded constraints (using owl:Restriction) should be introduced (see #105)

**Comment by andrea-perego** [comment]
I would be in favour of dropping the domain restriction.

In GeoDCAT-AP, such restriction prevented the use of `dcat:theme` when describing a service (and so `dct:subject` is used instead). Which makes this case related to #64.

`dcat:theme` could be also useful for describing the content of a `dcat:Catalog` (an information that can be inferred from the `dcat:theme`'s of the related datasets). Scenarios where this information could be relevant include (a) federated harvesting and (b) registries of data catalogues / repositories - e.g., [re3data](https://www.re3data.org/) and [fairsharing.org](https://fairsharing.org/).

**Comment by akuckartz** [comment]
:+1: for dropping the domain restriction

**Comment by dr-shorthair** [comment]
@andrea-perego is the GeoDCAT-AP or re3data/fairsharing issue mentioned in any of the UCs?

**Comment by andrea-perego** [comment]
> @andrea-perego is the GeoDCAT-AP or re3data/fairsharing issue mentioned in any of the UCs?

Nope. I think this can be added to the UC @jpullmann is going to create about relaxing domain/range restrictions for properties defined in the DCAT namespace.

I'll create the relevant action in the tracker (as trackbot was not able to record it yesterday), and include a link to the GH issues that can be used for the content of that UC.

**Comment by andrea-perego** [comment]
> I'll create the relevant action in the tracker (as trackbot was not able to record it yesterday), and include a link to the GH issues that can be used for the content of that UC.

Well, it seems I am not authorised to create actions in the W3C tracker. @draggett could you please help?

**Comment by andrea-perego** [comment]
> Well, it seems I am not authorised to create actions in the W3C tracker. [...]

While waiting that an action is created in the tracker, I added it as a GH issue (#130).

**Comment by arminhaller** [comment]
👍 to drop domain restriction.

**Comment by dr-shorthair** [comment]
@andrea-perego has provided evidence of why the domain constraint is harmful because it prevented a dcat:theme being applied to a service. 

In #121 I've also made what I think is an even easier case for thematic classifiers on catalogs. 
So it looks like it would be beneficial to drop the domain constraint. 

I see no reason to relax the range constraint - skos:Concept is good, at least it hints at use of a controlled vocabulary (usually a ConceptScheme from the Catalog/themeTaxonomy). 

I'll bring this proposition to the next DCAT team telecon for resolution.

**Comment by andrea-perego** [comment]
@dr-shorthair , I was thinking that, if we drop / relax the domain restriction of `dcat:theme`, we should try to provide guidance on when to use `dcat:theme` and when `dcat:themeTaxonomy` with a `dcat:Catalog`. The possibility of using both (whereas in the original version of DCAT only `dcat:themeTaxonomy` was allowed) may lead to some confusion and inconsistent practices.

**Comment by dr-shorthair** [comment]
+1 to drop global domain constraint, and add guidance about use of `dcat:theme` alongside `dcat:themeTaxonomy` in context of `dcat:Catalog`

**Comment by dr-shorthair** [comment]
https://www.w3.org/2018/03/21-dxwgdcat-minutes
resolved: relax (remove) domain constraint on dcat:theme

**Comment by dr-shorthair** [comment]
See #171

**Comment by rajaram5** [comment]
@dr-shorthair 

Why not relax range constraint for `dcat:theme`? In the biomedical domain we have more ontologies and often these ontologies have `owl:Class` typing for concepts.

**Comment by andrea-perego** [comment]
@rajaram5 , thanks for your question.

This issue is closed, so I moved your comment to a new one: https://github.com/w3c/dxwg/issues/1364

Please continue there all discussion.
