### ISSUE TITLE
WKT examples have wrong datatype

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#1233]
The WKT examples in https://www.w3.org/TR/vocab-dcat/#spatial-properties have the literals typed `geo:asWKT`. Should be `geo:wktLiteral`.

**Comment by andrea-perego** [comment]
Indeed, Thanks for spotting this, @dr-shorthair .

**Comment by agbeltran** [comment]
This should probably be added to the errata for DCAT2 as well.

**Comment by andrea-perego** [comment]
@agbeltran said:

> This should probably be added to the errata for DCAT2 as well.

+1

**Comment by riccardoAlbertoni** [comment]
I wonder if we should mark this errata as "editorial".

**Comment by andrea-perego** [comment]
@riccardoAlbertoni said:

> I wonder if we should mark this errata as "editorial".

It's a typo, and about an example, so I would consider it as editorial.

**Comment by akuckartz** [comment]
It is not a typo but a completely different word.

**Comment by agbeltran** [comment]
Summary: geosparql:asWKT (a DatatypeProperty) was changed to geosparql:wktLiteral (a Datatype) throughout the specification and examples. All usages are in non-normative examples or comments. Typos corrected in <a href="https://github.com/w3c/dxwg/pull/1234">#1234</a>. The corrections will appear in the next PWD.
