### ISSUE TITLE
dct:publisher is repeated twice in image

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1252]
In the image dct:publisher appears twice. As property from dcat:Resource and from dcat:Catalog. 

Because dcat:Catalog is a subclass from dcat:Resource, only the association from dcat:Resource is sufficient.

Note that dct:creator only appears once.

**Comment by dr-shorthair** [comment]
The image is non-normative - as explained in the caption. Inherited associations are shown where it was judged helpful for people reviewing the model. (and anyway, 'inheritance' is a concept from OO/UML that does not really belong in OWL/RDF.)

**Comment by bertvannuffelen** [comment]
First a reaction on your comment on inheritance:

Inheritance or better the logical notion of subclass are part of OWL. cfr: owl:subclassOf. 

Since here for the picture UML notation has been used and there are 2 arrow notations used in the figure, I can safely assume that the UML inheritance arrow corresponds with owl:subclassOf relation. 

Unless you disagree with this interpretation, I think we can use in this context inheritance en subclass interchangeable. 

So a property associated with dcat:Resource is applicable on dcat:Catalog, dcat:Dataset and dcat:DataService.


So back to my original question: is there a particular reason why dct:publisher is explicitly added to the picture for dcat:Catalog? If not, fine with me. But the question came to my mind because I followed the above reasoning, and that if they are the same (no additional information) then the picture can be more condensed.

**Comment by riccardoAlbertoni** [comment]
We have implemented two alternative solutions for making fig 1 more coherent... 
Either  adding the dcterms:creator arrow from dcat:Catalog to foaf:Agent as in  PR #1399  or deleting dcterm:publisher arrow starting from catalog  as in PR #1400
@bertvannuffelen: Is there one you prefer?

**Comment by riccardoAlbertoni** [comment]
We have deleted dcterm:publisher arrow starting from catalog from fig 1.  If there are no objections  I think we can close this issue.
