### ISSUE TITLE
Backward (in)compatibility among versions.

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1258]
Whether or not a new version of the resource is backward compatible with the previous version might be relevant in concrete applications. 

<code>owl:backwardCompatibleWith</code> / <code>owl:incompatibleWith</code>  can specify (in)compatibility among ontologies, but  [Section 3.5 in  OWL 2 specification](https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Ontology_Annotations) discourages their use for other kinds of resources.

Are there any other properties apart from <code>owl:backwardCompatibleWith</code> / <code>owl:incompatibleWith</code>, which could be usable with DCAT resources?

**Comment by andrea-perego** [comment]
@agreiner said in https://github.com/w3c/dxwg/issues/1275 :

> Backward compatibility seems unhelpful for datasets, but helpful for software. I think it is a great idea to support metadata about software! If we support that, we should also think about supporting other aspects of software (e.g., language, OS compatibility).

**Comment by agreiner** [comment]
The reason that I say backward compatibility isn't helpful for datasets is that it's pretty near impossible to predict what features of a dataset are being relied upon by any given usage. So if one were to come upon a revised dataset that claimed to be compatible with its previous versions, one would have to determine exactly what had changed to decide whether or not to believe it was indeed compatible. If compatibility were expressed more granularly, it could be helpful. That would essentially be a change log.

**Comment by andrea-perego** [comment]
> The reason that I say backward compatibility isn't helpful for datasets is that it's pretty near impossible to predict what features of a dataset are being relied upon by any given usage. So if one were to come upon a revised dataset that claimed to be compatible with its previous versions, one would have to determine exactly what had changed to decide whether or not to believe it was indeed compatible. If compatibility were expressed more granularly, it could be helpful. That would essentially be a change log.

@agreiner , about the changelog, there's a specific property  currently recommended in [the draft](https://w3c.github.io/dxwg/dcat/#version-info) - `adms:versionNotes` - for a free-text description of the version "delta", whereas an issue has been opened  for machine-actionable descriptions (diffs, etc.) - see https://github.com/w3c/dxwg/issues/1271

A possible revision we can then do is elaborating more on backward compatibility, highlighting the importance of providing a changelog.

WDYT?

**Comment by andrea-perego** [comment]
The new draft of the versioning section in PR https://github.com/w3c/dxwg/pull/1295 has temporarily moved this aspect to a specific section:

https://raw.githack.com/w3c/dxwg/dcat-versioning-v2/dcat/index.html#version-backward-compatibility

Based on what discussed so far, we have a number of options:

1. We remove this section, recognising that this aspect is specific to only some types of resources (ontologies, vocabularies, etc.), and elaborate about the use of `adms:versionNotes` to describe changes to a resource that may have an impact on backward compatibility

2. We define specific properties in the DCAT namespace corresponding to the OWL ones, but applicable to any kind of resource

3. Any other?

**Comment by agreiner** [comment]
As a part of DCAT, a binary indicator of backward compatibility for a dataset doesn't strike me as a good idea, since what makes a dataset unusable for one purpose has no effect on another, so I vote for 1. I agree it's a good idea to provide a changelog for a dataset, and VersionNotes is a very reasonable place for that. I think that backward compatibility should be noted for a vocabulary in the spec for the vocab itself. I don't think that a vocabulary is data unless you take the point of view that everything on the web is data, which is of course philosophically defensible but doesn't help in scoping a vocabulary like DCAT. It seems to me a binary indicator of backward compatibility for a dataset as a whole is more likely to be misleading than not.

**Comment by aisaac** [comment]
Just a note on the very first problem here (I will not dive into the issue of whether we need properties to represent (in)compatibility!). The fact that the [formal semantics of OWL](https://www.w3.org/TR/2012/REC-owl2-rdf-based-semantics-20121211/) specify that the domains and ranges of `owl:backwardCompatibleWith` and `owl:incompatibleWith` are owl:Ontology is quite a showstopper for using these two properties specifically. In general I'm not the one that is bothered too much by the consequence of applying OWL reasoning, as few among us do it. But in this case it could have quite bad consequences. The notion of ontology is quite flexible, but I'm not  very comfortable with saying that potentially any DCAT dataset could be named an ontology.

**Comment by andrea-perego** [comment]
Thanks, @agreiner & @aisaac .

Based on what discussed so far, I would then suggest we go for option (1) and drop these properties. 

As usual, we can revive this issue in case we receive relevant use cases.

Any objections?

**Comment by agreiner** [comment]
nope

**Comment by riccardoAlbertoni** [comment]
Solution 1 is good for me.

**Comment by andrea-perego** [comment]
Thanks, @agreiner & @riccardoAlbertoni .

Revision implemented via commit https://github.com/w3c/dxwg/commit/79125c11398d6eb337c798a0e3a93491ec05c6e2

Summary of relevant changes:
- Removed section on backward compatibility
- Added usage note to `adms:versionNotes`, mentioning explicitly its use for describing backward compatibility issues:
  - https://raw.githack.com/w3c/dxwg/dcat-versioning-v2/dcat/index.html#Property:resource_version_notes
  - https://raw.githack.com/w3c/dxwg/dcat-versioning-v2/dcat/index.html#version-info

Please review.
