### ISSUE TITLE
Dataset series and inheritance

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1273]
Should we guide inheritance for other annotation properties in the dataset series?

**Comment by andrea-perego** [comment]
This topic was partially discussed in https://github.com/w3c/dxwg/issues/1307

I report below the relevant comments.

@agreiner - https://github.com/w3c/dxwg/issues/1307#issuecomment-793225598

> I would suggest keeping only the inSeries property, so that one needn't worry about updating metadata for the series every time a new dataset is added to that series.

@riccardoAlbertoni - https://github.com/w3c/dxwg/issues/1307#issuecomment-801550988

> I suspect the metadata of the dataset series needs to be updated anyway. Especially if we keep the upstream inheritance explained in https://raw.githack.com/w3c/dxwg/dcat-dataseries-issue1272/dcat/index.html#dataset-series where it is said: "The update date (dcterms:modified) of the dataset series should correspond to the latest publication or update date of the child datasets."

@agreiner - https://github.com/w3c/dxwg/issues/1307#issuecomment-803658293

> [...]  I think any property that assumes people will make updates to a published dataset’s metadata is flawed. Even the most diligent publishers of data will never be able to update copies of datasets that find their way to secondary sites and to users. Update dates only make sense to me when they reflect the state when the dataset (or series) was published.

**Comment by riccardoAlbertoni** [comment]
close as a result of the resolution  https://www.w3.org/2022/02/08-dxwgdcat-minutes.html#r04
