### ISSUE TITLE
PROF - correctness of RDF serialisation in Example 3

### ISSUE THREAD

**Issue by pwin** [w3c/dxwg#1284]
EXAMPLE 3: Demonstrating conformance via the vocabulary's dct:conformsTo/prof:isProfileOf property chain.
# Profile X, is a profile of Specification Y
<http://example.org/profile/x> a prof:Profile ;
      prof:isProfileOf <http://example.org/specification/y>
      dct:title "Profile X" .

missing ";" at the end of the penultimate line

**Comment by andrea-perego** [comment]
@pwin , I guess this issue should be submitted at: https://github.com/w3c/dx-prof/issues

**Comment by pwin** [comment]
Indeed.  Sorry for the mistake.  Thanks
