### ISSUE TITLE
Dataset to Catalog association

### ISSUE THREAD

**Issue by riannella** [w3c/dxwg#1288]
It would also be useful to add a new explicit association from Dataset to Catalog.
(inverse of dcat:dataset)

**Comment by dr-shorthair** [comment]
Creating purely inverse relationships is often frowned upon, with the argument that the same effect can be gained by including a single triple in the original direction in the dataset, so having the inverse is unnecessary.

**Comment by andrea-perego** [comment]
@riannella , is @dr-shorthair 's reply addressing your comment?

If this is not the case, could you please explain the use case behind the proposal of  supporting the inverse of `dcat:dataset`?

**Comment by riannella** [comment]
The use case is Aviation datasets.
We are working on a mapping to use DCAT now: https://ext.eurocontrol.int/aixm_confluence/display/ADS/DCAT2+and+ISO+19115+representation

You can see there is a requirement in the Dataset to refer to which Dataset Series (dcat:Catalog) it belongs to.

We currently use the general dct:isPartOf property.

(We prefer not to expose dataset users to owl:inverseOf concepts, when we can make the property more explicit)

**Comment by andrea-perego** [comment]
Thanks, @riannella . So, basically, this is about how to map to DCAT the ISO 19115 element `MD_DataIdentification.citation.CI_Citation.series`. 

Actually, your approach (`dct:isPartOf`) is the same used in [the dataset series section of the current DCAT3 ED](https://w3c.github.io/dxwg/dcat/#dataset-series-specification). Do you think a more specific property is needed?

On a different note: 

I see that for the mapping between ISO 19115, DCAT, and Schema.org you are referring to:

https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.org_mapping

Please note that that wiki space has been frozen, and therefore the mappings have not been updated wrt the latest versions of DCAT and Schema.org. 

An up-to-date and more fine-grained mapping from ISO 19115 to DCAT is defined in GeoDCAT-AP:

https://semiceu.github.io/GeoDCAT-AP/releases/#rdf-syntax-bindings-for-inspire-and-iso19115-metadata-elements

**Comment by riannella** [comment]
Hi @andrea-perego - given what is said in Section 11.1 - does this mean using dcat:Catalog as the "data set series" is not recommended?

**Comment by andrea-perego** [comment]
@riannella , @dr-shorthair , as the discussion has moved to https://github.com/w3c/dxwg/issues/1272 , I'm closing this issue.
