### ISSUE TITLE
Advice on creating DCAT Profiles for controlled-access healthcare datasets

### ISSUE THREAD

**Issue by susheel** [w3c/dxwg#1291]
Looking for some advice. Not sure if we are use case. 

We created a rudimentary health dataset metadata specification, based on DCAT, Schema.org, Data Use Ontology and others. The latest spec in JSONSchema form is here - https://github.com/HDRUK/schemata. Is JSONSchema allowed for DCAT derived metadata specifications?

The specification is used to collect dataset specification from health data custodians in the UK for discovery and access management here - https://healthdatagateway.org

Reading some of the DCAT Profile guidance, I think what we may have created is a DCAT Profile. Please let me know if this wrong. If what we have created is a profile, is there a process to formalise the profile and what improvements can we make to align as much as possible to DCAT for interoperability?

Are there example profiles we could look at to learn and improve ours? Any advice would greatly be appreciated. Thanks in advance.

**Comment by rob-metalinkage** [comment]
@susheel - sound like you are correct and you are profiling DCAT (and possibly other vocabs). 

Re JSON schema this is a perfect example of a set of implementation constraints around a more general standard (and why we dont define a specific way of doing this - there are many.) You can use the PROF vocab (https://www.w3.org/TR/dx-prof/) to _describe_ you profile and how it works.

you might also be interested in a tool I have been developing - reading JSON schema and generating profile descriptions is on the roadmap - currently it is focussed on untangling profiles described using copy-and-paste OWL fragments.

https://github.com/RDFLib/profilewiz

If this approach has interest I'd welcome any input - either contributing code or adding an example and issues for this functionality and I'll get to it when I can.  Even if you do a manual description we can review it and reference it in the PROF vocabulary implementation report - and would be grateful for any feedback.

The DCAT revision team has put either creating profiles or publishing advice on how to out of scope in the past, so its probably best to work via the PROF channel:  https://github.com/w3c/dx-prof/issues

**Comment by kcoyle** [comment]
@susheel Thanks for this. The Dublin Core community is working on a [profile vocabulary ](https://github.com/dcmi/dctap) and I'd like to ask your permission to compare your profile against our work. It looks to me that there is high compatibility, but you also have some interesting features that we should put on our "to-do" list. Thanks.

**Comment by pwin** [comment]
You asked about where you can see examples of profiles.  Here are some:

**DCAT-AP** - [https://joinup.ec.europa.eu/release/dcat-ap-v11](https://joinup.ec.europa.eu/release/dcat-ap-v11)  and [https://github.com/SEMICeu/DCAT-AP/tree/master/releases](https://github.com/SEMICeu/DCAT-AP/tree/master/releases) for others 
**GeoDCAT-AP** - [https://semiceu.github.io/GeoDCAT-AP/releases/](https://semiceu.github.io/GeoDCAT-AP/releases/) 
**StatDCAT-AP** - [https://joinup.ec.europa.eu/release/statdcat-ap-v100](https://joinup.ec.europa.eu/release/statdcat-ap-v100)
**DCAT-AP_IT** - [https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0](https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0)
**DCAT-AP.de** - [https://www.dcat-ap.de/](https://www.dcat-ap.de/)
**DCAT-AP-NO** - [https://doc.difi.no/dcat-ap-no/](https://doc.difi.no/dcat-ap-no/)
**Transport-DCAT-AP** -[ https://oasis.team/storage/app/media/O1.2%20TransportDCAT-AP%20and%20Controlled%20Vocs.pdf]( https://oasis.team/storage/app/media/O1.2%20TransportDCAT-AP%20and%20Controlled%20Vocs.pdf) 
**EPOS-DCAT-AP** - [https://github.com/epos-eu/EPOS-DCAT-AP](https://github.com/epos-eu/EPOS-DCAT-AP)

**Comment by susheel** [comment]
Thanks for the advice all.
@rob-metalinkage I'll start with you suggested route via PROF vocab (w3.org/TR/dx-prof) and thanks for the examples @pwin 
@kcoyle - Of course. Happy to help.

**Comment by andrea-perego** [comment]
@susheel , do you have any additional points to discuss? Otherwise, we'll close this issue.

**Comment by andrea-perego** [comment]
No additional points have been raised. Closing this issue.
