### ISSUE TITLE
Range of locn:geometry

### ISSUE THREAD

**Issue by init-dcat-ap-de** [w3c/dxwg#1293]
You changed (already in DCAT2) the range of locn:geometry from locn:Geometry to rdfs:Literal.
According to the usage note to be "intentionally generic".

But rdfs:Literal is in my opinion more restrictive than locn:Geometry. According to the usage notes and examples of locn:geometry, it allows Literals AND IRIs: https://www.w3.org/ns/locn#locn:geometry

What am I missing?

**Comment by andrea-perego** [comment]
Thanks for reporting this issue, @init-dcat-ap-de .

This is being addressed in PR https://github.com/w3c/dxwg/pull/1303 (still work in progress).

**Comment by riccardoAlbertoni** [comment]
Summary: Range changed from <code>rdfs:Literal</code> to <code>locn:Geometry</code> via <a href="https://github.com/w3c/dxwg/pull/1303">#1303</a>. The corrections will appear in the next PWD.

**Comment by init-dcat-ap-de** [comment]
Thank you. 

I guess this should also apply to `dcat:bbox` and `dcat:centroid`.
