### ISSUE TITLE
Issue with OWL compatibility properties?

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#1305]
PR #1295 proposes to use `owl:backwardCompatibleWith` and `owl:incompatibleWith`. I agree with the need and the proposed pattern. But I'm not sure about re-using these two ontologies. The [formal semantics of OWL](https://www.w3.org/TR/2012/REC-owl2-rdf-based-semantics-20121211/) specify that the domain and range of these two properties are owl:Ontology. In general I'm not the one that is bothered too much by the consequence of applying OWL reasoning, as few among us do it. But in this case it could have quite bad consequences. The notion of ontology is quite flexible, but I'm not  very comfortable with saying that potentially any DCAT dataset could be named an ontology.

Apologies in advance in case you have already discussed this and I've missed it...

**Comment by andrea-perego** [comment]
This issue is begin discussed in https://github.com/w3c/dxwg/issues/1258

@aisaac , would you mind posting your comment there?

**Comment by aisaac** [comment]
OK done at https://github.com/w3c/dxwg/issues/1258#issuecomment-784867334
It seems the issue there evolved into a more fundamental discussion on whether to represent (in)compatibility in the first place, but the beginning of the issue was indeed about the OWL semantics. 
I think I can resolve this issue here then.
