### ISSUE TITLE
Namespace prefix for DC Terms

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#1314]
In our documentation we are using the prefix `dct:` to denote the Dublin Core Terms namespace, and `dcat:` for DCAT. 
I have found that users often conflate these, probably because the prefixes are so similar.  
I suggest using the prefix `dcterms:` instead.

**Comment by andrea-perego** [comment]
Makes sense to me. 

I created a draft PR, in case we go this way: https://github.com/w3c/dxwg/pull/1315

**Comment by riccardoAlbertoni** [comment]
It works for me as well.

**Comment by andrea-perego** [comment]
Spec and RDF voc updated via PR: https://github.com/w3c/dxwg/pull/1315

We have yet to deal with the examples - also to decide where to place them.

@riccardoAlbertoni , would you create a separate issue for this?

**Comment by riccardoAlbertoni** [comment]
> Spec and RDF voc updated via PR: #1315
> 
> We have yet to deal with the examples - also to decide where to place them.
> 
> @riccardoAlbertoni , would you create a separate issue for this?

Done in issue https://github.com/w3c/dxwg/issues/1319
