### ISSUE TITLE
Reasons for not adding properties to dcat:Resource (and therefore not to dcat:DataService)

### ISSUE THREAD

**Issue by init-dcat-ap-de** [w3c/dxwg#1317]
Hello,

we are in the process of integrating dcat:DataService into DCAT-AP.de. 

We are wondering why you decided to add properties, who describe the temporal or spatial aspects of a resource to the dcat:Dataset and not to the dcat:Resource. E.g. dcat:spatialResolutionInMeters, dcat:temporalResolution or dct:accrualPeriodicity.

Most of these properties could also be relevant when one would describe a dcat:DataService.
We have our own German properties and have to decide to either add them to dcat:Resource or dcat:Dataset. 
Knowing the reasoning for your decision will probably help us.

Thank you.

**Comment by andrea-perego** [comment]
Thanks for bringing your concern to our attention, @init-dcat-ap-de .

We actually have an open issue on this: https://github.com/w3c/dxwg/issues/1253 . Current discussion is going in the direction of moving these properties to `dcat:Resource`, but a final decision is yet to be made.

**Comment by init-dcat-ap-de** [comment]
Thank you, discoverability... one place is enough. 
I'll continue in #1253.
