### ISSUE TITLE
Linking a metadata record to the relevant catalogue(s)

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#132]
> Related to requirement [[RPS](https://www.w3.org/TR/dcat-ucr#RPS)] ("Publication souce")

In the current version of DCAT you can link a catalogue to a metadata record by using `dcat:record`, but no inverse property is provided.

Such a property is relevant in federated harvesting scenarios, where it is useful to know from which catalogue a metadata record has been harvested - which is possible, in the current version of DCAT, only if also the metadata record of the relevant catalogue have been harvested.

**Comment by makxdekkers** [comment]
@andrea-perego If I understand correctly, the semantics would not be a link to the Catalog of which this CatalogRecord is a part, so it is not the inverse of `dcat:record`, but rather a link to another Catalog, so something like `dcat:sourceCatalog`?

**Comment by andrea-perego** [comment]
Good point, @makxdekkers .

I think both options apply. It is to be seen whether this can be achieved just with 1 property, or we may need 2 different ones.

For instance, supposing we have a property `dcat:catalog`, inverse of `dcat:record`, the scenario you mention could be addressed as follows:

````turtle
a:Catalogue a dcat:Catalog .

the:SourceCatalogue a dcat:Catalog .

a:Record a dcat:CatalogRecord ;
  dcat:catalog a:Catalogue ;
  dct:source the:SourceRecord .

the:SourceRecord a dcat:CatalogRecord ;
  dcat:catalog the:SourceCatalogue .
````
In this case, the property you mention, namely, `dcat:sourceCatalog`, can be seen as equivalent to a composition/chain of properties `dct:source`/`dcat:catalog`.

**Comment by andrea-perego** [comment]
To be decided if this should go to milestone [DCAT Future Priority Work](https://github.com/w3c/dxwg/milestone/15).

**Comment by andrea-perego** [comment]
Noting no similar requirement was contributed since this issue was created, I'm closing this issue.
