### ISSUE TITLE
Changes to Class Diagram (figure 1).

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1320]
In this issue, we pile the changes to make to the DCAT class diagram  (figure 1 in the DCAT document) to do them all at once.

**Comment by riccardoAlbertoni** [comment]
~~Turn 'dct:' into 'dcterms' as for PR #1314 which has been merged.~~

**Comment by andrea-perego** [comment]
Another related issue to be taken into account is https://github.com/w3c/dxwg/issues/1252

**Comment by andrea-perego** [comment]
I think one of the things to be considered is whether we should limit the information in the diagram to increase its legibility. 

Some options:

1. We keep only classes and relationship, and remove datatype properties.
2. We provide different views of the diagram - e.g., a general and incomplete one for the voc, and more specific and detailed views for the main classes

**Comment by dr-shorthair** [comment]
It was hard work making the Figure legible for DCAT2. So it might be time for option 2.

**Comment by riccardoAlbertoni** [comment]
As a first step, we might simplify the figure by removing the inherited data properties.  This would still provide the overall view. What do you think?

**Comment by dr-shorthair** [comment]
I did that originally, but then it was requested to show the 'inherited' properties as well. 
It might be that we need 
1. one summary class diagram showing the relationships between the DCAT classes (i.e. the backbone)
2. one diagram-per-class with both local and 'inherited' properties
