### ISSUE TITLE
Should DCAT be more explicit on releases?

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1331]
ℹ️ Originally posted in https://github.com/w3c/dxwg/issues/1277#issuecomment-784557124 by @aisaac :

> [...] DCAT provides elements to describe releases, but the section on versioning is not very explicit on whether a new release is expected to be a new version.
>
> Again I reckon DCAT should remain generic, but I think it could feature a guideline that says that a new release of a resource would typically lead to the creation of a new version. This could otherwise result in inconsistencies in DCAT metadata, couldn't it? (that is, at least for the data publishers who would care about versioning).

**Comment by riccardoAlbertoni** [comment]
The current draft for the section version says 
>This section focuses specifically on how to use DCAT to describe versions resulting from a revision - i.e., from changes occurring to a resource as part of its life-cycle."

I think the above implies versions represent any new release.  Moreover, the reference to DWBP provides further guidelines on versioning.
 
@aisaac: Do you have any objections if we close this issue?

**Comment by riccardoAlbertoni** [comment]
Closing according to the "due for closing" policy which implies the issue can be closed after a 6 days period if no complaints are received. 
More than 10 days have passed, in case of late reactions, we will consider reopening this issue or creating a new one.
