### ISSUE TITLE
Applying PROV's lightweight approach for DCAT inverse properties 

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1336]
Discussions on adding inverse DCAT properties have appeared in distinct issues (e.g., #1322 and #1335).
Some people feel DCAT should recommend only one direction of properties, essentially to avoid extra efforts when maintaining and consuming the metadata. Others argue that inverse properties are not that difficult to maintain. 

A middle-out option would be supporting inverse properties with a "lightweight approach" such as the one adopted by PROV-O (https://www.w3.org/TR/prov-o/#inverse-names).

The idea is to avoid inverse properties (unless grounded explicitly by use cases). But rather, to claim in the DCAT Appendix the name of the inverse properties to ensure interoperability in case any specific application needs to use the non-recommended inverse properties.
In a recent DCAT teleconference,  we started discussing whether this strategy is suitable for DCAT, and we agreed on following/exploring the PROV approach for inverse properties (see https://www.w3.org/2021/03/17-dxwgdcat-minutes#r02). 

What do group members and contributors think about this approach?

**Comment by dr-shorthair** [comment]
It is a bit clunky, but there is the PROV precedent.

**Comment by riannella** [comment]
I was shocked to read that approach in a W3C recommendation.

**Comment by dr-shorthair** [comment]
They implicitly reserved the keywords without actually implementing them.

**Comment by riccardoAlbertoni** [comment]
A draft section about inverse properties is available at the link [1] and has been discussed at the last DXWG plenary.  The meeting minutes [2] register the rationale behind the section and the so-far positive reactions from the group. 

Are there any remarks or objections to the approach described in the section?
Any suggestions and improvements on the section wording are welcome.

We want to make sure we are all on the same page about the general approach, which is largely inspired by the PROV's lightweight solution, then refine the section incrementally, considering what inverse properties are missing in the current list and the remaining open issues in GitHub about the inverse properties.

[1] https://w3c.github.io/dxwg/dcat/#inverse-properties
[2]https://www.w3.org/2021/09/07-dxwg-minutes#t02

**Comment by andrea-perego** [comment]
As no objections have been raised so far on the adopted approach, I propose we close this issue.
