### ISSUE TITLE
Make URIs vs. IRIs consistent in the DCAT document

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#1341]
Throughout the DCAT document, both URIs and IRIs are used to refer to identifier types in various places.
I suspect that this is, at this moment, an unintentional inconsistency.
In many places (e.g. https://w3c.github.io/dxwg/dcat/#Property:resource_identifier) the usage of URIs is unnecessarily restrictive. For instance, in Czechia, those are almost always IRIs.

Since the document references RFC 3986 (URIs) and RFC 3987 (IRIs), it seems quite important to make this consistent and change URIs to IRIs wherever the identifier is not used in a context where IRIs are explicitly disallowed and therefore forced to be percent-encoded.

**Comment by andrea-perego** [comment]
@jakubklimek , thanks to reporting this inconsistency.

This issue is now being dealt with in PR https://github.com/w3c/dxwg/pull/1345
