### ISSUE TITLE
The prefix of DC terms is dcterms in the text and dct in the class diagram

### ISSUE THREAD

**Issue by kvistgaard** [w3c/dxwg#1365]

**Comment by dr-shorthair** [comment]
If the Enterprise Architect diagram is still what we want, I can update this. 
However, I understood that a new diagram in a more portable format was being contemplated.

**Comment by dr-shorthair** [comment]
See #1368

**Comment by kvistgaard** [comment]
And what's the argument for dterms? I personally use always dct.

Regarding the diagram, my hope would be that the new one is in SVG.

**Comment by dr-shorthair** [comment]
Frequent confusion with DCMI Type vocabulary which has its own ns. 
https://dublincore.org/specifications/dublin-core/dcmi-terms/#section-7

**Comment by dr-shorthair** [comment]
And also with `dcat:`. See https://github.com/w3c/dxwg/issues/1314

**Comment by kvistgaard** [comment]
I see. Thanks for the pointers.

**Comment by riccardoAlbertoni** [comment]
I think we can close this issue,  as the only pending part is the need to change "dc" and "dcterms," which is already under the radar of  #1320.
Any objections?
