### ISSUE TITLE
DCAT TTL - The label for the class dcat:Resource 

### ISSUE THREAD

**Issue by aidig** [w3c/dxwg#1388]
The label '**Catalogued resource**' for the class [dcat:Resource](https://www.w3.org/TR/vocab-dcat-2/#Class:Resource) in the [TTL ontology distribution ](https://www.w3.org/ns/dcat.ttl) of the ontology) implies that this is the class of all catalogued resources, yet it is stated in section [5.1 DCAT Scope](https://www.w3.org/TR/vocab-dcat-2/#dcat-scope) that this class also covers **resources which are not documented in any catalog**:

> dcat:Resource represents a dataset, a data service or any other resource that may be described by a metadata record in a catalog. This class is not intended to be used directly, but is the parent class of dcat:Dataset, dcat:DataService and dcat:Catalog. (..). dcat:Dataset and dcat:DataService can be used for datasets and services which are not documented in any catalog.

Although the label in the TTL distribution narrows the scope to "catalogued", the definition of [dcat:Resource](https://www.w3.org/TR/vocab-dcat-2/#Class:Resource) does not restrict the resource to be listed in a catalogue.

```
dcat:Resource
  a owl:Class ;
  rdfs:comment "Resource published or curated by a single agent."@en ;
  rdfs:label "Catalogued resource"@en ;
```
If [dcat:Resource](https://www.w3.org/TR/vocab-dcat-2/#Class:Resource) is to be understood and reused in other application profiles as a a resource not necessarily documented in a catalog, then the label 'Catalogued resource' seems somewhat inappropriate as the label for the DCAT defined class [dcat:Resource](https://www.w3.org/TR/vocab-dcat-2/#Class:Resource) in TTL distribution of the DCAT ontology...

**Comment by riccardoAlbertoni** [comment]
@aidig: Thank you for the comment.
To clarify the overall expectation of resources being part of catalogs,  we added "The instances of  Resource SHOULD be included in a catalog" in the usage note for dcat:Resource.
 
'SHOULD' is to be interpreted as described in BCP 14 [RFC2119] [RFC8174], which implies Resources are typically defined as part of catalogs, but the specification acknowledges that there are cases in which they are not. 

You can find more explanations  in the  DCAT teleconference minutes  accessible at https://www.w3.org/2021/07/07-dxwgdcat-minutes#t03

**Comment by riccardoAlbertoni** [comment]
@aidig: We are closing this issue as we think the above change has clarified the issue you pointed out. In case you think otherwise, please feel free to contact us again, reopening it. Thanks a lot.
