### ISSUE TITLE
Cardinality constraint for dcat:endpointURL (restrictions in dcat.ttl which are not visible in html)

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1394]
The specification on dcat:endpointURL: https://www.w3.org/TR/2020/REC-vocab-dcat-2-20200204/#Property:data_service_endpoint_url does not provide an indication of a cardinality constraint.

However https://www.w3.org/ns/dcat2.ttl contains a maxCardinality constraint. 

What is here the expected behaviour? Adding constraints in the machine readable syntax should be best reflected in the html representation. 

Similary the following restriction for dcat:Catalog
```
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:allValuesFrom dcat:Resource ;
      owl:onProperty dct:hasPart ;
    ] ;
```
If I am not mistaken that states that every dcat:Catalog is a dcat:Resource which has a dct:hasPart relation. 
I doubt this is the always the case.

The problem with these restrictions is that they are not visible. They are only discovered when people start reading the ttl file and interpreting the OWL statements. This adds a lot of conditionals in the interpretation of the DCAT specification. When discussing with others I am not sure if they take the html spec, the RDF ttl file or the OWL interpretation of the RDF ttl file as their interpretation of the DCAT specification.  

proposal: 
remove all restrictions from the dcat.ttl unless these are explicitely part of the html specification.

**Comment by riccardoAlbertoni** [comment]
I think if there are no objections, we can close this issue.

A summary of how we dealt with this issue:
We revised the Axioms in DCAT 2 RDF (PR #1401), and the new versions of RDF are available at 

https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2.rdf
https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2.ttl
https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2.jsonld

They will be available on the official http://www.w3.org/ns/dcat# as soon issue #1405 is addressed.

How to deal with the deleted axioms in DCAT 3 is going to be discussed in issue #1402

**Comment by bertvannuffelen** [comment]
agree to close.
