### ISSUE TITLE
Create a template for issues so that they follow the use cases templates

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#14]
As discussed on the call, create an issue template (https://help.github.com/articles/creating-an-issue-template-for-your-repository/) following the use case template (https://www.w3.org/2017/dxwg/wiki/Use_Case_Working_Space#.2F.2FUse_Case_template)

**Comment by aisaac** [comment]
It's been done

**Comment by andrea-perego** [comment]
Call 19-02-2019: resolved: close #14:

https://www.w3.org/2019/02/19-dxwg-minutes#x11
