### ISSUE TITLE
why is dcat:spatialResolutionInMeters part of Class Dataset and Class Distribution?

### ISSUE THREAD

**Issue by simsong** [w3c/dxwg#1404]
The RDF Property `dcat:spatialResolutionInMeters` appears in section 6.6.5 and in Section 6.8.13 of Version 3 W3C Working Draft 04 May 2021.

Likewise, the RFD property dcat:temporalResolution appears in both section 6.6.7 and in section 6.8.14.

From reading these sections, it is unclear to me if this is an editing mistake or if the two versions, in Dataset and in Distribution, are somehow different.

**Comment by riccardoAlbertoni** [comment]
These properties are repeated on purpose as one might need to specify the dcat:spatialResolutionInMeters at the dataset or distribution level.

For example, the usage note at https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_spatial_resolution says, "Alternative spatial resolutions might be provided as different dataset distributions".

@simsong: Does this explanation solve your doubt?

**Comment by riccardoAlbertoni** [comment]
This issue is addressed by previous comments. 
Please @simsong, feel free to reopen the issue if you think further clarifications are needed.
