### ISSUE TITLE
Support description of legal authorities

### ISSUE THREAD

**Issue by simsong** [w3c/dxwg#1406]
### Support description of legal authorities
Status:

Identifier:

Creator: (your name)

Deliverable(s): DCATv3

## Tags
dcat,profile,dataset,documentation,provenance
## Stakeholders
Governmental entities, be they data producers, data publishers or data consumers.

## Problem statement
Within governments, it is frequently important to document the legal authority under which data are:
* Collected
* Retained or destroyed
* Distributed

Currently, DCATv3 lacks a way to formally represent this. Needed are attributes for:
* CollectionAuthority
* RetentionAuthority
* DistributionAuthority

Also needed is an ontology to describe legal authorities. Within the United States such authorities can be a specific law, a  regulation, an administrative procedure, a legal precedent, or a constitutional authority, an executive order, or some other legal instrument. Although the temptation is to make the authorities a free-formed text field, it may be better to attempt more specificity.

## Existing approaches
Largely this is not formally tracked by most data producers or consumers, but is tracked with a variety of informal mechanisms.

## Requirements
- It would be useful to be able to cite a specific authority, and to distinguish between "unknown," "no existing authority," and other missing data conditions.
- [RPIF](https://www.w3.org/TR/dcat-ucr/#RPIF), https://github.com/w3c/dxwg/issues/76

## Related use cases

[UC13](https://www.w3.org/TR/dcat-ucr/#ID13)

## Comments

---

**Comment by dr-shorthair** [comment]
Could this use the same `qualifiedAttribution` mechanism also [mentioned here](https://github.com/w3c/dxwg/issues/1407#issuecomment-927033274)?

**Comment by simsong** [comment]
It could use `qualifiedAttribution`, but we would need to have multiple `qualifiedAttribution`s per catalog entry, and we would need to have more vocabulary for distinguishing each kind of of the attribution, and we would need to have a way of distinguishing attributions to people and attributions to legal documents or concepts.

**Comment by dr-shorthair** [comment]
> we would need to have multiple qualifiedAttributions per catalog entry

Sure. Why not? 

> we would need to have more vocabulary for distinguishing each kind of of the attribution

Of course. But they would likely be governed outside of DCAT - i.e. community level, not DCAT schema level. 

Attributions are always to Agents or Parties.

**Comment by riccardoAlbertoni** [comment]
I think @dr-shorthair's suggestion combining qualified attribution and externally-governed vocabularies provides a solution to this issue.

I also concur that defining a vocabulary for legal authorities is at the moment out the scope of DCAT being rather community-specific.

@simsong: Is it ok if we close this issue?
