### ISSUE TITLE
Distinguish dataset owner, curator, steward, and other functions

### ISSUE THREAD

**Issue by simsong** [w3c/dxwg#1407]
### Distinguish dataset owner, curator, steward, and other functions
Status:

Identifier:

Creator: (your name)

Deliverable(s): DCATv3

## Tags
dcat,profile,dataset,documentation,provenance
## Stakeholders
Governmental entities, be they data producers, data publishers or data consumers.

## Problem statement
Within governments, it imay be important to distinguish multiple entities that have responsibility for data. Specific roles that require distinguishing in some applications include:
* Owner
* Curator
* Steward
* Oversight or Governance Board

Currently, DCATv3 lacks a way to formally represent this. 

Each of these could be properties with a range of `foaf:Agent.`

## Existing approaches
Largely this is not formally tracked by most data producers or consumers, but is tracked with a variety of informal mechanisms.

## Requirements

[RPIF](https://www.w3.org/TR/dcat-ucr/#RPIF), https://github.com/w3c/dxwg/issues/76

## Related use cases

[UC13](https://www.w3.org/TR/dcat-ucr/#ID13)

## Comments

---

**Comment by dr-shorthair** [comment]
See https://www.w3.org/TR/vocab-dcat-2/#Property:resource_qualified_attribution 
explained here: https://www.w3.org/TR/vocab-dcat-2/#qualified-attribution

**Comment by simsong** [comment]
it's a great idea to use the `qualifiedAttribution`, but we still need to define each of the kinds of attributions with some sort of controlled vocabulary. That's because the curator really is different from the owner which is different from the steward.

**Comment by agbeltran** [comment]
There is the [contributor role ontology](http://www.obofoundry.org/ontology/cro.html), which is based on the [CASRAI Contributor Roles Taxonomy (CRediT)](https://casrai.org/credit/). Also ongoing work on the [CASRAI RDM terminology](https://codata.org/initiatives/data-science-and-stewardship/casrai-rdm-terminology/) may cover some aspects of attribution/roles.

**Comment by simsong** [comment]
The [contributor role ontology](http://www.obofoundry.org/ontology/cro.html) looks like it has what is needed! What is involved in bringing it into DCATv3? 

The [CASRAI RDM terminology](https://codata.org/initiatives/data-science-and-stewardship/casrai-rdm-terminology/) also looks good. Thanks for telling me about these! I will reference both of them moving forward.

**Comment by dr-shorthair** [comment]
We would be unlikely to 'bring it into DCAT', but it could be added to the usage notes in https://www.w3.org/TR/vocab-dcat-2/#qualified-attribution Generally the choice of which controlled-vocabulary to use in the range of a property will be a community decision, since different communities have different needs, while they can all use DCAT as the overall framework or 'schema'.

**Comment by riccardoAlbertoni** [comment]
Thanks for the comments, @simsong.
 Are there any aspects we haven't covered in the discussion above?
 Otherwise, I suggest closing this issue.

**Comment by simsong** [comment]
Thanks for the nudge, @riccardoAlbertoni . Yes, we can close this issue.
