### ISSUE TITLE
Using dcat:next and dcat:version in Dataseries

### ISSUE THREAD

**Issue by sde01** [w3c/dxwg#1409]
### Revising a dataset in a Dataserie
Status:

Identifier:

Creator: sde

## Tags
dcat Dataserie pav:version

## Problem statement
Should dcat:prev and dcat:next be updated when a dataset in the serie is revised ?

Let’s consider example  38
```

ex:budget a dcat:DatasetSeries ;
  dcterms:title "Budget data"@en ;
  .
  
ex:budget-2018 a dcat:Dataset ;
  dcterms:title "Budget data for year 2018"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2019-01-01"^^xsd:date ;
  dcat:next ex:budget-2019 ;
  .
  
ex:budget-2019 a dcat:Dataset ;
  dcterms:title "Budget data for year 2019"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2020-01-01"^^xsd:date ;
  dcat:prev ex:budget-2018 ;
  dcat:next ex:budget-2020 ;
  .
  
ex:budget-2020 a dcat:Dataset ;
  dcterms:title "Budget data for year 2020"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2021-01-01"^^xsd:date ;
  dcat:prev ex:budget-2019 ;
  .
```

Now let’s consider that budget-2019 is revised with a new dataset budget-2019-rev1

Dataserie can be updated in different ways

* budget-2019-rev1 can replace budget-2019 in the serie 
  * As a consequence budget-2018 and budget-2020 have to be updated for dcat:next / dcat:prev fields
* budget-2019-rev1 can be inserted in the Dataserie in between budget-2019 and budget-2020 
  * As a consequence, budget-2019 and budget-2020 have to be updated for dcat:next / dcat:prev fields
* No update to the dataserie. 
  * When encountering a dataset is a serie, one must check if a new version is available for this dataset. 
* budget-2019 is turned into a Dataserie and holds budget-2019-rev0 and budget-2019-rev1
  * This seems to be over engineering here

What will be the recommendation?

**Comment by andrea-perego** [comment]
@sde01 , apologies for the late reply.

The case you outline can be addressed by combining dataset series with dataset versions:



```mermaid
flowchart BT
C1(ex:budget-2019-rev1)
C0(ex:budget-2019-rev0)
B2(ex:budget-2020)
B1(ex:budget-2019)
B0(ex:budget-2018)
A(ex:budget)
C0 & C1--dcat:isVersionOf-->B1
B0 & B1 & B2--dcat:inSeries-->A
```

The link between versions is specified via property `dcat:previousVersion`:

```mermaid
flowchart RL
C1(ex:budget-2019-rev1)--dcat:previousVersion-->C0(ex:budget-2019-rev0)
```

So, Example 38 could be revised as follows:

````turtle
ex:budget a dcat:DatasetSeries ;
  dcterms:title "Budget data"@en ;
  .
  
ex:budget-2018 a dcat:Dataset ;
  dcterms:title "Budget data for year 2018"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2019-01-01"^^xsd:date ;
  dcat:next ex:budget-2019 ;
  .
  
ex:budget-2019 a dcat:Dataset ;
  dcterms:title "Budget data for year 2019"@en ;
  dcat:inSeries ex:budget ;
  dcat:hasVersion ex:budget-2019-rev0 , ex:budget-2019-rev1 ;
  dcat:hasCurrentVersion ex:budget-2019-rev1 ;
  dcterms:issued "2020-01-01"^^xsd:date ;
  dcat:prev ex:budget-2018 ;
  dcat:next ex:budget-2020 ;
  .

ex:budget-2019-rev0 a dcat:Dataset ;
  dcterms:title "Budget data for year 2019"@en ;
  dcat:version "rev0" ;
  dcat:isVersionOf ex:budget-2019 ;
  dcterms:issued "2020-01-01"^^xsd:date ;
  .

ex:budget-2019-rev1 a dcat:Dataset ;
  dcterms:title "Budget data for year 2019"@en ;
  dcat:version "rev1" ;
  dcat:isVersionOf ex:budget-2019 ;
  dcat:previousVersion ex:budget-2019-rev0 ;
  dcterms:issued "2020-05-10"^^xsd:date ;
  .
  
ex:budget-2020 a dcat:Dataset ;
  dcterms:title "Budget data for year 2020"@en ;
  dcat:inSeries ex:budget ;
  dcterms:issued "2021-01-01"^^xsd:date ;
  dcat:prev ex:budget-2019 ;
  .
````

**Comment by riccardoAlbertoni** [comment]
I propose to close this issue if there are no further requests by @sde01.

**Comment by sde01** [comment]
Hello Riccardo
Thanks for your feedback.
Your proposal is crystal clear.

Many thanks

**Comment by agbeltran** [comment]
I think it would be great to revise the example as @andrea-perego suggested to include this use case in the spec.

**Comment by andrea-perego** [comment]
@sde01 , we have decided to add a consolidated version of your example in the specification. It is now included in the Editor's Draft (PR https://github.com/w3c/dxwg/pull/1473):

https://w3c.github.io/dxwg/dcat/#ex-dataset-series-and-versions

Thanks for your contribution.
