### ISSUE TITLE
URI of dcat:byteSize - specification link is wrong

### ISSUE THREAD

**Issue by init-dcat-ap-de** [w3c/dxwg#1412]
Hello,

a quick errata: 

while the specification says the RDF Property is `dcat:byteSize`, the link itself goes to http://www.w3.org/ns/dcat#size
I checked in the ttl-version, it should be `byteSize`.

~ Ludger

**Comment by andrea-perego** [comment]
Thanks for reporting this typo, @init-dcat-ap-de .

Fix now being implemented via PR https://github.com/w3c/dxwg/pull/1422 (yet to be merged).
