### ISSUE TITLE
Example 54: use of dcterms:references

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1416]
I am not sure to understand the use of `dcterms:reference` as in example 54 https://www.w3.org/TR/2021/WD-vocab-dcat-3-20210504/

``` TTL
:d33937  
  rdf:type dcat:Dataset ; 
...
  dcterms:references :d33937.owl ;
...
.
```

where :d33937.owl seems to be the ontology followed by the dataset.

@dr-shorthair: Perhaps a `dcterms:conformsTo` would be a better choice? Am I missing anything?

In case we decide to keep the references, it is possible that we need to add the inverse as discussed in https://github.com/w3c/dxwg/pull/1410#issuecomment-942665724

**Comment by dr-shorthair** [comment]
I can't recall what the intention was here. 
I suggest deleting that line. No such artefact exists. 
(FWIW this item now has a DOI https://doi.org/10.25919/5b4d2b83cbf2d )

**Comment by riccardoAlbertoni** [comment]
> I can't recall what the intention was here. I suggest deleting that line. No such artefact exists. (FWIW this item now has a DOI https://doi.org/10.25919/5b4d2b83cbf2d )

@dr-shorthair :
I have deleted the line and all the statements related to  :d33937.owl . See pr #1424. Is this ok for you?
