### ISSUE TITLE
Are the dcat definitions and usage notes available in RDF?

### ISSUE THREAD

**Issue by simsong** [w3c/dxwg#1419]
### Allow Definitions and Usage Notes to be read programmatically

Creator: @simsong

Deliverable(s): DCAT3
It would sure be useful if I could read the Definition: and Usage notes from the DCAT specification from within a python program using RDF, rather than having to web-scrape the HTML file.  But I can't find where the information is located.

### Use Case
I want to write a function that given “dcat:landingPage” returns the text string "If the distribution(s) are accessible only through a landing page (i.e. direct download URLs are not known), then the landing page link SHOULD be duplicated as dcat:accessURL on a distribution. (see § 5.7 Dataset available only behind some Web page)”

I want it read from this:
https://www.w3.org/TR/vocab-dcat/

![image](https://user-images.githubusercontent.com/1594284/139912981-cb18685f-417d-47dc-9e9e-bb6dda91003c.png)

**Comment by dr-shorthair** [comment]
> I want it read from this: https://www.w3.org/TR/vocab-dcat/

Sorry - that is the specification document. The RDF can be found from the namespace URI - http://www.w3.org/ns/dcat where you can find directions to the RDF artefacts. You can also go to the maintenance GitHub site, which is also mentioned in the spec document.

**Comment by simsong** [comment]
Thank you so much. So it is at https://www.w3.org/ns/dcat2.rdf which is linked from https://www.w3.org/ns/dcat. That's incredibly useful. Do you know where the similar documents for dcat-us are located?

**Comment by dr-shorthair** [comment]
What is dcat-us?

**Comment by simsong** [comment]
dcat-us is the version of DCAT that the US Government is using on https://data.gov.  It is based on DCATv1. It is described here: https://resources.data.gov/resources/dcat-us/. It seems to have no namespaces. The HTML document was clearly automatically generated, but I cannot find the source documents or the source repo.

**Comment by pwin** [comment]
https://resources.data.gov/resources/podm-field-mapping/ has some links to
the JSON schema and json-ld context, but I'm unable to find any further
schema sources for the US version

**Comment by kcoyle** [comment]
Ditto to the above @simsong and @pwin. I also happened to be looking at dcat-us this week and was concerned with the lack of namespaces, so their vocab mixes dcat, dct and other properties without full identification. They claim to use json-ld but without namespaces I don't know how that would work. I did wander through their github repo and there is some dcat-us json code is at https://github.com/GSA/resources.data.gov/tree/main/pages/schemas/dcat-us/v1.1/schema but I haven't looked to see if this corresponds to the documentation. It does seem to be the same as displays from the page that Peter linked to. I'll report back if I do more work on it.

**Comment by simsong** [comment]
I am cleaning up dcat-us. You can find the work over here: https://github.com/usdhs/dcat-tool/blob/main/schemata/usg.ttl

I welcome suggestions, corrections, and pull requests. I'm just a beginner here.

**Comment by makxdekkers** [comment]
@simsong, I see in the ttl file that a range of `rdfs:Literal` is assigned to properties that are defined as `owl:ObjectProperty`. Now I am not an expert in OWL, but isn't it the case that `owl:DataProperty` is the kind of property that is meant to connect individuals with literals? 
There are for example properties like `usg:hostingLocation` and `usg:datasetClassification` with range `rdfs:Literal`, but should those not be _things_ rather than _strings_?

**Comment by simsong** [comment]
> @simsong, I see in the ttl file that a range of `rdfs:Literal` is assigned to properties that are defined as `owl:ObjectProperty`. Now I am not an expert in OWL, but isn't it the case that `owl:DataProperty` is the kind of property that is meant to connect individuals with literals? There are for example properties like `usg:hostingLocation` and `usg:datasetClassification` with range `rdfs:Literal`, but should those not be _things_ rather than _strings_?

Hi. If you are referring to the file `usg.ttl`, my request is that we move the discussion to https://github.com/usdhs/dcat-tool/issues.

If you can make specific recommendations for what to change, that would be great! Again, I am a beginner at this.

With respect to `usg:datasetClassification`, unfortunately my current plan is for this to be a string that is parsed, rather than for a well-developed ontology. This is a result of operational concerns: it is not possible for me to document all of the possible values of this string. So this is a way of kicking the can down the road.
