### ISSUE TITLE
Ranges of spatial and temporal resolution

### ISSUE THREAD

**Issue by makxdekkers** [w3c/dxwg#1420]
In DCAT2, the range of the new property `spatialResolutionInMeters` is given as `xsd:decimal` and the range of `temporalResolution` is given as `xsd:duration`. 

However, literal ranges of other properties are expressed differently, e.g. the range of `byteSize` is `rdfs:Literal` typed as `xsd:decimal`.

For consistency the ranges should be given as:

`spatialResolutionInMeters`: `rdfs:Literal` typed as `xsd:decimal`.
`temporalResolution`: `rdfs:Literal` typed as `xsd:duration`.

**Comment by dr-shorthair** [comment]
Consistency would be good
