### ISSUE TITLE
DCAT 2014 profile of DCAT

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#144]
A v1 (2014) profile of DCAT should be provided to support existing implementations and deployments. 
For example, to retain any axioms removed in the 2018-19 revision of DCAT.

**Comment by dr-shorthair** [comment]
See branch https://github.com/w3c/dxwg/tree/simon-dcat-v1.0-profile 
The domain axiom removed in https://github.com/w3c/dxwg/pull/97 is included in a new RDF graph, which imports the revised DCAT.

**Comment by rob-metalinkage** [comment]
See #75 for example..

**Comment by rob-metalinkage** [comment]
Note that a working definition of a "profile" has been agreed:

""A named set of constraints on one or more identified base specifications, including the identification of any implementing subclasses of datatypes, semantic interpretations, vocabularies, options and parameters of those base specifications necessary to accomplish a particular function."

see https://www.w3.org/2017/dxwg/wiki/ProfileContext

a draft ontology for metadata describing profiles is at https://github.com/w3c/dxwg/blob/roba-profile/dcat/rdf/profile.ttl

The namespace for this ontology is expected to  change,

**Comment by davebrowning** [comment]
The existing editors draft mentions this at https://w3c.github.io/dxwg/dcat/#RDF-representation but we don't have one....  Well, I don't thing dcat2014.ttl (which is a snapshot of what was published back then, I believe) is what we meant.

Is this easily do-able quickly (@dr-shorthair) - or am I incorrect and dcat2014 is adequate.

**Comment by riccardoAlbertoni** [comment]
as discussed in the [call](https://www.w3.org/2019/09/25-dxwgdcat-minutes.html#x07), we are not going to provide a profile but the files of the former DCAT 2014.

**Comment by dr-shorthair** [comment]
We should draft SHACL or ShEX descriptions of 2014 profile and other APs.

**Comment by dr-shorthair** [comment]
In fact I think I would like to re-open this but tag it 'future work' - OK? 
(alongside the other profiles)

**Comment by agbeltran** [comment]
I agree on leaving this open as future work.

**Comment by riccardoAlbertoni** [comment]
Ok from me.

**Comment by nicholascar** [comment]
Tagging with *profiles-vocabulary* since it's related to that too.

**Comment by kcoyle** [comment]
@nicholascar Can you give a sentence or two on how you see this relating to profiles vocabulary? Otherwise we may puzzle over this in the future when trying to remember. Thanks.

**Comment by rob-metalinkage** [comment]
the profile of DCAT is a "Thing" you need to make statements about - including the role and availability of SHACL and SHEX resources. This can be in a human-readable-only form in a doc somewhere and/or it could be done in PROF -   (SHACL and other forms of constraint language dont support these relationships even if people would be willing to inspect every possible type of implementation that may exist)

**Comment by nicholascar** [comment]
Something like this @kcoyle:

```
<https://www.w3.org/TR/vocab-dcat-2/>
    a dct:Standard ;
    dct:title "Data Catalog Vocabulary (DCAT) - Version 2" ;
    prof:hasResource [  # SHACL validator
        prof:hasRole <http://www.w3.org/ns/dx/prof/role/Validation> ;
        prof:hasArtifact <a-SHACL-file-somewhere> ;
        dct:conformsTo <https://www.w3.org/TR/shacl/> ;
        dct:format <https://w3id.org/mediatypes/text/turtle> ;
    ] ;
    prof:hasResource [  # ShEx validator
        prof:hasRole <http://www.w3.org/ns/dx/prof/role/Validation> ;
        prof:hasArtifact <a-ShEx-file-somewhere> ;
        dct:conformsTo <http://shex.io/shex-semantics/index.html> ;
        dct:format <https://w3id.org/mediatypes/text/shex> ;
    ] ;
    prof:hasResource [
        prof:hasRole <http://www.w3.org/ns/dx/prof/role/Guidance> ;
        prof:hasArtifact <https://www.w3.org/TR/vocab-dcat-2/> ; # yes, the Standard's URI is also its Guidance artifact
        dct:format <https://w3id.org/mediatypes/text/html> ;
        dct:conformsTo <https://www.w3.org/TR/> ;  # Andrea knows a better link to indicate conformance to W3C Recs
    ] ;
    prof:hasResource [  # converter from DCAT rev to DCAT 2014
        dct:description "This SHACL file converts DCAT 2014 content to DCAT rev content" ;
        # we (PROF) are still discussing mapping from & to annotations
        prof:hasRole <http://www.w3.org/ns/dx/prof/role/Mapping> ;  
        prof:hasArtifact <yet-another-SHACL-file-somewhere> ;
        dct:conformsTo <https://www.w3.org/TR/shacl/> ;
        dct:format <https://w3id.org/mediatypes/text/turtle> ;
    ] ;
.

<https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/>
    a prof:Profile ;
    dct:title "Data Catalog Vocabulary (DCAT)" ;
    prof:isProfileOf <https://www.w3.org/TR/vocab-dcat-2/> .
    prof:hasResource [
        prof:hasRole <http://www.w3.org/ns/dx/prof/role/Validation> ;
        prof:hasArtifact <a-different-SHACL-file-somewhere> ;
        dct:format <https://w3id.org/mediatypes/text/turtle> ;
        dct:conformsTo <https://www.w3.org/TR/shacl/> ;
    ] ;

```

**Comment by nicholascar** [comment]
I'm removing the PROF tag as there's no work here for PROF, *per se*, only perhaps future engagement with the PROF editors, if needed.

**Comment by andrea-perego** [comment]
I propose to close this issue, as it has been addressed in DCAT by maintaining access to the previous version of the RDF vocabulary from https://www.w3.org/ns/dcat

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
