### ISSUE TITLE
Clarification of definitions

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#1440]
DCAT Scope section:   The definitions should avoid tautologies, like defining dcat:Dataset as "represents a dataset". We could shorten it to "represents a collection of data, published or curated..."
  "dcat:DataService represents a data service. A data service is a collection of..."
  change to "dcat:DataService represents a collection of..."
  grammar:
  "some common characteristics that groups them": "groups" should be "group".
  grammar:
  "dcat:DatasetSeries is a dataset, which represents a collection of datasets"
  should be "A dcat:DatasetSeries is a dataset that represents a collection of datasets.."

**Comment by riccardoAlbertoni** [comment]
Thanks, @agreiner.  PR #1445 should fix the issues you pointed out.
