### ISSUE TITLE
Remove note in section 6.3

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#1441]
Note in section 6.3 seems to be left over from DCAT 2.

**Comment by davebrowning** [comment]
@agreiner - agree that this is redundant.  We discussed in the last editorial meeting what the best approach might be (partial discussion in the #1433 thread).  I have some ideas so will put together a prototype/suggestion by early January that  we can all discuss/critique.

Provisionally, the aim would be to 
- clearly flag new entries in a recommendation (so for example those terms introduced by DCAT 3)
- retain useful design/discussion that has long term value - often buried in these NOTES as well
- make it simple for implementers to understand which version a term was introduced (DCAT, DCAT2, DCAT3....) or perhaps deprecated/superseded in some way (if we ever did that).

Any suggestions welcome, but it might be easier to discuss when I've done an example or two...
