### ISSUE TITLE
Example 15: mistake in the used URIs?

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1459]
Hi,

In Example 15 in https://w3c.github.io/dxwg/dcat/#dereferenceable-identifiers the example starts with

```
<https://dcat.example.org/id> a dcat:Dataset;
  adms:identifier  <https://example.org/iddoi> ;
  dcterms:publisher <https://example.org/PoelenJorritH> ;
```

but later in the example the URI  of the publisher is 

```
<https://dcat.example.org/PoelenJorritH> a foaf:Person;
  foaf:name "Jorrit H. Poelen" ;
  adms:identifier <https://example.org/PoelenJorritHID> ;
```

This breaks the graph. Namely the upper part is not connected with the bottem part in the RDF graph. It might be intentional, but the description below the example does not highlight this.

**Comment by andrea-perego** [comment]
Thanks for reporting this typo, @bertvannuffelen .

We will address it via PR https://github.com/w3c/dxwg/pull/1463
