### ISSUE TITLE
Prepare DCAT document for FPWD

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#147]
The DXWG is committed to publishing a FPWD by end of Q1 2018. 
Publication of a FPWD is primarily aimed at getting feedback from the community, so the document should make clear where changes to the draft are being contemplated. This may be done by embedding links to the Issues in GitHub.

**Comment by dr-shorthair** [comment]
Intention is to send this to the dxwg plenary for release this week.

**Comment by dr-shorthair** [comment]
Agreed by DCAT Team https://www.w3.org/2018/03/28-dxwgdcat-minutes#x07 
subject to 
1. addition of changelog by @andrea-perego 
2. minor editorial suggestions, accepted at the prerogative of document editors (@jpullmann to contribute)

**Comment by andrea-perego** [comment]
Relevant PR created: #185

**Comment by dr-shorthair** [comment]
Published: https://www.w3.org/TR/2018/WD-vocab-dcat-2-20180508/
