### ISSUE TITLE
Should dcat:resource be subproperty of rdfs:member?

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1483]
I have noticed that <code>dcat:catalog</code>, <code>dcat:service</code>, and  <code>dcat:dataset</code>  are  all defined as subproperties of <code>rdfs:member</code> in the TTL.  The recently added  <code>dcat:resource</code> which is the super-property of the above is not. 

 Should we define <code>dcat:resource</code>  subproperty of <code>rdfs:member</code> ?  

 <code>rdfs:member</code> is never mentioned in the DCAT HTML, should we add it to <code>dcat:catalog</code>, <code>dcat:service</code>, and  <code>dcat:dataset</code> and <code>dcat:resource</code> or delete its occurences from the RDF?

**Comment by dr-shorthair** [comment]
`rdfs:member` is a pretty obscure element from RDFS. 
In fact if you read the documentation it is not fully clear if it should be subclassed, and I'm not sure that I've seen it done anywhere else. for example `skos:member` is not a sub-property. 

Probably remove it.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> `rdfs:member` is a pretty obscure element from RDFS. In fact if you read the documentation it is not fully clear if it should be subclassed, and I'm not sure that I've seen it done anywhere else. for example `skos:member` is not a sub-property.
> 
> Probably remove it.

I concur. Let's remove it.

**Comment by agbeltran** [comment]
I also agree with removing this restriction, note that there was a previous issue about relaxing the constraints on ```dcat:service``` (https://github.com/w3c/dxwg/issues/1363) and there was also a suggestion (by @dr-shorthair ) on removing the subproperty constraint with ```rdfs:member``` https://github.com/w3c/dxwg/issues/1363#issuecomment-844806375

**Comment by andrea-perego** [comment]
Statements making `dcat:catalog`, `dcat:dataset`, and `dcat:service` sub-properties of `rdfs:member` have been removed via PR https://github.com/w3c/dxwg/pull/1482
