### ISSUE TITLE
Finalizing the inverse property table

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#1485]
@riccardoAlbertoni said:

> The editor’s note in section https://w3c.github.io/dxwg/dcat/#inverse-properties says
> 
> > The list of properties in the following table is yet to be consolidated, and it includes also properties currently defined in [6. Vocabulary specification](https://w3c.github.io/dxwg/dcat/#vocabulary-specification).
> 
> Can we consider the list consolidated? In any case, I do not think we have any inverse properties that have been left in section 6
> 
> I would consider removing the note. What do the other editors think?

I think there's yet a property to be added, i.e., `dcat:inCatalog`, inverse of `dcat:resource`. After that, I would agree to remove the EDNOTE.

_Originally posted by @andrea-perego in https://github.com/w3c/dxwg/issues/1471#issuecomment-1069649226_

**Comment by riccardoAlbertoni** [comment]
Closed by https://github.com/w3c/dxwg/pull/1484

**Comment by andrea-perego** [comment]
In the meeting of 22 March 2022, the group approved the addition of property `dcat:inCatalog` to the section on the use of inverse properties - see resolution https://www.w3.org/2022/03/22-dxwgdcat-minutes#r03

This revision was implemented via PR https://github.com/w3c/dxwg/pull/1484
