### ISSUE TITLE
DCAT - DATS alignment (profile)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#149]
Prepare a formal alignment of DCAT to DATS

**Comment by nicholascar** [comment]
Can someone please define DATS?

**Comment by agbeltran** [comment]
DATS stands for DAta Tag Suite and it is a schema/model developed to describe datasets (as a convergence from other models/vocabularies) underlying the [DataMed system](http://datamed.org).

The development of DATS was done as part of a Working Group of the [bioCADDIE project](https://biocaddie.org/) and all the material is at [this Github repository](http://github.com/biocaddie/WG3-MetadataSpecifications).

More information: [Scientific Data DATS paper](http://doi.org/10.1038/sdata.2017.59), [JAMIA DATS paper](https://doi.org/10.1093/jamia/ocx119), [DataMed Nature Genetics paper](http://doi.org/10.1038/ng.3864).

**Comment by dr-shorthair** [comment]
Links to related standards, including DATS, are provided on the DXWG project page - https://www.w3.org/2017/dxwg/wiki/Main_Page#Background_and_reading

**Comment by agbeltran** [comment]
Some initial work on DATS/DCAT alignment is available here as JSON-LD context files:
https://github.com/datatagsuite/context/tree/master/dcat

**Comment by andrea-perego** [comment]
@agbeltran , is there any plan to create these alignments?

Otherwise, I propose we close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
