### ISSUE TITLE
Revisions to RDF files (dcat3-external.*)

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1498]
Following PR https://github.com/w3c/dxwg/pull/1488 & https://github.com/w3c/dxwg/pull/1491 , definitions and/or usage notes of some properties have been revised. Such revisions should be reflected in the corresponding RDF files.

The relevant properties are the listed below.

----

`dcterms:description` - [§6.4.5 Property: description](https://w3c.github.io/dxwg/dcat/#Property:resource_description)

Current definition:

> A free-text account of the item.

Revised definition:

> A free-text account of the **resource**.

----

`dcterms:title` - [§6.4.6 Property: title](https://w3c.github.io/dxwg/dcat/#Property:resource_title)

Current definition:

> A name given to the item.

Revised definition:

> A name given to the **resource**.

----

`dcterms:issued` - [§6.4.7 Property: release date](https://w3c.github.io/dxwg/dcat/#Property:resource_release_date)

Current definition:

> Date of formal issuance (e.g., publication) of the item.

Revised definition:

> Date of formal issuance (e.g., publication) of the **resource**.

----

`dcterms:modified` - [§6.4.8 Property: update/modification date](https://w3c.github.io/dxwg/dcat/#Property:resource_update_date)

Current definition:

> Most recent date on which the item was changed, updated or modified.

Revised definition:

> Most recent date on which the **resource**  was changed, updated or modified.

Current usage note:

> The value of this property indicates a change to the actual item,  not a change to the catalog record. An absent value MAY indicate that the item has never changed after its initial publication, or that the date of last modification is not known, or that the item is continuously updated.

Revised usage note:

> The value of this property indicates a change to the actual **resource**,  not a change to the catalog record. An absent value MAY indicate that the **resource** has never changed after its initial publication, or that the date of last modification is not known, or that the **resource** is continuously updated.

----

`dcterms:language` - [§6.4.9 Property: language](https://w3c.github.io/dxwg/dcat/#Property:resource_language)

Current definition:

> A language of the item. This refers to the natural language used for textual metadata (i.e. titles, descriptions, etc) of a cataloged resource (i.e. dataset or service) or the textual values of a dataset distribution

Revised definition:

> A language of the **resource**. This refers to the natural language used for textual metadata (i.e. titles, descriptions, etc) of a cataloged resource (i.e. dataset or service) or the textual values of a dataset distribution

----

`dcterms:publisher` - [§6.4.10 Property: publisher](https://w3c.github.io/dxwg/dcat/#Property:resource_publisher)

Current definition:

> The entity responsible for making the item available.

Revised definition:

> The entity responsible for making the **resource** available.

----

`dcterms:identifier` - [§6.4.11 Property: identifier](https://w3c.github.io/dxwg/dcat/#Property:resource_identifier)

Current usage note 1:

> The identifier might be used as part of the IRI of the item, but still having it represented explicitly is useful.

Revised usage note 1:

> The identifier might be used as part of the IRI of the **resource**, but still having it represented explicitly is useful.

----

`dcterms:relation` - [§6.4.14 Property: relation](https://w3c.github.io/dxwg/dcat/#Property:resource_relation)

Current definition:

> A resource with an unspecified relationship to the cataloged item.

Revised definition:

>A resource with an unspecified relationship to the cataloged **resource**.

Current usage note:

> dcterms:relation SHOULD be used where the nature of the relationship between a cataloged item and related resources is not known. A more specific sub-property SHOULD be used if the nature of the relationship of the link is known. The property dcat:distribution SHOULD be used to link from a dcat:Dataset to a representation of the dataset, described as a dcat:Distribution

Revised usage note:

> dcterms:relation SHOULD be used where the nature of the relationship between a cataloged **resource** and related resources is not known. A more specific sub-property SHOULD be used if the nature of the relationship of the link is known. The property dcat:distribution SHOULD be used to link from a dcat:Dataset to a representation of the dataset, described as a dcat:Distribution

----

`dcterms:accrualPeriodicity` in [§6.6.2 Property: frequency](https://w3c.github.io/dxwg/dcat/#Property:dataset_frequency). 

Current definition: 

> The frequency at which dataset is published.

Revised definition: 

> The frequency at which **a** dataset is published.

----

`spdx:checksumValue` in [§6.17.2 Property: checksum value](https://w3c.github.io/dxwg/dcat/#Property:checksum_checksum_value). 

Current definition: 

> The checksumValue property provides a lower case hexidecimal encoded digest value produced using a specific algorithm [[SPDX]].

Revised definition: 

> The checksumValue property provides a **lowercase hexadecimal** encoded digest value produced using a specific algorithm [[SPDX]]."

**Comment by riccardoAlbertoni** [comment]
Following #1532, update in the for [6.4.9 Property: language](https://w3c.github.io/dxwg/dcat/#Property:resource_language) 

Current Usage Note:
> "In the context of DCAT 2.0, if representations of a dataset are available for each language separately, define an instance of dcat:Distribution for each language and describe the specific language of each distribution using dcterm:language (i.e. the dataset will have multiple dcterm:language values and each distribution will have just one as the value of its dcterm:language property).

New Usage Note: 
>If representations of a dataset are available for each language separately, define an instance of dcat:Distribution for each language and describe the specific language of each distribution using dcterms:language (i.e., the dataset will have multiple dcterms:language values and each distribution will have just one as the value of its dcterms:language property). **In case of multilingual distributions, the distributions will have multiple dcterms:language values.**
