### ISSUE TITLE
Self-review TAG checklist [DRAFT]

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1515]
Draft based on the TAG review template from https://github.com/w3ctag/design-reviews/issues/new?assignees=&labels=Progress%3A+untriaged&template=010-specification-review.md&title= 

This checklist needs to be complemented by an explainer document, following the examples from https://tag.w3.org/explainers/

The explainer document is being drafted in PR https://github.com/w3c/dxwg/pull/1514

----

Wotcher TAG!

I'm requesting a TAG review of [feature name] : Data Catalog Vocabulary (DCAT) - Version 3.

DCAT is an RDF vocabulary designed to facilitate interoperability between data catalogs published on the Web.

DCAT enables a publisher to describe datasets and data services in a catalog using a standard model and vocabulary that facilitates the consumption and aggregation of metadata from multiple catalogs. This can increase the discoverability of datasets and data services. It also makes it possible to have a decentralized approach to publishing data catalogs and makes federated search for datasets across catalogs in multiple sites possible using the same query mechanism and structure. Aggregated DCAT metadata can serve as a manifest file as part of the digital preservation process.

  - Explainer¹ (minimally containing user needs and example code): https://github.com/w3c/dxwg/blob/gh-pages/docs/explainer.md
  - Specification URL: https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/
  - Security and Privacy self-review²: https://github.com/w3c/dxwg/issues/1507
  - GitHub repo (if you prefer feedback filed there): https://github.com/w3c/dxwg/
  - Primary contacts (and their relationship to the specification):
      - Peter Winstanley (@pwin), Invited expert: WG Chair & Specification Editor
      - Caroline Burle (@cburle), Invited expert: WG Chair
      - Riccardo Albertoni (@riccardoAlbertoni), Invited expert: Specification Editor
      - David Browning (@davebrowning), Invited expert: Specification Editor
      - Simon Cox (@dr-shorthair), Invited expert: Specification Editor
      - Alejandra Gonzalez Beltran (@agbeltran), Invited expert: Specification Editor
      - Andrea Perego (@andrea-perego), Invited expert: Specification Editor
  - Key pieces of existing multi-stakeholder review or discussion of this specification: https://github.com/w3c/dxwg/issues
  - External status/issue trackers for this specification (publicly visible, e.g. Chrome Status): https://github.com/w3c/dxwg/issues

Further details:

  - [ ] I have reviewed the TAG's [Web Platform Design Principles](https://www.w3.org/TR/design-principles/)
  - Relevant time constraints or deadlines: End of September, Early October as we plan to move to CR in Autumn.
  - The group where the work on this specification is currently being done: [Dataset Exchange Working Group](https://www.w3.org/groups/wg/dx)
  - The group where standardization of this work is intended to be done (if current group is a community group or other incubation venue): [Dataset Exchange Working Group](https://www.w3.org/groups/wg/dx)
  - Major unresolved issues with or opposition to this specification: The DXWG received considerable feedback, requests for additional features and specific use cases. The group has considered the feedback and included suggestions and revisions received, closing more than 160 GitHub issues and discussing an even greater number. However, the total number of issues exceeded the group capacity in terms of effort and available resources. As a result, DXWG was forced to prioritize the efforts to some of the most urgent extensions, dealing with versioning and dataset series. The remaining pending issues are left open in the Github repository for consideration in future DCAT versions.

We'd prefer the TAG provide feedback as:

  ☂️ open a single issue in our GitHub repo **for the entire review**

------------------------------------------------------------------------------------
CAREFULLY READ AND DELETE CONTENT BELOW THIS LINE BEFORE SUBMITTING

Please preview the issue and check that the links work before submitting.

In particular, if anything links to a URL which requires authentication (e.g. Google document), please make sure anyone with the link can access the document. We would prefer fully public documents though, since we work in the open.

¹ We require an explainer to give the relevant context for the spec review, even if the spec has some background information. For background, see our [explanation of how to write a good explainer](https://tag.w3.org/explainers/). We recommend the explainer to be in [Markdown](https://github.github.com/gfm/).

² A Security and Privacy questionnaire helps us understand potential security and privacy issues and mitigations for your design, and can save us asking redundant questions. See https://www.w3.org/TR/security-privacy-questionnaire/.

**Comment by riccardoAlbertoni** [comment]
Such a draft was discussed in a plenary  see https://www.w3.org/2022/06/07-dxwg-minutes  
A new issue mirroring this was opened to send the related request to the TAG  - see https://github.com/w3ctag/design-reviews/issues/758
