### ISSUE TITLE
Broken URIs from http://registry.it.csiro.au/ 

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#1517]
Following up from discussion in https://github.com/w3c/dxwg/pull/1510#issuecomment-1140330911

These URIs are used in examples of the DCAT3 specification.

To be decided if they need to be replaced.

**Comment by riccardoAlbertoni** [comment]
@dr-shorthair, @andrea-perego:   Did we discovered any alternatives for the missing links pointed out in https://github.com/w3c/dxwg/pull/1510#issuecomment-1140415089?

**Comment by dr-shorthair** [comment]
Sorry - it was taken down a couple of years ago. No replacement :-( 
'Linked data' eh?

**Comment by rob-metalinkage** [comment]
These are still broken - and as a reference to an ISO concept this represents a poor example.  better to put an obvious stub to ISO - or even better an normative ISO endorsed URI even if its not operationally resolvable yet.

**Comment by riccardoAlbertoni** [comment]
@rob-metalinkage: I am afraid I am not correctly interpreting your suggestion.

Considering the codelist related to Role in [EXAMPLE 53](https://w3c.github.io/dxwg/dcat/#ex-qualified-attribution)

```
ex:DS987
  a dcat:Dataset ;
  prov:qualifiedAttribution [
    a prov:Attribution ;
    prov:agent <https://www.ala.org.au/> ;
    dcat:hadRole <http://registry.it.csiro.au/def/isotc211/CI_RoleCode/distributor>
  ] ;
  prov:qualifiedAttribution [
    a prov:Attribution ;
    prov:agent <https://www.education.gov.au/> ;
    dcat:hadRole <http://registry.it.csiro.au/def/isotc211/CI_RoleCode/funder>
  ] ;
.`
```

what do you think could be a good replacement for http://registry.it.csiro.au/def/isotc211/CI_RoleCode/distributor? 

- the xml derived https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml#distributor
- the fictional http://iso.org/isotc211/CI_RoleCode/funder
- other option I have missed

If you meant one of the first two options,  I would consider to leave the URI as they are waiting for developments on the ISO side, or good proxies ;)

**Comment by rob-metalinkage** [comment]
I'd prefer a fictional but possibly future valid broken link than one guaranteed to be broken and confusing as a violation of principles of linked data.   Either that or something like http://placeholderforiso.org

**Comment by riccardoAlbertoni** [comment]
Thanks @rob-metalinkage,  I think I see your point and I appreciate your attempt to find a pragmatic solution. However, the more I think about it, the more I am not completely comfortable minting links in the ISO namespace.  People might start using our fake ISO URI, and this might turn out to be more problematic than the issue we are trying to address.

 On the second approach, I am slightly concerned about using a namespace that can be eventually hijacked by others, as in the case of http://placeholderforiso.org/

I suspect that doing nothing might be better than acting, and I propose moving this as a reminder for future addressing, hoping that in the future we will have time to find a more stable and definitive solution.

**Comment by pchampin** [comment]
Sorry for chiming in a little late, but I have another proposal: `urn:example:isotc211/CI_RoleCode/distributor`

* this is a valid URN (see [RFC6963](https://www.rfc-editor.org/rfc/rfc6963) for the `example` namespace) and therefore a valid URI;
* being a URN, it does not create wrong expectations about it being dereferenceable.

**Comment by riccardoAlbertoni** [comment]
Thanks, @pchampin 
I think this could be a compromise.   
PR #1568 implements your proposal.
