### ISSUE TITLE
DCAT - Datacite alignment (profile)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#152]
Prepare a formal alignment of DCAT to the Datacite schema

**Comment by andrea-perego** [comment]
Just to note that at JRC we have recently updated the relevant DataCite-to-DCAT-AP mappings to the latest version of DataCite (4.1):

https://ec-jrc.github.io/datacite-to-dcat-ap/

Here the "formal" definition of the mappings is done by using XSLT, and we are using it in the harvesting workflow of the JRC Data Catalogue.

**Comment by agbeltran** [comment]
It might be useful to consider this tool from the Datacite team (https://github.com/datacite/bolognese). It doesn't have a mapping to DCAT but there are a few other conversions, where the most relevant would be the mapping to schema.org.

**Comment by andrea-perego** [comment]
The DataCite profile of DCAT-AP (CiteDCAT-AP) - mentioned in https://github.com/w3c/dxwg/issues/152#issuecomment-371339299 - is now aligned with DCAT 2:

https://ec-jrc.github.io/datacite-to-dcat-ap/#methodology

Unless there are any objections, I propose we close this issue.

**Comment by andrea-perego** [comment]
> The DataCite profile of DCAT-AP (CiteDCAT-AP) - mentioned in [#152 (comment)](https://github.com/w3c/dxwg/issues/152#issuecomment-371339299) - is now aligned with DCAT 2:
> 
> https://ec-jrc.github.io/datacite-to-dcat-ap/#methodology
> 
> Unless there are any objections, I propose we close this issue.

Thanks, @dr-shorthair , @riccardoAlbertoni , @davebrowning .

Closing this issue.
