### ISSUE TITLE
dcterms:hasPart is repeated twice in image

### ISSUE THREAD

**Issue by hyunwooya** [w3c/dxwg#1528]
The hasPart property in the Class Catalog also exists in the Class resource. Therefore, it seems that the hasPart is written twice in the catalog of the diagram, and the dcat:resource that should be present is missing.

![dcat-issue](https://user-images.githubusercontent.com/86333483/186362433-254faf60-b0e7-4236-b7f1-bec7e54c8b8e.png)

**Comment by riccardoAlbertoni** [comment]
Thank you, @hyunwooya,  for pointing this out.
