### ISSUE TITLE
Questions following TAG review

### ISSUE THREAD

**Issue by rhiaro** [w3c/dxwg#1530]
Hello! @hadleybeeman and I left some [questions following our TAG review](https://github.com/w3ctag/design-reviews/issues/758#issuecomment-1195215972) last month, but only just realised this week you had indicated you prefer our feedback as an issue on your repo, so you might not have seen it. Apologies for that. Here it is again:

It would be really helpful for us if the explainer could go into a bit of detail about the "more pressing use cases and requests among those left unaddressed in the previous standardization round" that version 3 is addressing. It would help us to understand if/how you've accomplished what you set out to do with DCAT 3.0.

We also try to join up work across working groups and W3C specs. We see that you've created new terms (such as dcat:first, dcat:prev and dcat:last) which could instead be covered by something like [RDF lists](https://www.w3.org/TR/rdf-schema/#ch_collectionvocab) — could you tell us why you made that choice? Are there any other opportunities to reuse existing work in DCAT 3.0?

**Comment by riccardoAlbertoni** [comment]
Sorry for the late reply.
As for the prioritization made in DCAT, we have integrated into the explainer as requested. Please see  [updated explainer](https://github.com/w3c/dxwg/blob/gh-pages/docs/explainer.md).

We didn't reuse the rdfs:first and the rdfs:List because DCAT dataset series might be hierarchical, i.e. they are not necessary lists. Hierarchical dataset series are common in specific domains, for example, the geographical domain for remote sensing data.  

Considering that DCAT is widely profiled, as a rule of thumb, we try not to restrict properties and classes unless we have precise reasons and use cases imposing a specific restrictive interpretation. In our view, that strategy should pay off in the long term, making DCAT minimal, but impacting common for interoperability.

**Comment by danbri** [comment]
Wouldn't lists of lists handle the hierarchy aspect?

**Comment by hadleybeeman** [comment]
Hi @riccardoAlbertoni! Thanks for getting the ball rolling. What are your thoughts on @danbri's point?

**Comment by danbri** [comment]
There are also some issues with rdf lists in the context of OWL (or rather, the Description Logic flavours of OWL). OWL uses such lists for its own representation of complex expressions and in some settings gets upset if encountering such terms in “instance data”.

See recent discussion in this thread,

https://lists.w3.org/Archives/Public/semantic-web/2022Aug/0028.html

The survey paper mentioned in that post seems to be available here:

https://www.semantic-web-journal.net/system/files/swj2578.pdf

**Comment by riccardoAlbertoni** [comment]
> Hi @riccardoAlbertoni! Thanks for getting the ball rolling. What are your thoughts on @danbri's point?

Hi @hadleybeeman  and @danbri,
Yes, you can model hierarchies as lists of lists. However, some considerations have brought a different design pattern for DCAT dataset series:
- rdf:List recalls LISP-like list, while we chose to provide a different navigation structure closer to how dataset series are perceived in other domains.
- There wasn't any use case hinting at aligning dataset series with rdf:List.

Out of curiosity, I tried to explore possible mapping between dataset series and rdf:List. Unfortunately, the exploration was not very encouraging. Roughly speaking, RDF lists might be induced starting from a DCAT dataset series,  but at the cost of building a parallel RDF list structure (e.g., via a SPARQL construct) or collapsing the rdf:list and their list items/resources. 

As far as I could explore,  considering the requirements and considerations which drove the design,  forcing an alignment between the DCAT dataset series and the RDF list seems artificial.  
The same feeling informally emerged in our discussion during the last DCAT subgroup meeting last Tuesday, but we were only a few people. 

Also, a very shallow read to the mail and the semantic web paper pointed out by Dan seems not to encourage the effort. (BTW, Thanks, @danbri, for the suggestions.)

Anyway, we are open to considering ideas for mappings between dataset series in DCAT and rdf:List, especially if anyone has an elegant mapping to suggest and if a well-spotted motivating scenario emerges.

**Comment by riccardoAlbertoni** [comment]
Hi @rhiaro, @danbri and @hadleybeeman, 
Can you live with the supplied explanations?

If there is nothing else to clarify, please let us know when we can consider the review from TAG concluded. 

Thanks a lot.

**Comment by danbri** [comment]
Fine by me. Sequences and lists are always a nightmare. Using very similarly named terms to those in RDF might be a little confusing but not a showstopper nor something to trouble the TAG with.

**Comment by riccardoAlbertoni** [comment]
Thanks, @danbri. 
I am closing this PR since also the TAG has acknowledged the replies as satisfying in https://github.com/w3ctag/design-reviews/issues/758#issuecomment-1195215972 .
