### ISSUE TITLE
dcterms:language property in dcat:Distribution

### ISSUE THREAD

**Issue by marielleadam** [w3c/dxwg#1532]
In Belgium, we are often working with resources in different languages since we have 3 official languages. It can therefore happen that distributions are published in 3 or 4 languages at federal level, as our publications are intended for all publics. 

In paragraph 6.4.9 Property language, under Class: Cataloged Resource, usage note gives the following instruction:
_If representations of a dataset are available for each language separately, define an instance of dcat:Distribution for each language and describe the specific language of each distribution using dcterms:language (i.e., the dataset will have multiple dcterms:language values and each distribution will have just one as the value of its dcterms:language property)._
Nevertheless, in the vocabulary specification for Class: Distribution, the property language is not listed as specific to this class. 
Is it confirmed that we can use dcterms:language property for each distribution of a dataset available in different languages? 
How to deal with distributions that are the same for different languages? Can we use more than one dcterms:language property for a distribution?

**Comment by riccardoAlbertoni** [comment]
>Is it confirmed that we can use dcterms:language property for each distribution of a dataset available in different languages?

Yes, see the usage note for <code>dcterms:language</code> https://w3c.github.io/dxwg/dcat/#Property:resource_language

>How to deal with distributions that are the same for different languages? Can we use more than one dcterms:language property for a distribution?

Yes, it makes sense to me if a distribution supports more than a language, as there are 3 official languages which are required to be distributed jointly.

**Comment by riccardoAlbertoni** [comment]
To make it even more explicit, PR #1535 specifies in the usage note of dcat:Resource that "in the case of multilingual distributions, the distributions will have multiple dcterms:language values."
