### ISSUE TITLE
provide DCAT3 RDF and ttl downloads

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/dxwg#1533]
https://www.w3.org/ns/dcat is still only DCAT2. When can we expect DCAT3 RDF and ttl?

Possibly related to #1498.

**Comment by riccardoAlbertoni** [comment]
Dear @VladimirAlexiev, 
The in-progress draft RDF for dcat 3 is available at https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat3.ttl
External terms reused in DCAT are collected in https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat3-external.ttl

Both the RDF files still need some tweaks, particularly on translations and creation metadata  (see  https://github.com/w3c/dxwg/pull/1508 and, as you have already noted,  https://github.com/w3c/dxwg/issues/1498). 

The official RDF will be provided at the official IRI, https://www.w3.org/ns/dcat, once DCAT 3 gets to the subsequent phases of the rec process.
I do not know if the mentioned unofficial drafts can help you in any way in the meanwhile.

**Comment by VladimirAlexiev** [comment]
Thanks @riccardoAlbertoni ! This is very helpful
