### ISSUE TITLE
can dcat:version be used on any resource?

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/dxwg#1534]
- https://w3c.github.io/dxwg/dcat/#Property:resource_version doesn't define a domain, 
- https://w3c.github.io/dxwg/dcat/#version-info only gives an example with `dcat:Dataset`. 
- But eg https://github.com/Haigutus/Energy-Reference-Data/issues/22 item 10 wants to use it on `skos:ConceptScheme`

Is such use legit? 
When #1533 is done, that will become more clear. In the meantime, can you add a clarification?

**Comment by riccardoAlbertoni** [comment]
>can dcat:version be used on any resource?

Yes, that is the idea behind non-restricting the domain, at least as far as I can remember.

**Comment by davebrowning** [comment]
We have made a small change to highlight that where we haven't specified domains, we encourage users to reuse properties where they believe its appropriate (aka "legit").  If done sensibly we hope/believe this should help interoperability.

**Comment by VladimirAlexiev** [comment]
Thanks! this is seen around https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat3.ttl#L1732 and the equivalence to `pav:version`.
