### ISSUE TITLE
prefix adms

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1539]
In the list of the non-normative prefixes adms is set to https://www.w3.org/ns/adms# while it should be http://www.w3.org/ns/adms#
(http version instead of https version).

See https://www.w3.org/TR/vocab-adms/#namespaces-1.

**Comment by andrea-perego** [comment]
Thanks for reporting this problem, @bertvannuffelen .

Now fixed via PR https://github.com/w3c/dxwg/pull/1547
