### ISSUE TITLE
dcterms:hasVersion vs dcat:hasVersion

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1541]
In https://w3c.github.io/dxwg/dcat/#Property:resource_relation and the section on relations references are made to dcterms:hasVersion as subproperties of dct;relation.
Since in DCAT 3.0 the intend is to use dcat:hasVersion to denote version information, I propose to exclude dct:hasVersion from the usage note as preferred way to express version information.

**Comment by riccardoAlbertoni** [comment]
As version for dcterms is a wider notion than in DCAT, there are still cases in which users might want to use dcterms:hasVersion". For this reason we are mentioning both dcterms:hasVersion and dcat:hasVersion, as implemented in the PR #1544.
