### ISSUE TITLE
(minimal) Profile metadata extensions for DCAT

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#156]
In addition to expressions of profile constraints - such as the alignments (where these are just profiles - which remains to be seen) there is a need to provide basic metadata about profiles in the context of DCAT - just enough to find such constrain description and guidance resources and to resolve the inheritance relationships to thus to make statements about profile conformance. 

A draft approach is at https://github.com/w3c/dxwg/tree/roba-profile/dcat/rdf

Here is another resource which could be linked in to the DCAT-AP - hoping updating to include this is good opportunity to review approach and suggest whether it is necessary and sufficient, free of extraneous detail and improvements.  If resources supporting DCAT1 profile and other alignments are modelled this way it will be stronger than current practice: text documents pointing to these resources with suggestions to use them.

https://webgate.ec.europa.eu/CITnet/stash/projects/ODCKAN/repos/dcat-ap-to-schema.org/browse/sparql

**Comment by dr-shorthair** [comment]
@rob-metalinkage is this still alive?

**Comment by rob-metalinkage** [comment]
Addressed with profiles ontology :-) https://github.com/w3c/dxwg/tree/gh-pages/profilesont

**Comment by dr-shorthair** [comment]
Good. Maybe take a look through if there any other issues that could be closed as a consequence. 
https://github.com/w3c/dxwg/labels/profile-description 
https://github.com/w3c/dxwg/labels/profile-guidance 
I suspect there is more cruft in the tracker, but it is hard to fight past Nick's issue-blizzard.
