### ISSUE TITLE
DCAT v3 Expected Publication Timeline

### ISSUE THREAD

**Issue by AlasdairGray** [w3c/dxwg#1561]
I have asked the same question on the [public mailing list](https://lists.w3.org/Archives/Public/public-dxwg-comments/2023Feb/0000.html)

What is the expected publication date for DCAT v3?

The latest working draft dates from 10 May 2022
https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/ <https://www.w3.org/TR/2022/WD-vocab-dcat-3-20220510/>

On the working group wiki page the following table is included with publication dates but these have now passed
https://www.w3.org/2017/dxwg/wiki/Main_Page#Dates_for_CR

Deliverable | Date
-- | --
Last date to give WG doc for review | April 30, 2022
WG vote on CR | early June 2022
Transition request | mid-June 2022
Publication | End of June 2022
60 day exclusion period | End of August 2022
Implementation report | October 31, 2022
Editorial changes | allowed to mid-November
No substantive changes after | September 24, 2022

Please can a revised expected publication timeline be published?

**Comment by GKStGovData** [comment]
Did you mean year 2022 or 2023?

**Comment by AlasdairGray** [comment]
Yesterday the wiki showed:
![Screenshot 2023-02-24 at 14 44 05](https://user-images.githubusercontent.com/1141265/221207241-35fee1c4-6f7e-4828-a6e6-ec7a8552564a.png)

It was updated this morning (see [history](https://www.w3.org/2017/dxwg/wiki/index.php?title=Main_Page&action=history)) and now shows
![Screenshot 2023-02-24 at 14 42 27](https://user-images.githubusercontent.com/1141265/221206765-b3c93376-1184-4db7-b57e-4d4768af896e.png)

**Comment by riccardoAlbertoni** [comment]
Yes, @AlasdairGray, 
As you noticed, I was updating the publication timeline.  Also, we voted last week to publish a new WD [1], which should be out very soon. 

My apologies for the belated communication.

[1] https://www.w3.org/2023/02/14-dxwg-minutes#r03

**Comment by riccardoAlbertoni** [comment]
We discussed in tonight's DXWG plenary an update of the publication schedule; see https://www.w3.org/2017/dxwg/wiki/Main_Page#Dates_for_CR  

We keep this github issue open as a further way to communicate variations on the schedule.

**Comment by riccardoAlbertoni** [comment]
Update:  the PR has been voted.  I have just updated the schedule with the latest info
https://www.w3.org/2017/dxwg/wiki/Main_Page#Dates_for_CR
