### ISSUE TITLE
Modelling Persisted Views

### ISSUE THREAD

**Issue by Jonessmj** [w3c/dxwg#1565]
I need to model a persisted View in the catalog along with View specific properties such as the SQL of the View. Should dcat:Dataset be used for this purpose or is a new dcat:Resource needed for this?

**Comment by riccardoAlbertoni** [comment]
Could you provide more details about your use case?
I am not sure to get what you mean with persistent view. 
Thanks

**Comment by riccardoAlbertoni** [comment]
Whether you can use dcat:Dataset or you need to mint a new subclass of dcat:Resource depends on your specific application context.

As a first guess,  I consider the persisted view a derived dataset, model it as a derived dataset using dcat:Dataset, and find a way to track the dependence. However, if view-derived datasets require a different management policy than usual datasets in your use case, I would consider if a specific subclass ( of dcat:Dataset or dcat:Resource) may make more sense. 

DCAT does not specifically address this, and in the terms you have posed the issue, I would be inclined to consider this an application-related need. However, do not hesitate to describe more context if you think persistent views might be a source of requirements to consider in the next standardization rounds.
