### ISSUE TITLE
Explain non-reuse of PAV

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#1595]
DCAT3 implements properties such as [dcat:previousVersion](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_previous_version) that are _Equivalent Properties_ to PAV properties, in this case [pav:previousVersion](https://pav-ontology.github.io/pav/#d4e459) but why not just reuse the PAV properties directly?

A fundamental part of Semantic Web work is ontology reuse.

Is this reimplementation of PAV elements PAV is not an official W3C ontology? If so, then DCAT should reimplement DCTERMS elements too.

I assume the reasoning for non-reuse has been discussed in the WG but the reason is not given in the document so please could it be, or be added here.

**Comment by dr-shorthair** [comment]
The EC considered using PAV, but could find very little evidence of adoption of PAV in operational systems. It has not been touched in nine years. Nice work, but no benefit in importing it, and with the risk of adding yetanother namespace and thereby confusing implementers. We chose to model versioning in the `dcat:` namespace instead, with what is effectively an acknowledgement of the source of inspiration. 

Dublin Core is a very different thing. It is very very widely used, and actively maintained.  It would be folly not to use it directly.

**Comment by nicholascar** [comment]
Fair enough reasoning. Yes, the fact that PAV is unchanged in so long is a threat, although perhaps that's just because it's feature complete...!

PAV is adopted in a few places such as the BODC's NVS, see the `version` and `hasCurrentVersion` predicates in use here and for many other vocabs and vocab Concepts: <http://vocab.nerc.ac.uk/collection/A05/current/EV_OXY/?_profile=puv>

**Comment by dr-shorthair** [comment]
> PAV is adopted in a few places such as the BODC's NVS

Yeah - I recall proposing adoption of PAV when I was working with BODC under the SeaDataCloud project :-) That was much closer to 2015.
