### ISSUE TITLE
Use case: Dataset size characteristics

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/dxwg#161]
Submitting a new USE CASE:

---
### Dataset subsets and size characteristics
Status: 

Identifier: ID51 (proposed)

Creator: Vladimir Alexiev, Ontotext

Deliverable(s): DCAT1.1

## Tags
semantics statistics size

## Stakeholders
Data consumers often need to know how many of what sort of entities are included in a dataset.
In an aggregation scenario, different subsets (parts of a dataset) need to be expressed, eg because they come from different data providers.

Eg in the euBusinessGraph project we have a need to describe **Company** datasets by different providers,
what properties are included in each (eg `ebg:isStartup, org:orgActivity`),
and some partition info eg "the dataset covers jurisdiction Italy" or "the dataset has 1000 Italian startups"
(i.e. `rov:RegisteredOrganization` with `ebg:isStartup=true` and jurisdiction Italy)

## Problem statement
[DCAT 1.0](https://www.w3.org/TR/vocab-dcat/#Property:distribution_size) has only a property `dcat:byteSize`, which is pretty useless to describe any aspect of dataset content or value.

And it has no means of expressing subsets.

## Existing approaches
[VOID statistics](https://www.w3.org/TR/void/#statistics) includes these `void:` counting props: `triples, entities, classes, properties, distinctSubjects, distinctObjects, documents`.

Very importantly, these can be used on [subsets](https://www.w3.org/TR/void/#subset) such as [classPartition and propertyPartition](https://www.w3.org/TR/void/#class-property-partitions), which provides very powerful means to describe exactly what kinds of entities are present, and how many are in the dataset.
Thus I believe that subsets are instrumental in expressing the fine-grained content of a dataset.

## Links
Schema issue https://github.com/schemaorg/schemaorg/issues/1855

## Requirements
Ability to express the fine-grained content of a dataset:
* Ability to express subsets of a dataset.
* Describe subsets by kind of entity (e.g. Companies vs Events) and/or entity characteristics (e.g. Italian companies, Startups, Startups in Italy)
* The kinds and characteristics should be expressed by URLs
* Express the count of entities in a dataset or subset
* Optionally, express other dataset size characteristics. E.g. in RDF context, that's number of triples and nodes

Notes:
* It's pretty clear how to do this for RDF datasets (see VOID). The real challenge is how to do it for other datasets.
* I think it's mandatory to express subset characterization with URLs and not text.
* I think there's also need to express assertions to be used for characterization, eg `ebg:isStartup=true`

## Related use cases
ID33, ID7, RDSAT, RSS.

This one could be merged into ID33 to provide further details.

**Comment by dr-shorthair** [comment]
This looks like a clear gap in DCAT capabilities. 
Primarily applies to Dataset, but also to Catalog

Could UCR team extract Requirements from this?

**Comment by andrea-perego** [comment]
@dr-shorthair , @VladimirAlexiev ,

I think this use case relates very much to the following reqs:
- [Related vocabularies comparision [RVC]](https://www.w3.org/TR/dcat-ucr#RVC) #87
- [Related vocabularies mapping [RVM]](https://www.w3.org/TR/dcat-ucr#RVM) #88 

and also to the following UC:
- [5.44 Identification of versioned datasets and subsets](https://www.w3.org/TR/dcat-ucr/#ID44)

**Comment by VladimirAlexiev** [comment]
So both this one (ID51) and 5.44 (ID44) talk of **subsets** but also about other topics. 
I feel that subsets are such a crucial topic, they should be split into their own requirement.

**Comment by jpullmann** [comment]
The proposal seems to merge two concerns: 1) expressing the structure of data sets, like modeled in DATS ([hasPart](https://github.com/biocaddie/WG3-MetadataSpecifications/blob/master/json-schemas/dataset_schema.json)) and 2) indicating the size property of the composite or the individual parts. My suggestion is to rephrase this UC to cover only 2) and create and link here a new UC on behalf of 1)

**Comment by VladimirAlexiev** [comment]
hi @jpullmann! I've reread this proposal and I agree with you. As I wrote "subsets are such a crucial topic, they should be split into their own requirement". Requirement 5.44 (ID44) also talks of subsets, but for another reason. 

Someone needs to take **subset characterization** parts from this one (ID51), 5.44 (ID44), and your suggestion (DATS hasPart) and consolidate them. I could try it but I'm not sure I can capture other people's suggestions adequately. Are there designated *editors* in this WG?

**Comment by dr-shorthair** [comment]
Editors names on each draft https://www.w3.org/2017/dxwg/wiki/Main_Page#Deliverables 
For UCR document it is Ixchel Faniel, Jaroslav Pullmann, Rob Atkinson.

**Comment by dr-shorthair** [comment]
Relationship of a dataset to subsets is part of #81 
This issue should focus on better description of dataset size, perhaps including extent on different dimensions.  

I've renamed it to reflect that focus.

**Comment by agbeltran** [comment]
As per the last comment, assuming that the related datasets (sub-datasets) are considered in the requirement #81, should this UC be added to the UCR document focusing on the dataset size characteristics where the main requirements would be around (copied from above):

> - Express the count of entities in a dataset or subset
> - Optionally, express other dataset size characteristics. E.g. in RDF context, that's number of triples and nodes

Ping to @fanieli @jpullmann @rob-metalinkage

**Comment by davebrowning** [comment]
Also related to existing issue/requirement #84 and some of the discussion of  #313.

**Comment by dr-shorthair** [comment]
@VladimirAlexiev are you interested in reviving this?

**Comment by andrea-perego** [comment]
Unless there are any objections, I propose we close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
