### ISSUE TITLE
References to DCAT2 needs to be updated to DCAT3

### ISSUE THREAD

**Issue by ewrayjohnson** [w3c/dxwg#1613]
The JSON-LD version of DCAT v3 (https://www.w3.org/ns/dcat.jsonld) has references to DCAT2 which should be updated to DCAT3.
As an example, the following string: "This axiom needed so that Protege loads DCAT2 without errors."

**Comment by riccardoAlbertoni** [comment]
Duplicated issue, it is the same of  #1614,  we are going to address this via PR   #1618

**Comment by riccardoAlbertoni** [comment]
DCAT 3 derefentiation is in place.
