### ISSUE TITLE
https://www.w3.org/ns/dcat is still pointing to DCAT 2.0

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#1614]
As the recommendation of DCAT 3 has been published it should be best that the page https://www.w3.org/ns/dcat is updated to version 3.
It still reflects version 2.0

kr,

Bert

**Comment by rivettp** [comment]
Premature closure - I still get DCAT 2, despite using several browsers and wiping out my cache.
![Screenshot from 2024-10-15 17-02-15](https://github.com/user-attachments/assets/d7df5425-1255-4925-b421-ce66621becc1)

**Comment by riccardoAlbertoni** [comment]
Thanks @rivettp. You should now have DCAT 3 derefentiation in place.
