### ISSUE TITLE
Should we create human-readable documentation for DCAT alignments?

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#163]
Besides formal definitions - maybe using different languages (RDFS/OWL, SKOS, SPARQL) - I think it would be beneficial for users to provide a human-readable documentation of the DCAT alignments we plan to define.

If we decide to go this way, I wonder whether there's a W3C document template we could use.

**Comment by dr-shorthair** [comment]
We did RDF (axiomatic) alignments in SSN using separate files, as proposed for DCAT. 
Then documented them as tabulations in the rec document - see https://www.w3.org/TR/vocab-ssn/#VerticalSegmentation

**Comment by agbeltran** [comment]
@dr-shorthair did you do the tabulation manually or is there a tool allowing to convert the RDF alignments into the HTML?

**Comment by dr-shorthair** [comment]
The tabulation was done manually - sorry.

**Comment by andrea-perego** [comment]
An option - already used for creating namespace documents for some vocabularies - is to generate an RDF/XML version of the alignments, and generate the HTML document via an XSLT.

**Comment by andrea-perego** [comment]
I am closing this issue, as DCAT2 doesn't include alignments, besides schema.org, and we don't plan to work on this.
