### ISSUE TITLE
DCAT - DDI alignment (profile)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#164]
DDI v2 to Dublin Core is here: http://www.ddialliance.org/resources/ddi-profiles/dc

**Comment by nicholascar** [comment]
DDIv3 & v4 are very different to v2. DDI v4 is not complete yet but will be later this year. RDA DDI members will meet at the Berlin Plenary in late March and can discuss alignment.

**Comment by agbeltran** [comment]
The DDI-RDF discovery vocabulary (DISCO) does make some statements on [the relationship to DCAT and other vocabularies](http://rdf-vocabulary.ddialliance.org/discovery.html#relationship-to-data-cube-dcat-and-xkos) that I am including here for consideration:

>Our [LogicalDataSet](http://rdf-vocabulary.ddialliance.org/discovery.html#dfn-disco-logicaldataset) is a subclass of DCAT’s Dataset, and our [DataFile](http://rdf-vocabulary.ddialliance.org/discovery.html#dfn-disco-datafile) is a subclass of DCAT’s >Distribution. DCAT makes few assumptions about the kind of datasets being described, and >focuses on general metadata about the datasets (mostly using Dublin Core), and on different ways >of distributing and accessing the dataset, including availability of the dataset in multiple formats. >Combining terms from both DCAT and the Discovery Vocabulary can be useful for a number of >reasons:

>    Describing collections (catalogs) of research datasets (DCAT)
>    Providing additional information about physical aspects (file size, file formats) of research data >files (DCAT)
>    Providing information about the data collection that produced the datasets in a data catalog >(disco)
>    Providing information about the logical structure (variables, concepts, etc.) of tabular datasets in >a data catalog (disco)

>DCAT is richer for the description of collections and catalogue. Disco supports richer descriptions >of groups of datasets or individual datasets. In this spec, some of our examples are partially based >on DCAT (and we will indicate when this is the case).

**Comment by andrea-perego** [comment]
Thanks for the pointer, @agbeltran . I see that, [in the same section](http://rdf-vocabulary.ddialliance.org/discovery.html#relationship-to-data-cube-dcat-and-xkos), DISCO also discusses relationship with [RDF Data Cube](http://www.w3.org/TR/vocab-data-cube/) and [XKOS](http://purl.org/linked-data/xkos) (another DDI spec). I think their considerations are relevant for some of the vocabulary relationships we are discussing, especially in #88 . 

I'll post a comment on this topic there.

**Comment by agbeltran** [comment]
Thanks @andrea-perego - yes, I didn't get round to doing that earlier today. Cheers

**Comment by agbeltran** [comment]
As regards the relationship between the DISCO vocabulary and the DDI versions, the vocabulary refers to DDI 2.5 (Cookbook) and DDI 3.2 (Lifecycle), stating that:

>This vocabulary contains a selection of the major types of metadata defined by these two versions >in a highly simplified form, for the purposes of discovery. 

(from http://rdf-vocabulary.ddialliance.org/discovery.html#about-ddi)

**Comment by agbeltran** [comment]
This is the link to the vocabulary including the mappings to DCAT that I quoted above is here:
https://raw.githubusercontent.com/linked-statistics/disco-spec/master/discovery.ttl

**Comment by agbeltran** [comment]
Adding a comment by DDI as submitted to [the public comments list](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Sep/0000.html):

> Comment from the DDI Alliance that clarifies the link between Disco and the future DDI4:
> - Disco is based on common content of DDI Lifecycle 3.2 and DDI 2.1 focused on the discovery of statistical (micro)datasets.. Disco was never formally published by DDI.
The new model-driven version of the standard, DDI 4, will be also expressed as an OWL ontology (in the works), and be a complete and in-depth overhaul. In particular, it will encompass all kinds of data, not only statistical micro data. It takes over the features from Disco. A prototype release of DDI 4 will be published in the middle of the year. It will include the UML model and related complete representations/bindings in XML Schema and OWL/RDF-S.

**Comment by andrea-perego** [comment]
Should we revive this issue?

**Comment by nicholascar** [comment]
I am still interested in this alignment as I'm about to start producing datasets from Australian census data that may need to be both DCAT2- and DDI-conformant. I'm happy to be drawn in to work here if DCAT core contributors lead.

**Comment by dr-shorthair** [comment]
@agbeltran has been working on this.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> @agbeltran has been working on this.

@agbeltran , do you have any news to report on this work?

**Comment by riccardoAlbertoni** [comment]
Closed as no news occurred.
