### ISSUE TITLE
Erratum: in DCAT 1.0 RDF dcat:keyword is a sub-property of dct:subject

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#175]
In the RDF representation of DCAT v1, dcat:keyword is a sub-property of dct:subject - see https://www.w3.org/ns/dcat.ttl . 
In the recommendation document this is not mentioned - see tabulation at https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/#class-dataset 
so this row in the description was omitted in the draft moving forward, 

I think this is an unintentional omission, but perhaps worth checking with @makxdekkers and @aisaac if you have any insight? Else it should be added here https://w3c.github.io/dxwg/dcat/#Property:dataset_keyword

**Comment by andrea-perego** [comment]
I think it is probably more correct to say that `dcat:keyword`, whose range is `rdfs:Literal`, is a subproperty of [`dc:subject`](http://dublincore.org/documents/dcmi-terms/#elements-subject). By contrast, [`dct:subject`](http://dublincore.org/documents/dcmi-terms/#terms-subject) (quoting) "is intended to be used with non-literal values" - as `dcat:theme`.

**Comment by makxdekkers** [comment]
Given the definition at DCMI, I don't think `dcat:keyword` can be a subproperty of `dct:subject`. The note with the definition means that `dct:subject` is an `owl:ObjectProperty`, while `dcat:keyword` is an `owl:DatatypeProperty`. I think a sub-property should be the same property class as its parent. I agree with @andrea-perego that it could be a sub-property of `dc:subject`.

**Comment by fellahst** [comment]
I think dct:keyword should remain as is.  dct:subject typically refers to a skos:Concept and enable semantic search and discovery. Making dct:keyword subproperty of dc:subject will just add confusion. Almost no OWL ontology uses DC today. They are mostly using DCTerms ontology.

**Comment by andrea-perego** [comment]
> I think dct:keyword should remain as is. dct:subject typically refers to a skos:Concept and enable semantic search and discovery. Making dct:keyword subproperty of dc:subject will just add confusion. Almost no OWL ontology uses DC today. They are mostly using DCTerms ontology.

@fellahst , I agree that the range of `dcat:keyword` (`rdfs:Literal`) should not be changed, but the statement making it a subproperty of `dct:subject` is formally incorrect, and it should be marked as an erratum / deleted.

**Comment by dr-shorthair** [comment]
Definition of `dct:subject` here: http://dublincore.org/documents/dcmi-terms/#terms-subject 
Indeed, it says "This term is intended to be used with non-literal values", which would be inconsistent with `dcat:keyword`, which has an explicit range of `rdfs:Literal`. 

So it appears there is another erratum in the RDF representation of DCAT 1.0 - the rec document appears to be correct, so the RDF file has an incorrect sub-property axiom. 

@draggett @kcoyle @pwin another erratum?

**Comment by fellahst** [comment]
@andrea-perego I think you misunderstood my suggestion. I never said that dcat:keyword should be a subclass of dct:subject. It would be incompatible indeed.

**Comment by andrea-perego** [comment]
@fellahst said:

> @andrea-perego I think you misunderstood my suggestion. I never said that dcat:keyword should be a subclass of dct:subject. It would be incompatible indeed.

Sorry for the misunderstanding.

**Comment by davebrowning** [comment]
Since we're nearing the approval process for DCAT2, should we not at least log this on the 2014 DCAT errata page at https://www.w3.org/2001/sw/wiki/DCAT_Errata ?  [It looks like a wiki page editable by any W3 WG member though I haven't tried to save it yes].  SInce we will be providing a new dcat schema file it would be good to have some audit trail on the old file?

(I'm not sure of the process for actually correcting the file, since this isn't an erratum in the Recommendation which would need WG and AC approval. The schema makes it clear that the document has authority over the schema and not vice versa, but it would be nice to have a public erratum record.)

**Comment by andrea-perego** [comment]
@davebrowning , unless you think we should still deal with this DCAT 2014 erratum, I propose we close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.

**Comment by aisaac** [comment]
Sorry I'm re-opening this one. My fault, I have not made the connection between the content of the notification and the essential issue back several years ago...
Since then the definition (and formal range) of dcterms:subject have been changed. Especially, the [comment for using the property](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/subject) now reads:

> Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.

So I believe changing the subproperty axiom, i.e. replacing dcterms:subject by dc:subject, is not needed, and perhaps not desirable. Actually DCMI changed these formal ranges and comments specifically to remove incompatibility issues like the one raised here.
I am flagging this to @kcoyle who was involved in the DCMI discussions too.

**Comment by riccardoAlbertoni** [comment]
We discussed this issue last DCAT call see https://www.w3.org/2021/06/09-dxwgdcat-minutes#t06, 

Personally, I  agree with keeping the sub-property between `dcat:keyword` and `dcterms:subject` as it seems `dctems:subject` now accepts literals, it is an RDF property,  it is not defined as `owl:objectProperty`, ... . 

Other members do not read in the definition of `dcterms:subject` the possibility to use literals. They read  "a literal value that identifies the subject" as a literal embedded in a blank node having the actual lexical representation of the subject as an rdfs:label". 

I guess that more views on whether we can use `dcterms:subject` with literals can help in making a decision.

**Comment by aisaac** [comment]
> Other members do not read in the definition of dcterms:subject the possibility to use literals. They read "a literal value that identifies the subject" as a literal embedded in a blank node having the actual lexical representation of the subject as an rdfs:label".

The last update of DCMI Terms was meant to soften formal commitments and ease interoperability with more 'classical' data representations. It would be quite a disappointment if the outcome would be that the new spec foresees blank nodes being used place of simple literals.

For the record the ISO spec at https://www.iso.org/obp/ui/#iso:std:iso:15836:-2:ed-1:v1:en mentions:

> 3.1.6
> non-literal value
> either a blank node or URI (3.1.13)

So this means that if the idea was to refer to blank nodes, the definition of dcterms:subject would have used the phrase "non-literal value", not "literal value".

I have dug up an old issue from the DCMI Usage board about the note for dcterms:subject: https://github.com/dcmi/usage/issues/45 . Interestingly, @kcoyle had proposed a wording that was clearer: "A literal value may be used if the controlled vocabulary does not use URIs." Even though it seems that she wasn't happy with the wording of the entire note, and we opted for the slightly more convoluted form in the end, I hope this clarifies the intent of the group at the time the change was made.

**Comment by riccardoAlbertoni** [comment]
I have prepared PR #1384 as I think we should have the DCAT rec and the RDF files as much as possible aligned, and, if we decide to keep the sub-property in the RDF,   we need to add the sub-property in the DCAT 3 rec.

**Comment by andrea-perego** [comment]
@aisaac , I see your point, and I agree that the formal definition of `dcterms:subject` does not prevent it from being used with literals.

My concern is whether this was the actual intention. DCTERMS has so far kept a clear distinction between object and datatype properties, so I wonder whether the current version has changed this approach. Should this be the case, it might be worth stating this more explicitly in property definitions.

Said that, I still think it is safer to just drop the subproperty statement for `dcat:keyword`: not making it a sub-property of `dcterms:subject` does no harm, but has the advantage of avoiding misunderstandings on how this property should be used.

**Comment by riccardoAlbertoni** [comment]
It seems there is no agreement on having  `dcat:keyword` sub-property of `dcterm:subject`.  I would suggest accepting that "we agree that we disagree" and solve the issue merging  PR #1385.

PR #1385 aligns HTML and RDFs as it was meant by DCAT 2 , it removes the `dcat:keyword` sub-property of `dcterm:subject` from the RDF files.


> I still think it is safer to just drop the range constraint for `dcat:keyword`:

@andrea-perego  I haven't understood why dropping the range for `dcat:keyword`. 
At the moment,    `dcat:keyword` ranges in `rdfs:Literals`, and in the RDF files, the property is also defined as an `owl:DatatypeProperty`. What is the rationale behind the suggestion?

**Comment by andrea-perego** [comment]
> @andrea-perego I haven't understood why dropping the range for `dcat:keyword`.
> At the moment, `dcat:keyword` ranges in `rdfs:Literals`, and in the RDF files, the property is also defined as an `owl:DatatypeProperty`. What is the rationale behind the suggestion?

Sorry, @riccardoAlbertoni . I mixed up things.

What I really meant is

> I still think it is safer to just drop the subproperty statement for `dcat:keyword`:

**Comment by riccardoAlbertoni** [comment]
Closed as explained in  https://github.com/w3c/dxwg/issues/175#issuecomment-866810728
