### ISSUE TITLE
Add mechanism for including data distribution services in a DCAT Catalogue

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#180]
Per resolution of #172 the following must be added to the DCAT vocabulary:

1. a class for data distribution services
2. a property to allow a data distribution service to be part of a catalog

**Comment by dr-shorthair** [comment]
The mechanism used to resolve 2. will affect the resolution of #116 .

**Comment by dr-shorthair** [comment]
See proposal here: https://github.com/w3c/dxwg/wiki/Cataloguing-data-services

**Comment by rob-metalinkage** [comment]
IMHO Dataset and DataService look like subclasses of a generic CatalogEntry. If we solve this should also solve case where services are not bound to identified datasets - such as transformation services. Cant really put a counter-proposal until the two facilities needed are available - describing finer-grained service metadata in Distribution, and describing relationships between datasets.   Is a DataService just a subclass of Dataset that has relationships to one or more datasets that have a a service based distribution? Agnostic about final outcome but just feel we are modeling with half the story.

**Comment by dr-shorthair** [comment]
I've tried to sketch a few of the options in the Wiki page 
https://github.com/w3c/dxwg/wiki/Cataloguing-data-services#alternative-views

Of course this is not exhaustive, but we need some concrete proposals in order to move forward.

**Comment by dr-shorthair** [comment]
Resolved https://www.w3.org/2018/04/25-dxwgdcat-minutes 
See https://github.com/w3c/dxwg/wiki/Cataloguing-data-services#chosen-solution

**Comment by dr-shorthair** [comment]
Proposed RDF implementation in https://github.com/w3c/dxwg/blob/dcat-service-simon/dcat/rdf/dcat-service.ttl

**Comment by dr-shorthair** [comment]
Close this as a separate issue - part of #172 and #241
