### ISSUE TITLE
Fix to DCAT class/property diagram

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#186]
In [the DCAT diagram](https://w3c.github.io/dxwg/dcat/images/dcat-model-1.jpg), `dcat:contactPoint` is not depicted as a relationship between `dcat:Dataset` and `vcard:Kind`, but as an "attribute" of `dcat:Dataset` (which is how datatype properties are depicted in the diagram).

The same applies to properties:
- `dct:language`
- `dct:spatial`
- `dct:temporal`
- `dct:accrualPeriodicity`
- `dcat:landingPage`

**Comment by makxdekkers** [comment]
The European DCAT-AP does depict the relationships at https://raw.githubusercontent.com/SEMICeu/DCAT-AP/master/releases/1.1/dcat-ap_1.1.bmp.

**Comment by dr-shorthair** [comment]
That diagram looks like it came from Sparx Enterprise Architect. EA provides a lot of control in how the diagram appears, so might be used to finalize. (Though clearly the DCAT-AP is a lot busier than the DCAT backbone diagram should be.)

**Comment by dr-shorthair** [comment]
I've generated a new diagram using Sparx EA. 
Needs to be some annotation to confirm that RDF cardinality defaults [0..*] rather than UML [1..1] apply but this does allow more control over graphical representation. 
See https://github.com/w3c/dxwg/blob/dcat-service-simon/dcat/UML/DCAT-summary.png
