### ISSUE TITLE
Remove "maintainer" from dcat:Dataset usage note

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#203]
The usage note for ```dcat:Dataset``` states: ```In cases where a distinction between the actual dataset and its entry in the catalog is necessary (because metadata such as modification date and maintainer might differ), ...```. However, the word "maintainer" is not used anywhere else in the specification and therefore may cause confusion. I would remove this example or replace it with "listing date" which is actually present in the ```dcat:CatalogRecord``` description.

**Comment by davebrowning** [comment]
As notified/discussed: https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.04.02
