### ISSUE TITLE
Use Case: interoperability between metadata standards describing resources of various types

### ISSUE THREAD

**Issue by stijngoedertier** [w3c/dxwg#223]
### Use case name
Status: draft / proposed

Identifier: 

Creator: Mathias De Schrijver, Lieven Raes, Thomas D’Haenens, Stijn Goedertier

Deliverable(s): DCAT1.1

## Tags
 dcat meta service

## Stakeholders
data producer, data publisher, data consumer

## Problem statement
 At present, data providers in the public sector are using a wide variety of metadata standards to describe various resource types. For example:
- Geospatial datasets, dataset series, and services are encoded using metadata standards based on ISO19115:2003, ISO19119, ISO19139, or [ISO-19115-1];
- Archival Information on documents, file groups, and record series are described with Encoded Archival Description [EAD3](http://www.loc.gov/ead/)
- Open data datasets and APIs (encoded using DCAT).

Data publishers would like to continue to manage and describe resources of these types using the most appropriate metadata standards, while at the same time reaching the widest possible audience by converting metadata into a frequently used, cross-domain metadata vocabulary like DCAT for inclusion in DCAT-conform catalogs. The currently recommended version of DCAT defines dcat:Dataset as ‘_A collection of data, published or curated by a single agent, and available for access or download in one or more formats_'. If we want to support describing resource types that arguably do not meet this definition (e.g. services, documents, …), we may need to revise the DCAT class structure. One approach could be to provide a more general class than dcat:Dataset like 'Work' or ‘Expression’, taking for example inspiration from definitions in FRBR. In addition, it may be possible to define various sub-classes, like 'Document', 'Data Service', or perhaps even 'Software'. 

## Existing approaches 
- The [GeoDCAT-AP](https://www.w3.org/TR/dcat-ucr/#bib-GeoDCAT-AP) specification provides a mapping for converting ISO19115:2003/ISO19139-based metadata records into DCAT-AP. It also provides an extended vocabulary for encoding other resource types such as services and dataset series.
- The DCAT Application Profile for European Data Portals [DCAT-AP](https://www.w3.org/TR/dcat-ucr/#bib-DCAT-AP) provides an optional dcterms:type property on dcat:Dataset for indicating the resource type (soft typing). A controlled vocabulary for the resource types has not been established.

## Links
- Interoperability between metadata standards: a reference implementation for metadata catalogues. Geraldine Nolf. SDSVoc. 1 December 2016. URL: https://www.w3.org/2016/11/sdsvoc/agenda#p117
- [FRBR] Functional Requirements for Bibliographic Records. 2008. International Federation of Library Associations and Institutions URL: https://www.ifla.org/files/assets/cataloguing/frbr/frbr_2008.pdf#page=18

## Requirements
- [Dataset type \[RDST\]](https://www.w3.org/TR/dcat-ucr/#RDST): Consider creating a generic resource type like 'Work' or a limited set of sub-classes like 'Dataset, 'Data Service', 'Document', 'Series' , etc.

## Related use cases
[Scope or type of dataset with a DCAT description \[ID8\]](https://www.w3.org/TR/dcat-ucr/#ID8), [Modelling resources different from datasets \[ID20\]](https://www.w3.org/TR/dcat-ucr/#ID20), [Cross-vocabulary relationships \[ID36\]](https://www.w3.org/TR/dcat-ucr/#ID36)

## Comments
This relates to #180, #181, #182 and in particular #56 .

---

**Comment by dr-shorthair** [comment]
Following last week's call, I tried to lay out some of the options here: https://github.com/w3c/dxwg/wiki/Cataloguing-data-services#alternative-views 
This is not exhaustive.

**Comment by jpullmann** [comment]
Initially it seems the UC touches the general role of DCAT (and related profiles) as a possible shared standard used at interface level to establish interoperability among repositories while allowing for usage of legacy/internal standards within publisher's infrastructure. Definition of alternative resource types beyond "Dataset" is only one aspect among others. The topic would require a comparative analysis of the conceptual models and identify (in)compatibilities and possible mappings between the considered standards. UCs related to resource types exist already (you linked them), please consider clarifying/restating the UC, e.g. towards usage as a meta-standard at interface (not storage) level.

**Comment by stijngoedertier** [comment]
Thanks for looking into it, Jaroslav. Interoperability between metadata standards is a key selling point for DCAT and we were hoping to have it in the UCR document. The requirement that you derive from that to do a comparative analysis of conceptual models of metadata standards sounds perhaps strong; but some of that is actually done in the WG already. We will reword the UC to emphasize the interface-level interoperability; this is indeed the intended meaning. With regards to resource type, you are right, this is already covered in other UCs and addressed in Simon's proposals.

**Comment by andrea-perego** [comment]
I think this issue has been addressed by the definition of a new class `dcat:Resource`, that can be used as an extension point for resource types different from `dcat:Dataset` and `dcat:DataService`.

Seeing also that there has been no further discussion on this issue, I propose to close it.

**Comment by riccardoAlbertoni** [comment]
> I think this issue has been addressed by the definition of a new class `dcat:Resource`, that can be used as an extension point for resource types different from `dcat:Dataset` and `dcat:DataService`.
> 
> Seeing also that there has been no further discussion on this issue, I propose to close it.

+1 to close it

**Comment by andrea-perego** [comment]
Closing.
