### ISSUE TITLE
Use case: modeling permissions, obligations, prohibitions

### ISSUE THREAD

**Issue by stijngoedertier** [w3c/dxwg#224]
### Modeling permissions, obligations, prohibitions
Status: Draft / proposed

Identifier:

Creator: Mathias De Schrijver, Lieven Raes, Thomas D’Haenens, Stijn Goedertier - Agentschap Informatie Vlaanderen

Deliverable(s): DCAT1.1
## Tags
dcat rights

## Stakeholders
data publisher, data consumer

## Problem statement
For a data consumer, it is convenient to be able to search for data on the basis of (categories of) permissions, obligations, or prohibitions associated with it. These could include (but are not limited to):
- **royalties**: whether a fee must be paid (perhaps not specifying the amount) for example for a data license or usage of an API.
- **attribution**: whether attribution must be given and which text must be used when attributing.
- **commercial use**: whether commercial use is allowed.
- **derivatives**: whether derived work is allowed.
- **share-alike**: whether derivative works must be shared under the same license conditions.
- **reserved names**: whether there is a prohibition to use the name of the publisher/owner when communicating about derivative works (e.g. as an implied endorsement).
- **restrictions**: restrictions stemming from patents, copyright, trademarks, designs, etc.
- **access restrictions**:  whether there are limitations on public access or not.

In addition, a data consumer may wish to automatically meet or enforce obligations such as attribution by extracting relevant information (e.g. attribution text) from the metadata.

## Existing approaches
- The Creative Commons vocabulary ([ccRel](https://creativecommons.org/ns)) provides a vocabulary to describe copyright licenses, it provides properties attributionName, and attributionURL for attribution.
- The Open Data Rights Statement Vocabulary ([ODRS]( http://schema.theodi.org/odrs/)) allows modelling machine-readable rights statements. It provides properties such as attributionURL and attributionText.
- The Open Digital Rights Language ([ODRL](http://w3c.github.io/poe/vocab/)) aims to provide a standard description model and format to express permission, prohibition, and obligation statements to be associated to content in general.
- The Data on the Web Best Practices [DWBP](https://www.w3.org/TR/dwbp/#licenses) includes a best practice on including license information with data on the Web.
- ISO19115:2003 and ISO19115-1:2014 allows representing LegalConstraints in a somewhat structured way. 
- [DCAT-AP](https://www.w3.org/TR/dcat-ucr/#bib-DCAT-AP) proposes the use of a controlled vocabulary for ‘[license type](http://purl.org/adms/licencetype/)’ of license categories that can be convenient to filter resources based on the applicable rights.

## Links
- POE Use Cases and Requirements. URL: https://www.w3.org/TR/poe-ucr/ 

## Requirements
Provide a way for expressing permissions, obligations, prohibitions.
Provide a way to classify a dataset according to applicable (categories of) permissions, obligations, prohibitions.

## Related use cases
[Data access restrictions \[ID17\]](https://www.w3.org/TR/dcat-ucr/#ID17)

## Comments
This is already under discussion in #114, #160

**Comment by davebrowning** [comment]
Is #676 a successor to this?

**Comment by agbeltran** [comment]
This use case is related to (https://github.com/w3c/dxwg/issues/160) that was addressed in #607 (related to requirement https://w3c.github.io/dxwg/ucr/#RDSA at https://github.com/w3c/dxwg/issues/59). Indeed, #676 will provide examples related to this use case. But, shouldn't the use case be included in the UCR or mentioned in relation to existing ones (e.g. https://w3c.github.io/dxwg/ucr/#ID17)?

**Comment by andrea-perego** [comment]
I think this is broader than #160, which is specifically about access restrictions. I would be in favour of adding it to the UCR document, but I wonder whether this option was already discussed, and a decision taken.

**Comment by agbeltran** [comment]
We discussed this issue in [today's DCAT meeting](https://www.w3.org/2019/02/06-dxwgdcat-minutes.html). While this belongs to the UCR document and should be considered by the UCR sub-group (if not already addressed), we discussed that it would be good to add examples on how to deal with licenses and rights following the guidance given in [the corresponding section](https://w3c.github.io/dxwg/dcat/#license-rights).

**Comment by davebrowning** [comment]
From a DCAT perspective, this work is done (at least, its complete within the time available for DCAT 2 CR, though furtehr examples would be good).  As per  https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.04.02, I was going to close it.  However, it should be considered for inclusion in the ucr, and may stimulate some work.  Its already in the 'Future Priority" milestone, so I have removed the due for closing label and it can be processed in due time.

**Comment by andrea-perego** [comment]
As we have a specific issue (https://github.com/w3c/dxwg/issues/676) about adding examples to licences and rights, I propose to close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
