### ISSUE TITLE
DCAT - CERIF  alignment (profile)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#225]
Prepare a formal alignment of DCAT to the CERIF schema

https://www.eurocris.org/ontologies/cerif/

**Comment by VladimirAlexiev** [comment]
@dr-shorthair Interesting! Which of the entities (eg at https://www.eurocris.org/cerif/main-features-cerif) fall in scope of this alignment?
- what would you map Dataset to? The closest is cerif:Product "A research result that is classified neither as a patent nor as a publication" but that seems poor: Product is originally intended for business products (eg a new car or airplane), and Data is not only the end product of a research Project, it's also input and intermediate material.

BTW I'm not sure how up to date the ontology is... I think it's for version 1.3, whereas CERIF is at 1.6:
https://www.eurocris.org/Uploads/Web%20pages/CERIF-1.6/documentation/MInfo.html

**Comment by makxdekkers** [comment]
A report was published recently with an analysis of research metadata standards in relation to DCAT-AP, including CERIF. It can be downloaded from https://joinup.ec.europa.eu/document/research-data-analysis.

**Comment by dr-shorthair** [comment]
I don't think we will actively pursue this
