### ISSUE TITLE
Replace class .note with .ednote in DCAT draft

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#226]
Looking at the NOTE's blocks included in the current DCAT spec, I have the impression they are editorial notes - i.e., note that describe how the content is being / will be revised - which may disappear in the final version of the spec.

For these cases, the CSS class to be used for this block is [`.ednote`](https://github.com/w3c/respec/wiki/ednote), instead of [`.note`](https://github.com/w3c/respec/wiki/note).

PS: In case this proposal is approved, I can take care of creating the relevant PR.

**Comment by davebrowning** [comment]
@andrea-perego Is this issue  past its sell-by date?  Indeed we seem to have quite a few NOTE blocks now that provide commentary or rationale as well as those that describe how the content is being / will be revised.

**Comment by andrea-perego** [comment]
@davebrowning , I think I still saw some notes that should be better made "EDITOR'S NOTE". I'll share shortly a proposal via a PR.

**Comment by andrea-perego** [comment]
Done: https://github.com/w3c/dxwg/pull/743
