### ISSUE TITLE
PROF - VOAF alignment

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#235]
Prepare a formal alignment of PROF (Prof Desc Ont) to VOAF

**Comment by nicholascar** [comment]
Comments from @dr-shorthair suggest that VOAF might be a specialised version of PROF with vocabulary-specific terminology.

**Comment by andrea-perego** [comment]
Just to note that it may be worth considering the complementarity of VOAF (and not only the overlaps). Using multiple vocabularies for profile metadata would just be beneficial to their re-use across communities and platforms.

In the same spirit, I would suggest we do the same exercise with ADMS - if of interest, I can take care of that.

**Comment by andrea-perego** [comment]
@nicholascar , @rob-metalinkage , following the discussion during today's DCAT call on PROF, DCAT & ADMS, I prepared a draft PROF / ADMS alignment - see #240

**Comment by larsgsvensson** [comment]
Should the tag for this one be `profile guidance` instead of `profile negotiation`?

**Comment by aisaac** [comment]
@larsgsvensson indeed. I've changed it. There was 'profile-description' that seemed appropriate so I've added that one too.

**Comment by nicholascar** [comment]
This is now being addressed in Issue #405 so this is being marked due-for-closing in favour of that Issue.

**Comment by aisaac** [comment]
@nicholascar In principle the 'divide-and-conquer' approach (in agile dev) would dictate that we start from a general 'epic' like #405 and then create specific tasks like the one in this issue. But considering that the issue here is so cluttered, that it makes sense to close it.

And another comment: should you want to remove the 'Profile Guidance" label from an issue, please warn all other editors of that deliverable, before doing it (even though I agree that it can be done for this one...) ;-)

**Comment by nicholascar** [comment]
In addition to the VOAF alignment, there is now also a VOAF Related Work section, see the 3PWD candidate: https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#related-voaf

**Comment by aisaac** [comment]
@nicholascar the link you give is interesting for judging on this issue, but let's be clear this is a 'FYI' comment. The new related work session does not essentially (I hope) change the alignment and thus the resolution on this issue.

**Comment by nicholascar** [comment]
@aisaac yes that's correct, the Related Work section is discursive and doesn't change the Alignment at all.

**Comment by nicholascar** [comment]
Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.
