### ISSUE TITLE
Use Case: Profiles of DCAT-AP and various implementation resources

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#238]
Profiles of DCAT-AP and various implementation resource
---
### Development and governance of localised DCAT Application Profiles 
Status: proposed

Identifier: 

Creator:  Rob Atkinson (Please Andrea and Makx check details)

Deliverable(s): (DCAT1.1, AP Guidelines)

## Tags
Profiles, Semantics

## Stakeholders
Publishers and users of implementing profiles of DCAT. (This use case is evidence for a wider scope of any cases where the finer grained semantics of catalogues resources needs to address interoperability concerns.)

## Problem statement
As evidenced by DCAT-AP and GeoDCAT,  profiles of DCAT may be declared and then specialised by communities of practice or local jurisdictions. GeoDCAT-AP is thus a profile of both DCAT-AP and GeoDCAT,  DCAT-AP-IT is an Italian profile of DCAT-AP.
Profiles may be supported by multiple resources, with different roles. DCAT-AP for example provides documents in multiple formats, SHACL validations for multiple versions of SHACL, spreadsheet templates and other types of implementation resources.
The DCAT-AP example also illustrates the practical need to describe relationships between different versions of the profile, and for each of these a unique set of implementation resources.

[link to Makx's presentation at F2F here]

## Existing approaches
Current use of DCAT-AP is a clear example of the need for this pattern in practice.  https://joinup.ec.europa.eu/release/dcat-ap-v11 shows this registered in a catalogue (as a sort of Dataset - which suggests generalisation of DCAT scope) along with a set of implementations resources (described as "distributions").

## Links
https://joinup.ec.europa.eu/release/dcat-ap-v11

## Requirements
6.2.1 Version subject [RVSS]
6.2.3 Version identifier [RVSID]
6.8.1 Profile definition [RPFDF]
6.8.2 Profile representation [RPFRP]

## Related use cases
5.3 Responses can conform to multiple, modular profiles [ID3]
5.4 Dataset Versioning Information [ID4]
5.7 Support associating fine-grained semantics for datasets and resources within a dataset [ID7]
5.20 Modelling resources different from datasets [ID20]
5.24 Harmonising INSPIRE-obligations and DCAT-distribution [ID24]
5.30 Standard APIs for metadata profile negotiation [ID30]
5.39 DCAT Metadata profile integration [ID39]
5.41 Vocabulary constraints [ID41]

## Comments
The nature of profile inheritance and attached resources are implications of this Use Case that were previously inferred from the context in which, for example, the DCAT-AP example was raised, i.e.  in more specific Use Cases about single aspects of DCAT expressivity.  A comment was made that without a grounding in typical technical solution patterns it was insufficiently clear that these overarching governance and usage experiences directly drove the inferred requirements. 

---

**Comment by kcoyle** [comment]
@rob-metalinkage What new requirement(s) would you derive from this use case? (Note that we have a <a href="https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg/edit#heading=h.poqzq68p2cgj">requirement from Europeana</a> that speaks of expressing compatibility between profiles. Also, remember that profiles are not necessarily machine-actionable, so any requirements cannot assume that.)

**Comment by agbeltran** [comment]
As just discussed in the call today, I believe we are missing a requirement on the relationship between profiles (e.g. specifying that DCAT-AP-IT is related to DCAT-AP).

**Comment by kcoyle** [comment]
This may be a requirement that can be derived from the Europeana use case, since what is discussed there are issues that arise from related profiles. So I'll @rob-metalinkage and @aisaac on this. Thanks, @agbeltran

**Comment by rob-metalinkage** [comment]
@agbeltran This requirement is already present : "Profiles may inherit clauses from one or more parent profiles"  Perhaps is ought to be written as "Profiles may add to or specialise clauses from one or more base specifications. Such profiles inherit all the constraints from base specifications."

This requirement is consistent across all the profiling experience but has been left out of the current discussion centered around the https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg/edit#heading=h.5l26dadqk5v7

**Comment by kcoyle** [comment]
If this is to be based on the information that Makx included in his presentation at F2F3, then it should include the community and maintenance management that he outlines in [slides 5-9](http://makxdekkers.com/DXWG/DCAT-AP.pdf). That is missing from our requirements. Also, nothing about DCAT-AP as he describes it refers to inheritance. As you may recall, at the May 22 meeting we agreed that we would not use the term "inheritance" but would speak of relationships or dependencies between profiles. I think we need to adhere to that, here and elsewhere.

**Comment by kcoyle** [comment]
This use case was APPROVED at the plenary meeting of [August 28, 2018](https://www.w3.org/2018/08/28-dxwg-minutes#ResolutionSummary).

**Comment by rob-metalinkage** [comment]
The Use Case also includes other communities further profiling DCAT-AP

I dont think we need to add the governance procedures ... perhaps thats a
separate Use Case if we think it introduces additional requirements.

**Comment by andrea-perego** [comment]
As there has been no further discussion on this issue, I propose to close it.

**Comment by andrea-perego** [comment]
> As there has been no further discussion on this issue, I propose to close it.

Noting no objections, I am closing this issue.
