### ISSUE TITLE
PROF - ADMS alignment

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#240]
Draft added to the relevant [wiki page](https://github.com/w3c/dxwg/wiki/PROF-Alignments-and-crosswalks) ("Alignments and crosswalks").

**Comment by rob-metalinkage** [comment]
Also, we should look at whether ProfileDesc fits under ADMS semantics and hence under this alignment or whether separate alignments of ProfileDesc => DCAT and => ADMS make sense

**Comment by andrea-perego** [comment]
@rob-metalinkage , looking at the correspondences between PROF and ADMS, my understanding is that ADMS provides already the general classes and properties, with the exception of (a) the relationships used to specify dependencies, and (b) the "resource role" (validation, etc.).

More precisely, I think that `adms:Asset` covers the notion of profile, and `adms:AssetDistribution` the one of formal and/or human-readable definition/representation of that profile. It could be argued about the need of defining a profile as a subclass of `adms:Asset` etc., but again I don't see them as something with a semantic scope outside or only partially overlapping with ADMS.

Please note that I'm not saying that ADMS covers all the requirements of PROF: I rather see the two vocabularies as complementary, and only partially overlapping (such overlaps being mainly related to annotation properties - title, description, etc.). More precisely, PROF addresses cases where you need to know which are dependencies, and which of the available profile definitions can be used for doing what (the "resource role"). ADMS has been instead specifically designed for documenting an "asset", not only to make it discoverable, but also to provide contextual information (e.g., who's the publisher, which versions of an asset exist, etc.). Therefore, the use of both can be mutually beneficial - e.g.:
- It would facilitate adoption across communities
- PROF defines relationships that extend the contextual information missing in ADMS, whereas the ADMS approach to asset versioning could turn to be useful when specifying dependencies (if I'm not mistaken, the idea of specifying dependencies by referring to the specific version of a standard, instead of the latest version of it, was discussed during the last f2f).

Similar considerations can be done for VOAF - which, based on the current discussion threads, could be used whenever a profile can be classified as an RDF vocabulary / OWL ontology.

**Comment by rob-metalinkage** [comment]
+1 in general - however i thin adms:asset covers more than just the 'notion of profile" - so its worth subclassing it, and then adding the extra bits only to the subclass, not adms:asset

**Comment by nicholascar** [comment]
@andrea-perego PROF has had, since 2PWD, an alignment declared with ADMS (https://www.w3.org/TR/dx-prof/#alignment-adms). Are you happy with the alignment and thus are we able to close this issue?

**Comment by andrea-perego** [comment]
Sorry for my late reply, @nicholascar .

I see that `prof:Profile` is neither a subclass of `dcat:Dataset` nor `adms:Asset`.

If this is the final decision, the only specified alignment is of course correct - i.e., the one about `prof:ResourceDescriptor`.

**Comment by andrea-perego** [comment]
> If this is the final decision, the only specified alignment is of course correct - i.e., the one about `prof:ResourceDescriptor`.

Actually, this depends on the semantics of `prof:ResourceDescriptor`, and I see that this is still being discussed in https://github.com/w3c/dxwg/issues/573

**Comment by nicholascar** [comment]
With discussion about the remaining point here - semantics of `prof:ResourceDescriptor` elsewhere - and the fact that the substantive part of the Issue - the PROF - ADMS alignment section review - is complete, I'm closing this.
