### ISSUE TITLE
Licenses/rights/obligations on Services

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#248]
In #104 we considered whether usage controls should be added to Dataset alongside or in place of Distribution and it was explained why they are best kept associated with the distribution. 

Now we have a separate class for DataService, it is probably necessary to have similar access and usage controls there - key arguments on usage controls related to DOS risks, which obviously apply to services.

**Comment by andrea-perego** [comment]
GeoDCAT-AP uses `dct:license` and `dct:accessRights` (directly associated with `dctype:Service`) to specify, respectively, use and access conditions.

**Comment by agbeltran** [comment]
My view with this issue is that given the new section about 'License and rights statements' that was added to the ED, now we need to add the recommended properties to the relevant classes and then we can close this issue.

**Comment by agbeltran** [comment]
Additions related to this issue:  given the guidance in the [License and rights statements](https://rawgit.com/w3c/dxwg/dcat-issue633-issue114-daveb/dcat/index.html#license-rights), make sure that ```dct:license```, ```dct:accessRights``` and ```dct:rights``` and ```odrl:hasPolicy```explicitly to the list of properties in dcat:Resource and dcat:Distribution with corresponding requirement level.
