### ISSUE TITLE
Examples of quality for services

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#252]
We might want to include in the DCAT document examples of quality documentation related to services/catalogues. In particular, as suggested by Peter and other during  a DCAT call (see https://www.w3.org/2018/06/07-dxwgdcat-minutes)
>Given we are thinking of dataservices - we maybe need to think about these dimensions?
Platform stability (Average Availability; Mean time to failure; Mean time to repair; Mean time between failure; etc) Platform response (Response time; Throughput; Capacity; ) Scalability (static - add more kit; dynamic; predictive;) Latency Help Desk availability (none; 9-5; 24/7)

**Comment by riccardoAlbertoni** [comment]
This issue has lost some of its importance considered the stage of DCAT development and that we have decided to reduce the number of examples. I think we might consider to close it... 
@pwin: what do you think?   

Shall we label this issue as "wontfix", or do we want to mark it with a new label, for example, "FoodForAPrimer"?

**Comment by agbeltran** [comment]
I think it is good to tag it with ```dcat-primer``` and I've just created the label

**Comment by andrea-perego** [comment]
As no work is planned for a DCAT primer, I propose we close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
