### ISSUE TITLE
There need to be an http-based mechanism to point to representations conforming to other profiles [ID30] (5.30)

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#266]
Original wording: "Return http link headers using the following relationship types... [ID30] (5.30)"

Entered from Google Doc
 
* derivedfrom: The URL of the source document, containing the ISO 19139 records.
* profile: The URI of the metadata schema used in the returned document.
* self: The URL of the document returned by the API.
* alternate: The URL of the current document, encoded in an alternative serialization.

**Comment by nicholascar** [comment]
Lars' rewording suggestion: There needs to be a way to encode the necessary relations using an http link header

**Comment by larsgsvensson** [comment]
This feels more like a solution than a requirement. A req could be: "There need to be an http-based mechanism to point to representations conforming to other profiles". Using Link-headers could be a way of implementing that.

**Comment by nicholascar** [comment]
Changed as per Lar's suggesting with the original wording indicated in the description

**Comment by aisaac** [comment]
I think we should still (as part of the requirement derived from 5.30) list the "necessary relations": URL of the source document, etc (so, keeping the feature but removing the http link header that was suggested as solution)

**Comment by aisaac** [comment]
Just a note to clarify that my emphasis on the fact that there should be a focus on possible relations comes from my reading of the [Google doc](https://docs.google.com/document/d/13hV2tJ6Kg2Hfe7e1BowY5QfCIweH9GxSCFQV1aWtOPg/) of our discussions

**Comment by nicholascar** [comment]
De-tagging as profile-negotiation as dealt with by its point of view

**Comment by andrea-perego** [comment]
@aisaac , @larsgsvensson , @nicholascar , @rob-metalinkage ,

Based on the discussion, it seems that this issue is about ConnegP and/or PROF, and that it has been addressed in both.

Should we close it?

**Comment by nicholascar** [comment]
Yes, I think this is dealt with in ConnegP and the _Alternate Representations_ data model [ref in ConnegP](https://w3c.github.io/dx-connegp/connegp/#altr-detail). It's actually outside PROF's concerns as PROF only IDs and described the profiles.
