### ISSUE TITLE
A client should be able to discover which profiles are supported by a server, and with which content types or other properties, in order to receive the representation most appropriate for their use.

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#285]
Entered from Google Doc

**Comment by larsgsvensson** [comment]
Perhaps the latter part of the sentence should read "the representation most appropriate for their use".

**Comment by nicholascar** [comment]
Changed as per Lars' suggesting.

These requirements retain lineage - to check that changes like this don't break with the original intention - by being linked to from the originals in the Google Doc.

**Comment by rob-metalinkage** [comment]
Addressed in document.

**Comment by larsgsvensson** [comment]
Closed in conneg meeting 2019-03-13
