### ISSUE TITLE
Add void:rootResource as property of dcat:Resource ?

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#292]
Comment received by [email from Nuno Friere](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Apr/0001.html) suggests that void:rootResource might be a useful property to a dataset 'manifest'.

**Comment by jakubklimek** [comment]
Actually, this is not accurately specified.
`void:rootResource` (see [specification](https://www.w3.org/TR/void/#root-resource))

1. only applies to `void:Dataset`s, which are RDF datasets, not any datasets, which correspond (and this should be discussed as well, although we use it this way in Czechia) to RDF `dcat:Distribution`s of a `dcat:Dataset`.
2. the object of the property should be an RDF resource belonging to the dataset. A manifest would be metadata about a dataset, not belonging to the dataset.

Therefore I would suggest not using this property for attaching a manifest.

A related question - how would a manifest look like? Is there a specification for such manifests? If not, I would suggest trying to cover whatever would be in the manifest directly in DCAT.

**Comment by nfreire** [comment]
(Note: I do not have a complete knowledge of DCAT. I'm participating in the discussion from a DCAT user point of view, thus presenting my use cases for DCAT)

My original request for void:rootResource originated from a use case of Europeana, and was indeed having RDF datasets in mind. I'm working on a crawler for aggregating linked data into Europeana, and I wanted to use DCAT as the way to allow data providers to provide all technical details for allowing the crawler to start the process of crawling all the dataset's RDF resources.

But actually, the use case of the 'manifest' is also relevant to for Europeana. It can also allow the RDF crawling, and may fulfill also another use case where data providers specify their dataset to Europeana using a Sitemap.

**Comment by agbeltran** [comment]
Including here a link to the discussion in the comments list: https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0007.html

Also, in this DCAT revision we've added a way to represent loosely structured catalogues, where a dataset is form by a set of files. In this case, we are using dct:relation to connect the dataset with the different files that compose it (see the property description: https://w3c.github.io/dxwg/dcat/#Property:resource_relation, see the examples at: https://w3c.github.io/dxwg/dcat/#bag-of-files, and see discussion about this in the issue https://github.com/w3c/dxwg/issues/253)

We also have an open issue about representing the multiple files that are part of a dcat:Distribution (see https://github.com/w3c/dxwg/issues/482). 

So, do you agree that by considering those two points above, we will provide a way to navigate all the files corresponding to a distribution and to a dataset?

**Comment by nfreire** [comment]
I agree. 
Using that solution along with the use of dct:conformsTo and ideally, along with http://usefulinc.com/ns/doap#implements, should provide the full technical details a robot would need for the Europeana use cases.

Question: Is doap:implements included in DCAT (or its use under discussion)?

**Comment by agbeltran** [comment]
```doap:implements``` associates Projects to the Specifications the project implements. Where would this fit in the use case? Europeana as the project that implements DCAT? 

Currently, we associate ```dcat:Resource```s associated with ```dct:Standards```  via ```dct:conformsTo``` (see https://w3c.github.io/dxwg/dcat/#Property:resource_conformsto)

**Comment by nfreire** [comment]
I believe you're right, Alejandra. i was mixing up standards/semantics in my mind...
Having multiple files in a dcat:Distribution along with the use of dct:conformsTo should fulfill the Europeana use cases.

(I'll discuss it with my colleagues an give further feedback, if something relevant is identified)

**Comment by davebrowning** [comment]
Is this issue now closable?

**Comment by nfreire** [comment]
From my point of view, yes, the ticket may be closed, since the requirement is being addressed in the other tickets.

**Comment by davebrowning** [comment]
Thanks, @nfreire
