### ISSUE TITLE
Provide guidance discouraging usage of blank nodes

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#300]
Based on the discussion in #253 a need for guidance discouraging usage of blank nodes was identified.

Even though it is one of the principles of Linked Data (to identify everything with an IRI), publishers tend to use blank nodes for various types of entities including some very important ones like `dcat:Distribution`s.

I suggest:

1. Not to use blank nodes in any examples in the specification. A similar effect (shortening) can be achieved by a combination of prefixes and relative IRIs.
2. Recommend explicitly to identify everything with an IRI and support it with a link to [this Linked Data page](https://www.w3.org/DesignIssues/LinkedData.html). This should be placed somewhere in the beginning of the specification.
3. Explain the disadvantages of using blank nodes - impossible to link, different identifiers with each access

**Comment by riccardoAlbertoni** [comment]
@jakubklimek  wrote
> Explain the disadvantages of using blank nodes - impossible to link, different identifiers with each access

I guess the following sentence taken from the book [Leigh Dodds,
Ian Davis; Linked Data Patterns A pattern catalogue for modelling, publishing, and consuming Linked Data, chapter 2](http://patterns.dataincubator.org/book/identifier-patterns.html) might help.

> RDF allows resources to have global identifiers or to be un-named "blank nodes". While blank nodes may offer flexibility for some use cases, in a Linked Data context blank nodes limit our ability to collaboratively annotate data. A blank node cannot be the target of a link and we can't annotate it with new information from new sources. As one of the biggest benefits of the Linked Data approach is that "anyone can say anything anywhere", use of blank nodes undermines some of the advantages we can gain from wide adoption of the RDF model. Even within the closed world of a single application dataset, use of blank nodes can quickly become limiting when integrating new data.

**Comment by jakubklimek** [comment]
@riccardoAlbertoni That is a good reference. I would still look for a stronger discouragement in the specification. Maybe backed by this reference, I would say something like "Since DCAT is meant for description of entities with high linking potential such as not only catalogs, datasets, distributions and services, but also contact information and other useful metadata, the usage of blank nodes is strongly discouraged".

**Comment by agbeltran** [comment]
+1 to adding some text in line with @jakubklimek's suggestion after including the definition of a blank node and citing the article pointed out by @riccardoAlbertoni

**Comment by davebrowning** [comment]
Somebody want to make a contribution (ie merge request)?  I already have an action to check our  examples are consistent (which I plan to do by month end), but I'm a bit buried in some of the other tidying up.

**Comment by davebrowning** [comment]
This was discussed in todays DCAT meeting (minutes [here](https://www.w3.org/2018/08/23-dxwgdcat-minutes)).  The general view was that the resolution above looked acceptable, but it would be sensible to wait and check with a broader group after holidays.  This reflects an impression that blank nodes have been commonly and usefully used in a few corners (e.g. distributions) so we want to ensure the weight of any guidance for this text is appropriate for all.

In advance of that, the consensus of the (v small) group in discussion was that this would figure near the beginning of the  DCAT Vocab Overview section [here](https://w3c.github.io/dxwg/dcat/#vocabulary-overview) using the verb `SHOULD`.  Comments on this approach are welcome

@makxdekkers, @andrea-perego - any views from  experience or current practice?  Does this seem appropriate?

**Comment by makxdekkers** [comment]
In general, I agree that the use of blank nodes `should `be discouraged. 
However, it depends on whether or not there is an expectation that the object identified is something that should be linked to from other places or could be further described.
Of course, in the case of publishers and themes and locations and licences it's fairly obvious that blank nodes hinder linking and re-use, but there are cases where the use of a blank node might make sense. One of those is for the object of `dct:temporal`. In the European DCAT-AP, a period of time is defined with `schema:startDate` and `schema:endDate`, and in most cases it would not be useful to create a URI for a particular range of time. It needs to be noted that minting a URI implies a maintenance commitment -- a URI that is not maintained is worse than a blank node, in my opinion. 
Other than that, we can say whatever we want, but implementers will still do what works for them -- if they have legacy data that only contains text strings, they will very likely create blank nodes to carry the strings, because the only choice they have is mint a URI or use a blank node. In the future, given that, for example, DCMI plans to abandon `rdfs:range` for `schema:rangeIncludes`, it will be perfectly legal for those implementers to put the string, e.g. publisher's name, as a `rdfs:Literal` so the need for either minting URIs or creating blank nodes will go away.

**Comment by jakubklimek** [comment]
@makxdekkers I see your point, but from practice I can say that when you already have an IRI for a `dcat:Dataset` which you have to maintain (an I think we both agree that those should not be blank nodes), it is usually not a problem to also maintain an IRI `<datasetIRI>/temporal` and such.

Regarding the implementers, they should primarily do what works for the users, and the specification should guide them in that way. In my opinion, we should simply convey that minting IRIs for everything is the normal thing to do, and using blank nodes has only disadvantages in the world of data on the web. Then, if they still decide to use blank nodes, they know it is not good and so do the users.

Btw see for instance the [Richard Cyganiak's blog post regarding blank nodes](http://richard.cyganiak.de/blog/2011/03/blank-nodes-considered-harmful/).

**Comment by makxdekkers** [comment]
@jakubklimek The example of dct:temporal falls into the third bullet point "_auxiliary resources that don’t correspond to a meaningful entity in the domain of interest (e.g., some n-ary relations) and are not worth the hassle of maintaining a stable URI_". 
I do not necessarily agree that maintaining one set of URIs means you can maintain many sets of URIs without problems. Maintenance implies cost and cost needs to be justified by benefit.
Anyhow, I think we agree that blank nodes should be avoided as much as possible.

**Comment by jakubklimek** [comment]
> The example of dct:temporal falls into the third bullet point 

@makxdekkers True, if you do not consider the time interval as a meaningful entity. I would personally much rather specify it to be a meaningful entity such as http://reference.data.gov.uk/id/gregorian-interval/2004-01-01T00:00:00/P3Y so that you can easily search for datasets covered by similar time intervals, etc. but that is another issue.

**Comment by makxdekkers** [comment]
@jakubklimek I would say that the URI you suggest can *only* be used for searching for resources that have that *exact same* time interval. To compare the ranges, you need to follow your nose to that URI in order to look at the dates -- the URI might be indicative of the real-world entity it represents, but you should treat the URI as an opaque string.

**Comment by jakubklimek** [comment]
@makxdekkers Yes, the "follow your nose" principle is one of the basic principles of Linked Data, I see nothing wrong with that. I am not suggesting parsing URIs here.

If an implementation does range queries, it can always cache the data from the authoritative source as optimization, if that is what worries you.

**Comment by kcoyle** [comment]
Perhaps the document can be worded in terms of functionality: if you want to be able to do X you SHOULD NOT use blank nodes.

**Comment by makxdekkers** [comment]
Or the other way around: if you use blank nodes, you and people that use your data won't be able to do X, Y and Z.

**Comment by riccardoAlbertoni** [comment]
@makxdekkers  wrote
> Or the other way around: if you use blank nodes, you and people that use your data won't be able to do X, Y and Z.

 It seems to me that the sentence taken from the linked data pattern book goes in the Makx's direction and  it can be a starting point ;) Perhaps considering the large and mixed audience we are targeting with DCAT,  the sentence might need some rewording, Is there anything more we want to stress?

**Comment by agbeltran** [comment]
PR including guidelines discouraging blank nodes has been merged: https://github.com/w3c/dxwg/pull/326
