### ISSUE TITLE
DCAT - CSMD/ICAT alignment (profile) 

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#302]
Prepare an alignment of DCAT to CSMD: the Core Scientific Metadata Model and ICAT

- https://icatproject-contrib.github.io/CSMD/csmd-4.0.html
- https://icatproject.org/user-documentation/icat-schema/

CSMD was developed by UK STFC, and is facilities/investigations oriented, with datasets seen as results or outputs from these. The ICAT metadata schema appears to be the contemporary realization of CSMD.

**Comment by andrea-perego** [comment]
@dr-shorthair , is there any work planned on this? Otherwise, I suggest we close this issue.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
