### ISSUE TITLE
Links from DCAT draft to (DCAT 2014) rdf 

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#320]
Looking at the editors draft, some (possibly all)  of the internal links in the vocabulary specification pick up old RDF.  Its most obvious where the RDF Property field contains something like `dcat:dataset` which takes you to what's basically a redirect page at https://www.w3.org/ns/dcat that then links to the 2014 ttl or rdf/xml...so you're no longer looking at the updated version.  By comparison, links to definitions in specifications like DCT take you from `dct:hasPart` direct to the ttl (even if the anchor syntax is a bit irrelevant). 

[There's a separate consistency issue - which is what I was trying to address - where we've mixed up links to the rdf with links within the document but that's comparatively minor - I'm fixing that on the back of existing actions]

I think there are two questions:

1. Do we want to persist the 2014 approach of an intermediate page which allows then points independently to the RDF?  That only makes sense to me if we plan to do both ttl and rdf/xml forms - I think we decided not to do that?
2. For Second public draft, what do we want to achieve?  We do have a link to the live version of the ttl in Abstract - which is good, but I don't think its adequate.  [We know nobody reads introductions, but people do read abstracts, I think.  Unfortunately its not always the same people who read the doc.....]

My instinct is that we should fix this so the links work but open to be persuaded...

**Comment by pwin** [comment]
Re: Q1.  I don't see much point in RDF/XML if we have ttl.  I think that a diagram of the examples (just simple circles and arrows) could also be helpful if we are going to do any duplication of the representation of examples.  What do you think?

**Comment by davebrowning** [comment]
While following this up via the published [W3C policy on namespaces](https://www.w3.org/2005/07/13-nsuri), what we have at https://www.w3.org/ns/dcat is an abbreviated namespace document as described in the policy.  Looking for some current practice (for example for [XML](https://www.w3.org/XML/1998/namespace), [XSD](https://www.w3.org/2001/XMLSchema) or [Prov-O](https://www.w3.org/ns/prov#)) the contents of these appear to be fairly flexible though the DCAT offering is a little abbreviated.

For 2PWD purposes, I propose we update the existing DCAT namespace document to add a simple link to the updated dcat ttl file - there is perhaps a broader discussion needed on what we want to do as we get closer to proposed rec etc - now raised as #377

**Comment by davebrowning** [comment]
This issue which was raised in the context of 2PWD is actually resolved.  The longer term/REC approach should be addressed under #377, so I'm closing this one.
