### ISSUE TITLE
Profile description model and vocabulary

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#323]
There are decisions that the group needs to make regarding the [profile description ontology ](https://github.com/w3c/dxwg/tree/gh-pages/profiledesc)and model brought by @nicholascar and @rob-metalinkage. 

There are a number of components here that are likely to be conflated:

1. **Requirements for description.** There are requirements for the description of profiles, e.g. "Requirement: Profiles should be able to indicate what external standards specifications are expected to be applied/have been applied to the data provided". Many of these could be included in a profile or be part of a separate profile description. ([Karen's analysis of requirements](https://github.com/w3c/dxwg/wiki/Profiles-Requirements-Analisys)). These could provide the rationale behind a profile description vocabulary

2. **Model for profile description.** There is the possibility to provide, within profile guidance, a model of profile description. This model could be presented as a part of a profile (similar to administrative metadata), as a separate set of metadata, or both. The separate solution would be implementable today, but as a part of a profile, because we have no  ontology for profiles. Providing this model may or may not also imply WG endorsement of the profileDesc vocabulary. A roundup of possible outlines for the deliverable is [here](https://www.w3.org/2017/dxwg/wiki/ProfileRoundup).

3. **profileDesc ontology.** The third component is the profileDesc vocabulary. We have discussed the options here as:

- Include the ontology in the Profile Publication Guidance document, on recommendation track
- The ontology would be a separate deliverable on recommendation track
- The ontology would be a WG note
- The ontology would not be a WG deliverable

**Comment by rob-metalinkage** [comment]
The options are indeed the question - and they implicate whether or not we can provide any recommendations about the accepted requirements. We may choose not to offer suggested solutions where none is identified.

However, I think the separation of these concerns is false - profileDesc is providing an option for a solution for the first two concerns, where no other option has yet been identified,  and is only "conflated" in that sense, its not a separate concern nor an alternative solution - its a direct response to the requirements arising from these.

Then, "description" and a "model for description" is hard to separate - you cant have a description without a model for that description. And if that model is not published in a formalism you simply cant have an interoperable description.

**Comment by rob-metalinkage** [comment]
This seems a little inverted: we have a set of requirements, and to meet those requirements we will create the minimal set of resources needed support interoperability of data exchange within communities of practice.

Profile guidance is the key deliverable - but for several key requirements we can offer no guidance in the absence of an available solution - other than to "go and develop a standard solution". ProfileDesc is a candidate, but not proscriptive, option for meeting some specific requirements.

I fear that if we continue to confuse this with the issue of the "perfect" profile specification language, (which also doesnt appear to exist) then we will keep on worrying about "i dont know how to describe my profile with profiledesc therefore there is something wrong". It doesnt peel potatoes either.

**Comment by kcoyle** [comment]
There's nothing inverted about it. Among the 4 options are 2 that include profileDesc vocabulary. I don't know why you think including it isn't desirable. Including a model in the document and a solution in a note is one of the suggested approaches based on prior discussion. I can see that you may have preferred options, but I don't understand objecting to having options that have been discussed. Are you saying that we should not consider these options?

**Comment by kcoyle** [comment]
Adding in here a link to [ADMS](https://www.w3.org/TR/vocab-adms/) as a descriptive vocabulary, and one that would probably fit with ideas put forth that profiles be considered datasets, with their actionable files as distributions.

Asset Description Metadata Schema (ADMS)
W3C Working Group Note 01 August 2013 

This could fit in with the requirement in the charter that we provide "an explanation of one or more methods for publishing and sharing" profiles. If profileDesc is described as a note, then we would have multiple suggestions for describing a published profile. The ADMS one would be more closely tied to DCAT, the profileDesc one would be independent of DCAT. The combination seems to be a good one.

**Comment by kcoyle** [comment]
Also adding in here some links relating to what W3C calls a "note". Notes are documents produced by working groups that are generally in support of the group's work but do not get the imprimatur of a Recommendation. They also do not need to be approved by W3C membership. They are, however, often highly usable and used. Here are some examples of notes that introduce ontologies:

[ Dataset Usage Vocabulary](https://www.w3.org/TR/vocab-duv/)
[Data Quality Vocabulary](https://www.w3.org/TR/vocab-dqv/)
[Asset Description Metadata Schema (ADMS)](https://www.w3.org/TR/vocab-adms/)


This is the kind of document that would be developed if the working group decides to offer profileDesc as a W3C Note.

**Comment by rob-metalinkage** [comment]
ADMS is certainly a relevant profile of DCAT for describing all the asset management aspects of cataloguing profiles. 

We still need to subclass it for the specifics of profiles as semantic assets to meet identifued requirements. And profiles still exist outside the context of asset management (but arguably shouldnt).

More analagous to a SKOS vocabulary... its a type of semantic asset we want to catalogue... but developing and testing one needs the clean model, not the administrative metadata rules. 

I will work on examples capturing the natural alignment with ADMS following the DCAT ADMS precedents.

**Comment by dr-shorthair** [comment]
Also see diagrams here: https://github.com/w3c/dxwg/issues/279#issuecomment-417969642

**Comment by rob-metalinkage** [comment]
Its obvious i ran ahead of the group when during UCR editing i had the opportunity (was forced to make the effort to) analyse all the requirements and think about existing vocabularies - before going on to proposing profileDesc as a straw man. So here i set out a set of propositions that reflect that logic  + more recent conversations, so we can work through and vote on if necessary, at which point hopefully we either come up with a common understanding,  or someone can propose a viable alternative, or we can all go home:

1. guidance around development and use of profiles should include, but not be limited to, profiles of RDF vocabularies such as DCAT
2. descriptive metadata needed to meet the identified requirements around profile guidance should be interoperable
3. Where possible, existing RDF vocabularies published by W3C should be used to fulfil requirements, provided these do not introduce excessive unwanted scope and complexity.
4. Where an existing RDF vocabulary within the W3C canon cannot be identified to meet one or more requirements, one may be created as per the WG charter instructions
5. The issues of a conceptual model of profiles and cataloguing of such as semantics are complementary but distinct concerns
6. The ADMS profile of DCAT is relevant for _cataloguing_ profiles
7. Various constraints languages such as SHACL MAY be used to specify profiles
8. No existing vocabulary has been identified to describe the relationships between profiles and base standards and the various specialised relationships between a profile and various representational resources
9. ProfileDesc is a "straw man" or placeholder for a vocabulary to describe profiles, without addressing the scopes of specifying constraints or cataloguing profiles. No part of its naming or model is immutable, and it may be updated as required to best meet identified requirements.
10. a profile of ADMS is appropriate for the cataloguing of profiles - this may be postulated in guidance discussions or published as a Note as appropriate.
11. The status of profileDesc as a Note or Recommendation can be addressed once its design and scope are settled, based on perceived stability and status of independent implementations.

**Comment by nicholascar** [comment]
We have a schedule for Guidance, Ontology & Connec doc delivery now so I'd like to close this.

**Comment by kcoyle** [comment]
I agree that this can be closed. If there are any changes going forward they will happen as part of the publication process.

**Comment by aisaac** [comment]
+1
