### ISSUE TITLE
Clarify intention of 'UML' style diagram

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#347]
In various places we have discussed the merits and risks of using the UML-style diagraming to summarize the DCAT model: 
#186 https://github.com/w3c/dxwg/issues/317#issuecomment-418204334 https://github.com/w3c/dxwg/issues/279#issuecomment-417722427 

While there are many precedents for use of UML to diagram OWL/RDF in W3C specs, some warnings are probably warranted to head off any confusion.

**Comment by kcoyle** [comment]
This is my personal opinion, feel free to ignore if it doesn't meet the needs of the document: I would provide a class diagram with classes and their relationships alone, and ample explanation of the meaning of the classes. Then I would provide the (valid or preferred?) descriptive properties of the classes in a list or table. That would avoid infering any OO meaning to the property list, but would still imply a validation of properties to classes (which is not enforced by RDF, but would naturally be a part of metadata creation and use).

**Comment by dr-shorthair** [comment]
> and ample explanation of the meaning of the classes

While the diagram is becoming busy, the class count is still quite low, and it can be argued that the definition of the classes inheres primarily in their relationships and properties, so making these visible is the clearest way to provide such an explanation. Having a diagram _and_ a table requires readers to look in two places, and correlate between these. 

Geological map legends used to have a hilarious two- or three-step legend, with some kind of hatching or colouring in the map, then a set of tablets linking the hatching to alpha-numeric codes, then captions that linked the codes to text. This was of course due to the limitations of drafting and reproduction technologies. It was bewildering ...

**Comment by kcoyle** [comment]
Thanks, @dr-shorthair. I guess I misunderstood the question you are asking here. Are you looking for some language to accompany the diagram?

**Comment by dr-shorthair** [comment]
I had a go at adding some clarification to the figure caption. See #348. If you think that is still missing something then please say what.

**Comment by agbeltran** [comment]
PR #348 merged
