### ISSUE TITLE
Expand note to explain reason for removal of sub-class relationship to dctype:Dataset 

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#350]
[Feedback from DDI](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Sep/0000.html) asks about relationship between `dcat:Dataset` and `dctype:Dataset` which was relaxed in #98. 

On the one hand the relationship between `dcat:Resource` and the DCTYPE vocabulary is mentioned in [Section 5.3](https://w3c.github.io/dxwg/dcat/#classifying-dataset-types) . 

But it is probably worth expanding the NOTE against the definition of `dcat:Dataset` to indicate _why_ the sub-class axiom was removed.

**Comment by agbeltran** [comment]
The follow up of this discussion is available [here](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Sep/0002.html) and [here](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Sep/0003.html). PR merged, so closing the issue.
