### ISSUE TITLE
Complete list of definitions

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#378]
Feedback sought on any additional definitions we should include here to help with understanding this document.

**Comment by agbeltran** [comment]
Dropping here the link to the wiki where definitions were discussed: 
https://www.w3.org/2017/dxwg/wiki/ProfileContext

The document currently defines: formalism, specification, standard and profile. 

There are mentions to "application profiles", "metadata application profiles", "metadata profiles" - as equivalent - is the intention to clarify these definitions too?

**Comment by nicholascar** [comment]
We haven't worked that out yet @agbeltran! We have a series of other terms in the conneg doc too in Definitions, e.g. *client* & *server* but they are all from the HTTP & URI RFQs.

We plan to take feedback on the definitions needed from the WG and also from the public after FPWD release.

**Comment by agbeltran** [comment]
Thanks @nicholascar - I know there is the issue about normative and non-normative sections but maybe it would be better to have the definitions in one single place, combining [section 2](https://w3c.github.io/dxwg/conneg-by-ap/#definitions) and [section 5.1](https://w3c.github.io/dxwg/conneg-by-ap/#abstractmodelcontext)?

**Comment by kcoyle** [comment]
@agbeltran We talked about the placement of definitions in the guidance document. Placing them all at the beginning was seen (by @aisaac) to be unfriendly to readers, who probably aren't ready for all of that so early in the document. At the same time, without a definition of profile at the very beginning the early text is ambiguous. I don't have a suggestion, just putting this here for context regarding what we've already discussed.

**Comment by agbeltran** [comment]
thanks @kcoyle - but it might have been a cache issue in my browser before, as the latest version of the document has now all the definitions in the same section at the beginning:

https://w3c.github.io/dxwg/conneg-by-ap/#definitions

**Comment by nicholascar** [comment]
Alejandra meant the Conneg doc, not the Guidance doc but yes, they are in one place now after the latest update.

**Comment by aisaac** [comment]
Indeed it was for the Profile Guidance doc that I didn't like to have all the definitions at the beginning. I would say that I don't like much that the Conneg doc, either. But but for now I certainly I won't object to what the editors of the Conneg prefer.

**Comment by agbeltran** [comment]
I was referring to the conneg doc before, but I'm actually in favour of putting all the definitions in a single section in all the documents - this works like a glossary that one reads when needs clarification of the terms used across the document (and people can choose to read all the definitions in one go or not)

**Comment by aisaac** [comment]
@agbeltran you mean to have the definitions in one section in one doc, which would be refer to from other docs? Or each doc has their own section, possibly redundant with the one of other docs?

**Comment by nicholascar** [comment]
A definitions list has appeared in two PWDs now so this issue can be closed.
