### ISSUE TITLE
Ensure de-duplication with concerns in Intro

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#379]
This issue was created in the [Conneg by Profile document](https://w3c.github.io/dxwg/conneg-by-ap/) and is listed in it. Once consensus on addressing it is reached here in comments below, the results will be added to the document and the issue closed.

**Comment by nicholascar** [comment]
Motivation & Intro not overlapping so ready for close.

**Comment by larsgsvensson** [comment]
Decision in CNEG meeting 2018-07-11 to close as resolved.

**Comment by aisaac** [comment]
As part of my reviewing, I actually disagree with this: the second small paragraph of the motivation does overlap with the last paragraph the intro. And once this would merged, there is not much interest to one one paragraph of motivation standing alone. It would be a good addition to the current intro, making it more clear what we mean, that is not negotiation by Media-Type or Language

**Comment by aisaac** [comment]
Just to be clear: I don't think the text in either section reads bad. But I see it could be quite easily merged.

**Comment by larsgsvensson** [comment]
Removed "due for closing" since this issue is not yet resolved. cf #575

**Comment by rob-metalinkage** [comment]
Thanks Antoine - I will have a copy edit pass over this...

**Comment by rob-metalinkage** [comment]
wording as accepted in FWPD - can revisit if raised again
