### ISSUE TITLE
Prof Ont Test Suite tools

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#407]
This issue was created in the [Profiles Ontology document](https://w3c.github.io/dxwg/profilesont/) and is listed in it. Once consensus on addressing it is reached here in comments below, the results will be added to the document and the issue closed.

**Comment by nicholascar** [comment]
How much information about tools to action the shapes graph should be given?

**Comment by nicholascar** [comment]
Consider the prevision of a Test Suite to support the vocabulary. Won't be a normative part of the specification

**Comment by nicholascar** [comment]
Note that no other W3C vocabs have test suites. 

There is a start to SHACL files for testing instance of PROF at https://github.com/w3c/dxwg/blob/gh-pages/profilesont/full-constraints.ttl. The relationship of this SHACL file to the other parts of PROF. e.g the HTML spec, will be described with... PROF!

**Comment by nicholascar** [comment]
See the PROF description of PROF: https://github.com/w3c/dxwg/blob/gh-pages/profilesont/profile.ttl

**Comment by kcoyle** [comment]
I think this is a question for @plehegar in terms of "what are the requirements for a vocabulary as Recommendation?"

**Comment by nicholascar** [comment]
DCAT has no Test Suite while Conneg does. Since PROF is a vocabulary, like DCAT, this Issue is now redundant - we won't be making a Test Suite for the vocab *per se*, although we might make one (SHACL stuff) for other purposes.

**Comment by kcoyle** [comment]
There are no such requirements for WG notes, so you needn't worry about these kinds of formalities. Of course, lots of *examples* aid in uptake, but that's up to you.

**Comment by nicholascar** [comment]
I've raised a new issue to deal specifically with the continuation of the SHACL constraints testing: #1184
