### ISSUE TITLE
Citations and Distributions

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#433]
Citation is discussed at the level of the dataset, in section 6.8. I think we should consider citation at the level of the distribution. This is another thing that depends on the decision about how distributions can vary. If they vary in substantive ways, it will be important for reproducibility to enable citation of a specific distribution.

**Comment by makxdekkers** [comment]
The issue of in what way distributions can be different is discussed in https://github.com/w3c/dxwg/issues/411. I think we need to resolve that issue once and for all.
But apart from that, I think that should be no restrictions to what can be cited, so the object of a citation could be distribution.

**Comment by agbeltran** [comment]
Related to what we provided for dataset citation: https://github.com/w3c/dxwg/issues/61

**Comment by dr-shorthair** [comment]
Discussion in Sprint meeting was that 
- the lack of domain constraints on properties needed for citation (e.g. `dct:creator`, `dct:publisher` etc) means that they could be used on a `dcat:Distribution` if required
- we are reluctant to copy more of the properties associated with a `dcat:Dataset`  down to the `dcat:Distribution` class, as it muddies the model. We do want to preserve the core distinction between datasets and distributions
- we generally expect citations to be to datasets. If only a specific distribution is intended then that should be indicated with additional narrative alongside the formal citation 

The consensus was not to change the model for `dcat:Distribution`.

**Comment by dr-shorthair** [comment]
https://www.w3.org/2019/02/05-dxwgdcat-minutes.html
