### ISSUE TITLE
accessService property of a Distribution

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#434]
I find it confusing that we define a property of a Distribution to point to a thing called an accessService, which is a DataDistributionService. A DataDistributionService is a service that serves data through an API, no? But a Distribution is now defined not to include APIs, so why does it have an accessService property?

**Comment by dr-shorthair** [comment]
A 'Distribution' describes a file representation or serialization of a Dataset. 
It is available directly from the dcat:downloadURL
It is available from a service endpoint at dcat:accessURL
It is available through a service described in a DCAT catalogue as indicated by dcat:accessService.. 

This is related to the introduction of services to DCAT raised primarily in #172, #180, #181 
There was detailed discussion in May when it was resolved.

**Comment by agreiner** [comment]
I think my confusion is coming from the Note where we say "Under the revised scope, instances of type dcat:Distribution SHOULD be limited to representations of datasets which might be transported as files, and SHOULD NOT be used for data services such as APIs or feeds." Is it the case that a distribution is meant to still be *available* via an API or feed? If so, the fix is relatively easy.  "Data services including APIs and feeds SHOULD be described using instances of type dcat:DataService or dcat:DataDistributionService, which in turn serve dcat:Distributions."

**Comment by agreiner** [comment]
Sorry to bring up an old issue, but it was only resolved in the DCAT subgroup. It's only now that the plenary is being asked to look at the document "with fresh eyes."

**Comment by agreiner** [comment]
Probably that should say "which in turn *may* serve dcat:Distributions

**Comment by dr-shorthair** [comment]
PR #440 has 

Under the revised scope, instances of type dcat:Distribution SHOULD be limited to representations of datasets which might be transported as files, and SHOULD NOT be used for data services such as APIs or feeds. Data services including APIs and feeds SHOULD be described using instances of type dcat:DataService whose sub-class dcat:DataDistributionService MAY serve dcat:Distributions.

**Comment by davebrowning** [comment]
@agreiner - so we can close this now?

**Comment by agreiner** [comment]
yes, I think so.
