### ISSUE TITLE
In Figure 1, dcat:Resource is missing dcat:theme

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#437]
In the [Vocabulary Overview section](https://w3c.github.io/dxwg/dcat/#vocabulary-overview), the dcat:Resource representation in Figure 1 is missing the [dcat:theme](https://w3c.github.io/dxwg/dcat/#Property:resource_theme) property.

**Comment by dr-shorthair** [comment]
I think it is there - showing as a directed association, rather than an attribute. 
This follows what was done in DCAT 2014, and allows the onward association to a skos:ConceptScheme which is known to the Catalog to be indicated.

**Comment by agbeltran** [comment]
you're right! closing...
