### ISSUE TITLE
Determine how to reference ResourceRole vocab

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#452]
Alongside the Profiles Ontology a vocabulary of ResourceRole instances has been made (see [the RDF file](https://github.com/w3c/dxwg/blob/gh-pages/profilesont/resource_roles.ttl) however the way this is referenced from the Profiles Ont doc has not yet been determined.

**Comment by nicholascar** [comment]
There is now a reference to the vocab in the Concaptual Model section and also the Usage Note of the Resource Role class, see 
https://github.com/w3c/dxwg/commit/3937331868b392ada169fd5b5a18c518daae84ef

**Comment by nicholascar** [comment]
Issue about overall use of a Roles vocab taking place in other Issues so no need for that to be raised here.

**Comment by nicholascar** [comment]
Listed for Plenary 2019-08-20 so closing now after 1 week + no comment.

**Comment by kcoyle** [comment]
We didn't get around to looking at those at the plenary as we had lots else to do. Let's try to get a short list of high impact issues and discuss them at the plenary.

**Comment by nicholascar** [comment]
#1049 PROF roles and their definitions is now open and that focusses on a discussion of the roles. That Issues is now live so this one, which is just about references the document, can be closed.
