### ISSUE TITLE
vocabulary specification of VoiD is dead

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dxwg#454]
Dear, 

a topic to be considered: the namespace domain http://rdfs.org/ns/void for the vocabulary https://www.w3.org/TR/void/ is down (404). Hence referencing this vocabulary creates a dead-link in the specification. It seems that the hosting organisation has removed the vocabulary.

I quickly scanned the text, it only refers to VoiD as to the w3c document. So an immediate impact on the specification it would not have. But I have not checked if there are side impacts (like recommendations of use).

kr,

Bert

---

**Comment by makxdekkers** [comment]
I have no problem accessing http://rdfs.org/ns/void#. It redirects to http://vocab.deri.ie/void.

**Comment by agbeltran** [comment]
It wasn't working earlier but it seems to have been fixed, possibly thanks to @philarcher's tweet (https://twitter.com/philarcher1/status/1049254726024552448)
thanks for pointing this out @bertvannuffelen - closing issue now

**Comment by nicholascar** [comment]
Confirming it is indeed fixed. I emailed the owners of the system at DERI but it seems a few people did as they knew all out the issue and fixed it. Closing this issue now.
