### ISSUE TITLE
Provide an example of both a profile and a resource adhereing to it

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#455]
Currently we haven't actually articulated how a resource claiming to conform to a profile indicates that cliamed conformance. Is it by simple use of `dct:conformsTo`? If so, what's the pattern of going from a resource to the Profile it conforms to then to a Resource Descriptor with some sort of Constraints Resource Role so it can be tested?

**Comment by kcoyle** [comment]
By "resource" do you mean instance data?

**Comment by nicholascar** [comment]
Yes, poorly worded of me since we have a *resource* property in use in the ontology too and it’s a general word.

So if I have a profile, described using the ont which may include Resource Descriptor instances for things like SHACL constraints, I’m now talking about an instance of the profile, like a metadata record claiming to adhere to the profile. 

I’ll make an instance of my demo profile here shortly for testing: https://github.com/CSIRO-enviro-informatics/csiro-epub-dcap

**Comment by nicholascar** [comment]
There are now multiple instances of resources conforming to profiles in the document, e.g. each of the `Resource Descriptors` in [Example 1](https://w3c.github.io/dxwg/profilesont/#example-1-a-full-example-described-using-the-profiles-vocabulary-in-rdf-turtle) and [Example 8](https://w3c.github.io/dxwg/profilesont/#example-8-adms-profile-of-dcat-according-to-prof-in-rdf-turtle) however a specific, short, example showing instance data conforming to a profile seems appropriate/required to explain conformance to profiles in isolation.

**Comment by nicholascar** [comment]
Addressed by PR #1046
