### ISSUE TITLE
Re-write intro to DCAT

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#457]
We copied the Intro text from DCAT 2014. 
It does not read much like an intro as it only mentions RDF serializations ... either the section needs s new title, or we need a better intro. At the least, need a motivation and background about dataset catalogues.

**Comment by agbeltran** [comment]
Agreed - the new intro is where we should also clarify that the initial DCAT was targetting more e-gov catalogues and that now we have expanded the scope to consider, e.g., research data catalogues.
