### ISSUE TITLE
Add 'Security and privacy' section to all the documents

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#460]
During the publication process, W3C advice to add a 'Security and privacy' section to all the documents (even if indicating that is not relevant or not covered)

See https://www.w3.org/TR/security-privacy-questionnaire/

I searched for examples and found e.g. ODRL: https://www.w3.org/TR/2018/REC-odrl-model-20180215/#privacyConsiderations

**Comment by davebrowning** [comment]
Profiles guide security and privacy discussed at #478

**Comment by andrea-perego** [comment]
This section has been included in all DXWG reports:
- DCAT: https://w3c.github.io/dxwg/dcat/#security_and_privacy
- PROF: https://w3c.github.io/dx-prof/prof/#security_and_privacy
- CONNEGP: https://w3c.github.io/dx-connegp/connegp/#security_and_privacy

@agbeltran , @davebrowning , can we close it?

**Comment by andrea-perego** [comment]
No objections raised. Closing this issue.
