### ISSUE TITLE
Conneg doc Security and Privacy

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#461]
This section needs discussion: whether to have such a section at all, if so, what's in it etc.

**Comment by agbeltran** [comment]
As per #460, the section is needed for publication, even if you indicate that there are no security and privacy considerations for the document.

**Comment by larsgsvensson** [comment]
I did a first shot at answering the questionnaire: https://www.w3.org/2017/dxwg/wiki/CnegPrivacyAndSecurityQuestionnaire. My proposal for a privacy and security section text would be
"The use of profile preference information during content negotiation adds information to that process that -- together with other information such as user agent, accept-headers, IP address etc -- can potentially be used as identifying information. Particularly, the IP address adds information about geolocation and institutional membership. Apart from that, there are no known security or privacy impacts of this feature."

**Comment by larsgsvensson** [comment]
The use of http also makes it possible to geolocate the user and identify as a member of a specific institution!

**Comment by nicholascar** [comment]
But we are not doing anything about the use of HTTP *per se* - the user's already doing that and this spec doesn't really deal with that any more or less than without this spec. The reason I mention this is that surely you don't have to recursively address all privacy issues a user might face to even get to using this spec's recommendations, only the new thing that this spec deals with. Else you would have to cater for things like using a browser (conneg by QSA), etc. too, ad infinitum.

**Comment by larsgsvensson** [comment]
No, but we're supposed to address things people should watch out for even if they are only side-effects of the use of our specification, sort of "user, beware!". The W3C team contacts were very particular on that.

**Comment by kcoyle** [comment]
Could we say that all P/S issues that are relevant to HTTP are also relevant here? without reiterating them, but giving the reader a direction to go in to follow up.

**Comment by larsgsvensson** [comment]
@kcoyle Would this be what you mean:

"The use of http to negotiate and transport implies that all privacy and security issues that are relevant for that protocol are also relevant for profile negotiation. E. g., information such as user agent, accept-headers, IP address etc.  can potentially be used as identifying information, and particularly, the IP address adds information about geolocation and institutional membership. Apart from that, there are no known security or privacy impacts of this feature."

**Comment by kcoyle** [comment]
Yes. That's even more than I would have said, but I think your proposal is better.

**Comment by larsgsvensson** [comment]
Closed in CNEG meeting 2018-11-07

**Comment by larsgsvensson** [comment]
Removed label due for closing since it's really closed...
