### ISSUE TITLE
Model implementation reporting as done in SHACL

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#467]
The [SHACL](https://www.w3.org/TR/shacl/) Recommendation contains a link to an [SHACL Test Suite and Implementation Report](https://w3c.github.io/data-shapes/data-shapes-test-suite/) that we should emulate to implementations.

**Comment by nicholascar** [comment]
Closing as being handled as part of normal admin

**Comment by aisaac** [comment]
@nicholascar fair enough but at this stage it would make sense to show how's the 'normal admin' is being handled. Are you refering to the regular W3C Process (that indeed dictates that implementation and tests are documented)?

**Comment by nicholascar** [comment]
@aisaac yes, the normal W3C processes will ensure that these links are present in the document so we don't need a GitHub issue for it and, in fact, we now have the officially-provisioned W3C repo present in the 3PWD candidate (https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html) which replaces the temporary repo I put there before.

**Comment by nicholascar** [comment]
Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.
