### ISSUE TITLE
Move DCAT examples from Overview to an Annex

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#470]
Chapter 5 has become too long, with unrelated examples. 
Needs to be stripped back to a single evolving worked example, and move the rest to a portfolio of more extended examples in an annex, or maybe a separate document or register. Applies to 5.7-5.9. Add just one new elaboration for services to chapter 5, but a simple one based on the existing (imaginary) example. 

(From DCAT telecon 2018-10-11)

**Comment by agbeltran** [comment]
PR #471 merged
