### ISSUE TITLE
rdf:property and owl:datatypeProperty, problem with poolParty import

### ISSUE THREAD

**Issue by smrgeoinfo** [w3c/dxwg#496]
I'm trying to import dcat.ttl into a poolParty project, and errors are getting thrown along the lines of 
```
Invalid data! http://www.w3.org/ns/dcat#byteSize was defined as 
http://www.w3.org/2002/07/owl#DatatypeProperty and 
http://www.w3.org/2002/07/owl#ObjectProperty. Those classes are disjoint and cannot be used 
on the same resource.
```
It appears that this is because the property is declared 
```
dcat:byteSize
  rdf:type rdf:Property ;
  rdf:type owl:DatatypeProperty ;
```
and according to [owl ref](https://www.w3.org/TR/owl-ref/) Both owl:ObjectProperty and owl:DatatypeProperty are subclasses of the RDF class rdf:Property. it looks like the rdf:Property declaration is leading to interpretation that the property is both and ObjectProperty and DatatypeProperty.   

Should the type declaration be only 'rdf:type owl:DatatypeProperty ;'?

**Comment by dr-shorthair** [comment]
Hmm. The axiomatization is not wrong, but the ` rdf:type rdf:Property ;` is unnecessary. 
I'd be comfortable removing it. 
Would it break anything that anyone knows about.?

**Comment by agbeltran** [comment]
```rdf:type rdf:Property;``` is unnecessary but it shouldn't affect either - @smrgeoinfo were you importing some other resource too?

**Comment by smrgeoinfo** [comment]
Yes, there are various other ontologies in the workspace. I removed the rdf:Property declarations and the the error went away. But then I got a new error "An internal server error occurred. If this happens again, please contact your server administrator."  Not much to go on for debugging that; I wrote to the PoolParty developers to see if they have any ideas.

**Comment by nicholascar** [comment]
@smrgeoinfo: “it looks like the rdf:Property declaration is leading to interpretation that the property is both and ObjectProperty and DatatypeProperty”

Is that’s happening it’s definitely a PoolParty error as you can’t infer *downwards* to more specialised subclasses like that. Definitely worth raising with Semantic Web Co

**Comment by larsgsvensson** [comment]
In the second note about Properties, the [OWL 1 specficiation](https://www.w3.org/TR/owl-ref/#Property) says "In OWL Full owl:ObjectProperty is equivalent to rdf:Property". Don't know if that's relevant here, though...

**Comment by davebrowning** [comment]
@smrgeoinfo - did this get resolved?  Are you happy if we close it?
