### ISSUE TITLE
DCAT-Rev profile to simulate 2014/DCAT-AP

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#499]
While the WG charter explicitly puts the production of profiles for 'narrow' domains out of scope, the possibility of creating a DCAT profile that has the effect of backward compatibility with the 2014 spec or DCAT-AP (details and precise goal tbd).  

After discussion at F2F4,  the general feeling was that it was worth keeping this idea on the list, to be re-assessed for final decision closer to the completion of CR.

**Comment by nicholascar** [comment]
We have a couple of draft Profiles Ontology representations of the DCAT, DCAT 2014, DCAT-AP & GeoDCAT & GeoDCAT-AP relations of course which will shortly be re-added back into the Profiles Ont doc now that it’s heading for FPWD. 

We, in profiling land, would love to assist with this task to fill out the profiles’ parts to make them the very best of examples.

**Comment by nicholascar** [comment]
DCAT are not doing this so there is nothing here for PROF. De-tagging for PROF

**Comment by davebrowning** [comment]
This still seems like a good idea, but there has been no time to do it for DCAT CR.  Rather than close it, suggest keeping it open, but marked as future work.

**Comment by andrea-perego** [comment]
As no work is planned in DCAT on this issue, I propose to close it.

**Comment by andrea-perego** [comment]
Noting no objections, I'm closing this issue.
