### ISSUE TITLE
Add dct:conformsTo to dcat:CatalogRecord

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#502]
This refers to #58 and discussions in the F2F

**Comment by andrea-perego** [comment]
Examples of the use of `dct:conformsTo` with `dcat:CatalogRecord` are included in DQV:

https://www.w3.org/TR/vocab-dqv/#ExpressConformanceWithStandard

**Comment by agbeltran** [comment]
This would address "Metadata conformance with a metadata standard." from https://www.w3.org/TR/dcat-ucr/#ID14

**Comment by kcoyle** [comment]
@andrea-perego Thanks, Andrea. It would be great if this could be given as an example when the work is done on examples (either in the document or in a primer) because it makes the usage very clear.

**Comment by davebrowning** [comment]
Looking at the text for this use of `dct:conformsTo` in association with `dcat:CatalogRecord` and its companion in `dcat:Resource` as well as the example @andrea-perego gave above I get a bit lost in which resource's metadata we're talking about so I'm a bit confused.  

Isn't this use about having a standard that the metadata of the dataset conforms to?  If so, why does the text in the note ([current ED](https://w3c.github.io/dxwg/dcat/#Property:record_conformsto)) say "specifies the structure of a dataset."  Would it be better to say "specifies the structure of a dataset's metadata"? What have I missed?  (And yes, I have looked at the F2F minutes, and am still confused)

**Comment by smrgeoinfo** [comment]
I suggest some edits to resolve the ambiguity in index.html in my fork of the projects, updating the language for conformsTo property on the [resource](https://smrgeoinfo.github.io/dxwg/dcat/index.html#Property:resource_conformsto), [catalogRecord](https://smrgeoinfo.github.io/dxwg/dcat/index.html#Property:record_conformsto), and [distribution](https://smrgeoinfo.github.io/dxwg/dcat/index.html#Property:distribution_conformsto). 

the revised note text reads:
NOTE
dct:Standard is defined as "A basis for comparison; a reference point against which other things can be evaluated." The target resource is not restricted to formal standards issued by bodies like ISO and W3C. In this context it is any resource that specifies one or more aspects of the [resource, catalog record, or distribution representation] content, for example schema, semantics, syntax, usage guidelines, file format, or specific serialization. The meaning of conformance is determined by provisions in the target standard.

**Comment by agbeltran** [comment]
@davebrowning this issue was about adding the conformance to a standard for ```dcat:CatalogRecord``` (as per @andrea-perego example), as we had it already for the other classes.

The problem with the note about ```dct:Standard``` seems to have been that of copying and pasting without modifications from another section (https://w3c.github.io/dxwg/dcat/#Property:distribution_conformsto) 

@smrgeoinfo thanks for that, I think that text would work- maybe we could have slightly different text according to what class the ```dct:conformsTo``` is applied to?

**Comment by smrgeoinfo** [comment]
Yes, if you look at the links in https://github.com/w3c/dxwg/issues/502#issuecomment-439137127 for   [resource](https://usgin.github.io/dxwg/dcat/index.html#Property:resource_conformsto), [catalogRecord](https://usgin.github.io/dxwg/dcat/index.html#Property:record_conformsto), and [distribution](https://usgin.github.io/dxwg/dcat/index.html#Property:distribution_conformsto) you'll see slight variations in the text.

**Comment by agbeltran** [comment]
@smrgeoinfo I was checking your comment, and it seems that your fork of the project has moved? Thanks

**Comment by agbeltran** [comment]
Changes to the text implemented in #622
