### ISSUE TITLE
Namespace for profiles ontology (and other things?)

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#503]
Pinging @nicholascar and @draggett to discuss here.

Note: suggestion that came up at lunch: /dx/

**Comment by agbeltran** [comment]
duplicate of https://github.com/w3c/dxwg/issues/398

**Comment by andrea-perego** [comment]
> duplicate of #398

Can we then close this issue?

**Comment by andrea-perego** [comment]
> > duplicate of #398
> 
> Can we then close this issue?

Noting no objections, I am closing this issue.
