### ISSUE TITLE
Support for existing QSA parameter names

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#511]
Many systems use query string argument (QSA) to control profiles of representations to be returned - even when not using this terminology. whilst much of this is ad-hoc, standard API specifications may include canonical parameter names for these concepts.  The specification proposed here is a recommendation in the absence of an alternative.  The implication however is that a canonical means to discover mappings between other APIs and the Abstract Model is required.

**Comment by nicholascar** [comment]
I don’t disagree Rob, just wanted to go end-to-end with a full Implementation using fixed terms to get all the functionally right before adding in other term flexibility.

**Comment by nicholascar** [comment]
This issue is dependent on Issue https://github.com/w3c/dxwg/issues/538

**Comment by nicholascar** [comment]
This issue is long resolved with support in the specification for alternate SQA key names. This is formally described with the *qsa-alt* profile of the specification.
