### ISSUE TITLE
Reference ARK

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#514]
This issue was created in the [Conneg by Profile document](https://w3c.github.io/dxwg/conneg-by-ap/) and is listed in it. Once consensus on addressing it is reached here in comments below, the results will be added to the document and the issue closed.

**Comment by larsgsvensson** [comment]
Proposed text for the "related work" section:
> ARK (Archival Resource Key) [ARK]( https://tools.ietf.org/id/draft-kunze-ark-15.txt) is an identifier scheme for the persistent identification of information objects. ARK identifiers can contain an optional qualifier that „that extends the base ARK in order to create a kind of service entry point into the object named by the NAA [sc. Name Assigning Authority].“ Through a qualifier, any NMA (Name Mapping Authority, service provider offering ARK resolution) can supply access to variants of that object. There set of qualifiers is open and any ARK NAA or NMA can invent its own. The ARK specification lists versions, languages and formats as examples of qualifiers (§2.5) and but a profile name could be used as a qualifier to refer to a representation of an information object conforming to that specific profile. E. g. could https://gallica.bnf.fr/ark:/12148/btv1b6930739z.edm return metadata for the object identified by ark:/12148/btv1b6930739z using the profile ‘edm’.

**Comment by larsgsvensson** [comment]
pinging @aisaac to review since he probably knows the most about how to use ARKs

**Comment by aisaac** [comment]
@larsgsvensson I'm not a big expert, in fact. But I think that what you've written is good!

**Comment by aisaac** [comment]
@larsgsvensson in fact googling around I even found a real-world example (though I'm not sure it's very persistent and one of the profiles seems access-protected)
https://twitter.com/ISTEX_Platform/status/976450730121945095
check the MODS/XML and basic XML there (and their JSON is probably not MODS anyway, so the difference is not only about syntax)

**Comment by larsgsvensson** [comment]
@aisaac Thank you and great that you found an example! I'll include the basic example in my PR even if we don't know how persistent it is.
