### ISSUE TITLE
Consider the addition of a conformanceTarget property

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#521]
Following the OGC's Modular Specification [[modspec]], consider adding a property conformanceTarget (domain: prof:Profile, range: ?) that allows for the linking of Profiles to the *sorts of thing* or *instances of the sorts of thing* that are expected to conform to it.

What might the inverse property of this be?

**Comment by kcoyle** [comment]
Nick, can you give a functional link to the OGC spec? Thanks.

**Comment by smrgeoinfo** [comment]
In answer to @kcoyle question [The Specification Model - A Standard for Modular specifications (08-131r3) ](https://portal.opengeospatial.org/files/?artifact_id=34762)

**Comment by smrgeoinfo** [comment]
An example spec using this approach:
https://docs.opengeospatial.org/is/16-008/16-008.html . 
Requirements for three standardization target types are considered:
• Logical Model
• Encoding
• Data instance.

**Comment by smrgeoinfo** [comment]
The Energistics Energy Industry Profile of ISO 19115-1:2014 (v1.1) (https://www.energistics.org/wp-content/uploads/2017/03/EIP_v1.1.pdf) Defines a URI to identify instance documents conforming to the profile in section 4.2.9 Metadata Standard:
http://w3.energistics.org/energyml/profiles/EIP/v1.1/metadataStandard_citation.xml

**Comment by dr-shorthair** [comment]
Also see this paper: [Configuration management of a system of interdependent standards](https://doi.org/10.1109/SIIT.2011.6083604) as mentioned in https://github.com/w3c/dxwg/issues/72#issuecomment-382207466

**Comment by dr-shorthair** [comment]
![figure 1](https://user-images.githubusercontent.com/608303/47889448-23b40700-de9e-11e8-9e8e-fa300ee9ca5f.png)
_Figure 1. Conceptual model of normative dependencies in ISO/TC 211 standards_

![figure 2](https://user-images.githubusercontent.com/608303/47889462-3b8b8b00-de9e-11e8-9c74-b5f3beb48286.png)
_Figure 2. Conceptual model of a modular standard (from OGC, 2009)_

**Comment by nicholascar** [comment]
It looks like we might have bypassed this Issue by 1. detailing the competency questions used in the definition of `prof:isProfileOf` and by 2. dealing with resources via roles.

For 1.:
**IF** A isProfileOf B
**AND** X conformsTo A
**THEN** X conformsTo B

For 2.:
If a profile wishes to indicate a resource that can be used to assess conformance to it, such as a SHACL file, then that could be indicated as:
```
:A 
    a profi:Profile ;
    prof:hasResource :R .

:R
    a prof:ResourceDescriptor ;
    prof:hasRole role:conformanceTest .  # an imagined role, yet to be fully defined
```

**Comment by nicholascar** [comment]
No further comment on this issue in a week and it appear to me to be bypassed (see comment above) and we are running out of time for vocabulary editions so I'm marking it "due for closing".

**Comment by rob-metalinkage** [comment]
I think we can leave this - the OGC model has a target per requirement - not per "conformanceClass" (aka Profile) - so its not a direct evidence of the usefulness of such a pattern.  I think this can be considered as a future work item, because the typology of conformance targets will require some thought and experience.

**Comment by kcoyle** [comment]
To close we need to poll the participants.

All - please upvote if you agree to leave this as a future work item.

**Comment by nicholascar** [comment]
Closing after WG notification period of due-for-closing and the vote above to leave this for Future Work. We'll review all Future Work-tagged Issues, close or open, in a final Issue search before final draft of this WG Note.
