### ISSUE TITLE
Link to the Resource Roles vocab in the Profiles Ont doc

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#536]
Currently the Resource Roles vocab is referenced in the Prof Ont doc (see last para https://w3c.github.io/dxwg/profilesont/#introduction) but no actual link is given. [PR  532](https://github.com/w3c/dxwg/pull/532) brings the Resource Roles vocab into W3C styling and updates it so now a link to that doc needs to be added.

The reason for this whole issue here is that how it is referenced needs discussion. If it is to be a NOTE, how will this impact future re-publication of it as a dynamic vocab, not a static document?

**Comment by aisaac** [comment]
At this stage just add it in the same place as the rest, please!
There's no evidence that it's better to separate them, as there's no obvious reason to judge one part is less mature than the other.
As per the point I've tried to convey in the F2F in Lyon, the ability to allow extensions of role shouldn't be an argument against providing a list of roles as a default. That list can then be extended. This is the pattern in the Web Annotation Model and Ontology, and it's a good one.

**Comment by agreiner** [comment]
I agree that the roles should go in the profiles ontology doc.

**Comment by nicholascar** [comment]
I have seen several scenarios where code lists are published within a spec "to be extended" but then never are: ISO19115 (old and new versions), IGSN models with sample type and others. People wanting to extend the lists have no go-to place close to the spec to publish extensions for others to reuse.

Here we want to initially publish a vocab independently (at least a different doc) from the ontology so that it is able to grow in place. Then it will be obvious how and where new terms can be added. 

The W3C might implement tooling for good vocab publication soon but even as a simple HTML & RDF pair of text documents this vocab will be easy enough to grow, as long as its allowed to for which it can't be in the ontology doc which will be locked down.

**Comment by kcoyle** [comment]
I'm going to agree with @aisaac - a list of clearly obvious roles should at least be included in the document. For the FPWD the current roles could be listed and that would elicit feedback. Anything that is not in the document is less likely to be seen and commented on. That they are in the FPWD document does not determine where they could be in future versions.

**Comment by aisaac** [comment]
@nicholascar I would add that creating a place for people to put extensions can be done besides adding a set of roles in the main spec. You can still create your extension place besides the main spec, as Web Annotation have done. 
One may argue that 'seeding' the roles could help, but whatever you do, there will always be a difference of status between the 'first, DXWG born' roles and the others. And that will also make it awkward to handle extensions with such an approach.

In any case like @kcoyle  I am not 100% against having roles outside of the main spec in the end. It's just that for the moment (1) it is much simpler to have them in (2) we have not seen the W3C-supported extension mechanism yet and frankly I wouldn't put a dollar on it until I've seen some concrete plans.

**Comment by nicholascar** [comment]
A compromise might be to both list instances of Resource Roles in the Resource Role definition and examples using real Resource Role instances in the ontology. This way, real Roles are present in the ontology for discovery and use, along with lists to the full and growing vocabulary of all Roles, but we head off "the 'first, DXWG born' roles and the others" which is, indeed, my main goal here.

The SSN Ontology give examples of Results, see https://www.w3.org/TR/vocab-ssn/#Results "The following examples illustrate how the terms related to Results can be used:", linked from there https://www.w3.org/TR/vocab-ssn/#iphone_barometer-sosa, https://www.w3.org/TR/vocab-ssn/#coil_oil_plant-sosa etc.

**Comment by kcoyle** [comment]
Looking at the SSN document, the roles are not even described. I don't know what the intention of that document is in relation to roles but I don't see it as analogous to profont, where the roles are really essential to the purpose of the ontology. I still vote for a list of initial roles in the FPWD, and we'll see how they play out for the final document. But I can't imagine that even the final document won't have a strong treatment of the roles.

**Comment by aisaac** [comment]
@nicholascar I'll need your help as I'm not familiar with SSN. It seems the results there are a whole module/extension with its own classes and properties too, isn't it?
The situation for PROF is a bit different then, as the property that relates to roles is in the core ontology, so it would be legitimate that the roles to be used with it appear in the core, if we expect (and recommend) them to be used in many (most?) Profile descriptions.
If you had a (non-normative) set of classes and properties specifically dedicated to describe roles with more details, then it could be included/refered as SOSA is in the SSN doc.

**Comment by nicholascar** [comment]
Yes, the SSN ont has such an extension. The Reference to the SOSA document wasn't to suggest that Roles might be a module within PROF - just a vocab -  but the reference was just to show another W3C document referring to non-normative individuals in examples.

> it would be legitimate that the roles to be used with it appear in the core

It would indeed be legitimate but is it preferable? I think not, given the static nature (after completion) of the ontology but the dynamic nature of an extensible roles list.

> If you had a (non-normative) set of classes 

Indeed. You would see that a `Resource Descriptor` should indicate a `Resource Role`, and that's normative, but then the specific `Resource Role` individual chose for an instance could be one of any in a non-normative vocabulary.

I don't anticipate "a (non-normative) set of classes and properties specifically dedicated to describe roles with more details" really, just a listing of individual Roles (with SKOS properties such as prefLabel etc.) but it's just a vocab, not an ontology module.

**Comment by aisaac** [comment]
OK so if there's not a full module this also means that the price to include some roles in the nromative part is very small. I really, really don't see the point of making everyone's life (especially the one of the reader of the spec) more complex at this stage. Again:
- we don't have any idea that there will be a W3C registry for real
- even if there are roles in the normative set they can still be extended
- we can revisit the simpler option at a later stage

**Comment by nicholascar** [comment]
This Issue's initial issue - linking to the vocab - is complete and the final point raised here is discussion about the existence of the Roles vocab overall. This latter point is also contained in Issue https://github.com/w3c/dxwg/issues/535 so I recommend shutting this Issue to contain discussion about the exitence of the Roles vocab in Isseu https://github.com/w3c/dxwg/issues/535 only.

**Comment by andrea-perego** [comment]
I wonder whether part of the discussion was about allowing people to add new roles in the future under the same `role:` namespace. If this is the case, I don't think this is actually a requirement and we shouldn't not go that way. New roles to be used in PROF can also be added under other / new namespaces.

**Comment by aisaac** [comment]
+1 for @nicholascar on closing this issue, but only after @andrea-perego has put his comment at #535 ;-)

**Comment by andrea-perego** [comment]
@aisaac wrote:

> +1 for @nicholascar on closing this issue, but only after @andrea-perego has put his comment at #535 ;-)

Done! https://github.com/w3c/dxwg/issues/535#issuecomment-458738549
