### ISSUE TITLE
Distribution package [RDIP]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#54]
<section class='requirement' id='RDIP'><h3>Distribution package [<a href='https://www.w3.org/TR/dcat-ucr#RDIP' target='_blank'>RDIP</a>]</h3><p>Define way to specify content of packaged files in a Distribution. For example, a set of files may be organised in an archive format and then compressed, but dct:hasFormat property only indicates the encoding type of the outer layer of packaging.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID1' target='_blank'>DCAT packaged distributions [ID1]</a> </section>

**Comment by makxdekkers** [comment]
There is an RFC (6839, Additional Media Type Structured Syntax Suffixes, https://www.rfc-editor.org/rfc/rfc6839.txt) that defines the '+zip' suffix that can be appended to any IANA defined media type. This takes care of a common way of packaging distribution files, although it is not a full solution to the issue raised.
A more general solution (but still only covering one level of embedding) is the one adopted by ADMS (https://www.w3.org/TR/vocab-adms/). ADMS contains a property representationTechnique (https://www.w3.org/TR/vocab-adms/#adms-representationtechnique) that points to "_More information about the format in which an Asset Distribution is released. This is different from the file format as, for example, a ZIP file (file format) could contain an XML schema (representation technique)_."

**Comment by kcoyle** [comment]
Incorporated into DCAT WD.
