### ISSUE TITLE
References in profile negotiation document

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#540]
The references to the profile guidance document and the profiles description ontology say "Editors' Draft" but point to TR URLs that don't exist yet. 

https://w3c.github.io/dxwg/conneg-by-ap/#bib-prof-guide

**Comment by agbeltran** [comment]
This includes the link to 
https://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema/ (giving a 404), which it should be:
http://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema.txt

**Comment by nicholascar** [comment]
Should actually be https://profilenegotiation.github.io/I-D-Accept--Schema/I-D-accept-schema (no trailing slash)

**Comment by larsgsvensson** [comment]
@agbeltran does https://raw.githack.com/w3c/dxwg/larsgsvensson-editors-list/conneg-by-ap/index.html look OK to you?

**Comment by agbeltran** [comment]
thanks @larsgsvensson - yes, I think all the references are ok in that branch

**Comment by larsgsvensson** [comment]
OK, thanks. Then we just wait for @nicholascar or @rob-metalinkage to merge that branch.
