### ISSUE TITLE
Clarify abstract list operations can be realized in a single API 

### ISSUE THREAD

**Issue by azaroth42** [w3c/dxwg#548]
(conneg)

The two abstract operations for listing could be implemented in a realization using a single call, e.g. 
```
{
  "http://example.org/profile/1": "1",
  "http://example.org/profile/2"; "2"
}
```
As a response includes the list of URIs _and_ the short token to use for it.
If this is an acceptable realization, this should be clarified in section 5.

This is covered a little bit by:
> The list profiles request MAY be an independent request or part of another realisation's request.

But this text is not repeated for list profiles tokens. Propose to abstract the text and move it to the introduction of section 5.

**Comment by nicholascar** [comment]
Yes, I think we may be able to tidy things up, as you say, with fewer operations. Certainly a QSA Realisation - or any realisation able to respond with complex data structures like JSON - might only need one function for the current two. 

My worry is for HTTP where a Profiles listing in a link header may not have the expressive power to list URIs & tokens and, within HTTP, there's no need anyway as the tokens are not used.

**Comment by rob-metalinkage** [comment]
This is moot now a mechanism for HTTP has been agreed and implemented in PR-1031

**Comment by larsgsvensson** [comment]
@rob-metalinkage scripsit:
> This is moot now a mechanism for HTTP has been agreed and implemented in PR-1031

should that be pulls #1063, #1066 and #1067?

**Comment by nicholascar** [comment]
Closing after a period of due-for-closing and no further actions. wontfix label means this will be findable for post Conneg follow ups, if needed.
