### ISSUE TITLE
Harmonise Ont/Conneg references and content

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#551]
The last part of the [motivation section of the prof-ont document](https://w3c.github.io/dxwg/profilesont/#motivation) refers to machine interpretation of profiles and how the ontology could help in conneg with fallback options (e.g. retrieving a more generic version of a requested resource, which the server could not deliver, based on a profile link). Then, a note points to the prof-conneg document. However, the prof-conneg document doesn't include these fallback options based on the ontology yet.

**Comment by agbeltran** [comment]
This issue is the one that I submitted in a [message](https://lists.w3.org/Archives/Public/public-dxwg-wg/2018Nov/0300.html) to the mailing list. This PR https://github.com/w3c/dxwg/pull/554 adds a link to this issue in the prof-ont document.

**Comment by nicholascar** [comment]
Closing since there is current (3PWD) alignment happening in both documents and the PR is merged

**Comment by kcoyle** [comment]
Need consensus that this change solves the issue.

**Comment by aisaac** [comment]
@nicholascar what would be needed to close this issue is a reference to the Conneg draft where the reference to PROF is made.

**Comment by nicholascar** [comment]
The [current Conneg ED](https://w3c.github.io/dxwg/conneg-by-ap/)'s [Overview of DXWG documents on profiles](https://w3c.github.io/dxwg/conneg-by-ap/#FamilyOfDocs) section lists all W3C & IETF Profile docs in this series. The IDs of the profile documents there are used in each other's documents for referencing.

Closing after listing in plenary [2019-09-03](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.09.03) + 3-day wait period.
