### ISSUE TITLE
Conformance section of conneg-by-ap is not compliant with ReSpec

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dxwg#560]
[ReSpec says](https://github.com/w3c/respec/wiki/conformance) that a section with ID "conformance" will automatically add everything about normative language.
```
<section id="conformance">
  <!-- boilerplate will be added here -->
  <p>The specification specific conformance text…</p>
</section>
```
This text is currently hard-coded in §1.2

**Comment by nicholascar** [comment]
Issue addressed for both Profile and Conneg doc in the same commit: https://github.com/w3c/dxwg/commit/410bd1f5d5bfdc9431eb50db2234550ee591c116

**Comment by larsgsvensson** [comment]
Looking at the conneg document, I think that https://github.com/w3c/dxwg/commit/410bd1f5d5bfdc9431eb50db2234550ee591c116 didn't solve this issue since we now have both a compliance _and_ a conformance section with much duplicate text... I'll make a new PR.
