### ISSUE TITLE
Jaroslav's conneg doc edits

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#569]
From: https://lists.w3.org/Archives/Public/public-dxwg-wg/2018Nov/0400.html

> "When a non-existent or unsupported profile is requested, a server returns default content"

1. clarify what is meant here:
    - non-existent: profile identifier not understood by server?
    - unsupported: generally well known profile applicable to variety of contents that happens to not be supported by given server?
        - this may imply there will be registry of profiles, like IANA offers for Media Types. But this is excluded later on:
        "There is no proposal yet to create a central register of profiles as this is thought by the authors to be un-sustainable
        in the long-term, given the likely numbers of profiles to be established."  
        
2. section 2, definitions
    "profile", is ambiguous, "constraints on one or more identified base specifications",
    i.e. profiles constraint specifications or do they in fact reuse and "specialise clauses 
    from one or more base specifications" in order  to express constraints on content?

    "token", a short name identifying something (profile) --> better "alias"?

3. section 5.1 Context
    "In some cases, a server may have to make a request of a client and receive a response."
    - which are these cases, is this relevant to mention while unclear?

    "These aspects are to be treated independently so content negotiation for a resource involving
    negotiation by profile and potentially multiple other aspects of a resource will not affect each other."

    - this is not the case, Media Type and Profile may and will inter-depend, only one set of Media types
    may be available for a particular profile, another set for a different profile. All these content
    constraints interact and are not independent of each other. 

4. section 5.2. Requests and Responses
    - is there a reason why invoking "list profiles" can't deliver information of "list profiles tokens", making it obsolete?
    - response to "get resource by profile" should indicate the profile applied (the requested or the default one)

5. section 6.1.1.2 Using a HTTP Link header field
    - Example 2, Using a Link-header to point list available profiles
    - the "Content-Location" does not seem to be used in accordance to HTTP spec, since referring to profile and not to a particular resource representation
        - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.14
    - same holds for link relation, since performing a head on a resource (and not a profile) should not it read:
        - &lt;link rel="profile" .. >?

6. section 6.2.1 list profiles
    - I would not suggest reusing the same query parameter for identifying individual profiles (_profile=URI) *and* requesting a list of them (_profile=list)
    - a dedicated parameter may by used (_list), e.g. allowing for listing of profile (_list=profile) or media type (_list=media-type)

7. section A.1 Requirements
    - is there a reason of stating CONNEG requirements separate from other (profile-related) requirements outside of the UCR document?

(update comment: changed a &lt; to &amp;lt;)

**Comment by larsgsvensson** [comment]
@jpullmann scripsit:
>  section 6.1.1.2 Using a HTTP Link header field
>
> *  Example 2, Using a Link-header to point list available profiles
>     *   the "Content-Location" does not seem to be used in accordance to HTTP spec, since referring to profile and not to a particular resource representation
        https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.14

Hmm, don't quite understand this: `http://example.org/a/resource.prof1.ttl` is a representation URI (or URL). The profile URIs are `urn:example:profile:1` and `urn:example:profile:2`.

And as an aside: Please don't quote RFC 2616 but RFC 7230-7234. RFC 2616 is obsolete...

**Comment by larsgsvensson** [comment]
@jpullmann scripsit:
>* section 6.1.1.2 Using a HTTP Link header field
>     * same holds for link relation, since performing a head on a resource (and not a profile) should not it read:
        <link rel="profile" .. >?

It could make sense to add that too, since it would link the current resource (the representation specified in the `Content-Location` header, `Context IRI` in RFC 5988 lingo) to the profile. In this example I've chosen to use the same pattern for all representations of the generic resource. This is done by enumerating all existing representations of the resource as `Target IRI`s and their attributes `type` and `profile`. The linking from the `Target IRI` to the `Context IRI` is done through the `rel` attribute. When the `Target IRI` and the `Context IRI` are the same representation, the relation is `rel="self"`, in all other cases it's `rel="alternate"`. Does that clarify how the example is meant?

**Comment by nicholascar** [comment]
These changes in Commit https://github.com/w3c/dxwg/commit/ddcdfafc0f3937ee9b7f05d3f8dbb89dcb1f9c8e:

1. I have changed "When a non-existent or unsupported profile is requested, a server returns default content" to "When no profile or an unsupported profile is requested, a server returns default content, that is, content conforming to the default profile supported by the server.". I think this is clearer.

2. **"profile", is ambiguous**. We can't directly address the definition here as this document is tied to the Profiles Guidance document and the definition is shared. Rest assured that the definition will be able to be revisited in that document (for it's FPWD) and that any changes there will flow to this document.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**token --> better "alias"?** We've used the word "token" as the range class is an xsd:token literal in the Profiles Ontology. I think also, that alias means something more along the lines of an identifier that is equivalent in nature to another where as a token is not this for a URI: it can be used only in certain circumstances and elsewhere cannot be, thus it is not equivalent in nature (it doesn't resolve, the URI does, it's not universally unambiguous, the URI is).

3. **"In some cases, a server may have to make a request of a client and receive a response"**. This sentence was put in as a generic sentence as that may happen generally in conneg situations but it's been removed as its not seen relevant to profile conneg (we've not defined any actions that work that way around)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**"These aspects are to be treated independently so content negotiation for a resource involving negotiation by profile and potentially multiple other aspects of a resource will not affect each other."**

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;We are aware of these interactions but haven't mapped out things like Header precedence, how to deal with Content-Types that also contain profile information (as some JSON-LD formats do) but we are working on this! There is an Issue for the precedence challenges which will deal with interactions too: Issue https://github.com/w3c/dxwg/issues/505).

4. **"is there a reason why invoking "list profiles"** can't deliver information of "list profiles tokens", making it obsolete?" Perhaps not and we are thinking about combining these. The technical issue is whether HTTP can deliver such a dictionary of values, as opposed to a list. Even if it can though, we have to decide whether or not it's easier to have distinct functions. I have created an Issue for this: Issue https://github.com/w3c/dxwg/issues/587.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**"response to "get resource by profile"** should indicate the profile applied (the requested or the default one)". Yes, we've failed to indicate that this needs to be the case in the Abstract Model, even though it's present in the Realizations. I've created Issue https://github.com/w3c/dxwg/issues/588 for this and listed it in the doc.

5. Lars' discussed this above so I've not addressed it for now.

6. **"I would not suggest reusing the same query parameter for identifying individual profiles (_profile=URI) and requesting a list of them (_profile=list)"**. OK, thanks for the suggestion. I've created Issue https://github.com/w3c/dxwg/issues/589 for this and listed it in the doc.

7. **"is there a reason of stating CONNEG requirements separate from other (profile-related) requirements outside of the UCR document?"** We are listing Requirements here just to indicate how and if we will address them. Likely this list will be dropped from a final document. As the NOTE in that section says "at the time of the First Public Working Draft of this document, for demonstration only".
