### ISSUE TITLE
Quality-related information [RDQIF]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#57]
<section class='requirement' id='RDQIF'><h3>Quality-related information [<a href='https://www.w3.org/TR/dcat-ucr#RDQIF' target='_blank'>RDQIF</a>]</h3><p>Define a way to associate quality-related information with Datasets.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID45' target='_blank'>Annotating data quality [ID45]</a> </section>

**Comment by makxdekkers** [comment]
Include a reference to DQV (https://www.w3.org/TR/vocab-dqv/)?
The European StatDCAT-AP (https://joinup.ec.europa.eu/release/statdcat-ap-v100) specifies the use of property dqv:hasQualityAnnotation (https://www.w3.org/TR/vocab-dqv/#dqv:hasQualityAnnotation) with range dqv:QualityAnnotation (https://www.w3.org/TR/vocab-dqv/#dqv:QualityAnnotation) and usage note "_The annotation requires the provision of information about the motivation of the annotation (oa:motivation), and an explicit link to the resource being annotated (oa:hasTarget) together with either a link to a resource that contains the annotation (oa:hasBody) or text field (oa:bodyText)._"

**Comment by riccardoAlbertoni** [comment]
I have included  two proposals (Proposal 1 and Proposal 2)  in the [wiki page](https://github.com/w3c/dxwg/wiki/Quality-documentation), which are based on the DQV and we might want to discuss and refine in order to meet this requirement.

**Comment by aisaac** [comment]
I am very much in favor of trying Proposal 1. Duplicating DQV in DCAT seems quite a counter-productive effort unless there is a strong reason to do it - which I do not see!

**Comment by andrea-perego** [comment]
+1 from me as well to Proposal 1 - I don't see the need of duplicating / subclassing DQV in DCAT.

**Comment by riccardoAlbertoni** [comment]
>I am very much in favor of trying Proposal 1. Duplicating DQV in DCAT seems quite a counter-productive effort unless there is a strong reason to do it - which I do not see!

Replying to @aisaac:
Neither do I.  I was just provoking to see if others have a different view on this.

**Comment by agbeltran** [comment]
+1 to proposal 1 that reuses DQV

**Comment by dr-shorthair** [comment]
Resolved in DCAT telecon 2018-06-14 https://www.w3.org/2018/06/14-dxwgdcat-minutes.html#x06
