### ISSUE TITLE
Sentence to be fixed in PROF spec

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#579]
See last paragraph of [Section 8.2](https://w3c.github.io/dxwg/profilesont/#eg-hierarchy):

> [...] **Belgium** could release a **Belgium** StatDTAC-AP that is both a profile of **DCAT-BE and DCAT-BE**.

I found it out while working on PR https://github.com/w3c/dxwg/pull/578 , but I'm unsure how to fix it.

**Comment by nicholascar** [comment]
Fixed in commit https://github.com/w3c/dxwg/commit/54c736b055a749a1370f0a91f57c1e05dd865e6a so Due for Closing.

**Comment by andrea-perego** [comment]
Thanks, @nicholascar , but it still needs fixing - see https://github.com/w3c/dxwg/commit/54c736b055a749a1370f0a91f57c1e05dd865e6a#commitcomment-31306654

**Comment by andrea-perego** [comment]
@nicholascar , I think https://github.com/w3c/dxwg/pull/590 closes this issue.

**Comment by nicholascar** [comment]
Closing due to actioning of Pull https://github.com/w3c/dxwg/pull/590
