### ISSUE TITLE
Dataset access [RDSA]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#59]
<section class='requirement' id='RDSA'><h3>Dataset access [<a href='https://www.w3.org/TR/dcat-ucr#RDSA' target='_blank'>RDSA</a>]</h3><p>Provide a way to specify access restrictions for both a dataset and a distribution.</p><p>Provide a way to define the meaning of the access restrictions for a dataset or distribution and to specify what is required to access a dataset and distribution.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID17' target='_blank'>Data access restrictions [ID17]</a> </section>

**Comment by makxdekkers** [comment]
The European DCAT-AP (https://joinup.ec.europa.eu/release/dcat-ap-v11) specifies dct:accessRights (http://dublincore.org/documents/dcmi-terms/#terms-accessRights) for Dataset with a controlled vocabulary Access right (http://publications.europa.eu/mdr/authority/access-right/). 
This property could be added to DCAT for both Dataset and Distribution.
I don't think DXWG should go into defining the meaning of access restrictions. That should be left to application profiles.
