### ISSUE TITLE
Explore whether list_profiles operation could be provided by an external component

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#602]
Many existing systems that support use of alternative information profiles do not provide an explicit list. However, external catalogues or other sources of metadata may provide this list, and the server may perform negotiation over a specific request. 

Feedback is sought on whether this should be deemed mandatory.

**Comment by nicholascar** [comment]
Do you mean mandatory for servers that serve resources for which profiles are listed to represent that listing if requested, perhaps by handoff?

client: give me the list of profiles supported for resource_x
server: see catalogue listing for resource _x

Which catalogue profile list formalisations should we support? Would it be that a catalogue uses Profiles Ontology to describe resource_x conforming to profile_a, profile_b, profile_c and a server can/must understand that metadata? If so, we need to extend PROF to show how resources can be indicated to be conformant to profiles (could be as simple as `ex1:resource_x dct:conformsTo ex2:profile_y` however there's that discussion about the range value of dct:conformsTo at https://github.com/w3c/dxwg/issues/273#issuecomment-440093417 and beyond).

**Comment by rob-metalinkage** [comment]
that would be one redirect case - the other is whether the returned resource is responsible for listing all the profiles it supports - and what happens if a redirect occurs - how does the ultimate resource even know what profile was asked for? (may need statements about headers being preserved in redirects)

**Comment by nicholascar** [comment]
Long due for closing since content addressing this is present in spec.
