### ISSUE TITLE
Dataset publications [RDSP]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#63]
<section class='requirement' id='RDSP'><h3>Dataset publications [<a href='https://www.w3.org/TR/dcat-ucr#RDSP' target='_blank'>RDSP</a>]</h3><p>Provide a way to link publications about a dataset to the dataset.</p><br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RPFL' target='_blank'>Profiles listing [RPFL]</a> <a href='https://www.w3.org/TR/dcat-ucr#RDSAT' target='_blank'>Dataset aspects [RDSAT]</a> <a href='https://www.w3.org/TR/dcat-ucr#RDSP' target='_blank'>Dataset publications [RDSP]</a> <br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID9' target='_blank'>Common requirements for scientific data [ID9]</a> </section>

**Comment by nicholascar** [comment]
Is this an inverse of a prov:wasDerivedFrom where a Publication is wasDerivedFrom the Dataset?

PROV recommends the inverse prov:hadDerivation but doesn't declare it.

**Comment by andrea-perego** [comment]
> Is this an inverse of a prov:wasDerivedFrom where a Publication is wasDerivedFrom the Dataset?
>
> PROV recommends the inverse prov:hadDerivation but doesn't declare it.

In the JRC Data Catalogue we actually use `dct:isReferencedBy`, that [[PROV-DC](https://www.w3.org/TR/prov-dc/)] defines as a subproperty of `prov:hadDerivation`:

https://www.w3.org/TR/prov-dc/#term_isReferencedBy

**Comment by nicholascar** [comment]
Interesting. To my reading, isReferencedBy is a looser association than hadDerivation. The former indicates a only somewhat influential association (A isReferencedBy B means B knows about A but isn't wholly resulting from actions on A) whereas the latter indicated a much closer association (A hadDerivation B means B comes from A in some substantive way in which work was done on A to produce B).

If we are talking a publication that is about a dataset then the publication is a result of work on on the dataset and the relation is close, not a passing reference. I would choose hadDerivation.

**Comment by andrea-perego** [comment]
> Interesting. To my reading, isReferencedBy is a looser association than hadDerivation. The former indicates a only somewhat influential association (A isReferencedBy B means B knows about A but isn't wholly resulting from actions on A) whereas the latter indicated a much closer association (A hadDerivation B means B comes from A in some substantive way in which work was done on A to produce B).

Looking at the mappings defined in [[PROV-DC](https://www.w3.org/TR/prov-dc/)], it seems that, in the intention of the PROV WG, `prov:hadDerivation` is more generic, as it is defined as superproperty of both `dct:isReferencedBy` and `dct:hasFormat` - thus denoting different _types_ of derivation.

> If we are talking a publication that is about a dataset then the publication is a result of work on on the dataset and the relation is close, not a passing reference. I would choose hadDerivation.

This is one of the cases, but you may have a publication just referring to a dataset as related work, or documenting how the dataset has been created. Moreover, it is often the case that a publication has different types of relationship with a dataset. 

For instance, our requirement was to provide the list of publications about a given dataset - so, those "citing" a given dataset, which is one of the cases included in [the definition of `dct:isReferencedBy`](http://dublincore.org/documents/dcmi-terms/#terms-isReferencedBy):

> _A related resource that references, cites, or otherwise points to the described resource._

However, if a publication is documenting how a dataset has been created, we specify it both with `dct:isReferencedBy` and `dct:provenance`:

````turtle
a:Dataset a dcat:Dataset ;
  dct:isReferencedBy a:Publication ;
  dct:provenance a:Publication .

a:Publication a foaf:Document ;
  ...
````

**Comment by agbeltran** [comment]
When considering linking datasets and publications or other references, the [HCLS Dataset Description community profile](https://www.w3.org/TR/hcls-dataset/) recommends:
- ```dct:references``` for web pages and documents
- ```cito:citesAsAuthority``` to include publications about the dataset
- ```rdfs:seeAlso``` for other references

**Comment by agbeltran** [comment]
For [DATS](https://github.com/datatagsuite), we found the requirement to make the distinction between primary publications (one or more publications that describe how the dataset was produced) and other references or citations (publications that refer / cite or use the dataset):

https://github.com/datatagsuite/schema/blob/29134fd4aa16f7e76b6b9e20238c7b4de82b8518/dataset_schema.json#L112

For annotating these properties, we used [sdo:citation](https://schema.org/citation) in both cases,  as schema.org doesn't distinguish between primary or other publications:
https://github.com/datatagsuite/context/blob/master/sdo/dataset_sdo_context.jsonld#L29
Same for context files based on OBO ontologies, we relied on [iao:citation](http://purl.obolibrary.org/obo/IAO_0000301) in both cases:
https://github.com/datatagsuite/context/blob/1ea30cbda28c814ed3635994264d679c3af4eca9/obo/dataset_obo_context.jsonld#L18

Given the introduction of ```dcat:Resource```, this requirement should apply to any catalogued resource (including datasets and services).

**Comment by agbeltran** [comment]
@andrea-perego: 
> However, if a publication is documenting how a dataset has been created, we specify it both with `dct:isReferencedBy` and `dct:provenance`:
> 
> ```turtle
> a:Dataset a dcat:Dataset ;
>   dct:isReferencedBy a:Publication ;
>   dct:provenance a:Publication .
> 
> a:Publication a foaf:Document ;
>   ...
> ```

The range for [dct:provenance](http://dublincore.org/documents/dcmi-terms/#terms-provenance) is [dct:ProvenanceStatement](http://dublincore.org/documents/dcmi-terms/#terms-ProvenanceStatement), so could it be a ```foaf:Document```?

**Comment by riccardoAlbertoni** [comment]
@agbeltran wrote:
>When considering linking datasets and publications or other references, the HCLS Dataset Description community profile recommends:
>- dct:references for web pages and documents
>-  cito:citesAsAuthority to include publications about the dataset
>-  dfs:seeAlso for other references

I haven't found the actual axiom or explanation saying that, but I guess `dct:references` and  `dct:isReferencedBy` are one the inverse of the other, so +1 to use 

```
a:Dataset a dcat:Dataset ;
  dct:isReferencedBy a:Publication .

a:Publication a foaf:Document .
```

> The range for dct:provenace is dct:ProvenanceStatement, so could it be a foaf:Document?

I might be wrong, but I don't see much restriction about dct:ProvenanceStatement, it seems just a class, which potentially can be anything.
