### ISSUE TITLE
Specify the semantics of prof:isTransitiveProfileOf wrt prof:isProfileOf

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#644]
(This came to mind while writing the ESWC paper)
One note at https://w3c.github.io/dxwg/profilesont/#Property:isTransitiveProfileOf says

> While this ontology provides this `prof:isProfileOf` & `prof:isTransitiveProfileOf` pair of properties, it does not specify how a particular implementation of a Profile that is related to another Profile or Standard by `prof:isTransitiveProfileOf` should implement specific inferences. 

That talk about lack of inference could be confusing. As a matter of fact if PROF is to follow the SKOS pattern for `skos:broader` and `skos:broaderTransitive`, the idea is that `prof:isTransityProfileOf` should be a transitive property and it should be a super-property of `prof:isProfile`. It isn't either, at the moment.

**Comment by andrea-perego** [comment]
+1 to @aisaac . See also my more general concerns on this property in https://github.com/w3c/dxwg/issues/643#issuecomment-452643079

**Comment by rob-metalinkage** [comment]
proposed action: declare prof:isProfile as a subproperty of prof:isTransitiveProfileOf

**Comment by aisaac** [comment]
+1 to @rob-metalinkage 's proposed action. I would still push for trying to remove from the notes any occurrence of the word 'inference' that could (after a first, shallow look) contradict with the goal of applying the formal semantics given to the property (ie. applying an inference engine to infer the transitive closure of the property).

**Comment by nicholascar** [comment]
Addressed by PR https://github.com/w3c/dxwg/pull/734

**Comment by kcoyle** [comment]
@nicholascar I'm not convinced that this PR is a response to the question posed here. As I read it, the PR says: 

```
# A profile that is within a hierarchy of profiles may wish to indicate it profiles
# things "further up the chain". To do this, prof:isTransitiveProfileOf can be used
# to indicate anything the profile is related to by a series of one or more
# prof:isProfileOf properties.
```

but that's pretty vague: "things further up the chain". What does "profile" mean as a verb? Is anything a "thing" to be profiled?

Perhaps the diff doesn't show enough context and this snippet out of context isn't sufficient. 

Also, there is still at least one reference to "inference" that should be reviewed by @aisaac .

```
# Now, according to the semantics of prof:isTransitiveProfileOf, using the
# prof:isProfileOf statements above, one can infer the following additional
# statements:
```

I think it would be better to post proposed wording here for review, and not propose closing until the wording has been agreed on here. I'll remove the "due for closing" until we have agreed text.

**Comment by aisaac** [comment]
I agree with @kcoyle 's point about the interest of having the proposed changes discussed here, especially as PR #734 mixes two issues.

This said I don't think the text needs to do much, once we have agreed on the subproperty axiom. This issue is merely about specifying the semantics of the property with prof:isTransitiveProfileOf with respect to another property (prof:isProfileOf) it doesn't need to address all the possible imperfections of the latter property (which are debated at length in #507 and other places).

We really need a divide-and-conquer approach here. Which is also the motivation for my comment on #734. Solving this issue (#644) does not require solving #643 either.

**Comment by nicholascar** [comment]
The PR that was claimed to address this issue did do so - by adding axioms into the RDF document which are reflected in the HTML description. The PR also added examples, discussion of which is off-topic for this Issue, interesting though it may be.

**Comment by aisaac** [comment]
@nicholascar could you add pointers to the specific places in the editor's draft that address this? I'd be happy to review!

**Comment by nicholascar** [comment]
@aisaac see https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#Property:isTransitiveProfileOf & https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#Property:isProfileOf where the formal semantics (`prof:isProfileOf rdfs:subPropertyOf prov:isTransitiveProfileOf`) is described in HTML tables and Usage Notes.

**Comment by aisaac** [comment]
Thanks @nicholascar , I would be happy with the issue being closed. Some definitions in the current draft may be criticized (for example in #507), but one cannot deny that the text now provides semantics, and this is what I was missing.

**Comment by nicholascar** [comment]
Closing after WG notification period of due-for-closing and response above from proponent to changes made.
