### ISSUE TITLE
Entailment of schema.org [RES]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#65]
<section class='requirement' id='RES'><h3>Entailment of schema.org [<a href='https://www.w3.org/TR/dcat-ucr#RES' target='_blank'>RES</a>]</h3><p>Define schema.org equivalents for DCAT properties to support entailment of schema.org compliant profiles of DCAT records.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID40' target='_blank'>Discoverability by mainstream search engines [ID40]</a> </section>

**Comment by andrea-perego** [comment]
Some work has been carried out in the framework of SDW that can turn to be relevant here:

https://www.w3.org/2015/spatial/wiki/ISO_19115_-_DCAT_-_Schema.org_mapping

The specified mappings were based on existing work, including a mapping of DCAT-AP, GeoDCAT-AP, and StatDCAT-AP to Schema.org:

https://ec-jrc.github.io/dcat-ap-to-schema-org/

**Comment by makxdekkers** [comment]
This would be very useful for tools that could create the relevant schema.org markup for a landing page for the dataset based on the DCAT description.

**Comment by andrea-perego** [comment]
> This would be very useful for tools that could create the relevant schema.org markup for a landing page for the dataset based on the DCAT description.

The DCAT-AP to Schema.org mapping exercise I mentioned earlier in this thread includes also SPARQL queries implementing such mappings:

https://github.com/ec-jrc/dcat-ap-to-schema-org/tree/master/sparql

**Comment by dr-shorthair** [comment]
I propose adding an RDF alignment document for DCAT-schema.org to enable this discussion

**Comment by dr-shorthair** [comment]
More mappings from SDWWG and Project Open Data added in #146

**Comment by dr-shorthair** [comment]
Preliminary DCAT-schema.org alignment here: https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/schema.ttl

**Comment by dr-shorthair** [comment]
This repo https://github.com/earthcubearchitecture-project418/p418Vocabulary#dataset-diagram provides a detailed analysis of how schema.org supports describing a dataset.

**Comment by azaroth42** [comment]
Could someone explain the relevance of `profile-negotiation` here, other than as an instance of negotiating for schema.org vs dcat? :)

**Comment by dr-shorthair** [comment]
@rob-metalinkage responded on the email list: 

> Thats pretty much the basic case - both schema.org and dcat might be expressed in RDF using turtle serialisation - so its not MIME type negotation, rather "profile". 
>
> Profiles are semantically finer grained than just the schema - so covers the case of choices of both structure and content.
> 
> rob A

**Comment by larsgsvensson** [comment]
If this is only about selecting content that is packaged using schema.org, this issue is out of scope for profile-negotiation.

**Comment by davebrowning** [comment]
Isn't this addressed by this section in the ED: https://w3c.github.io/dxwg/dcat/#dcat-sdo? What more is needed in DCAT to address the requirement?
