### ISSUE TITLE
Clarify use of dct:conformsTo perhaps with additional properties

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#660]
From Irene Polikoff for the W3C SHACL CG:

> I found the use of `dct:conformsTo` in the example somewhat confusing. It seems to say that a resource with the role `role:ConformanceTest` conforms to SHACL. Is this correct? Or is the intention to say that the test is implemented in SHACL to test the conformance of something else (what is that something else? Some dataset?) to this profile. Of course, if a test is implemented in SHACL, then the test should be expected to conform to SHACL specification. However, for me, there was some cognitive overloading or dissonance here in the use of the term ‘conform’. I would prefer to see some other property.

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0001.html

**Comment by nicholascar** [comment]
This issue is now handled by #521

**Comment by kcoyle** [comment]
Please link to response sent to commenter, and ask if this satisfies the concern. A positive response should also then be linked here so we know this was resolved.

**Comment by nicholascar** [comment]
Within the [Conceptual Model](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#conceptualmodel) it now states: “Resource Descriptors must indicate the role they play (to guide, to validate etc.), the formalism they adhere to (dct:format) and any dct:Standard that they themselves conform to (dct:conformsTo).” 

Additionally: "Any rdfs:Resource MAY indicate conformance to a profile as per Example 2 by using dct:conformsTo. Individual communities MAY determine what constitutes an appropriate URI to identify a profile."

So dct:conformsTo, within the Profiles Vocabulary, is always used to indicate a resource's conformance to a dct:Standard or a prof:Profile. Within the Profile Vocabulary's own classes it is suggested for use only once, with the ResourceDescriptor class, but it is expected to be used for instance data (i.e. "outside" the Profiles Vocabulary) referring to profiles/standards characterised by the vocabulary.

A SHACL Resource that is part of a profile should indicate its conformance to SHACL by use of dct:conformsTo and it is likely that such a resource could play the role of either Constraints or Validation, as per the initial Roles vocabulary in the document in [Section 9](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#resource-roles-vocab). See the "[Initial Example](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#eg-initial-example)" in the document for this exact scenario. Note that the Role referenced, ConformanceTest has been replaced with the Validation role, as used in the "Initial Example"

These comments have been forwarded to the Issue raiser, Irene Polikoff, via the DXWG public mailing list: https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Sep/0000.html.

**Comment by nicholascar** [comment]
I've not received further comments from the issue proponent some time after contact so I'm marking this due for closing.
