### ISSUE TITLE
Simplify ontology by remove inverse and transitive properties

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#661]
From Irene Polikoff for the W3C SHACL CG:

> I also wondered why for one object property (prof:isProfileOf), inverse and transitive properties were specified, but not for others. 

> Personally, I would prefer to see no inverses and no properties intend to hold transitive inferences since the goal here is to improve interoperability. 

> If some users will publish information using the inverses, then applications using this information will need to work harder to support the inferencing. This will introduce some obstacles to adoption. Which may be OK if there is some important value to be derived from this, but the value was not clear to me. And if there is an important value, is it limited to just this specific property? Why not inverse for prof:hasRole, for example? Or transitive alternatives for other properties such as prof:isInheretedFrom?

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0001.html

**Comment by kcoyle** [comment]
+1 to leaving off inverses as they can be inferred from the direct form - unless, of course, we can prove that they are necessary for specific functionality.

**Comment by aisaac** [comment]
+1

**Comment by nicholascar** [comment]
We have removed the inverse property for `prof:isProfileOf` and the transitive properties (`prof:isTransitiveProfileOf`) have motivating use cases so they need to remain.

We believe this issue is now addressed but we have also created a new Issue to review transitivity: #1043

**Comment by kcoyle** [comment]
Was the commenter informed?

**Comment by rob-metalinkage** [comment]
Just need to inform actioned this suggestion on release of 3PWD

**Comment by aisaac** [comment]
@rob-metalinkage my friendly advice, looking at all the discussion that there is going to be about 3PWD, would be to email Irene now. Anyway, it's better to warn commenters asap, in case they would have something to say, which would have been relevant to include in whatever PWD!

**Comment by aisaac** [comment]
Another formality: now that so much time has passed I guess we should acknowledge the source of the comment (also in the answer): I guess it was https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0001.html ?

**Comment by nicholascar** [comment]
As stated above, we have motivating use cases for a transitive property ("flattening" of profile hierarchies) so `prof:isTransitiveProfileOf` remains for now, however the discussion about it continues see #643.

Currently, [next to the property in question](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#Property:isTransitiveProfileOf), we have placed a rational for including it based on SKOS' use of similar properties and illustrated potential use with an example ([Example 3](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#eg-isTransitiveProfileOf)).

These comments have been forwarded to the Issue raiser, Irene Polikoff, via the DXWG public mailing list: https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Sep/0000.html.

**Comment by nicholascar** [comment]
Closing after notice period to whole WG and any continuing discussion with proponent via the Public Comments mailing list.
