### ISSUE TITLE
Justify the use of opaque URIs for profiles

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#663]
From Gregg Kellogg via the W3C JSON-LD CG:

> There certainly is a conversation on the difference between the profile parameter, and Accept-Profile header, which looks like a good direction for you, IMHO. It would be useful to be able to content-negotiate over this; an opaque frame URL is not helpful, as it would be challenging to know what it meant if it wasn’t registered. We came down on the use of the profile parameter to specify registered profiles, that may imply specific contexts or frames to be used as part of the profile specification. Of course, the profile URI could, itself, be used to returned the context or frame.

**Comment by nicholascar** [comment]
Subgroup meeting 2019-02-14 noted that it looks like there's much difference between the JSON-LD @context section & the information you might get from a profile, potentially described using the Profiles Ontology.

**Comment by nicholascar** [comment]
This Issue depends on an answer to Issue https://github.com/w3c/dxwg/issues/662

**Comment by larsgsvensson** [comment]
#662 has now been resolved and closed. @nicholascar: is there anything left to do here?

**Comment by nicholascar** [comment]
@larsgsvensson we just need to communicate results from this and 662 to Gregg Kellogg so i’ll close after replying to all points in his email.
