### ISSUE TITLE
Is is possible to specify a void:rootResource in DCAT?

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#667]
From @nfreire in [this email from April](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Apr/0001.html):

> Dear all,
> I'm evaluating the use of DCAT for enabling automatic harveting/crawling
of linked data (LD) datasets.
> When using VoID to describe LD datasets, it is possible to indicate a
void:rootResource. This rdf resource will contain all the URIs of a
dataset that enable it to be harvested/crawled completely.
Does DCAT contain any property similar to void:rootResource? Or is this
requirement being taken in consideration for the future versions of DCAT?
> (Note: I'm working in the context of aggregation of LD cultural heritage
resources, for Europeana - http://europeana.eu )
> Thanks in advance for any feedback or advice.

This is a rather old comment, maybe it is already answered elsewhere. But I have not seen it.

I see a reference to it in at https://github.com/w3c/dxwg/issues/81#issuecomment-400977338 but I am not sure it covers the original comment fully (as issue #81 seems broader).

**Comment by riccardoAlbertoni** [comment]
This relates and perhaps duplicates issue #292

**Comment by agbeltran** [comment]
Yes, I think this could be considered a duplicate.

**Comment by agbeltran** [comment]
The [comment](https://github.com/w3c/dxwg/issues/81#issuecomment-400977338) referred to the point raised in https://github.com/w3c/dxwg/issues/292 , which we also discuss in today's [DCAT meeting](https://www.w3.org/2019/01/16-dxwgdcat-minutes.html). Closing this issue and we will use https://github.com/w3c/dxwg/issues/292 instead

**Comment by aisaac** [comment]
OK, thanks!
