### ISSUE TITLE
Comments to DCAT identifier section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#675]
A couple of comments on the current version of the [DCAT section about identifiers](https://w3c.github.io/dxwg/dcat/#Dereferenceable-identifiers):

1. The text mentions as examples of ID schemes DOIs, ELIs, and arXiv. This are all about documents, datasets, and, in general, creative works. But in the same section it is also said that IDs can apply to any entity in DCAT (see also the relevant discussion in https://github.com/w3c/dxwg/issues/67). Considering the importance of IDs also to identify "actors", I think it is worth mentioning ID schemes as ORCID, VIAF, ISNI, etc., and possibly include them in examples.

2. One of the topics addressed in that section is to use URIs for identifiers whenever available. The problem here is that the URI pattern to be used for this purpose is not always unique. E.g., for DOIs, people use `http://doi.org/`, `http://dx.doi.org/`, `https://doi.org/`. So, I wonder whether we could provide some guidance on that (e.g., the current recommendation in CrossRef and DataCite is to use the URI prefix `https://doi.org/`). In case it could turn to be useful, at JRC we drafted a mapping table for the ID schemes supported in DataCite - you can find it here: 
https://ec-jrc.github.io/datacite-to-dcat-ap/#mapping-identifiers
This table (or a revised version of it) could be included in appendix to the DCAT spec as a non-normative guidance

3. The section refers to the `info:` URI scheme in the text and examples. I wonder whether we should avoid mentioning it, as the info Namespace Registry has been closed in 2010.

**Comment by dr-shorthair** [comment]
+1 to these proposals by @andrea-perego

**Comment by riccardoAlbertoni** [comment]
My understanding is that we have addressed the issue #675- "Comments to DCAT identifier section"  with a proper PR, so I am  labelling it as "due for closing".

**Comment by andrea-perego** [comment]
Call 2019-02-20: resolved: close issue

https://www.w3.org/2019/02/20-dxwgdcat-minutes#x12
