### ISSUE TITLE
Compile DCAT-rev implementation evidence

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#680]
In order to support the case for DCAT-rev on rec-track, a detailed tabulation of evidence of implementation is needed.

**Comment by dr-shorthair** [comment]
See [wiki page on DCAT implementation evidence](https://github.com/w3c/dxwg/wiki/DCAT-implementation-evidence)

**Comment by riccardoAlbertoni** [comment]
@dr-shorthair Just a doubt, should we provide evidence also for terms that are already defined in other Vocabularies?  (Eg, prov:wasDerivedFrom)

**Comment by dr-shorthair** [comment]
I think we would like to provide evidence for their use in the context of a `dcat:Resource`

**Comment by andrea-perego** [comment]
Thanks for starting this, @dr-shorthair . I just started adding the existing DCAT-AP profiles where these terms are used.

**Comment by andrea-perego** [comment]
My apologies for having opened another issue (#767) concerning a follow-up from this one.

**Comment by andrea-perego** [comment]
For the current version of the implementation report, see PR https://github.com/w3c/dxwg/pull/1138

I think we can close this issue.
