### ISSUE TITLE
UCR: Editorial issues

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#683]
While reviewing the current version of the UCR document, I saw some editorial issues that needs to be addressed. I include here the ones I found:

1. The are still in some places the name of the person who added a comment - see, e.g., [Section 5.32](https://www.w3.org/TR/dcat-ucr/#ID32):

    > (Makx Dekkers) Specific cases of relationships that I have come across:
    >
    > - a dataset that contains multi-annual budget data (e.g. for a multi-annual programme) but also contains the data for individual years -- this could be as a spreadsheet with worksheets for each year and a sheet with the sum for the whole period
    > - two datasets that contain the same data but differ in other aspects than format, for example currency, measurement units, resolution, projection -- if we adopt an understanding that distributions of a dataset may only differ in format

    I guess this needs to be fixed

2. The cited standards and specification are sometimes cited other times directly linked to. The result is that the list of references is not comprehensive

3. All references are said to be normative - see https://w3c.github.io/dxwg/ucr/#references. Is this correct?

I've started fixing points (1) & (2), and I'll create shortly a PR with a proposed revision

**Comment by andrea-perego** [comment]
See also #700 & #701

**Comment by andrea-perego** [comment]
I partially addressed the issues listed here via PR #684 . 

I include below an update of what done so far:

- > 2 The cited standards and specification are sometimes cited other times directly linked to. The result is that the list of references is not comprehensive

  This is more or less fixed in PR #684, although I may have missed some

- Issue #701 : Fixed

- > 1 The are still in some places the name of the person who added a comment [...]

  I marked as EDITOR's NOTEs all these, plus those NOTEs that seemed more comments for the WG rather than explanations for the reader. This way they could be easily identified and reviewed, to see if any action needs to be taken

- > 3 All references are said to be normative - see https://w3c.github.io/dxwg/ucr/#references. Is this correct?

  Yet to be fixed.

- Issue #700 : Yet to be fixed

In addition to this, I made further editorial changes, all summarised in #684 

Unless there's any objection, I would propose merging PR #684 and open separate issues for points (1) and (3) above.

@w3c/dxwg-editors  , WDYT?

**Comment by aisaac** [comment]
@andrea-perego thanks a lot for the review! I agree with creating issues for (1) and (3) and keeping names with notes for the moment.

**Comment by jpullmann** [comment]
@andrea-perego thanks for a careful review!
1) this is true, these sentences tend to differ from the rest of the UC, so it appears fine to leave the commenter's name here (the "ednote" annotation helps to locate)
2) thanks for homogenizing the standards citation style! 
3) this is a legacy naming, will review the (in)formal ones ..

**Comment by andrea-perego** [comment]
Thanks! :)

**Comment by andrea-perego** [comment]
Just to restate also here that, about point (3), I raised the issue in ReSpec, and a fix is under-way: https://github.com/w3c/respec/issues/1754#issuecomment-458749170

After the fix is implemented, documents not having a "conformance" section will treat by default all bib refs as "informative".

**Comment by jpullmann** [comment]
@andrea-perego do you consider this issue resolved as of  https://github.com/w3c/dxwg/commit/4aa3a09b5530be4df18be3566e82754a00a2f7d7 ?

**Comment by andrea-perego** [comment]
+1 from me. But I would create separate issues concerning:
- Problem with informative/normative refs (to be checked once the revision in ReSpec will be done)
- Review all EDITOR'S NOTEs - to decide if they should be dropped / revised.

**Comment by andrea-perego** [comment]
Just to note that the fix I mentioned in https://github.com/w3c/dxwg/issues/683#issuecomment-458878824 has been commited in ReSpec - see https://github.com/w3c/respec/issues/2051

So, we can remove all `class="informative"` from the UCR document.

**Comment by andrea-perego** [comment]
As no further work is planned on the UCR document, I'm closing this issue.
