### ISSUE TITLE
Ambiguity in Abstract and Introduction

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#686]
In the Abstract (https://w3c.github.io/dxwg/profilesont/), there is a double article expression “a the usage”.

In the Introduction (https://w3c.github.io/dxwg/profilesont/#introduction), the definition of a profile is quoted twice. I suggest this be tidied up to once only. I also suggest adding a link to the data dictionary in which it is ultimately defined.

**Comment by nicholascar** [comment]
Addressed in [2PWD](https://www.w3.org/TR/dx-prof/)

**Comment by nicholascar** [comment]
@kamhayfung we've addressed this issue a long time ago and you can see the latest Editor's draft at https://w3c.github.io/dxwg/prof/. Can you please respond here so we know what you think about it being addressed?
