### ISSUE TITLE
Ambiguous relationship in Figure 1

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#687]
In 6 Figure 1 (https://w3c.github.io/dxwg/profilesont/#conceptualmodel), what is “[0]” in “is profile of [0]” – between “Base Specification” and “dct:Standard” - referring to? Please clarify.

**Comment by nicholascar** [comment]
Addressed in [2PWD](https://www.w3.org/TR/dx-prof/) with Base Specification removed

**Comment by nicholascar** [comment]
@kamhayfung please see the updated spec: https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/

**Comment by nicholascar** [comment]
@kamhayfung please now see the Editor's Draft at https://w3c.github.io/dxwg/prof/ and respond here so we know what you think of the change.

**Comment by kamhayfung** [comment]
They look much clearer in Figs 2-11 (excl 4). Nice work.

Here are some feedback:

**dct:conformsTo**
In Figure 2, "`dct:confromsTo`" should be "`dct:conformsTo`".
In Figure 11, both "`dct:conformsTo`" and "`conforms to`" appear. Do they mean the same thing?

**dct:format**
It inconsistently appears in many forms, e.g.
- "`dct:format`" (Figure 2)
- "`has format`" (Figure 3)
- "`format`" (Figure 7)

Please cross check all the diagrams and use the single form.

"`dct:hasFormat`", in Dublin Core (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-hasFormat) reads better as a complete sentence in the unidirectional relationship
`A--dct:hasFormat-->B` than `A--dct:format-->B`. 
However, "`dct:hasFormat`" seems to have a slightly different meaning.

**Redundant Legends**
It seems that Figures 12-17 still have the legends which are now available in Figure 1. They can be removed.

**Comment by kcoyle** [comment]
dct:hasFormat is deceptively named. The definition is:

>"A related resource that is substantially the same as the pre-existing described resource, but in another format."

It would be more intuitive if it was "hasAnotherFormat" and the accidental pairing of `dct:format` and `dct:hasFormat` undoubtedly leads to quite a bit of confusion. 

Since we don't have an example of how this is to be used, I can't tell if the object/value is supposed to be a URL pointing to the alternate-format file (which is what makes sense to me), or if the object is to be a format type (I don't see how that would be useful). 

In any case I am pretty sure that the prof vocabulary is correct in using dct:format only.

**Comment by nicholascar** [comment]
I have attempted to address all points raised here in https://github.com/w3c/dxwg/issues/687#issuecomment-533844506 in PR [1091](https://github.com/w3c/dxwg/pull/1091).

You will see there that the commits deal with:

1. Figs 12 - 17 legends removal
2. inconsistent `dct:conformsTo` & "conforms to" (all moved to `dct:conformsTo`)
3. inconsistent `dct:format` & "conforms to" (all moved to `dct:format`)

...and one or two other typos.

As per @kcoyle's comment above: we shouldn't be using `dct:hasFormat` anywhere.
