### ISSUE TITLE
Unused namspaces in profilescont.ttl

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#688]
In 7.1 profilescont.ttl (https://w3c.github.io/dxwg/profilesont/profilesont.ttl), several namespaces are declared but not used (xml, foaf, prov). Please consider why they are necessary and clean up as required.

**Comment by nicholascar** [comment]
Addressed in Commit https://github.com/w3c/dxwg/commit/6e2083d97cfd1a2fd71fdc78b6b73ea563fd26c7

**Comment by nicholascar** [comment]
@kamhayfung can you please confirm you are happy with this change? We need specific acknowledgement for each Issue from the proponent.

**Comment by kamhayfung** [comment]
Yes, it looks cleaner than before the change. FYI, removing unused namespaces will speed up schema validation of a document, I hope.
