### ISSUE TITLE
Visual clues in Figures 3 and 4

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#689]
Figure 3 in 8.1 (https://w3c.github.io/dxwg/profilesont/#examples), two arrow notations (property and rdf:type) are identical. Please consider using two distinguished ones. Figure 3 is also crowded for comprehension. Please expand it. Figure 4 in 8.2 has similar problems.

**Comment by nicholascar** [comment]
Both diagrams now redrawn with well differentiated arrows, colouring of classes and a reduction in clutter. Re-issued diagrams now in main document: https://w3c.github.io/dxwg/profilesont/#eg-dcat-ap & https://w3c.github.io/dxwg/profilesont/#eg-hierarchy.

**Comment by kamhayfung** [comment]
They look much better. If there are significant meanings in the colours used in the diagrams, please document them, too.

**Comment by nicholascar** [comment]
Yes, the caption for the first contains info about the colours: 

> Figure 6 Part of the DCAT-AP Profile described using this ontology. The DCAT-AP profile of DCAT is outlined in blue. The formats of the DCAT-AP Profile's Resource Descriptors are outlined in orange. The roles that those two Resource Descriptors play are outlines in red. The second Resource Descriptor conforms to SHACL, outline in purple. The artifacts (files) that DCAT-AP has, described here by the Resource Descriptors, are outlined in green. 

I've added this to Figure 7's caption:

> Figure 7 DCAT-AP and related profiles in a hierarchy. '?' shows a potential future profile instnace that profiles both DCAT-BE & StatDCAT-AP. The '?' instnace's two `is profile of` properties are highlighted in blue to draw attention to them to indicate allowed multiple use of this property.

**Comment by nicholascar** [comment]
All points addressed in PR https://github.com/w3c/dxwg/pull/804

**Comment by nicholascar** [comment]
Closing after a week's listing as "due for closing" in [Plenary 2019-08-27](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.08.27)

**Comment by aisaac** [comment]
I'm reopening as 
(1) a cheap way to flag a typo "two two" in the caption of figure 6.
(2) at the time of closing it seems that the two diagrams ([here](https://w3c.github.io/dxwg/profilesont/#eg-hierarchy) and [here](https://w3c.github.io/dxwg/profilesont/#eg-dcat-ap)) are actually different from what was in March. Especially there is no apparent color coding anymore, contrary to what is mentioned [here](https://github.com/w3c/dxwg/issues/689#issuecomment-470314224). 

On the verge of closing the issue, it seems it would have made sense to ask @nicholascar to confirm that indeed the colors have disappeared, give @kamhayfung a week to jump in if he thinks the diagram is still ok, and @nicholascar to fix the typo :-)

**Comment by kcoyle** [comment]
Note: 

1. Figure 7 has "prof class" in its key, but no elements of the diagram are coded as prof class. 
1. Ditto the XSD datatype in the key, but not the diagram. 
1. All of the relationships are labeled except the "type of" between DCAT and dct:Standard
1. The shading is pretty hard to see, but I suppose that aspect of the diagram could be beefed up for final publication. (I printed it on my laser printer and the shading is pretty faint.)

I'm also unsure why the ? for a "potential future profile" is listed there ...  the diagram should either be of real profiles or it could be purely an example, but showing a mix of real and fictional is odd. Is there something in the works based on DCAT-BE and StatDCAT-AP? If so, I'd give it a tentative name, not just a ?

**Comment by kamhayfung** [comment]
@kcoyle , regarding your note 4, I agree that symbols may turn out with different densities from different printers that the shades symbols might sometimes be indistinguishable from the hollow symbols. One way to fix is to use not shading but a different line type for drawing the symbol (e.g. dashed line in this case).

Regarding 1 & 2, since most diagrams use the same notations (i.e. element keys), I suggest that the notations could be documented once at the beginning such that they can be removed from each of the subsequent diagrams.

**Comment by nicholascar** [comment]
> One way to fix is to use not shading but a different line type for drawing the symbol (e.g. dashed line in this case).

I'll try to move to shapes, not colours.

> I suggest that the notations could be documented once at the beginning such that they can be removed from each of the subsequent diagrams.

Great suggestion, will do!

**Comment by nicholascar** [comment]
Removing "due-for-closing" until the changes I agreed to above are implemented.

**Comment by nicholascar** [comment]
* Pattern background used instead of shading.
* Diagram key moved to separate Figure.

Both changes in 3PWD candidate: https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/
