### ISSUE TITLE
URI type of a profile identifier

### ISSUE THREAD

**Issue by kamhayfung** [w3c/dxwg#690]
In 5.2 (https://w3c.github.io/dxwg/profiles/#RPFDECOS), the Note from Antoine said a profile's URI should be an HTTP. 

However, the Content Negotiation by Profile (e.g. 6.1, https://www.w3.org/TR/dx-prof-conneg/#abstractmodelcontext) merely says the profile's identifier is just a URI. 

An HTTP is an URI but the converse is not true. Please address the discrepancy above.

**Comment by aisaac** [comment]
I'm not sure whether this can be fixed very quickly. I had included this note in the document, but I'm not sure that this corresponds to an accepted requirement. At least #242 probably shouldn't be cited as the source of official requirements.

**Comment by aisaac** [comment]
So maybe we can close by saying that for the moment the view of the Conneg document should prevail, and we'll check all this against the finalized requirements a bit later?

**Comment by kamhayfung** [comment]
What a profile identifier should look like can be further debated in #242, so long as the documentation is eventually consistent. This ticket serves a friendly reminder.

**Comment by rob-metalinkage** [comment]
Profiles may be referenced using either a URI or a token. If a URI is used it is recommended that it be a HTTP URI that dereferences to a description of the profile. URNs may also be used however systems will need to provide means to describe such profiles for given URN.  In the case of a short token the server is responsible for declaring the context by which the token may be resolved into a unique profile identifier,  such as an HTTP namespace.

**Comment by larsgsvensson** [comment]
suggested edit:
>  URNs may also be used however systems will need to provide means to describe such profiles for given URN.

Other kinds or URIs, e. g. URNs may also be used ...

**Comment by kcoyle** [comment]
I think this would all be clearer if the examples were more "real" - using actual URIs not dummy ones. If you can't think of a real example for URNs then maybe they should be mentioned in the text but not shown in the example. 

(In general I think that real-ish examples explain more than dummy ones because people may see something that they recognize. There's more meaning conveyed.)

**Comment by larsgsvensson** [comment]
No, I don't have any examples of published profiles that are identified by URNs. My point is merely to highlight that we're not restricting ourselves (or the spec) to http-URIs but that _any_ URI can be used as a profile identifier. I'm definitely not pushing for an example using a [data-URI](https://tools.ietf.org/html/rfc2397) though!
