### ISSUE TITLE
DCAT Recommendation -  Security and Privacy section

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#691]
As per #460, the section is needed for publication, even if you indicate that there are no security and privacy considerations for the document

First step is to answer the questionnaire (for example https://www.w3.org/2017/dxwg/wiki/CnegPrivacyAndSecurityQuestionnaire though it should be simpler for DCAT)

**Comment by andrea-perego** [comment]
A possible privacy-related issue concerns metadata including individuals as agents (e.g., the authors/contributors of a dataset).

This is a tricky point, as not specifying an author could lead to an IPR infringement. It is probably worth pinging the [W3C DPV CG](https://www.w3.org/community/dpvcg/) (Data Privacy Vocabularies and Controls Community Group) about this issue.

**Comment by davebrowning** [comment]
As notified/discussed: https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.04.02
