### ISSUE TITLE
Create regular text to refer to other Profile docs

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#693]
As discussed in Profiles Guidance meeting 2019-01-25, we need a regular way refer from one Profile doc to another.

**Comment by larsgsvensson** [comment]
Hm, I just tried to add this to the Conneg 2PWD milestone but couldn't. Can issues only belong to one milestone? It feels a bit awkward to triplicate issues in order to have one issue for each document milestone...

**Comment by nicholascar** [comment]
Conneg & PROF now both use the same "Overview of DXWG documents on profiles" text, see:

* [Conneg](https://w3c.github.io/dxwg/conneg-by-ap/#FamilyOfDocs)
* [PROF](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#FamilyOfDocs)

**Comment by nicholascar** [comment]
Closing after a period of due-for-closing and no further actions.
