### ISSUE TITLE
Indicate  / explain dagram formalisms

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#697]
Request from @paulwalk: 

> I find the diagrams quite difficult to understand. I think I'm unclear whether the diagrams represent entity relationships or object-oriented-hierarchies. These seem to be mixed together - for example the relationships between Standard and Profile. I guess it's not necessarily invalid for these to be mixed in this way, but I find it unusual and a little confusing.

**Comment by nicholascar** [comment]
Addressed in [3PWD](https://w3c.github.io/dxwg/profilesont/) by standardising all diagrams.

**Comment by nicholascar** [comment]
@paulwalk can you please see the diagrams in the [latest ED](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/) and indicate whether you think they are improved? If so I'll mark this "due-for-closing" since standardization had occurred and now the next step - to indicate a diagram key only once - is being addressed in #689.

**Comment by paulwalk** [comment]
@nicholascar Thanks for following this up. I agree that the diagrams are improved, in the sense that I can follow them and believe that I understand what they are trying to convey in general.

Note: this is not an endorsement of the model - this comment refers to the *notation* used.

**Comment by nicholascar** [comment]
@paulwalk ok, I'll take what I can get and mark this due-for-closing on the basis of the editorial diagram issue bing improved, not anything to do with the model they represent!

**Comment by tombaker** [comment]
@nicholascar I do not see why this issue should be closed before a new diagram has been proposed, discussed, and accepted.  Are you saying that diagram formalisms are purely editorial in nature and have nothing to do with the model they represent?

**Comment by nicholascar** [comment]
@tombaker new diagrams proposed, discussed and accepted by other editors via [PR 1074](https://github.com/w3c/dxwg/pull/1074) and present in the ED. Feedback on the diagrams from outside the WG received and actioned (see #687). There is now a new [Diagram Conventions section in the ED](https://w3c.github.io/dxwg/prof/#diagramconventions) which included a diagram element key. 

This issue was notified to WG in previous plenary so I'm closing it now for any further work to be taken up in follow-on Issues.
