### ISSUE TITLE
UCR: Re-phrase description of UC26

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#700]
Ref: https://w3c.github.io/dxwg/ucr/#ID26

The UC description currently reads as follows:

> Considering DCAT a high-level model for data exchange agree on significant aspects missing so far and define extension points (typically properties) for re-use and integration of existing standards, application profiles etc. The reference listing of aspects deemed relevant is based on evaluation of DXWG use cases and [ISO-19115-1]:

@jpullmann , the first sentence sounds wrong (something missing?), and should be re-phrased. A minimal revision could be (please note also the added commas):

> Considering DCAT a high-level model for data exchange,  **it would be important to** agree on significant aspects missing so far and define extension points (typically properties) for re-use and integration of existing standards, application profiles, etc.

**Comment by jpullmann** [comment]
@andrea-perego  This sentence reads like a requirement (imperative), will update in suggested way, thanks!

**Comment by andrea-perego** [comment]
Thanks, @jpullmann !

I wonder whether we should add a milestone for the 3rd PWD of the UCR document...

**Comment by jpullmann** [comment]
resolved by commit https://github.com/w3c/dxwg/commit/4aa3a09b5530be4df18be3566e82754a00a2f7d7
