### ISSUE TITLE
Comment from Bart Hanssens

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#701]
Mail: http://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0005.html

I think Bart is referring here to the UCR document:

https://w3c.github.io/dxwg/ucr/#ID41

The link is fixed in one of the commits in PR https://github.com/w3c/dxwg/pull/684

**Comment by aisaac** [comment]
Thanks @andrea-perego !

**Comment by aisaac** [comment]
@jpullmann will you answer? Or should @andrea-perego do it after his change is merged?

**Comment by andrea-perego** [comment]
:)

**Comment by jpullmann** [comment]
broken link is repaired, Bart was notified of update
