### ISSUE TITLE
DCAT: Check normative references

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#702]
I am unsure whether all the specs listed as normative references are actually normative for DCAT. An example is [VIVO](https://w3c.github.io/dxwg/dcat/#bib-vivo-isf) and [DOAP](https://w3c.github.io/dxwg/dcat/#bib-doap). 

Checking the HTML source, I saw that they are not explicitly marked as normative (i.e., with `[[!DOAP]]`).

If these specs have been unintentionally included in the normative reference section, I wonder whether this may be caused by a change in ReSpec triggered from issue https://github.com/w3c/respec/issues/1754 (the relevant PR was merged on Oct 1, 2018).

**Comment by andrea-perego** [comment]
Just to note I raised the issue in ReSpec: https://github.com/w3c/respec/issues/1754#issuecomment-458749170

**Comment by andrea-perego** [comment]
Following today's (30 Jan 2019) discussion during the DCAT subgroup call, I tried to fix this via the following PR: https://github.com/w3c/dxwg/pull/719

Basically, I put a `?` in front of all refs not explicitly marked as normative (`!`).

@dr-shorthair , could you please review?

**Comment by dr-shorthair** [comment]
OK - so you are implicitly trying to force the issue - all refs informative by default. 
(I guess you did a regex search for all \[\[([a-zA-Z]+) and inserted a ? - that's the easy bit! )

So I will go back through and mark some 'normative' instead.

**Comment by dr-shorthair** [comment]
So I will go back through and mark some 'normative' instead.

**Comment by andrea-perego** [comment]
Please check first the result here:

https://rawgit.com/w3c/dxwg/andrea-perego-fix-to-refs/dcat/index.html#references

Some specs, as FOAF and DCTERMS, are already ending up in the "normative references" section because they are also cited in normative sections.

**Comment by dr-shorthair** [comment]
Whoops. Two remaining bugs:
1. In https://w3c.github.io/dxwg/dcat/#license-rights there is a !normative reference to DWBP in a `Note:`  paragraph. I suggest this should not be marked !normative
2. In https://w3c.github.io/dxwg/dcat/#dependencies [[VCARD-RDF]] is referred to normatively. This is not allowed as VCARD-RDF is a W3C note - i.e. a non-normative document itself.

**Comment by andrea-perego** [comment]
Just to note that the fix I mentioned in https://github.com/w3c/dxwg/issues/702#issuecomment-458749886 has been commited in ReSpec - see https://github.com/w3c/respec/issues/2051
