### ISSUE TITLE
DCAT Document - where do alignments/relations to other vocabs actually belong?

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#715]
We currently have three sections that talk about alignment/relationship  of DCAT with other vocabularies.  These are [Section 13](https://w3c.github.io/dxwg/dcat/#alignments) (non-normative), [Section 16](https://w3c.github.io/dxwg/dcat/#other-w3c-recommendations) (currently normative.... including the output from #254) and [Appendix A](https://w3c.github.io/dxwg/dcat/#alignments-domains) (non-normative). 

It would be good to have a clear and obvious rationale here - are we happy with the current structure?  Would it be better to have the non-normative alignments included in a primer or other more discursive document?

**Comment by andrea-perego** [comment]
I agree it would be better to move at least the non-normative alignment outside the DCAT spec.

**Comment by davebrowning** [comment]
This now being addressed by #865, #866 (and one or two earlier ones).

**Comment by davebrowning** [comment]
As notified/discussed: https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.04.02
