### ISSUE TITLE
Use case for "wasGeneratedBy" and for rate

### ISSUE THREAD

**Issue by pwin** [w3c/dxwg#726]
If you are submissing a new USE CASE, please use the template below. Otherwise, delete the use case template before submitting your contribution.

---
### Data Streams and Pushed Data
Status: Draft

Identifier: ID52

Creator: Peter Winstanley

Deliverable(s): DCAT 

## Stakeholders
Data Consumers, Data Publishers, Data Aggregators

## Problem statement
When delivering time-critical data the periodic polling of an API may miss the exact time of a data update.  To avoid this latency varied approaches are used including the use of a variety of protocols including ftp, rsync, STOMP, OpenWire, and also HTTP using PUT. Examples of this type of data include news data in general, and particularly sports event data.  The problem of latency requiring a "push" service occurs in many other areas too.  In order to accommodate this sort of data feed, recipients would like to be aware of features of the data feed such as the maximum rate of the data feed, the maximum unit size of the data that is provided in one bolus, in addition to other attributes necessary for connecting with this type of data services.  

## Links
Examples include:  https://www.pressassociation.com/pa-ready/  , http://www.xmlteam.com/feeds.php  and  http://datafeeds.nationalrail.co.uk/ (see also https://wiki.openraildata.com/index.php?title=Darwin:Push_Port )

## Requirements
For consumers to be able to document in their data repository that the content was generated by a specific set of push services..  For publishers to be able to alert potential recipients to the scale of the data bolus that they need to be prepared to receive, and the maximum rate at which to expect the push feed.

* Provide consumers with a means to document the source of their data coming from a push service
* Provide publishers with a means to describe the volume and maximum rate at which their data will be pushed to the recipient
* Provide  

## Related use cases
''Optional references to related local (refer to anchor identifier <nowiki>[[#Id...]]</nowiki>) and remote use cases (e.g. POE-WG UCs)''.

## Comments
''Optional section for editorial comments, suggestion and their interactive resolution''

---

**Comment by davebrowning** [comment]
These relate to issue tracker issues [173](https://www.w3.org/2017/dxwg/track/actions/173), [174 ](https://www.w3.org/2017/dxwg/track/actions/174) and will close the action [197](https://www.w3.org/2017/dxwg/track/actions/197)

**Comment by andrea-perego** [comment]
@pwin , are you interested in reviving this issue?

**Comment by andrea-perego** [comment]
Unless there are any objections, I propose we close this issue.

**Comment by andrea-perego** [comment]
> Unless there are any objections, I propose we close this issue.

No objections raised. Closing this issue.
