### ISSUE TITLE
Profile representation [RPFRP]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#75]
<section class='requirement' id='RPFRP'><h3>Profile representation [<a href='https://www.w3.org/TR/dcat-ucr#RPFRP' target='_blank'>RPFRP</a>]</h3><p>Create a way to retrieve more information about a profile. This must be flexible enough to support human and machine readable resources, such as input and editing guidance, validation resources, usage notes etc.</p><p class='note'>Following additional requirements consider the representation of a profile (document), expressing concrete constraints, compared to the definition of the concept in<a href='https://www.w3.org/TR/dcat-ucr#RPFDF' target='_blank'>#RPFDF</a></p><ol><li>Machine-readable specifications of application profiles need to be easily publishable, and optimize re-use of existing specifications.</li><li>Application profiles need a rich expression for the validation of metadata</li><li>Profiles must have properties for at least two levels of documentation: 1) short definition 2) input and editing guidance</li><li>Profiles must support declaration of vocabulary constraints</li><li>A mechanism must be available to identify conformance to each inherited profile given conformance to a profile that specialises it.</li><li>Profiles list valid vocabulary terms for a metadata usage environment</li><li>Profile vocabulary lists may be defined as closed (no other terms are allowed) or open (other terms are allowed)<a href='https://www.w3.org/TR/dcat-ucr#ID37' target='_blank'>#ID37</a></li><li>Profiles should reuse vocabulary terms defined elsewhere (Dublin Core profiles; no use case)</li><li>Profiles must be able to support information that can drive data creation functions, including brief and detailed documentation<a href='https://www.w3.org/TR/dcat-ucr#ID46' target='_blank'>#ID46</a></li><li>Profiles must support discoverability via search engines<a href='https://www.w3.org/TR/dcat-ucr#ID40' target='_blank'>#ID40</a></li><li>Profiles must have identifiers that can be used to link the DCAT description to the relevant profile</li></ol><br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RPFDF' target='_blank'>Profile definition [RPFDF]</a> <a href='https://www.w3.org/TR/dcat-ucr#RPFL' target='_blank'>Profiles listing [RPFL]</a> <br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID2' target='_blank'>Detailing and requesting additional constraints (profiles) beyond content types [ID2]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID41' target='_blank'>Vocabulary constraints [ID41]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID46' target='_blank'>Profile support for input functions [ID46]</a> </section>

**Comment by rob-metalinkage** [comment]
I have created a branch with an early attempt to model the key concerns around profiles (but not the profiling mechanisms themselves) at

https://github.com/w3c/dxwg/blob/roba-profile/dcat/rdf/profile.ttl
https://github.com/w3c/dxwg/blob/roba-profile/dcat/rdf/profile_examples.ttl

with examples from DCAT -AP, OGC service interface specification profiles and DCAT 1 as DCAT profile (#144 )

**Comment by aisaac** [comment]
F2F3: closed since handled in other requirements
