### ISSUE TITLE
Project relation [RPR]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#77]
<section class='requirement' id='RPR'><h3>Project relation [<a href='https://www.w3.org/TR/dcat-ucr#RPR' target='_blank'>RPR</a>]</h3><p>Provide a means to indicate the relation of Datasets to a project.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID49' target='_blank'>Dataset business context [ID49]</a> </section>

**Comment by dr-shorthair** [comment]
Related to #71

**Comment by dr-shorthair** [comment]
The relation should be to a generic activity (not just a project, which is a very specific kind of activity)
In which case we can make datasets a kind of Entity from the [PROV-O ontology](https://www.w3.org/TR/prov-o/), by adding 
  `dcat:Dataset rdfs:subClassOf prov:Entity .`
Then the `prov:wasGeneratedBy` predicate can be used to satisfy this requirement directly.

**Comment by dr-shorthair** [comment]
Suggest removing the following tags:
[version] [usage control] [status] [service] [profile]

**Comment by dr-shorthair** [comment]
Resolved by #312
