### ISSUE TITLE
Add dct:relation to the properties of dcat:Dataset

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#774]
The property is used in the examples for [loosely structured catalogues](https://w3c.github.io/dxwg/dcat/#bag-of-files), but not listed in the [dcat:Dataset properties](https://w3c.github.io/dxwg/dcat/#Class:Dataset).

**Comment by dr-shorthair** [comment]
It is listed as one of the properties 'inherited' from `dcat:Resource`.

**Comment by davebrowning** [comment]
And it still is..
