### ISSUE TITLE
Advisability of non-HTTP URI examples

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#775]
Some of the examples in Profile Conneg use URNs to identify profiles, for example [Example 1](https://w3c.github.io/dxwg/conneg-by-ap/#example-1-using-http-options-to-list-available-pr`ofiles) uses `urn:example:profile:1` alongside `http://example.org/profiles/2`.

Should we continue to use URNs in examples, given that Profile Guidance will indicate URIs should be used (see https://w3c.github.io/dxwg/profiles/#RPFDECOS) and that most URIs use are now HTTP URIs? (yes, an assertion but I think true)

This issue was raised due to an OGC presentation of Profile Conneg where the use of a URN in an example was seen as uncomfortable.

**Comment by makxdekkers** [comment]
@nicholascar Using URN in examples is not in conflict with the note "A profile _MUST_ have URI (or an IRI?) identifying it. The URI _SHOULD_ be an http URI". A URN is a URI, just not a http URI.

**Comment by nicholascar** [comment]
@makxdekkers yes, agreed. I suppose I’m questioning the advisability of URN examples, rather than ruling them completely incomparable. I’ll change the title to reflect this.

A legitimate answer to this issue might be that there is a continuing case for URNs and this examples using them are warranted. I never use URNs so I’d like to hear someone champion them if we are to keep using them in examples.

**Comment by nicholascar** [comment]
Duplicate of https://github.com/w3c/dxwg/issues/690
