### ISSUE TITLE
Publication source [RPS]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#78]
<section class='requirement' id='RPS'><h3>Publication source [<a href='https://www.w3.org/TR/dcat-ucr#RPS' target='_blank'>RPS</a>]</h3><p>Provide a way to cite the original metadata with a dereferenceable identifier.</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID25' target='_blank'>Publication of catalog information [ID25]</a> <br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RPC' target='_blank'>Publication control [RPC]</a> </section>

**Comment by andrea-perego** [comment]
Isn't this related to (meta)data provenance instead of usage control?

**Comment by agbeltran** [comment]
at the moment the labels are those inherited from the use cases (and ID25 was tagged with usage_control) but I agree with you @andrea-perego that this should be provenance

**Comment by makxdekkers** [comment]
The European DCAT-AP uses dct:source on Dataset referring to "_the original metadata that was used in creating metadata for the Dataset_".

**Comment by dr-shorthair** [comment]
This is metadata-about-the-metadata so should be implemented through `dcat:CatalogRecord`
Suggests perhaps that  `dcat:CatalogRecord rdfs:subClassOf prov:Entity .` ?
(see #76 and #94)

**Comment by andrea-perego** [comment]
I think here there's another aspect worth considering - I described it in a separate issue (#132).

**Comment by andrea-perego** [comment]
As there has been no further discussion on this issue, I propose to close it.

**Comment by andrea-perego** [comment]
> As there has been no further discussion on this issue, I propose to close it.

Noting no objections, I am closing this issue.
