### ISSUE TITLE
Privacy concern with profile negotiation

### ISSUE THREAD

**Issue by agreiner** [w3c/dxwg#782]
The Privacy and Security section states that "there are no known security or privacy impacts of this feature." There is one privacy issue that I think we should acknowledge. That is the fact that offering a list of acceptable profiles in the beginning of a negotiation can reveal information about the user's interests. It takes relatively few data points of that type to begin to compromise privacy. Headers facilitating server-side content negotiation could become a new method of mining data about users.

**Comment by larsgsvensson** [comment]
Hi @agreiner ,

Hmm, the [Privacy and Security section of the current ED](https://w3c.github.io/dxwg/conneg-by-ap/#security_and_privacy) does talk about the possibility that http headers disclose information about the user. Is that what you mean or which document do you refer to?

**Comment by agreiner** [comment]
This is what I see in the ED: "The use of HTTP to negotiate and transport implies that all privacy and security issues that are relevant for that protocol are also relevant for profile negotiation. E. g., information such as user agent, accept-headers, IP address etc. can potentially be used as identifying information, and particularly, the IP address adds information about geolocation and institutional membership. Apart from that, there are no known security or privacy impacts of this feature. " 
That suggests that profiles add no new privacy concerns over existing HTTP headers.

**Comment by larsgsvensson** [comment]
@agreiner OK, I see. If we change the last sentence to
> Further, offering a list of acceptable profiles in the beginning of a negotiation process can reveal information about the user's interests that could be used to add such information to a user profile.

**Comment by agreiner** [comment]
Exactly.
