### ISSUE TITLE
Determine roles and role descriptions for profile resources

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#788]
Here are the current ideas for roles.  In TTL as this is a compact form for the different parts of each definition

:aggregatedConstraints a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:broader :fullConstraints ;
    skos:definition "Full Constraints not only for this Profile but also for all dependencies (Profiles or dct:Standards)"@en ;
    skos:usageNote "Use this Role when you want to provide a resource that validates data according to this profile and also its dependents. You must include the Full Constraints of all dependencies within this resource" ;
    skos:prefLabel "Aggregated Constraints"@en .

:codeRepository a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Repository for source code and profile artifacts"@en ;
    skos:prefLabel "Code repository"@en ;
    skos:topConceptOf : .

:extensionConstraints a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:broader :partConstraints ;
    skos:definition "Constraints implemented by this Profile building on dependencies but not including them"@en ;
    skos:usageNote "Use this Role when you want to provide a resource that validates data according to this profile but only in so far as it is a constraint on its dependents. Therefore, this resource must not also include any dependents' constraints" ;
    skos:prefLabel "Extension Constraints"@en .

:fullConstraints a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Complete set of constraints for a profile"@en ;
    skos:prefLabel "Full Constraints"@en ;
    skos:topConceptOf : .

:guidance a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Guidance notes of profile"@en ;
    skos:prefLabel "Guidance"@en ;
    skos:topConceptOf : .

:partConstraints a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Partial set of constraints for a profile"@en ;
    skos:prefLabel "Part Constraints"@en ;
    skos:topConceptOf : .

:specification a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Reference document which describes the standard"@en ;
    skos:prefLabel "Specification document"@en ;
    skos:topConceptOf : .

:vocabulary a owl:NamedIndividual,
        skos:Concept,
        prof:ResourceRole ;
    skos:definition "Machine readable definition of a vocabulary or schema. Typically expressed in RDF, XSD, UML DDL, Table Schema or similar"@en ;
    skos:prefLabel "Vocabulary"@en ;
    skos:topConceptOf : .

**Comment by rob-metalinkage** [comment]
I think we should simplify and prioritise these - here is a straw man

:specification - human readable definition of the profile
:guidance 
:constraints - constraints specific to the profile
:validation - provides validation resource for the profile (implies inclusion or import of inherited constraints) 
:structure (schema?) - provides a machine readable structural description of a profile - such as a schema or shape
:mapping - provides a mapping between two specifications
  (could add :mappingTo and :mappingFrom properties to indciate both target and direction)
:vocabulary - provides definitions for terms used in the profile specification

note i think subtleties about aggregation etc can be left to extensions

**Comment by makxdekkers** [comment]
Can I again make a comment about circular definitions? Saying that 'constraints' are 'constraints' or that 'validation' 'provides validation resource' or that 'mapping' 'provides a mapping' is not really helpful for someone who does not have the right background. Also, the use of 'provides' in the definition should be avoided -- it's much better to just state what it *is* rather than what it *does*.
E.g.
'constraint': description of obligations, limitations or restrictions that apply to the profile
'validation': instructions to be used to verify conformance to the profile
'mapping': description of conversion between two specifications

**Comment by nicholascar** [comment]
https://docs.google.com/document/d/1ddygq4EcKr1DzJykdhM_WxkkmTAoU1qQWsf8xuZxcKc/edit?usp=sharing

**Comment by rob-metalinkage** [comment]
Straw man list of roles and descriptions merged into current WD. closing this issue - open new ones about specific roles as required.

**Comment by kcoyle** [comment]
Strawman list of roles is not "determine roles".

**Comment by nicholascar** [comment]
Roles now in [2PWD](https://www.w3.org/TR/dx-prof/).

**Comment by rob-metalinkage** [comment]
Roles released for feedback already - i still think further thinking is worthwhile but need to be new and concrete proposals for specific role descriptions to revisit.

**Comment by kcoyle** [comment]
@nicholascar The roles in 2pwd are not what was "determined" from the discussion. In fact, there were no agreed roles or definitions as that discussion was only just getting started and consensus was far from being reached. 

Also note that as per the [March 19 meeting](https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.03.19) github issues are to be marked "due for closing" and @pwin  and I will close them if we feel they should be closed. Please mark issues but do not close them.

(fixed typo)

**Comment by kcoyle** [comment]
@rob-metalinkage "released for feedback already" - are you refering to the editors' draft? Has there been a published draft and call for comment since these were added? It doesn't appear so from the list on the group's home page, but I worry that I may have missed something while I was away. Thanks.

**Comment by rob-metalinkage** [comment]
@kcoyle 2PWD
@pwin - the point is to close this issue as superseded and raise specific issues based on concrete proposals to improve the released 2PWD draft.  No one is saying these are perfect (and i am keen to explore improvements based on actual examples)  - but its a matter of applying common sense to closing issues when things have moved on from general to specific.  New issues can be tagged to 3PWD and dealt with by informed discussing in the sub-group.

**Comment by nicholascar** [comment]
This issue is superceded by #1049 and with discussion there, I'm closing this one.
