### ISSUE TITLE
Machine understanding of "profile"

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#796]
From Leslie Sikos

The concept “Profile” has no clear machine-interpretable definition (only a human-readable description), and software agents can interpret nothing more from the ontology file that it is a subclass of dct:Standard.

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0020.html

**Comment by rob-metalinkage** [comment]
The statement "while the PROF ontology aims at setting constraints as well." is incorrect - so the machine understanding of "profile" is probably not the issue.

The actual machine understanding aspect of the profile ontology is limited to transitive conformance in the inheritance tree and discovery of other resources by role.  IMHO This can be addressed by clarifying the competency questions.

**Comment by nicholascar** [comment]
Section added to PROF to indicate its relationships to Constraint Languages including that PROF is not setting constraints like they are: https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/index.html#related-constraintlanguages.

Examples throughout doc show profiles with Constraint Languages resources as parts of them.

**Comment by kcoyle** [comment]
Note some typos in that section: "used in profile profile definitions" and I would say "define" rather than "defined" in the first sentence. Although I must say that I'm not convinced that this section needs to be there at all. 

Here's the full comment from Sikos, and I admit to having some trouble understanding what the actual suggestions are:

>Please find my comments and suggestions to the PROF Ontology below.

>The ontology file is syntactically correct. The ontology features a DL expressivity of ALIN(D), so no complex relationships are defined for the concepts of the ontology, and therefore it almost looks like a controlled vocabulary only rather than a fully-featured ontology.

* Done - name has been changed

>The concept “Profile” has no clear machine-interpretable definition (only a human-readable description), and software agents can interpret nothing more from the ontology file that it is a subclass of dct:Standard.

* This seems to be true

>There are specific ontologies for particular resource types, so the need for defining general resource descriptors has to be justified. When referring to data exchange situations, it has to be specified what exactly can be captured as contextual information.

* I'm not sure what this means, so you may need to ask.

>Relationship with standard and de facto standard vocabularies and ontologies, such as Dublin Core, PROV-O, and SKOS, should be defined (more) clearly in the specification and formally in the ontology file itself. For example, the range of :isTransitiveProfileOf is defined to be dct:Standard—much more similar definitions would be needed.

* Inquire if the reviewer is now satisfied with the ranges in the vocabulary.

>By reading the specification, the relationship with SHACL remains somewhat unclear, and it is mentioned mainly in the context of implementations only, while the PROF ontology aims at setting constraints as well.

* The key statement here, IMO, is "the relationship with SHACL remains somewhat unclear, and it is mentioned mainly in the context of implementations only, while the PROF ontology aims at setting constraints as well." I think the response to this reviewer would be to clarify that other than providing a vocabulary for the naming of resources making up a profile, no constraints are implied.

>The namespace of PROF, https://www.w3.org/ns/dx/prof/, is a symbolic link only (gives a 404 error in the browser). The best practice is to point the namespace URI to the ontology file itself (for semantic agents), which in this case is https://www.w3.org/TR/2018/WD-dx-prof-20181218/profilesont.ttl, and to a dedicated webpage describing the ontology (for browsers), using content negotiation on the web server; and optionally dedicated webpages created for each term of the ontology with addresses concatenated in the form namespace URI + term + optional trailing slash.

* I do note that DCAT uses a hash namespace http://www.w3.org/ns/dcat#. I don't know if that is the W3C best practice.

**Comment by nicholascar** [comment]
> There are specific ontologies for particular resource types, so the need for defining general resource descriptors has to be justified. When referring to data exchange situations, it has to be specified what exactly can be captured as contextual information.

I assume when you say "ontologies for particular resource types" you mean something like the [DCMI Type Vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-7) and perhaps more details ontologies that provide taxonomies of resource types?

If so, my answer here is that: PROF doesn't provide a taxonomy of resource types only a way of associating resources to profiles (identified by URI and able to be used as conformance targets) and several properties for describing those resources, such as `dct:format` and `prof:hasRole`. One could add `dct:type` to indicate a DCMI Type Vocabulary class or any other property that can be added to a descriptor of an artefact to describe the artefact (i.e. to a `ResourceDescriptor`, not the artefact itself). You *could always, as per normal OWL/RDF* add further descriptors to an artefact! This is not excluded by PROF.

**Comment by nicholascar** [comment]
> Relationship with standard and de facto standard vocabularies and ontologies, such as Dublin Core, PROV-O, and SKOS, should be defined (more) clearly in the specification and formally in the ontology file itself. For example, the range of :isTransitiveProfileOf is defined to be dct:Standard—much more similar definitions would be needed.

This s addressed in https://github.com/w3c/dxwg/issues/797

**Comment by nicholascar** [comment]
Email sent to raiser via public comments list, awaiting response or suitable time before closing.

**Comment by nicholascar** [comment]
Closing since no comments received back from raiser in over a month after direct contact.
