### ISSUE TITLE
PROF relationship to other vocabularies

### ISSUE THREAD

**Issue by kcoyle** [w3c/dxwg#797]
From Leslie Sikos

Relationship with standard and de facto standard vocabularies and ontologies, such as Dublin Core, PROV-O, and SKOS, should be defined (more) clearly in the specification and formally in the ontology file itself. For example, the range of :isTransitiveProfileOf is defined to be dct:Standard—much more similar definitions would be needed.

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jan/0020.html

**Comment by nicholascar** [comment]
The current [Editor's Draft](https://w3c.github.io/dxwg/prof/) contains both a [Related Work section](https://w3c.github.io/dxwg/prof/#relatedwork) section detailing relations of PROF to  PROV-O and other ontologies and also an [Alignments section](https://w3c.github.io/dxwg/prof/#alignments) which contains alignments to Dublin Core, SKOS, VOAF and others.

> For example, the range of :isTransitiveProfileOf is defined to be dct:Standard—much more similar definitions would be needed.

There are now many property notes for this property and related notes and examples in the Editor's Draft](https://w3c.github.io/dxwg/prof/#Property:isTransitiveProfileOf).

**Comment by nicholascar** [comment]
Email sent to raiser via public comments list, awaiting response or suitable time before closing.

**Comment by kcoyle** [comment]
@nicholascar Until the "raiser" gives an ok it doesn't seem that this should not be 'due for closing'. Maybe we need a different tag for the case where you have acted but are waiting on a reply? Maybe even "waiting on a reply"?

**Comment by nicholascar** [comment]
Closing after no response from raiser in a month after direct contact.
