### ISSUE TITLE
Mapping of qualified and non-qualified forms [RQFM]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#80]
<section class='requirement' id='RQFM'><h3>Mapping of qualified and non-qualified forms [<a href='https://www.w3.org/TR/dcat-ucr#RQFM' target='_blank'>RQFM</a>]</h3><p>Specify mapping of qualified to non-qualified forms (lowering mapping). The reverse requires information (qualification) that might not be present/evident.</p><p class='note'>This requirement is still under review</p><br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID19' target='_blank'>Guidance on the use of qualified forms [ID19]</a> </section>

**Comment by nicholascar** [comment]
I think this is an important Req but can it be un-tagged with "provenance"? The reason is that the PROV-O style of qualification should be used for both provenance and non-provenance as a general ontology pattern, therefore this is not provenance-specific.

**Comment by riccardoAlbertoni** [comment]
I suggest to untag "quality",  this is not a quality-specific requirement, it affects the general way in which we want to model thing in dcat.  In some of the related use cases, DQV is mentioned as a source for possible modelling examples but the requirement itself is not related to quality.

**Comment by dr-shorthair** [comment]
I've attempted an axiomatization of the simple form in terms of a qualified forms in the Wiki Page here: https://github.com/w3c/dxwg/wiki/Qualified-relations#simple-relations

**Comment by dr-shorthair** [comment]
See axiomatization of some of the relations here: https://github.com/w3c/dxwg/blob/dcat-issue79-simon/dcat/rdf/dcat-prov.ttl#L63

**Comment by dr-shorthair** [comment]
Branch gone, now here https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat-prov.ttl#L63

**Comment by dr-shorthair** [comment]
Issue discussed in DCAT meeting 2019-02-07. As it is a niche concern likely to be only of interest to OWL mavens, it is low priority and will not be addressed further.

**Comment by agbeltran** [comment]
Link to minutes: https://www.w3.org/2019/02/06-dxwgdcat-minutes.html
