### ISSUE TITLE
Examples for dataset series

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#806]
#81 was closed by #651. However, I still haven't found specific guidance for my two common dataset series cases:
1. Dataset of all addresses in the Czech Republic split into datasets for individual (6000+) towns. - This is a dataset series divided by geographical region. How do I specify a single entity (dataset?) with all the information?
2. Dataset with budget information per year. Each year is a separate dataset. How do I represent the entity (dataset?) with budget for all years?

Generally, how do I represent the series?
- n+first `dcat:Dataset` with no distributions connected to the multiple datasets using `dct:hasPart`? `dct:hasPart` for some reason is only specified in `dcat:Catalog`, not `dcat:Dataset` or `dcat:Resource`. I know that there is nothing prohibiting me from using `dct:hasPart` on `dcat:Dataset` for this, but I would wish that other people/implementations understood what exactly I mean by that.
- Should I use my own `dcat:Relationship` for that?

I think this is such a common use case that it needs to be explicitly dealt with. I was hoping #81 would deal with that, but the current resolution does not provide any guidance in this matter. Or am I missing something? Could we flesh out examples covering this?

**Comment by makxdekkers** [comment]
@jakubklimek DCAT is indeed silent about how you can model those kinds of relationships. 
However, the approach you suggest, with a `dcat:Dataset` with no distributions connected to the multiple datasets using `dct:hasPart`, sounds reasonable. Even if the consumer did not understand the approach, they would still be able to find and use the individual datasets. 
Having said that, I am not sure that DCAT, as a base standard, should include a strong statement recommending this approach, as there might be other ways to do this. Some of that additional understanding could maybe be built into a profile for a particular community.

**Comment by andrea-perego** [comment]
> #81 was closed by #651. However, I still haven't found specific guidance for my two common dataset series cases:
> 
> 1. Dataset of all addresses in the Czech Republic split into datasets for individual (6000+) towns. - This is a dataset series divided by geographical region. How do I specify a single entity (dataset?) with all the information?
> 2. Dataset with budget information per year. Each year is a separate dataset. How do I represent the entity (dataset?) with budget for all years?
> 
> [...]

@jakubklimek , as mentioned in https://github.com/w3c/dxwg/issues/868#issuecomment-713485006 , we have prepared a wiki page to collect examples of dataset series:

https://github.com/w3c/dxwg/wiki/Examples-on-dataset-series

Could you please check if the examples cover your use cases, and let us know if there's something different / missing?

Also, would you mind elaborating your first use case (i.e., "Dataset of all addresses in the Czech Republic split into datasets for individual (6000+) towns")? Especially, why they are split, instead of being merged into a single dataset / distribution? This would help outline scenarios requiring the use of dataset series.

**Comment by jakubklimek** [comment]
@andrea-perego regarding addresses in the Czech Republic - they are split for practical reasons, mainly the size of the resulting distributions - the publisher is not comfortable with serving multi-GB files over HTTP.

This use case is currently covered by what is in the wiki. I.e. the addresses are covered by the spatial (individual towns).

I can see other types of series as well (and I do not have edit permissions for the wiki):
- topic/theme related series - e.g. datasets coming from a single information system, or covering one "area in common sense" - like "dataset related to finances", including "budget datasets", "spending datasets", ...
- I would change "Example 4: Another space-related dataset series" to "level of detail" series - as the difference can be both in spatial and temporal resolution. Here, what is missing for me, is the ability to specify spatial resolution using a concept scheme instead of a number of meters. E.g. I cannot specify that the resolution (in the case of addresses) is to the level of districts, towns, regions, states, etc.

**Comment by andrea-perego** [comment]
Thanks, @jakubklimek . We'll look into your proposal.

About this point:

> [...] what is missing for me, is the ability to specify spatial resolution using a concept scheme instead of a number of meters. E.g. I cannot specify that the resolution (in the case of addresses) is to the level of districts, towns, regions, states, etc.

would you mind creating a separate issue, describing your use case?

**Comment by jakubklimek** [comment]
@andrea-perego I created #1263 .

**Comment by andrea-perego** [comment]
> @andrea-perego I created #1263 .

Thanks, @jakubklimek .
