### ISSUE TITLE
Cleaning the CR from references to backlogged and open issues

### ISSUE THREAD

**Issue by riccardoAlbertoni** [w3c/dxwg#838]
I am trying to clean the document from the references to issues,  If merges must be endorsed in the plenary I think we have to make the most in term of cleaning before it.

I have prepared two branches

[dcat-deleting-issues-riccardo](https://github.com/w3c/dxwg/tree/dcat-deleting-issues-riccardo): in which I have deleted the references not anymore pertinent, namely
- ISSUE 252: Examples of quality for services, as we moved it in a future primer
- ISSUE 411: Distributions, services and implementation-resource, as it was closed

Getting rid of these two should not be much problematic. 
Please revise the related PR so that we can merge it in the next plenary.

[dcat-commenting-backlogissues-riccardo](https://github.com/w3c/dxwg/tree/dcat-commenting-backlogissues-riccardo):
In which I have commented with the string "!--backlog"  the reference to the issues that have been put in the backlog, so that they are not anymore listed in the document. Instead of mention the single issues in the backlog, I have proposed to add a sentence in the document in which we warn the reader about the backlog ( see issue #837  "Mentioning the Backlog in the DCAT CR").  However, the string   "!--backlog"  is a hook to retrieve these commented issues back in the case we want to turn them in notes instead of making them disappear from the document.
 This branch has made invisible the following issues:
- issue 105:  Use owl:Restriction constraints to bind DC properties to DCAT classes
- issue 62: Datasets vs. Catalog relation [RDSCR]
- issue 71: Project context [RPCX]
- issue 70: Publication control [RPC]
- issue 78: Publication source [RPS] 
- issue 125: dcat:byteSize - check constraints 
- issue 90: Version definition [RVSDF]

There are also a certain number of issues which are referenced in the current DCAT document but are not in the backlog nor DCAT CR. 
- issue 65: Entailment of schema.org [RES]
- issue 110 : Review global domain axioms on dcat properties 
- issue 144 : DCAT 2014 profile of DCAT
- issue 145:  Distinguish query and item access semantics [RDISA]
- issue 149 : DCAT - DATS alignment (profile)
- issue 150: DCAT - H CLS alignment
- issue 151: DCAT - ISO 19115 alignment (profile)
- issue 152: DCAT - Datacite alignment (profile)
- issue 164: DCAT - DDI alignment (profile)
What do we what to do with these? Shall we move these in the backlog? 

Further issues which haven't been included in any milestones but are labeled 'dcat" are available at [[1]](https://github.com/w3c/dxwg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Adcat+no%3Amilestone%09), should we put these in the backlog as well?

**Comment by davebrowning** [comment]
@riccardoAlbertoni - Is there still something to do here, I'm afraid I've lost track :smile:

**Comment by riccardoAlbertoni** [comment]
@davebrowning wrote:
> @riccardoAlbertoni - Is there still something to do here, I'm afraid I've lost track 😄

I am afraid You were not the only one ;)
I've just made the PR #899  with the missing parts, I think we can close this issues after we have accepted my PR.
