### ISSUE TITLE
Remove Annex B (external alignments)

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#853]
As discussed in https://www.w3.org/2019/03/27-dxwgdcat-minutes.html 
we are unable to complete or document these further with the resources available, so remove from the document and leave on the backlog (probably to be dealt with in separate documents anyway.

**Comment by davebrowning** [comment]
As notified/discussed: https://www.w3.org/2017/dxwg/wiki/Meetings:Telecon2019.04.02
