### ISSUE TITLE
Editorial issues in prof:inheritedFrom example

### ISSUE THREAD

**Issue by aisaac** [w3c/dxwg#858]
This is a spin-off from #642 

The statement `1:Standard_X a prof:Profile` may not be wrong, but it does not add anything useful to the example and thus it could be removed. Of course the comment next to it ("this may be a 'null' profile [...]") would go away as well, which as @kocyle pointed, is good for the understanding of the example.

Wrong comments: 
`# RS 2 in diagram` should refer to Resource Descriptor 2
`# RS 3 in diagram` should refer to Resource Descriptor 3

In the diagram, I guess `Profile X, Resource Descriptor 2` should be `Profile Y, Resource Descriptor 2`

@nicholascar @rob-metalinkage I believe that these changes are no-brainers and could be implemented this week if you have time.

**Comment by nicholascar** [comment]
@aisaac 

> The statement `ex1:Standard_X a prof:Profile` may not be wrong, but it does not add anything useful to the example and thus it could be removed.

I don't follow: the Resource Descriptor `ex1:RD_1` is defined by that profile (`ex1:Standard_X prof:hasResource ex1:RD_1`) and since that's the the Resource Descriptor that's the focus of the inheritance, we need to see where it comes from, i.e. not `ex2:Profile_Y` but that it's inherited.

> Of course the comment next to it ("this may be a 'null' profile [...]") would go away as well, which as @kocyle pointed, is good for the understanding of the example.

Sure, we can remove that.

> Wrong comments:
* RS 2 in diagram should refer to Resource Descriptor 2
* RS 3 in diagram should refer to Resource Descriptor 3

Correct, will fix

> In the diagram, I guess Profile X, Resource Descriptor 2 should be Profile Y, Resource Descriptor 2

Correct again!

**Comment by nicholascar** [comment]
PR https://github.com/w3c/dxwg/pull/859 addresses 3/4 of the points @aisaac raised

**Comment by aisaac** [comment]
@nicholascar the fixes are ok.

For the first point I am a bit puzzled. I see you've removed the statement that I wanted to remove. I am not suggesting we should remove ex1:Standard_X, which is indeed important to understand what is happening in terms of inheritance.

By the way I realize that the diagram (and its caption) could also replace Profile X by Standard X, so that it's aligned with the example code.

**Comment by nicholascar** [comment]
@aisaac ok, I understand you now, it was just the triple `ex1:Standard_X a prof:Profile` which, as you say isn't necessarily wrong but may be unhelpful. I read `ex1:Standard_X a prof:Profile` as a stand in for all the triples about `ex1:Standard_X`. Great.

> By the way I realize that the diagram (and its caption) could also replace Profile X by Standard X, so that it's aligned with the example code.

Ooops, thought I'd got all the references but missed the Caption. I've updated the caption with a commit against the branch in the PR now, see test rendering https://raw.githack.com/w3c/dxwg/prof-isInheritedFrom-eg-fixes/profilesont/index.html#Property:isInheritedFrom.

**Comment by aisaac** [comment]
Issue can be closed as soon as PR #859 is merged.

**Comment by nicholascar** [comment]
Closing since PR merged
