### ISSUE TITLE
DCAT: Ack section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#886]
This the current text:

>The editors gratefully acknowledge the contributions made to this document by all members of the working group.
>
> The editors also gratefully acknowledge the chairs of this Working Group: Karen Coyle, Caroline Burle and Peter Winstanley — and staff contacts Phil Archer and Dave Raggett.

I think it may be worth extending our ack's to the people outside the group (those who sent comments, members of other WG) who helped in reviewing, revising, and consolidating the spec.

It may also worth mentioning explicitly those WG members who provided important contribution to this work.

As an example, I include below pointers to ack sections from other W3C specs:
- DWBP: https://www.w3.org/TR/dwbp/#acknowledgements
- SDWBP: https://www.w3.org/TR/sdw-bp/#acknowledgments
- DQV: https://www.w3.org/TR/vocab-dqv/#acknowledgements

**Comment by riccardoAlbertoni** [comment]
@andrea-perego - I am collecting the names of people who have commented on the issues labeled "dcat", so that we can put an appropriate acknowledgment in the DCAT CR.

**Comment by andrea-perego** [comment]
Thanks, @riccardoAlbertoni . On my side, I'll start and give it a try with a PR.
