### ISSUE TITLE
CONNEG: Ack section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#888]
The current text reads as follows:

> Comments and suggestions from Annette Greiner, Erik Wilde, Gregg Kellogg and Kam Hay Fung improved this specification.

I suggest extending it - aknowledgements should include WG members, chairs and W3C team contacts.

Some examples that can be used as templates:

DWBP: https://www.w3.org/TR/dwbp/#acknowledgements
SDWBP: https://www.w3.org/TR/sdw-bp/#acknowledgments
DQV: https://www.w3.org/TR/vocab-dqv/#acknowledgements

**Comment by nicholascar** [comment]
Addressed by PR https://github.com/w3c/dxwg/pull/905
