### ISSUE TITLE
Version delta [RVSDA]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#89]
<section class='requirement' id='RVSDA'><h3>Version delta [<a href='https://www.w3.org/TR/dcat-ucr#RVSDA' target='_blank'>RVSDA</a>]</h3><p>Provide a way to indicate the change delta or other change information from the previous version.</p><br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RVSDF' target='_blank'>Version definition [RVSDF]</a> <br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID4' target='_blank'>Dataset Versioning Information [ID4]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID50' target='_blank'>Annotating changes that do not change the information content [ID50]</a> </section>

**Comment by makxdekkers** [comment]
The European DCAT-AP uses [adms:versionNotes](https://www.w3.org/TR/vocab-adms/#adms-versionnotes) for a textual "_description of the differences between this version and a previous version of the Dataset_".

**Comment by nicholascar** [comment]
What about a pointer to a Git transaction?

**Comment by davebrowning** [comment]
I quite like the idea of a Git transaction but not all new versions would naturally be picked up that way, I think.  For those that do, then perhaps we should encourage it

An example where the textual approach works better would be where a publisher has changed coverage in some way, but the rest stays the same.  [This is fairly common practice with financial data - I may have a dataset that claims to cover corporates across the EU for example but has systematic issues for the UK (for example).  When I address those issues, I may want to treat it as a new version of the original dataset rather than a new dataset as a way of signalling to users that its an important change but still an evolution of what I produced before]  This is all information domain specific, of course.

**Comment by makxdekkers** [comment]
@nicholascar Not sure I understand the idea. Are you saying that Datasets should be published on GitHub? I do not think that is common practice.
@davebrowning Your use case of versioning is interesting and should be part of a more thorough discussion on versioning. In your description, I do not entirely understand the distinction you make between a _new version of the original dataset_ and a _new dataset_. After all, both the original dataset  and the new version would be datasets (`dcat:Dataset`); the signal to the users would be expressed as links between the two datasets, further detailed by the version delta info.

**Comment by davebrowning** [comment]
@makxdekkers - yes, I agree it needs to be part of a broader/more thorough discussion on versioning (persummably under action #90 ).  I also agree that these are both examples of dct:Dataset so could use some links as you describe,  if that mechanism is available.  

What the publisher is usually trying to achieve by calling the new set of published data a new version of a pre-existing set is to signall that its a successor or evolution of what was previously available, and perhaps _in the publishers perspective_ essentially replaces it (eventually).  It can also help with alignment with non-technical documentation like contracts of supply (though that usually gets confused anyway).  I'll put together some coherant notes and we can discuss under #90. 

The point I was trying to make here is that version delta info can cover a wide range of stuff, not all of it that would come from some easily referenceable process tool like github.  [Assuming I've understood the suggestion, of course]

**Comment by riccardoAlbertoni** [comment]
We discussed this issue in last [dcat teleconference](https://www.w3.org/2020/06/17-dxwgdcat-minutes.html), we were in a restricted group, but we voted to register an initial consensus on using  [adms:versionNotes](https://www.w3.org/TR/vocab-adms/#adms-versionnotes).

**Comment by andrea-perego** [comment]
Issue closed as decided in the [11 Nov 2020 DCAT call](https://www.w3.org/2020/11/11-dxwgdcat-minutes#r09) and following the extension of the versioning section in the ED - in particular, see [§10.2 Version information](https://w3c.github.io/dxwg/dcat/#version-info).

A new issue has been created, concerning the specification of machine-actionable version deltas - see https://github.com/w3c/dxwg/issues/1271

New issues should be created for further discussion on this topic.
