### ISSUE TITLE
DCAT: Duplicated DATS bib entry

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#895]
The DATS entry is duplicated in [`config.js`](https://github.com/w3c/dxwg/blob/gh-pages/dcat/config.js):

````
        "DATS": {
            href : "http://wg3-metadataspecifications.readthedocs.io/",
            title : "Data Tag Suite",
            authors : ["Philippe Rocca-Serra", "Alejandra Gonzalez-Beltran"],
            publisher : "NIH Big Data 2 Knowledge bioCADDIE project.",
            date : "2016"
        },
       ...   
        "DATS": {
            "href": "https://github.com/datatagsuite/",
            "title": "Data Tag Suite",
            "authors": ["Alejandra Gonzalez-Beltran", "Philippe Rocca-Serra"],
            "publisher": "NIH Big Data 2 Knowledge bioCADDIE and NIH Data Commons projects",
            "date": "2016"
        },
````

@agbeltran , which is the right one?

BTW, I also found out this one:

https://datatagsuite.github.io/docs/html/

which seems to be the human-readable rendering of the 2nd entry above.

**Comment by davebrowning** [comment]
The first of these references has the following Note at the beginning:

> NOTE: this documentation has been replaced by the documentation at the Data Tag Suite github organization

with a link to the second ref (actually to `https://datatagsuite.github.io/docs/html/`) which is the actual document to my eyes.

So we should link there, I think

**Comment by agbeltran** [comment]
That is correct, the latest documentation is at https://datatagsuite.github.io/docs/html/

**Comment by andrea-perego** [comment]
The question is whether the only thing to be changed in the relevant entry is the URL - namely:

````javascript
        "DATS": {
            "href": "https://datatagsuite.github.io/docs/html/",
            "title": "Data Tag Suite",
            "authors": ["Alejandra Gonzalez-Beltran", "Philippe Rocca-Serra"],
            "publisher": "NIH Big Data 2 Knowledge bioCADDIE and NIH Data Commons projects",
            "date": "2016"
        },
````

**Comment by andrea-perego** [comment]
@agbeltran , I removed the duplicate entry and update the URL in draft PR https://github.com/w3c/dxwg/pull/919

Can you please check if the authors, publisher and date in the entry are correct? If this is not the case, please add a commit to PR https://github.com/w3c/dxwg/pull/919

Thanks!
