### ISSUE TITLE
DCAT: Figures format and legibility

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#896]
Opening the DCAT specification on different platforms (Linux vs Windows) and/or browsers, and using not enough large monitors, the content of the figures is not always easily legible.

I wonder whether using a vector format (as SVG) instead of PNG may solve the issue. Also, it would be nice to give users the ability to preview the figures in a larger size by clicking on them.

**Comment by dr-shorthair** [comment]
I've been using Sparx Enterprise Architect to prepare the figures you see at the moment. 
It does not export SVG. So if SVG is needed a different tool will be needed to make the figures.

**Comment by davebrowning** [comment]
Moving to future release....

**Comment by andrea-perego** [comment]
Discussion now in https://github.com/w3c/dxwg/issues/1294

Closing this issue.
