### ISSUE TITLE
DCAT: Main editorial fixes for CR

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#918]
There are a couple of section that may need to be fixed:

- [§ A. Alignment with other general purpose metadata vocabularies](https://w3c.github.io/dxwg/dcat/#alignments): There's only one subsection here, about Schema.org. So, it may be worth merging the two, and renaming the section accordingly
- [§ D.5 More examples needed](https://w3c.github.io/dxwg/dcat/#more-examples-needed): I guess this section should be dropped

**Comment by andrea-perego** [comment]
I wonder whether current Sections 8 (Quality information) and 9 (Qualified relations) would be better placed after current Section 13 (Data citation), as they address more sophisticated issues (compared to Sections 7, 9, 10-13).

**Comment by dr-shorthair** [comment]
I agree that the chapters should be shuffled into a more rational sequence. Currently they are more or less in chron order of creation

**Comment by andrea-perego** [comment]
Thanks, @dr-shorthair . Do you think that the order I proposed makes sense, or we should shuffle also the other sections?

**Comment by andrea-perego** [comment]
About my proposal below:

> - § A. Alignment with other general purpose metadata vocabularies: There's only one subsection here, about Schema.org. So, it may be worth merging the two, and renaming the section accordingly
> - § D.5 More examples needed: I guess this section should be dropped

unless anybody disagrees, I'll implement the revision in PR #919 within today.

**Comment by riccardoAlbertoni** [comment]
@andrea-perego  No objection from me on changing the order of sections.  
Also, the appendices are in a  peculiar order, the acknowledgemnt section is between alignment and example, should we move it as the first appendix?

I wonder if we still need the section [appendinx about issue summary](https://w3c.github.io/dxwg/dcat/#issue-summary), I would drop it considering that we have already said in the status of document that " Issues, requirements, and features that have been considered and discussed by the Data eXchange Working Group but have not been addressed due to lack of maturity or consensus are collected in GitHub. Those believed to be a priority for a future release are in the milestone DCAT Future Priority Work."

**Comment by andrea-perego** [comment]
I just saw that link to "Alignment and crosswalks" in the note after [Section A](https://w3c.github.io/dxwg/dcat/#alignments) is broken:

https://github.com/w3c/dxwg/wiki/Alignments-and-crosswalks

Where is it supposed to point to?

**Comment by dr-shorthair** [comment]
I think it was just a list - now https://github.com/w3c/dxwg/labels/alignment

**Comment by andrea-perego** [comment]
Fixes done in #919 - please have a check if you are happy with re-ordering and removal of sections (BTW, I haven't deleted them - just commented the code):

https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

**Comment by riccardoAlbertoni** [comment]
> Fixes done in #919 - please have a check if you are happy with re-ordering and removal of sections (BTW, I haven't deleted them - just commented the code):
> 
> https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

I am happy, Thanks!

**Comment by andrea-perego** [comment]
Another issue:

At the end of [Section 10 (Versioning)](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#dataset-versions), there's the following NOTE:

> NOTE
> In this chapter it is planned to describe some patterns for describing Dataset and/or Distribution versions. See the wiki page on Dataset versioning for more discussion.

Should we drop it?

**Comment by andrea-perego** [comment]
[Section 6.3 (Class: Catalog)](https://w3c.github.io/dxwg/dcat/index.html#Class:Catalog) includes the following NOTE:

> NOTE
> The scope of DCAT 2014 was catalogs of datasets [VOCAB-DCAT-20140116]. A number of use cases for the revision involve also having data services as members of a catalog - see DCAT Distribution to describe web services - ID6 and Modeling service-based data access - ID18. It has been decided to add an explicit class for Data Services in this revision of DCAT, and to enable these to be part of a Catalog. Provision for Catalogs to be composed of other Catalogs is also enabled. See Issue #172 and Issue #116.

I wonder whether we should also mention that:
- `dcat:Catalog` was made a subclass of `dcat:Dataset`
- A generic class `dcat:Resource` was added as an extension point for resource types not included in DCAT

**Comment by dr-shorthair** [comment]
+1

**Comment by dr-shorthair** [comment]
Maybe also remove the note at the beginning of the conformance chapter as part of thus pr .

**Comment by davebrowning** [comment]
@dr-shorthair suggested

> Maybe also remove the note at the beginning of the conformance chapter as part of thus pr .

(Updated once i engaged brain)

+1 to removing it -  especially since there's little change in what the text tries to say (at least for DCAT conformance.  We've been more expansive on profiles.

The auto-included text in that part of the document now  throws an error source of a broken link that should go to a reference entry for RFC8174...  I guess this will go away at some point (The error that is)

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> Maybe also remove the note at the beginning of the conformance chapter as part of thus pr .

Done in #919 via https://github.com/w3c/dxwg/commit/b194250e088c02d822ce4d7da18adb47955e5d83

**Comment by andrea-perego** [comment]
About this one:

> [Section 6.3 (Class: Catalog)](https://w3c.github.io/dxwg/dcat/index.html#Class:Catalog) includes the following NOTE:
> 
> > NOTE
> > The scope of DCAT 2014 was catalogs of datasets [VOCAB-DCAT-20140116]. ...
> 
> I wonder whether we should also mention that:
> 
> * `dcat:Catalog` was made a subclass of `dcat:Dataset`
> * A generic class `dcat:Resource` was added as an extension point for resource types not included in DCAT

I revised accordingly the text in #919 via https://github.com/w3c/dxwg/pull/919/commits/4074c9444dd6bd9c6656f4e21a1234e18a6949d0

I also realised that there was no entry in the change history about the changes made to class `dcat:Catalog`. So, I added one at the end.

However, I am unsure which are relevant issues concerning:
- `dcat:Catalog` made a subclass of `dcat:Dataset`
- addition of property `dct:hasPart`
- addition of property `dcat:service` 
- addition of property `dcat:catalog`

Could you please help?

**Comment by andrea-perego** [comment]
@davebrowning said:

> The auto-included text in that part of the document now throws an error source of a broken link that should go to a reference entry for RFC8174... I guess this will go away at some point (The error that is)

I don't see the error now. Maybe it was just a temporary problem with the SpecRef API...

**Comment by andrea-perego** [comment]
> Another issue:
> 
> At the end of [Section 10 (Versioning)](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#dataset-versions), there's the following NOTE:
> 
> > NOTE
> > In this chapter it is planned to describe some patterns for describing Dataset and/or Distribution versions. See the wiki page on Dataset versioning for more discussion.
> 
> Should we drop it?

Done in #919 via https://github.com/w3c/dxwg/pull/919/commits/d744c8be8935172c47bb5c762df0b3f85fb74e15

**Comment by andrea-perego** [comment]
> ...
> However, I am unsure which are relevant issues concerning:
> 
> * `dcat:Catalog` made a subclass of `dcat:Dataset`
> * addition of property `dct:hasPart`
> * addition of property `dcat:service`
> * addition of property `dcat:catalog`
> 
> Could you please help?

Fixed in #919 via https://github.com/w3c/dxwg/commit/132f35597c41d03605685e316cd617dafeb97c66

**Comment by andrea-perego** [comment]
All the reported issues have been addressed.

I think we can close this one.
