### ISSUE TITLE
Version identifier [RVSID]

### ISSUE THREAD

**Issue by jpullmann** [w3c/dxwg#92]
<section class='requirement' id='RVSID'><h3>Version identifier [<a href='https://www.w3.org/TR/dcat-ucr#RVSID' target='_blank'>RVSID</a>]</h3><p>Provide a means to identify a version (URI-segment, property etc.). Clarify relationship to identifier of the subject resource.</p><br/><em>Related requirements</em>: <a href='https://www.w3.org/TR/dcat-ucr#RVSDF' target='_blank'>Version definition [RVSDF]</a> <a href='https://www.w3.org/TR/dcat-ucr#RVSDT' target='_blank'>Version release date [RVSDT]</a> <br/><em>Related use cases</em>: <a href='https://www.w3.org/TR/dcat-ucr#ID4' target='_blank'>Dataset Versioning Information [ID4]</a> <a href='https://www.w3.org/TR/dcat-ucr#ID44' target='_blank'>Identification of versioned datasets and subsets [ID44]</a> </section>

**Comment by riccardoAlbertoni** [comment]
We discussed this issue in tonight's [dcat teleconference](https://www.w3.org/2020/06/03-dxwgdcat-minutes.html), please see the discussion and the [resolution](https://www.w3.org/2020/06/03-dxwgdcat-minutes.html#r02) the tonight's restricted group has voted to register an initial consensus on using owl:versionInfo.

**Comment by dr-shorthair** [comment]
Since `owl:versionInfo` is an `owl:AnnotationProperty` then it is mostly harmless. But I'm not really used to seeing OWL properties in a-box data ...

**Comment by riccardoAlbertoni** [comment]
> Since `owl:versionInfo` is an `owl:AnnotationProperty` then it is mostly harmless. But I'm not really used to seeing OWL properties in a-box data ...

@dr-shorthair: I wonder if you wanted to object to the `owl:versionInfo` usage or just provide a sort of "minor side comment" with your comment above. 

owl:versionInfo is also one of the implementation examples considered in the "Data Web Best Practice 7: Provide a version indicator" https://www.w3.org/TR/dwbp/#dataVersioning. 
Indeed, examples in the DWBP Rec have not normative status. Nevertheless, they should suggest proper ways to implement Best Practices.

**Comment by dr-shorthair** [comment]
Mostly a side-comment I guess. The description of `owl:versionInfo` is "The annotation property that provides version information for **an ontology** or another **OWL construct**." and I think the proposal here is to use it more generally in the context of data which often (usually) is not OWL. But it is from a trusted 'RDF vocabulary' so is preferable to minting something new.

**Comment by andrea-perego** [comment]
Issue closed as decided in the [11 Nov 2020 DCAT call](https://www.w3.org/2020/11/11-dxwgdcat-minutes#r07) and following the extension of the versioning section in the ED - in particular, see [§10.2 Version information](https://w3c.github.io/dxwg/dcat/#version-info).

New issues should be created for further discussion on this topic.
