### ISSUE TITLE
dcat.ttl - editorialNotes

### ISSUE THREAD

**Issue by davebrowning** [w3c/dxwg#920]
editorialNotes in dcat.ttl need reviewing/revising (as does the `owl:versionInfo`) to reflect the current state of the document.

**Comment by davebrowning** [comment]
Best to do this across the file in English and then do the translations?

**Comment by riccardoAlbertoni** [comment]
@davebrowning wrote:
>editorialNotes in dcat.ttl need reviewing/revising (as does the owl:versionInfo) to reflect the current state of the document.

The owl:versionInfo review you are suggesting reminds me that we might want to doublecheck dcat.ttl by using the [OntOlogy Pitfall Scanner (OPSS)](http://oops.linkeddata.es/response-advanced.jsp#). 

There are different issues raised when applying OPSS on the current dcat.ttl, some perhaps are not so important but others might provide hints for improvements.
For example,  
- Results for P08: Missing annotations. 28 cases suggest the following elements have no rdfs:label defined: 
› http://www.w3.org/ns/dcat#startDate 
› http://www.w3.org/ns/dcat#endDate 
› http://www.w3.org/ns/dcat#centroid 
› http://www.w3.org/ns/dcat#bbox 

- we might want to doublecheck why results for P12: Equivalent properties not explicitly declared raise that the following properties could be defined as equivalent: 
› http://www.w3.org/ns/prov#hadRole, http://www.w3.org/ns/dcat#hadRole  

- Results for P41: No license declared.

**Comment by riccardoAlbertoni** [comment]
I am preparing a distinct PR  to fix the Missing annotation ( rdfs:label) for  ›http://www.w3.org/ns/dcat#startDate
› http://www.w3.org/ns/dcat#endDate
› http://www.w3.org/ns/dcat#centroid
› http://www.w3.org/ns/dcat#bbox

**Comment by davebrowning** [comment]
Work moved from #921 to #926
