### ISSUE TITLE
Editorial comments on DCAT ED

### ISSUE THREAD

**Issue by larsgsvensson** [w3c/dxwg#922]
Having read the DCAT ED I stumbled over some minor(?) editorial issues:
* In the last part of the abstract it says "The (revised) DCAT vocabulary is available _here_." IIRC hyperlinks with the text "here" are considered a Bad Practice (TM). Suggestion "There is a _Turtle version of the (revised) DCAT vocabulary_ available".
* In the [section on Namespaces](https://w3c.github.io/dxwg/dcat/#namespaces) there is a reference to `dc:`. In the document `dc:` is only used in [example 19](https://w3c.github.io/dxwg/dcat/#ex-genoa-bus-stops-dataset-completeness-note), [example 28](https://w3c.github.io/dxwg/dcat/#ex-conformance-test-error) and in the [definition of `dct:type`](https://w3c.github.io/dxwg/dcat/#Property:resource_type) (and there only for the `rdfs:subClassOf` axiom). I suggest to get rid of `dc:` and only use `dct:`, particularly since none of the other `dct:` property descriptions highlight the subclass axiom.
* In [§5.1](https://w3c.github.io/dxwg/dcat/#dcat-scope) there is a note after the UML diagram saying that "Cardinalities are shown in a few places to reinforce expectations, but these are not axiomatized or enforced in any way by this recommendation". This is not entirely true, since the ttl file declares cardinalities for the use of `dct:relation` on `dcat:Relationship` and `dct:type` on `dcat:Resource`.
* Just above [Example 4](https://w3c.github.io/dxwg/dcat/#ex-distribution) the text says "a 5Kb CSV file". Should that be "a 5 kB CSV file"? (minor k for prefix kilo)
* The [scope note for `dcat:byteSize`](https://w3c.github.io/dxwg/dcat/#Property:distribution_size) says "The size in bytes can be approximated when the precise size is not known." I think it would avoid possible errors if we highlighted that even if the size is approximated, it still must be a decimal number, i. e. if the true size is 2,912 bytes, we can approximate with `"3000"^^xsd:decimal` but not with `"3k"^^xsd:decimal`.
* Minor type in the usage note for [spatial resolution](https://w3c.github.io/dxwg/dcat/#Property:dataset_spatialresolution): "For other kinds of spatial dataset," should probably be "For other kinds of spatial datasets,"
* [`dcat:compressFormat`](https://w3c.github.io/dxwg/dcat/#Property:distribution_compression_format) and [`dcat:packageFormat`](https://w3c.github.io/dxwg/dcat/#Property:distribution_packaging_format): There is no note that those were added during the revision.
* [`dcat:Role`](https://w3c.github.io/dxwg/dcat/#Class:Role): The note says that the property was newly added, but `dcat:Role` is a class...
* Are the sections on [Qualified Relations](https://w3c.github.io/dxwg/dcat/#qualified-forms), [License and rights statements](https://w3c.github.io/dxwg/dcat/#license-rights), [Versioning](https://w3c.github.io/dxwg/dcat/#dataset-versions) and [DCAT Profiles](https://w3c.github.io/dxwg/dcat/#profiles) really all normative? They do not say _non-normative_ so by reverse conclusion they are...

If you agree with those, I'd be happy to prepare a PR.

And: **Great Work**

**Comment by riccardoAlbertoni** [comment]
> * In the [section on Namespaces](https://w3c.github.io/dxwg/dcat/#namespaces) there is a reference to `dc:`. In the document `dc:` is only used in [example 19](https://w3c.github.io/dxwg/dcat/#ex-genoa-bus-stops-dataset-completeness-note), [example 28](https://w3c.github.io/dxwg/dcat/#ex-conformance-test-error) and in the [definition of `dct:type`](https://w3c.github.io/dxwg/dcat/#Property:resource_type) (and there only for the `rdfs:subClassOf` axiom). I suggest to get rid of `dc:` and only use `dct:`, particularly since none of the other `dct:` property descriptions highlight the subclass axiom.

 Please @larsgsvensson note that  [Web Annotation Vocabulary](https://www.w3.org/TR/annotation-vocab/) uses dc:format and dc:language instead of dct:format and dct:language.  I was not completely sure about the reason behind this choice,  and  I wanted to avoid introducing issues in the reuse of OA due to my lack of knowledge, as a consequence,  when writing the [Example 19 in dcat](https://w3c.github.io/dxwg/dcat/#ex-genoa-bus-stops-dataset-completeness-note) I have stubbornly stuck to the example available in OA [see example 15 in web annotation](https://www.w3.org/TR/annotation-vocab/#dc-format).

**Comment by andrea-perego** [comment]
Thanks a lot for your review, @larsgsvensson .

I started addressing the issues you reported in draft PR https://github.com/w3c/dxwg/pull/919 (see PR summary)

**Comment by andrea-perego** [comment]
@larsgsvensson said:

> Are the sections on Qualified Relations, License and rights statements, Versioning and DCAT Profiles really all normative? They do not say non-normative so by reverse conclusion they are...

Yes, I think they should  be non-normative.

Unless anyone disagree, I'll proceed with this revision in https://github.com/w3c/dxwg/pull/919

**Comment by andrea-perego** [comment]
@larsgsvensson said:

> In the last part of the abstract it says "The (revised) DCAT vocabulary is available here." IIRC hyperlinks with the text "here" are considered a Bad Practice (TM). Suggestion "There is a Turtle version of the (revised) DCAT vocabulary available".

Agreed. Maybe we have another option, namely, linking to the file  via `config.js` ([`alternateFormats`](https://github.com/w3c/respec/wiki/alternateFormats)), and dropping that sentence altogether.

I just made the relevant commit in #919 (but keeping the sentence in the abstract) - preview here: https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html (the link is included just before the copyright statement in the document header).

**Comment by larsgsvensson** [comment]
@riccardoAlbertoni scripsit:
> Please @larsgsvensson note that Web Annotation Vocabulary uses dc:format and dc:language instead of dct:format and dct:language. I was not completely sure about the reason behind this choice, and I wanted to avoid introducing issues in the reuse of OA due to my lack of knowledge, as a consequence, when writing the Example 19 in dcat I have stubbornly stuck to the example available in OA see example 15 in web annotation.

Ah, I didn't know that. In that case of course it's fine to keep the reference to `dc:`

**Comment by larsgsvensson** [comment]
@andrea-perego scriptit:
> I started addressing the issues you reported in draft PR #919 (see PR summary)

OK, thanks!

**Comment by andrea-perego** [comment]
> @larsgsvensson said:
> 
> > Are the sections on Qualified Relations, License and rights statements, Versioning and DCAT Profiles really all normative? They do not say non-normative so by reverse conclusion they are...
> 
> Yes, I think they should be non-normative.
> 
> Unless anyone disagree, I'll proceed with this revision in #919

Done in #919 - made sections 7-14, B, C "informative":

https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

**Comment by dr-shorthair** [comment]
Since most of the rec is written in terms of 'recommended for use ...' probably the only really normative elements are the descriptions of the existence of classes and properties. 7-14 are all good illustrations of usage, best practice etc. I guess that makes them non-normative, which only leaves chapter 6 and the conformance chapter as normative - is that what we intend?

**Comment by andrea-perego** [comment]
The following comments from @larsgsvensson are yet to be addressed:

> - In §5.1 there is a note after the UML diagram saying that "Cardinalities are shown in a few places to reinforce expectations, but these are not axiomatized or enforced in any way by this recommendation". This is not entirely true, since the ttl file declares cardinalities for the use of dct:relation on dcat:Relationship and dct:type on dcat:Resource.

> - Just above Example 4 the text says "a 5Kb CSV file". Should that be "a 5 kB CSV file"? (minor k for prefix kilo)

> - The scope note for dcat:byteSize says "The size in bytes can be approximated when the precise size is not known." I think it would avoid possible errors if we highlighted that even if the size is approximated, it still must be a decimal number, i. e. if the true size is 2,912 bytes, we can approximate with "3000"^^xsd:decimal but not with "3k"^^xsd:decimal.

**Comment by andrea-perego** [comment]
@dr-shorthair said:

> Since most of the rec is written in terms of 'recommended for use ...' probably the only really normative elements are the descriptions of the existence of classes and properties. 7-14 are all good illustrations of usage, best practice etc. I guess that makes them non-normative, which only leaves chapter 6 and the conformance chapter as normative - is that what we intend?

Makes sense to me. But I would keep normative also Section 3 (Namespaces).

Not sure about Section 15 (Security and privacy).

About Section A (Acknowledgments) and Section D (Change history), I don't think there's a need to mark them explicitly as "informative".

**Comment by andrea-perego** [comment]
> @larsgsvensson said:
> 
> > In the last part of the abstract it says "The (revised) DCAT vocabulary is available here." IIRC hyperlinks with the text "here" are considered a Bad Practice (TM). Suggestion "There is a Turtle version of the (revised) DCAT vocabulary available".
> 
> Agreed. Maybe we have another option, namely, linking to the file via `config.js` ([`alternateFormats`](https://github.com/w3c/respec/wiki/alternateFormats)), and dropping that sentence altogether.
> 
> I just made the relevant commit in #919 (but keeping the sentence in the abstract) - preview here: https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html (the link is included just before the copyright statement in the document header).

Unless anybody disagrees, I would drop the last sentence in the abstract, pointing to the dcat.ttl file.

**Comment by andrea-perego** [comment]
> > @larsgsvensson said:
> > > In the last part of the abstract it says "The (revised) DCAT vocabulary is available here." IIRC hyperlinks with the text "here" are considered a Bad Practice (TM). Suggestion "There is a Turtle version of the (revised) DCAT vocabulary available".
> > 
> > 
> > Agreed. Maybe we have another option, namely, linking to the file via `config.js` ([`alternateFormats`](https://github.com/w3c/respec/wiki/alternateFormats)), and dropping that sentence altogether.
> > I just made the relevant commit in #919 (but keeping the sentence in the abstract) - preview here: https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html (the link is included just before the copyright statement in the document header).
> 
> Unless anybody disagrees, I would drop the last sentence in the abstract, pointing to the dcat.ttl file.

Done in #919 via https://github.com/w3c/dxwg/pull/919/commits/fc8e3a156d8b0f44a9a1d9d336abd83475fe43a3

**Comment by andrea-perego** [comment]
@larsgsvensson dixit:

> - Just above Example 4 the text says "a 5Kb CSV file". Should that be "a 5 kB CSV file"? (minor k for prefix kilo)

Fixed in #919 via https://github.com/w3c/dxwg/pull/919/commits/2f79ace948358ad7d394099b5ae8fdb1a19d09a4

**Comment by andrea-perego** [comment]
The following comments from @larsgsvensson are yet to be addressed:

> - In §5.1 there is a note after the UML diagram saying that "Cardinalities are shown in a few places to reinforce expectations, but these are not axiomatized or enforced in any way by this recommendation". This is not entirely true, since the ttl file declares cardinalities for the use of dct:relation on dcat:Relationship and dct:type on dcat:Resource.

> - The scope note for dcat:byteSize says "The size in bytes can be approximated when the precise size is not known." I think it would avoid possible errors if we highlighted that even if the size is approximated, it still must be a decimal number, i. e. if the true size is 2,912 bytes, we can approximate with "3000"^^xsd:decimal but not with "3k"^^xsd:decimal.

**Comment by davebrowning** [comment]
#1056 (when merged) aims to address these final points....

**Comment by davebrowning** [comment]
Now merged
