### ISSUE TITLE
Harmonise notes about 'property/etc added in this revision of DCAT'

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#923]
We're using a variety of forms e.g. 'Explicit use of this property added in this revision of DCAT. ', 'Property added in this revision of DCAT. ' 'New property in this context in this revision of DCAT. ' and it might be better to harmonise the text.

**Comment by andrea-perego** [comment]
I've started doing that.

I was also thinking that in these NOTEs it may be good to add a link to the relevant issue (as done already in some of the NOTEs).

WDYT?

**Comment by andrea-perego** [comment]
Done in #919:

https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html

I used consistently the following sentences (let me know if I missed any):
- For new classes / properties in the DCAT namespace:
  > New class / property added in this revision of DCAT.
- For classes / properties from other namespaces added in DCAT 2:
  > Class / Property added in this context in this revision of DCAT.

Pointers to the relevant issues are yet to be added.

**Comment by agbeltran** [comment]
Adding the links to the issues is good for people to be able to track the discussions - are you aware of others specs doing this though?

**Comment by davebrowning** [comment]
I've done a parallel set of edits to the ttl file (just for editorial and change notes) in #926. 

@andrea-perego question on [6.4.4](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#Property:resource_creator) - should that use the 'added in this context' language?  [For example, like [6.4.14](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#Property:resource_relation)

The rest seemed fine

**Comment by andrea-perego** [comment]
@davebrowning said:

> I've done a parallel set of edits to the ttl file (just for editorial and change notes) in #926.

Thanks!

> @andrea-perego question on [6.4.4](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#Property:resource_creator) - should that use the 'added in this context' language? [For example, like [6.4.14](https://raw.githack.com/w3c/dxwg/andrea-perego-dcat-ed-rev/dcat/index.html#Property:resource_relation)

Thanks for spotting this. Fixed in #919 via https://github.com/w3c/dxwg/pull/919/commits/a84b690c4d8fd730f832c905f52876e64031db11

> The rest seemed fine

Thanks!

**Comment by andrea-perego** [comment]
@agbeltran said:

> Adding the links to the issues is good for people to be able to track the discussions - are you aware of others specs doing this though?

Not sure - I should check.

**Comment by davebrowning** [comment]
Looks like this should close with #984 (which is 'due for closing')
