### ISSUE TITLE
dcat:accessURL mentioning SPARQL endpoint in rdfs:comment

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#933]
`dcat.ttl` says:
```turtle
dcat:accessURL rdfs:comment """A URL of a resource that gives access to a distribution of the dataset. E.g. landing page, feed, SPARQL endpoint.
          Use for all cases except a simple download link, in which case downloadURL is preferred."""@en ;
```

It seems confusing to mention a SPARQL endpoint here, when this should be modeled as a `dcat:DataService`, since we have the endpoint URL.

**Comment by dr-shorthair** [comment]
The sentence below the definition box addresses this issue. 
> dcat:accessURL matches the property-chain dcat:accessService/dcat:endpointURL.

**Comment by jakubklimek** [comment]
@dr-shorthair OK, shouldn't this be also present in the notes in the `.ttl` file? Or how do we decide whether a note is in `.ttl`, in the actual doc or in both?

**Comment by dr-shorthair** [comment]
In this case it is axiomatized:  
https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.ttl#L500 

Usually the text in the tables is copied into the scope-notes in the TTL, but the text in the surrounding text, not.

**Comment by jakubklimek** [comment]
OK then, that should be enough.
