### ISSUE TITLE
URL/URI inconsistency in dcat:endpointURL comment

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#934]
`dcat.ttl` says:
```turtle
dcat:endpointURL
  rdfs:comment "The URI of the service end-point"@en ;
```

We should be consistent - if it is a URL, we should say URL. Since this is actually used to locate the service, it is a URL.

**Comment by dr-shorthair** [comment]
I had originally written "The **location** of the ..." but this got overruled in some later discussion :-)

**Comment by riccardoAlbertoni** [comment]
I propose to uniform the dcat.ttl to the current DCAT WD, which says
>The root location or primary endpoint of the service (an IRI).

as for the  @jakubklimek's comment, we might need to drop "(an IRI)"

**Comment by smrgeoinfo** [comment]
maybe

> The root location or primary endpoint of the service, should be identified by a web-resolvable IRI.

**Comment by riccardoAlbertoni** [comment]
Thanks, @smrgeoinfo and @jakubklimek, as a compromise point, I have proposed 
>The root location or primary endpoint of the service (a web-resolvable IRI).

 in PR #999 
Would this work for you?
