### ISSUE TITLE
dcat:compressFormat and dcat:packageFormat description inconsistency

### ISSUE THREAD

**Issue by jakubklimek** [w3c/dxwg#935]
In `dcat:compressFormat`, there is:
```turtle
dcat:compressFormat
  rdfs:comment "The format of the distribution in...
```
In `dcat:packageFormat`, there is:
```turtle
dcat:packageFormat
  rdfs:comment "The format of the file ...
```
The question is which one is correct, but it should be only one of them. I would vote for "file".

**Comment by makxdekkers** [comment]
I agree that both should refer to 'file'.

**Comment by agbeltran** [comment]
I agree that 'file' definitely makes sense, but given that the domain of the properties is `dcat:Distribution` I wonder if we are not causing confusion by only saying file. I note that the specification uses 'file' in both cases too. 

However, we have a whole section of examples of compressed and packaged distributions: https://w3c.github.io/dxwg/dcat/#examples-compressed-and-packaged-distributions

And also when we talk about format, we mention the file format of the distribution: https://w3c.github.io/dxwg/dcat/#Property:distribution_format

So, what about saying the 'compression format of the distribution' and the 'package format of the distribution' to be consistent across the document and with the domain of the property?

**Comment by agbeltran** [comment]
We discussed this today and there was agreement on using 'distribution' for consistency - https://www.w3.org/2019/07/10-dxwgdcat-minutes.html

**Comment by agbeltran** [comment]
BTW, the changes should be made in both spec and ttl file. We also discussed on the option of adding a `skos:usageNote` where we clarify that in many cases the distribution will be a file.

**Comment by riccardoAlbertoni** [comment]
> ... We also discussed on the option of adding a `skos:usageNote` where we clarify that in many cases the distribution will be a file.

Rereading the usage notes we have for dcat:packageFormat and dcat:compressFormat (see below)  I think this is already quite explicit. 

dcat:packageFormat Usage Note:
>This property to be used when the files in the distribution are packaged, e.g. in a TAR file. The format SHOULD be expressed using a media type as defined by IANA [[!IANA-MEDIA-TYPES]], if available.

dcat:compressFormat Usage Note:
>This property to be used when the files in the distribution are compressed, e.g. in a ZIP file. The format SHOULD be expressed using a media type as defined by IANA [[!IANA-MEDIA-TYPES]], if available.

**Comment by agbeltran** [comment]
Agreed - then we don't need to add anything else.
