### ISSUE TITLE
DCAT: Inconsistent use of "profile" / "application profile"

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#937]
I got some feedback concerning the fact that, in the DCAT spec, we are using sometimes "profile" sometimes "application profile", and whether we mean two different things or, at least, we use on purpose the different terms in different contexts.

As far as I know, we actually mean the same thing, but anyway we have to address this issue by 
1. be consistent in how we use these two notions
2. pointing to the actual definitions of "profile" and/or "application profile" we are using

**Comment by riccardoAlbertoni** [comment]
@andrea-perego  wrote:
> As far as I know, we actually mean the same thing,
> but anyway we have to address this issue by
> 
> 1. be consistent in how we use these two notions
> 2. pointing to the actual definitions of "profile" and/or "application profile" we are using

I agree "DCAT application profile" and "DCAT profile" are used interchangeably,  we have used mainly "DCAT application profile". 
We have also defined the term "DCAT profile" in the conformance section, as

> A DCAT profile is a specification for a data catalog that adds additional constraints to DCAT. A data catalog that conforms to the profile also conforms to DCAT. Additional constraints in a profile MAY include:
>- Cardinality constraints, including a minimum set of required metadata fields
>- Sub-classes and sub-properties of the standard DCAT classes and properties
>- Classes and properties for additional metadata fields not covered in DCAT
>- Controlled vocabularies or URI sets as acceptable values for properties
>- Requirements for specific access mechanisms (RDF syntaxes, protocols) to the catalog's RDF description

I have found some occurrences of  "profile" where we generically refer to profiles that are not necessarily of DCAT. However, I do not think this is a problem if we make clear that "DCAT application profile" and "DCAT profile" are not distinct in the document.

I propose to fix the issue  with one of the following options
A- replace "DCAT Application Profile" with "DCAT profile";
B- reformulate the definition above with  "A DCAT profile (aka DCAT Application Profile) is a specification ... "; 
C- do both A and B.

If we agree on one of the above options, I can take care of submitting a PR.

**Comment by agbeltran** [comment]
I think that we should, in the first appearance in the document, point to the definition of profile given in the Content Negotiation by Profile spec (https://www.w3.org/TR/2019/WD-dx-prof-conneg-20190430/#definitions), clarifying again that they are used indistinctively. So, option 2 of the ones that @andrea-perego proposed.

**Comment by andrea-perego** [comment]
This issue was discussed during [the DCAT subgroup call of 22 May](https://www.w3.org/2019/05/22-dxwgdcat-minutes#x08).

This is what was decided:
1. A definition of profile is already included in the conformance section, so we can stick to it
2. We'll consistently "profile" instead of "application profile", unless when referring to specifications which include "application profiles" in their name
3. A note should be added to the conformance section, explaining that what we indicate with "profile" would be called in the Dublin Core community an "application profile"

Relevant action: https://www.w3.org/2017/dxwg/track/actions/335

**Comment by andrea-perego** [comment]
> This issue was discussed during [the DCAT subgroup call of 22 May](https://www.w3.org/2019/05/22-dxwgdcat-minutes#x08).
> 
> This is what was decided:
> 
> 1. A definition of profile is already included in the conformance section, so we can stick to it
> 2. We'll consistently "profile" instead of "application profile", unless when referring to specifications which include "application profiles" in their name
> 3. A note should be added to the conformance section, explaining that what we indicate with "profile" would be called in the Dublin Core community an "application profile"
> 
> Relevant action: https://www.w3.org/2017/dxwg/track/actions/335

Revisions implemented in PR https://github.com/w3c/dxwg/pull/941

Please review / revise

**Comment by rob-metalinkage** [comment]
+1 for resolution.

just to note, some communities feel quite strongly that "profile" is "downstream" of their core specifications, even if their core specifications may be profiles to some other groups view of the world.  The conneg-by-ap view is that all specifications are profiles, and the choice of "root" specifications is arbitrary - so you can declare something conforms to (or a resource is available as) DCAT as easily as DCAT-AP.
