### ISSUE TITLE
CONNEG: Reference to WFS3

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#942]
I don't remember if any reference has been made to WFS3 in relation to profile negotiation:

https://rawcdn.githack.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html

Notably, in [Section 10 (Media Types)](https://rawcdn.githack.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html#mediatypes), WFS3 makes use of a `profile` param in the HTTP headers / quoting:

> JSON media types that would typically be used in a WFS that supports JSON are
> - `application/geo+json` for feature collections and features, and
> - `application/json` for all other resources.
> 
> XML media types that would typically occur in a WFS that supports XML are
> - `application/gml+xml;version=3.2` for any GML 3.2 feature collections and features,
> - `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for GML 3.2 feature collections and features conforming to the GML Simple Feature Level 0 profile,
> - `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for GML 3.2 feature collections and features conforming to the GML Simple Feature Level 2 profile, and
> - `application/xml` for all other resources.
> 
> The typical HTML media type for all "web pages" in a WFS would be `text/html`.
> 
> The media type for an OpenAPI definition in JSON is `application/openapi+json;version=3.0`.

/cc @cportele

**Comment by cportele** [comment]
The `profile` parameter is discussed in the media type definition of GML (https://www.iana.org/assignments/media-types/application/gml+xml) and is consistent with RFC 6906, which is discussed in the conneg by profile draft.

**Comment by andrea-perego** [comment]
Thanks, @cportele . I guess I misunderstood then: this is the standard `profile` parameter used to specify the "profile" of the current resource, and not to request a specific profile.

Is there anything in WFS3 that is related to profile negotiation, and/or you think it is worth including in the CONNEG spec? I mean, something similar to the `outputSchema` parameter in CSW.

**Comment by rob-metalinkage** [comment]
relates to #662 - we have attempted to distinguish these issues.  If a WFS3 based  example around use of outputSchema (as opposed to outputFormat) is available we will consider it as an example of Query String base negotiation - if there is a way to list options and schemas wont be further profiled in practice.

**Comment by cportele** [comment]
Yes, we have ignored profile negotiation aspects for now and only use the media type etc. as foreseen by HTTP. The idea is to maybe add such capabilities once there is a more broadly accepted practice, but this will always be outside of the core spec.

**Comment by andrea-perego** [comment]
Thanks, @cportele . So, we are not going to point to WFS3 for the moment.

I think this issue can be closed.

**Comment by larsgsvensson** [comment]
Since @andrea-perego as the creator of the issue thinks it can be closed, I guess it's safe to add "due-for-closing"
