### ISSUE TITLE
Remove redundant super property for dct:conformsTo

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#943]
Even though it is indicated in the DCT spec, it's redundant to say that `dct:conformsTo` refines both `dct:relation` & `dc:relation` since `dct:relation` itself refined `dc:relation`.

Remove `dct:conformsTo` refines `dc:relation`.

**Comment by nicholascar** [comment]
`dc:relation` removed from 3PWD

**Comment by aisaac** [comment]
Issue seems closable! When this is merged: https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#Property:conformsTo

**Comment by nicholascar** [comment]
Closing after a period of due-for-closing and no further actions.
