### ISSUE TITLE
DCAT: ODRL CG review

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#949]
Submitted on 6 Jun 2019: 

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jun/0000.html

Quoting:

> Dear DXWG, the W3C ODRL Community Group meet recently [1] to discuss the latest DCAT working draft [2].
> 
> We provide the following comments and feedback:
> 
> 1 - Section 3 Namespaces
> 
> Please update the odrl namespace URI to: http://www.w3.org/ns/odrl/2/
> 
> 
> 2 - Section 6.4.21 Property: has policy
> 
> An ODRL Policy expression is normatively defined by the ODRL Information Model recommendation [3]
> 
> Please update the Definition to:
> 
> “An ODRL conformant policy expressing the rights associated with the resource.
> 
> And update the Usage note to
> 
> “Information about rights expressed as an ODRL policy  [ODRL-MODEL] using the ODRL vocabulary [ODRL-VOCAB] MAY be provided for the resource."
> 
> 
> 3 - Section 6.7.8 Property: has policy
> 
> See comments above, but change “resource” to “distribution"
> 
> 
> 4 - Section 8 License and rights statements
> 
> In the first NOTE, change "W3C ODRL vocabulary [ODRL-VOCAB]” to "W3C ODRL model [ODRL-MODEL] and vocabulary [ODRL-VOCAB]”
> 
> In the paragraph before the last NOTE:
>  - remove “use” from “..use use..”
>  - the phrase “...in addition to the relevant dct property.” should be updated to “...in addition to the corresponding dct property that matches the same ODRL policy type."
> 
> 
> Cheers, ODRL CG
> 
> [1] https://lists.w3.org/Archives/Public/public-odrl/2019Jun/0003.html
> [2] https://www.w3.org/TR/2019/WD-vocab-dcat-2-20190528/
> [3] https://www.w3.org/TR/odrl-model/

**Comment by andrea-perego** [comment]
Requested revisions implemented in https://github.com/w3c/dxwg/pull/950

**Comment by kcoyle** [comment]
I noted in their email the phrase: "to the relevant dct property." In that sentence, "dct property" should be changed to "DCMI metadata term". Thanks.

**Comment by andrea-perego** [comment]
Thanks, @kcoyle .

The proposed revision has been implemented as follows:

> Finally, in the particular case when rights are expressed via ODRL policies, it is recommended to use the odrl:hasPolicy property as the link from the description of the cataloged resource or distribution to the ODRL policy, in addition to the corresponding [DCTERMS] property that matches the same ODRL policy type.

Can this work, or we should revise it? 

BTW, the reason behind using "property" was that the DCMI terms recommended for specifying rights as `dct:rights`, `dct:license`, `dct:accessRights`, which are all RDF properties.

**Comment by kcoyle** [comment]
Thanks Andrea. I think that's ok since it points to a reference that has the full citation. All of the DCMI terms are properties, yet they get called "terms". However, the way you have done that includes all the concepts. Great!

**Comment by andrea-perego** [comment]
Thanks, @kcoyle . 

Unless of any additional comments, I'll reply to the ODRL CG's mail.

**Comment by andrea-perego** [comment]
Mail sent: https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jun/0001.html

Waiting to have confirmation that the implemented revisions address the reported comments.

**Comment by andrea-perego** [comment]
ODRL CG replied on June, 21st, that they are happy with the revisions:

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jun/0002.html

This issue can be closed.
