### ISSUE TITLE
Proposal for relaxing domain of dcat:contactPoint

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#95]
> From: https://github.com/w3c/dxwg/issues/76#issuecomment-359124922

This proposal is about relaxing the domain of `dcat:contactPoint`, to allow its use not only for datasets (as it is [in the current version of DCAT](https://www.w3.org/TR/vocab-dcat/#Property:dataset_contactPoint)), but also for other resources (e.g., catalogues, catalogue records).

This issue popped up during the development of GeoDCAT-AP, since all the agent roles (`dcat:contactPoint` included) supported in ISO 19115 can be specified for any resource.

Besides this, the "contact point" is probably the most important role for data consumers, not only for datasets. For instance, for a `dcat:Catalog` it is possible to specify the `dct:publisher`, but if I need to ask questions and/or report issues about the catalogue I need to get in touch with the publisher's dedicated contact point.

**Comment by dr-shorthair** [comment]
Also, is the range right? While vcard:Kind is an RDF encoding of a commonly used contact data structure, there are other options ...

**Comment by makxdekkers** [comment]
I agree that the use of only vCard for contact information is too restrictive. If the range were :ContactInformation, vCard could be one possible expression of that class, while allowing other ways of specifying contact details.
I have seen cases where implementers use dcat:contacPoint to refer to resources of class Agent, but I think that would not be desirable.

**Comment by dr-shorthair** [comment]
Proposal accepted https://www.w3.org/2018/02/07-dxwgdcat-minutes
Partially implemented in PR #97 
Document needs to be updated to match https://github.com/w3c/dxwg/blob/gh-pages/dcat/index.html

**Comment by makxdekkers** [comment]
I understand that the proposal was accepted to drop the domain axiom. Is there further discussion on relaxing the range, or introducing a class dcat:ContactInformation?

**Comment by dr-shorthair** [comment]
Document also updated. Resolved by #97

**Comment by smrgeoinfo** [comment]
... Distribution should have contactPoint as well...
