### ISSUE TITLE
[I18N] Various date types could be more specific

### ISSUE THREAD

**Issue by aphillips** [w3c/dxwg#957]
Property: release date
https://www.w3.org/TR/2019/WD-vocab-dcat-2-20190528/#Property:resource_release_date

A number of date values have range text like this:

>    rdfs:Literal encoded using the relevant ISO 8601 Date and Time compliant string [DATETIME] and typed using the appropriate XML Schema datatype [XMLSCHEMA11-2]

This is not very specific, since 8601 and schema provide a plethora of date/time types/value spaces. It might be better to be more specific and restrict this to RFC3339 full-date or date-time (i.e. in the case of a timestamp) or by specifying the XML Schema types `date` or `dateTime` (which is the same thing as the RFC).

[This comment is part of the I18N horizontal review.]

**Comment by makxdekkers** [comment]
Doesn't the instruction that the string should be "_typed using the appropriate XML Schema datatype [XMLSCHEMA11-2]_" already solve the issue? Or could it be made more explicit by saying "_typed using the appropriate XML Schema datatype [XMLSCHEMA11-2], i.e. `xsd:date` or `xsd:dateTime`_"?

**Comment by pwin** [comment]
@makxdekkers I think the more explicit approach is a better recommendation.  There are so many options for data/datetime formatting and given that this is a pretty fundamental nugget of information then reducing the hassle of processing when it comes to aggregating across catalogues is a real benefit

**Comment by makxdekkers** [comment]
Another point is also that the text "_rdfs:Literal encoded using the relevant ISO 8601 Date and Time compliant string [DATETIME]_" does not allow the "_plethora of date/time types/value spaces_" of ISO 8601, as it points to DATETIME which refers to https://www.w3.org/TR/NOTE-datetime, a W3C Note that proposes to only use a small subset of the options in ISO 8601.

**Comment by andrea-perego** [comment]
The point of not being bound to a specific date/time datatype is that information as dataset release / modified date are expressed with different levels of precision by different communities / tools. Some are using a date (`xsd:date`), others a date-time (`xsd:dateTime`), others just the year (`xsd:gYear`).

About processing issues, I don't think this should be the case if the literal is typed.

**Comment by smrgeoinfo** [comment]
https://www.w3.org/TR/NOTE-datetime defines 6 options for date or date+time formatting. Here they are with xsd equivalents if they exist:
Year:
      YYYY (eg 1997)  == xsd:gYear
   Year and month:
      YYYY-MM (eg 1997-07)  == xsd:gYearMonth
   Complete date:
      YYYY-MM-DD (eg 1997-07-16) == xsd:date

   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)  (NO XSD equivalent-- xsd doesn't have a time format hh:mm without seconds)

   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)  ( xsd:dateTime, with time zone)

   Complete date plus hours, minutes, seconds and a decimal fraction of a second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)  ( xsd:dateTime, with time zone)

The options allowed by xsd or https://www.w3.org/TR/NOTE-datetime give 7 possibilities-not unmanageable for writing parsers, but I wouldn't want to have to deal with even more possibilities.  Xsd doesn't have an hh:mm format without seconds, so can't type a valid https://www.w3.org/TR/NOTE-datetime using xsd if that format is used.   

Seems like sticking with specifying use of xsd date and time formats is best for interoperability: Suggested edit (on 6.14.1, 6.14.2

> rdfs:Literal encoded using the relevant ISO 8601 Date and Time compliant string [DATETIME] that can be typed using the appropriate XML Schema datatype [XMLSCHEMA11-2] (xsd:gYear, xsg:gYearMonth, xsd:date, or xsd:dateTime).

**Comment by aphillips** [comment]
I18N is satisfied by these changes. Thanks.
