### ISSUE TITLE
The requirement "6.7.3 Dataset publications [RDSP]" refers to itself as related requirement

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#96]
The [6.7.3 Dataset publications [RDSP]](https://www.w3.org/TR/dcat-ucr/#RDSP) is referring to itself as related requirement and it should be removed.

**Comment by jpullmann** [comment]
Thanks for the hint, resolved: https://rawgit.com/w3c/dxwg/gh-pages/ucr/index.html#RDSP
