### ISSUE TITLE
DCAT: s/getCapabilities/GetCapabilities/

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dxwg#961]
Submitted by James Passmore (@nmtoken) on 26 Jun 2019:

http://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jun/0004.html

Quoting:

> " An endpoint description may be expressed in a machine-readable form, such as an OpenAPI (Swagger) description [OpenAPI], an OGC getCapabilities response [WFS], [ISO-19142], [WMS], [ISO-19128], a SPARQL Service Description [SPARQL11-SERVICE-DESCRIPTION], an [OpenSearch] or [WSDL20] document, a Hydra API description [HYDRA], else in text or some other informal mode if a formal representation is not possible. "
>
> "getCapabilities" should be "GetCapabilities".  OGC specs tell us this parameter value is case sensitive.

**Comment by andrea-perego** [comment]
Suggested revision implemented in PR https://github.com/w3c/dxwg/pull/964

**Comment by andrea-perego** [comment]
@agbeltran , I suggest we keep this issue open until James confirms he's happy with the revision.

**Comment by agbeltran** [comment]
good point, issue re-opened...

**Comment by andrea-perego** [comment]
Thanks, @agbeltran . I just informed James about the implemented revision:

https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jul/0000.html

**Comment by agbeltran** [comment]
Replied by James agreeing with the revision:
https://lists.w3.org/Archives/Public/public-dxwg-comments/2019Jul/0002.html

Closing issue now.
