### ISSUE TITLE
Replace prov#Role with #Class:Relationship for hadRole

### ISSUE THREAD

**Issue by nicholascar** [w3c/dxwg#962]
Range value of `dcat:hadRole` in HTML links to PROV's Role (`http://www.w3.org/ns/prov#Role`) but should link to the DCAT 2 Role (`https://www.w3.org/TR/vocab-dcat-2/#Class:Role`).

**Comment by andrea-perego** [comment]
Thanks, @nicholascar .

Link fixed via PR https://github.com/w3c/dxwg/pull/965

**Comment by riccardoAlbertoni** [comment]
PR  #965 approved by three editors and merged
