### ISSUE TITLE
JSON examples

### ISSUE THREAD

**Issue by tomkralidis** [w3c/dxwg#971]
Looking at https://www.w3.org/TR/vocab-dcat-2/, it would be valuable to have explicit JSON examples for those wishing to represent in same.  Happy to add this if folks agree/find useful.

**Comment by dr-shorthair** [comment]
Many (but not all) of the examples  in the document, and some others, are here https://github.com/w3c/dxwg/tree/gh-pages/dcat/examples Some are already in JSON. 
We should complete the collection from the document and their re-serialisation in JSON here for starters. 

Are you also suggesting that some JSON should be included in the document? JSON-LD?

**Comment by tomkralidis** [comment]
Exactly, to have some examples directly in the doc.

**Comment by smrgeoinfo** [comment]
Since some of us will need to implement schema.org records that parse with the Google Structured data testing tool, working up more examples using the schema.org mappings (e.g. /dcat/examples/dataset-004-sdo.jsonld) would be useful as well.

**Comment by davebrowning** [comment]
Looking at the timeline that we need to follow to ensure the W3 process can complete, its now very unlikely that we'll be able to include these examples in the recommendation itself.  We will still be able to provide json-ld examples (equivalent to those in the text) as @dr-shorthair mentioned earlier, but as standalone example files.  and possibly include in other non-normative/discursive documents such as a primer (if the WG has the time and resource to get this done).  

Assuming this proposal is acceptable, then we'll  keep this issue open to ensure it doesn't get forgotten, and mark it for the "Future Priority" milestone.
