### ISSUE TITLE
notes on 6.15.4 and 6.15.5 latitute and longitude

### ISSUE THREAD

**Issue by smrgeoinfo** [w3c/dxwg#974]
The NOTE says:

> The datum for w3cgeo:alt values is WGS84.

for w3cgeo:lat, w3cgeo:long, and w3cgeo:alt. I assume it should be 

> The datum for w3cgeo:lat values is WGS84.

for latitude and 

> The datum for w3cgeo:long values is WGS84.

for longitude

**Comment by davebrowning** [comment]
Good point - but the resolution of  #970 (with associated PR #988) will recast this, so this issue will be superceded (as per discussion at DCAT sub-group meeting https://www.w3.org/2019/07/10-dxwgdcat-minutes#x05)
