### ISSUE TITLE
New UC - Specification documents with multiple roles

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#978]
### Specification documents with multiple roles
Status: Proposed

Identifier:

Creator: Rob Atkinson

Deliverable(s): (AP Guidelines)

## Tags
''Optional space-separated list of tags out of the above catalog (extend on demand)''

## Stakeholders
In the main, people describing conformance of data in relation to requirements embedded in documents that contain multiple specifications or other information, such as recommendations, examples etc.

## Problem statement
It is common practice to write a single document that contains a range of different types of information. Some of this may be one or more formal specifications (often formalisms of these may be an appendix), examples, and non-binding recommendations. 

This needs explicit recognition for several reasons:
1) its a common and reasonable case
2) There is a tendency to confuse "the thing" and "the representation" - in this case "the thing" is the "named set of requirements" (that can be conformed to, can be further profiled, can be tested etc.) and the document (the representing artefact)
3) There is often a weakness in explicitly naming each set of requirements and suggestions in a citable way, so use of any functional approach to data description (e.g. dct:conformsTo statements means finding a way to name such requirements unambiguously.)
4) Documents often contain both mandatory requirements and suggestions, making statements of conformance difficult to understand if the document identifier is inappropriately used as a surrogate identifier for the specification component

## Existing approaches
In the OGC this is formally recognised by a policy to explicitly identify each "conformance Class" in such documents, and recognition that the pattern is typically a mandatory "core" and optional extensions.

## Links
http://www.opengeospatial.org/standards/modularspec

## Requirements
Documents that perform multiple roles, such as multiple discrete sets of requirements, suggestions etc need provide stable identifiers for each logical grouping of requirements.

The role of documents w.r.t. specifications needs to be explicit

Each document may perform multiple roles w.r.t. specifications

## Comments
Hopefully this will resolve some of the confusion around the nature of conformance by making it clear what conformance relates to.

This can be more explicitly modelled to provide working examples, and given profiling is a key role that may co-exist within the same document as a base specification it is reasonable to add classes and properties to express these requirements to the profile description ontology.

---

**Comment by smrgeoinfo** [comment]
@rob-metalinkage This is a good use case, but bears largely on the construction of specifications. I definitely agree that much of the difficulty with defining 'profile' has to do with specifications that aren't constructed to address the problems you outline!

**Comment by agreiner** [comment]
I think I agree with the idea behind this use case, but I find it confusing as written. It says "It is common practice to write a single document" and then goes on to say that "Some of this may be one or more formal specifications". Are you talking about a document or a specification? Are you using "may be" to mean "may call for" or perhaps "may refer to"? You correctly state that there is a tendency to confuse the thing and the representation, which is exactly the issue with this text. It would help a lot to have a concrete example.

**Comment by rob-metalinkage** [comment]
The text decouple the notion of document from specification - so I dont think it is confusing the thing and representation at all - but you are highlighting the natural tendendency of a reader to do so - and you are right examples are needed. This use case is in response to people saying their "profiles" do more than constrain requirements - so we should unpack one of those examples - it should be a lot less effort than trying to create a definition that is meaningful for all possible packaging of concerns in a document.

**Comment by aisaac** [comment]
@rob-metalinkage I think I agree with this use case, even though I am a bit puzzled by the fact that it quickly dives into self-reflection (i.e. "This needs explicit recognition for several reasons"). Maybe this could be mitigated by providing with example of documents that accomplish several specification roles?

Other suggestions: 
- "role of documents w.r.t. specification" and "role w.r.t. specification" may be simpler if written "specification role" (of (parts of) documents)
- get rid of "the pattern" (which is not defined/introduced)
- I somehow have the feeling that you have listed the 3 requirements in the reverse order of intuitiveness and importance. Can you re-order them into ("Each document may perform multiple roles w.r.t. specifications". "The role of documents w.r.t. specifications needs to be explicit" "Documents that perform multiple roles, such as multiple discrete sets of requirements, suggestions etc need provide stable identifiers for each logical grouping of specifications."

**Comment by kcoyle** [comment]
First, I am trying to work out the relationship described here between specifications and documents. It seems to me that some documents ARE specifications, and some specifications ARE documents. Are we in agreement on that? If not, what is the relationship that people see? 

I'm much less clear on how one can separate out some part of a "document" and call it a "specification" and give it a separate identifier, so I would need examples for how that could be done. It rather sounds to me like trying to separate the flour, sugar and eggs in a baked cake. A good example to work on would be DCAT-AP since we're pretty familiar with that. What part of that document would be separately identifiable as a "specification"? And how would one make that clear? Tagging individual sections? Thanks.

**Comment by smrgeoinfo** [comment]
I think the idea is that the specification is a 'Work'-- a collection of requirements, conformance classes, and tests (a conceptual thing); the document is an expression of the specification. 

Have a look at http://docs.opengeospatial.org/is/16-008/16-008.html. Section 8.2-8.9 and section 9 lay out requirements, Annex A defines conformance classes. Each conformance class asserts that some set of requirements is met, and defines tests to validate conformance.  Instance documents assert conformance to a conformance class, so in a sense, this specification defines several kinds of interchange documents, based on the conformance classes for which they assert conformance.  Each conformance class has an identifier.   This is a specification pattern in use (to varying degrees) in ISO and OGC.

**Comment by pwin** [comment]
@rob-metalinkage  I come across this sort of compound document quite often, such as [STATS21](https://www.transport.gov.scot/media/13222/stats21_scottish_2011_.pdf)  where there is mixed contents and different audiences:  this doc has procedural,  interface and data schema and constraint aspects.  The different levels of interoperability (Legal; Procedural; Semantic) are all there.  Being able to identify each component would make possible much clearer reference to what the data really conforms to

**Comment by kcoyle** [comment]
@smrgeoinfo @pwin Given the great variability of the kinds of documents that "specify" is there a way to achieve greater clarity regarding specifications v. documents? If one is to identify the specifications, how are they defined? What if they aren't in a separate section or appendix from more documentary contents? (DCAT-AP seems to be of this type.) It sounds like we are talking about creating a standard of sorts for specification documents, saying that there would be n sections having x, y, z contents. Is that reasonable?

**Comment by pwin** [comment]
@kcoyle  - yes, in that it could be a reference architecture similar to [EIRA](https://joinup.ec.europa.eu/sites/default/files/distribution/access_url/2019-03/76cb237b-0de8-464c-84ca-1327945eac3e/EIRA_v3_0_0_Overview.pdf) and from some time ago the US DoD [data reference architecture](https://web.archive.org/web/20070617034325/http://www.defenselink.mil/cio-nii/docs/DoD_DRM_V04_5aug.pdf)

**Comment by smrgeoinfo** [comment]
@kcoyle OGC has a specification for specifications like you suggest (http://xml.coverpages.org/OGC-08-131r2-SpecificationModelModularSpecifications.pdf).  That degree of formalization was motivated by the desire to have specs that can be used to build interoperable automated systems, and is not warranted for specifications that are not so constrained.

**Comment by aisaac** [comment]
@rob-metalinkage at the call today there is a scoping question: does your use case apply to the "generalized" notion of DCAT#1/CONNEG "data profile" or the "specific" one of DCAT#2/APs (in https://lists.w3.org/Archives/Public/public-dxwg-wg/2019Jun/0106.html)? 

And now trying to not use my artificial labels... I feel that the UC is agnostic on whether the specification is based on another specification, but @kcoyle noted that you have used the labels "profile-description" and "profile guidance", which would hint that you rather had in mind a use case for (application) profiles being based on other specifications.

**Comment by kcoyle** [comment]
As per discussion on June 9, questions came up as per:

1. Can we get an idea of how this relates to Conneg and DCAT, which are our main goals? The labels only refer to the profiles projects
1. Can we find a better word for "roles" which is vague and doesn't fit well with IT functions
1. Does this refer to all types of existing specifications and profiles? If not, is its intention to be prescriptive rather than descriptive? What if a specification does not have separate sections that can be addressed precisely?
1. What does it mean to "provide stable identifiers for each logical grouping of specifications"? Is this just a reference to sections of a specfication document?

There may have been more, but that's what I recall.

Also, in general the group felt that some examples are needed - not only examples that fulfill the use case such as the OGC documents, but ones that possibly do not.

**Comment by rob-metalinkage** [comment]
1. ok - could label this DCAT and CONNEG - but it wont actually affect them - this is making sure in DCAT context usage of conformsTo is useful, and addresses the issue for CONNEG that a profile is any specification that can be conformed to (and named so it can be asked for!)  We could break those senses with a bad definition, but we dont need to change those deliverables if we get it right

2. what is an "IT function" and who is making the statement "doesnt fit well" with what evidence, and what would it matter if our definition works for the cases we are considering?  

3. a)
Does this refer to all types of existing specifications and profiles?  - define "all" ? Am happy to accept the notion it relates to information in our WG context, but i dont see any reason it couldnt relate to behaviour - such as Service Level Agreements, or licences - or any other thing in which conformance could notionally be tested.  
b) I expect there will be cases where "a specification does not have separate sections that can be addressed precisely" - and we will probably need to agree a convention - such a role connecting the document to a notional sub-section without an explicit address within the document. i.e. we can mint an ID and use the Profiles Vocabulary to describe this case without drama - and you can use "fragment ID" on document reference URL where such an address does exist.

4. my bad - updated original text - should be "logical grouping of requirements"

**Comment by aisaac** [comment]
@rob-metalinkage thanks your point 1 exactly answers my question (and I bvelieve @kcoyle's , sorry we wrote our stuff at the same time). So the UC is about what I've called DCAT#1/CONNEG (and because this subsumes that, also about DCAT#2/APs)

**Comment by rob-metalinkage** [comment]
And i vbeleive there seems to be plenty of people understanding the nature of the problem and providing examples - in fact the first example to prompt this was the vaguely referenced cases of DC application profiles doing more than just constraining - so those folk who raised it are in a better position to provide the definitive example for that. (the OGC is a special case beacuse they have explicitly modelled what they do - its the organic approaches to specification which are more of a challenge, but nevertheless are important to handle well.)
