### ISSUE TITLE
remove subsumption axiom `dcat:Dataset rdfs:subClassOf dctype:Dataset.`

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dxwg#98]
dctype:Dataset is part of the [DCMI Type Vocabulary](http://dublincore.org/documents/dcmi-terms/#section-7), alongside text, image, sound, software and some other genre terms. 

In DCAT 1.0 dcat:Dataset is a subclass of dctype:Dataset. However, the scope of DCAT 'dataset' is more general than the DCMI Type 'dataset' (see [Scope or type of dataset with a DCAT description [ID8]](https://www.w3.org/TR/dcat-ucr/#ID8)), and also includes 'text' at least, and maybe multimedia types as well - the Datacite-DC-DCAT mapping provided at https://github.com/w3c/dxwg/issues/64#issuecomment-362113915 certainly shows this. 

So, while the DCMI Type Vocabulary could reasonably used as a typing vocabulary for classifying a dcat:Dataset (see #64), it is incorrect to pre-empt this by making dcat:Dataset a subclass of dctype:Dataset.

**Comment by makxdekkers** [comment]
I agree that it is too restrictive to declare dcat:Dataset a subclass of dctype:Dataset.

**Comment by dr-shorthair** [comment]
Resolved in meeting https://www.w3.org/2018/02/07-dxwgdcat-minutes
Implemented in #108

**Comment by agbeltran** [comment]
Re-opening until the PR is merged.

**Comment by dr-shorthair** [comment]
@agbeltran action on the PR is currently with you. 
Do you see any problems?

**Comment by agbeltran** [comment]
@dr-shorthair the PR is actually about two issues (I suggest we do a PR per issue, what do you think)? I'm still reviewing one of the issues.

**Comment by dr-shorthair** [comment]
This issue is fully resolved by #108 so can be closed. 
#64 should remain open until documentation is completed, per the comments. 

I combined two changes in one PR as they are logically bound together - the subsumption axiom is replaced by (... generalised to ...) the dct:type property.
