### ISSUE TITLE
dcat:Resource usage note

### ISSUE THREAD

**Issue by agbeltran** [w3c/dxwg#980]
In the usage note for [dcat:Resource](https://w3c.github.io/dxwg/dcat/#Class:Resource), indicates "It is strongly recommended to use a more specific sub-class when available."

This is clear for the subclasses that are defined in the spec but, should we clarify that it is recommended to extend dcat:Resource when no specific sub-class is available?

If changes are made, they also need to be reflected in the [dcat.ttl](https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat.ttl) file.

**Comment by riccardoAlbertoni** [comment]
Should we force the user to extend dcat:Resource whenever the type of resource considered in not represented explicitly as a class?
I wonder if there is any case in which a cataloger does not want to define explicitly the subclass, and use Resource as a generic resource...

**Comment by agbeltran** [comment]
I don't think we should *force* the user, but I was suggesting *recommending* to extend dcat:Resource. I would imagine that it is always useful to know what kind of entity you are cataloguing.

When we said  "It is strongly recommended to use a more specific sub-class when available.", the point is that the only available subclasses are `dcat:Dataset` and `dcat:DataService`, so I think we should add more clarifications on what to do when a sub-class is not available.

**Comment by riccardoAlbertoni** [comment]
what about the following sentence?
>"It is strongly recommended to use a more specific sub-class when available. dcat:Resource SHOULD be extended with more specific sub-class when the cataloged resource is not a dcat:Dataset or dcat:DataService"

**Comment by smrgeoinfo** [comment]
Since dcat:Resource has a dct:Type property, it might be better for interoperability if the recommendation is to use dcat:Resource for other resource types if no additional properties are required to describe them, and define new sub classes if additional properties are required.  Soft typing vs. hard typing....

**Comment by dr-shorthair** [comment]
Indeed - `rdf:type` gives you the 'hard type' with entailments, while `dct:type` is a classifier without consequences (... soft) ;-)

Soft-typing can be quite useful, perhaps as a first step towards developing a fully axiomatized hard-type, but maybe just as a flag for use in a particular context.

**Comment by smrgeoinfo** [comment]
You could also set up SWRL rules based on soft types...?

**Comment by agbeltran** [comment]
Then, what about

```It is strongly recommended to use a more specific sub-class when available. If cataloging other resources different from dcat:Dataset or dcat:DataService, it is recommended to rely on the dcat:Resource or extend it, while including the dct:type to indicate the specific type/genre```.

?

ping @riccardoAlbertoni @dr-shorthair @smrgeoinfo

**Comment by dr-shorthair** [comment]
```
It is strongly recommended to use a more specific sub-class. When describing a 
resource which is not a dcat:Dataset or dcat:DataService, it is recommended to create a 
suitable sub-class of dcat:Resource, or use dcat:Resource with the dct:type property to 
indicate the specific type.
```

**Comment by riccardoAlbertoni** [comment]
I agree that we should let the users decide between soft- and hard- typing or even both. 
IMO the following @dr-shorthair's proposal is a more direct formulation than the previous
> ```
> It is strongly recommended to use a more specific sub-class. When describing a 
> resource which is not a dcat:Dataset or dcat:DataService, it is recommended to create a 
> suitable sub-class of dcat:Resource, or use dcat:Resource with the dct:type property to 
> indicate the specific type.
> ```
