### ISSUE TITLE
Provide a pathway for referencing profiles embedded in documents with broader scope.

### ISSUE THREAD

**Issue by rob-metalinkage** [w3c/dxwg#990]
Many documents that are called "specifications" or "profiles" actually contain a range of information, and profiles may be defined within the same document that defines one or more base specifications. The onus is thus on communities using these documents to unambiguously identify the sections which constitute a specification for which conformance can be declared, or a concept of conformance compatible with the usage in Conneg-by-ap or dct:conformsTo. 

For example, a set of mandatory requirements might be logically separated from a list of recommendations, so that its possible to declare that either all mandatory requirements are met, or that all recommendations are followed.

**Comment by tombaker** [comment]
@rob-metalinkage 
> Many documents that are called "specifications" or "profiles" actually contain a range of information,
> and profiles may be defined within the same document that defines one or more base specifications.

Saying that a "profile" is not a specification; that, rather, the "real" profile is a section (or sections) _embedded_ in a specification, seems like a non-starter.  Putting the onus on communities to "unambiguously identify" sections of a specification, and even assuming that authors of profiles have a notion of conformance that can be so explicitly formulated, is simply unrealistic.  One would have to tell alot of profile authors that the things they are calling profiles are not "really" profiles, or not "just" profiles, and that the "real" profile is actually just _a part of_ the thing they are calling a "profile".

Is that your intention?  If it is not your intention, may I suggest you use a word other than "profile" to describe what you expect.  Redefining well-known words like "profile" to mean something much more limited and prescriptive than the general meaning is not a good idea.

It is also not clear to me why such a requirement is needed for CONNEG, which uses URIs simply to indicate a preference among potential HTTP responses.

**Comment by rob-metalinkage** [comment]
If you have multiple specifications, and other things like recommendations you want to make statements about, then you simply have to identify them. so happy to leave it up to communities to decide how thier "profiles" conform to a clear functional definition - rather then blur the definition to try to catch all cases.

in practical terms the intention is to have a valid object for the usage of the  predicate dct:conformsTo that makes sens in DCAT and other contexts. The goal is to provide a way for communities that have clear requirements to make statements about them in an interoperable fashion.

That said, you raise a valid concern that such profiles do exist and have utility, but have not been modelled this explicilty.  I think the solution lies in providing guidance to such communities as to how to reference their information resources in an unambiguous way.

I think that a convention like "if my document contains a set of mandatory requirements then we regard that as the specification" fits in quite well with conneg by AP - you could ask for the SHACL profile of a profile document or the text (we'd need to have a name for that)

Maybe we could mint a special identifier for a profile that describes such documents, so people can reuse that...

If we define"canonical profile" identifiers which can be applied to "specifications embedded in documents without explicit identifiers" does it help?

(at the risk of confusing people who find it hard to untangle that a specification is also an information resource, and as such can also conform to a profile )

e.g.

prof:SpecificationDocument a prof:Profile ;
 rdfs:comment "A document that contains a single or clearly identified main set of requirements that can be used as a specification. This applies to the mandatory requirements in the document. Content negotiation by profile may be used to access specific components.  If multiple such specifications exist these need to be separately identified.  .

prof:Requirements a prof:Profile; 
rdfs:comment "The mandatory requirements in a specification document".

prof:Recommendations a prof:Profile; 
rdfs:comment "The set of recommendations defined in a specification document".

prof:conformsToRecommendations rdfs:subPropertyOf dct:conformsTo;
 rdfs:comment "conforms to non-mandatory recommendations in a target specification. dct:conformsTo is by convention assumed to mean conforms to strict mandatory requirements only. ".

**Comment by kcoyle** [comment]
Hmm. Not sure why "mandatory" requirements are given special consideration. There are often a lot of non-mandatory aspects to a profile but that still make use of constraints and get validation. It is perhaps an extreme case, but the main library data schema has about 1400 data elements of which one is mandatory. Emphasis on mandatory is not relevant to that set of data.

I agree with Tom that this idea that there are "things" within a profile that are considered the profile is a non-starter. Also, the use of "requirements" and "recommendations" has not come up before  so I don't know where that comes from in terms of our prior work. I think this approach should be dropped as it has no basis in our work.

**Comment by rob-metalinkage** [comment]
what is mandatory is that is you use a term you use it according to its definition - mandatory cardinality is one case of this, but you cannot have dc:author "3"xsd:int to indicate there were 3 authors - therefore there is a specification you can validate against. I can see that "mandatory" is too confusing a general term - we could find something else that means "semantically consistent with and, if syntax is specified, syntactically consistent with" 

I dont think there is problem saying all documents that use terms from "the main library schema" in a semantically consistent fashion and include the single mandatory (of cardinality) term conform to the schema - as we have i think established conformance is up to communities to decide - but thats a general notion that works for any vocabulary.

(Are you sure the issue of confusing cardinality and semantics actually covers all the concerns raised? - i would have thought there would be profiles that provide recommendations ( such as authors use ORCID identifiers where known ) which a not mandatory - but following the semantics of "author" is still mandatory, and possibly including at least one author is mandatory - and possibility including all contributing authors is mandatory (which is an example of a possible  profile of the semantics of "author", which does not require all authors to be included).

The point is the definition needs to be useful - and describe a behaviour which is distinct and useful to declare. It also needs to be unambiguous.

**Comment by aisaac** [comment]
@rob-metalinkage do you have examples about such cases?
As much as I'm ready to accept the case for #978 I have doubts about the requirement here, which is a bit the converse case. This issue here is about documents possibly specifying several profiles at the same time? I can accept that this may exist, but I would immediately flag this as sub-optimal practice as part of our guidance/recommendation, as it would force implementers of a profile to ingest stuff that they don't have necessarily to be aware of (i.e. the specs of other profiles).

**Comment by nicholascar** [comment]
Returning to the issue as phrased in the title "Provide a pathway for referencing profiles embedded in documents with broader scope", this is clearly an issue for Conneg by P (viz. "...referencing profiles...") for Conneg is the mechanism proposed to retrieve representations of a resource conforming to a profile. Conneg is dealing with this issue in #1017.

I cannot see how this Issue is directly relevant to PROF: PROF is an OWL vocabulary for describing profiles for the purposes of identifying related resources and conformance targets. If this cannot be done for an existing profile due to lots of things going on in the profile, then this only means it's not easily describable using PROF with the net result that any PROF-dependent mechanics will not be able to handle it. How to make profiles PROF profiles is clearly put in PROF: URI IDs, characterisation in PROF semantics etc. It's a matter outside of PROF as to whether or not a community may choose to do that - it's a Profile Guidance thing.

@rob-metalinkage as the proponent of the Issue, can you state specifically what change in PROF's vocabulary or documentation this Issue could or should precipitate? If not, I'd like to de-tag this one from the vocab and leave it for Guidance on how to formulate profiles.

**Comment by nicholascar** [comment]
@rob-metalinkage on reflection, this is not a profile-negotiation issue either - there is nothing that ConnegP can say that will affect how "profiles may be defined within the same document that defines one or more base specifications" by communities. For this reason, I am removing the profile-negotiation tag and leaving this Issue entirely for profile-guidance.

**Comment by rob-metalinkage** [comment]
Closing this as no longer relevant to this repo. If something concrete that needs to be addressed about behavour or description can be identified it should be raised as a specific issue in the relevant project repo.
